<?
regGS("Delete article $1","Eliminar Artigo $1.");
regGS("Show article on front page","Mostrar Artigo na 1ª Página");
regGS("Show article on section page","Mostrar Artigo na página de Secção");
regGS("Enter keywords, comma separated","Entre Palavras-Chave, separadas por virgulas");
regGS("Adding new article","Adicionando Artigo");
regGS("You must select an article type.","Tem de escolher um Tipo de Artigo");
regGS("The article $1 has been created","O Artigo $1 foi criado");
regGS("The article $1 could not be created","O Artigo $1 não pode ser criado");
regGS("Do you want to edit the article?","Confirma a edição do Artigo?");
regGS("Article $1 added to $2. $3 from $4. $5 of $6","Artigo $1 adicionado a $2. $3 de $4. $5 de $6");
regGS("Delete article","Eliminar Artigo");
regGS("You do not have the right to delete articles.","Não tem permissões para eliminar Artigos.");
regGS("Are you sure you want to delete the article $1 ($2)?","Confirme a Eliminação do Artigo $1 ($2)?");
regGS("Deleting article","Eliminando Artigo");
regGS("The article $1 ($2) has been deleted.","Artigo $1 ($2) foi eliminado");
regGS("The article $1 ($2) could not be deleted.","Artigo $1 ($2) não pode ser eliminado");
regGS("Article $1 ($2) deleted from $3. $4 from $5. $6 ($7) of $8","Artigo $1 ($2) foi eliminado de $3. $4 de $5. $6 ($7) de $8");
regGS("Change article status","Alterar Estado do Artigo");
regGS("Change the status of article $1 ($2) from $3 to","Alterar Estado do Artigo $1 ($2) de $3 para");
regGS("Changing article status","Alterando o estado do Artigo");
regGS("Status of the article $1 ($2) has been changed from $3 to $4.","Estado do Artigo $1 ($2) foi alterado de $3 para $4.");
regGS("Status of the article $1 ($2) could not be changed.","Estado do Artigo $1 ($2) não pode ser alterado");
regGS("You do not have the right to change this article status. Once submitted an article can only changed by authorized users.","Não tem permissões para alterar o Estado do Artigo. Após um artigo ser submetido apenas poderá ser alterado por Utilizadores Autorizados pelo Sistema.");
regGS("Article $1 status from $2. $3 from $4. $5 ($6) of $7 changed","Alteração no Artigo $1 de $2, $3 de $4. $5 ($6) de $7");
regGS("Translate article","Traduzir Artigo");
regGS("You do not have the right to change this article.  You may only edit your own articles and once submitted an article can only changed by authorized users.","Não tem permissões para alterar o Estado do Artigo. Apenas pode alterar os seus artigos, mas após um artigo ser submetido apenas poderá ser alterado por Utilizadores autorizados pelo Sistema.");
regGS("Edit article details","Editar Detalhes do Artigo");
regGS("Simple editor","Editor Simples");
regGS("Advanced editor","Editor Avançado");
regGS("Allow users without subscriptions to view the article","Permitir que leitores sem assinatura vejam Artigo.");
regGS("Unlocking article","Desbloquear Artigo");
regGS("The article has been unlocked.","Este Artigo encontra-se bloqueado");
regGS("The article could not be unlocked.","Este Artigo não pode ser desbloqueado");
regGS("You do not have the right to unlock the article. Once submitted an article can only changed by authorized users.","Não tem permissões para desbloquear o Artigo. Após um artigo ser submetido apenas poderá ser alterado por Utilizadores autorizados pelo Sistema.");
regGS("Changing article details","Alterando detalhes do Artigo");
regGS("The article has been updated.","Artigo actualizado");
regGS("The article cannot be updated or no changes have been made.","O Artigo não pode ser actualizado, ou não foram efectuadas alterações.");
regGS("Edit field: $1","Editar Campo $1");
regGS("Preview article","Pre-visualizar Artigo");
regGS("This article cannot be previewed. Please make sure it has a <B><I>single article</I></B> template selected.","Este Artigo não pode ser visulaizado, certifique-se de que se encontra definido um Modelo para Artigo");
regGS("This article has been locked by $1 ($2) at","Este Artigo foi bloqueado por $1 ($2) às");
regGS("Now is $1","São agora $1");
regGS("Are you sure you want to unlock it?","Confirme o desbloqueamento");
regGS("Edit article","Editar Artigo");

?>