<?
regGS("Delete article $1","Smazat článek $1");
regGS("You do not have the right to add articles.","Nemáte právo přidat článek");
regGS("Show article on front page","Zobrazit článek na titulní straně");
regGS("Show article on section page","Zobrazit článek na stránce rubriky");
regGS("Enter keywords, comma separated","Vložte klíčová slova, oddělená čárkou");
regGS("Adding new article","Přidání nového článku");
regGS("You must select an article type.","Vyberte typ článku");
regGS("The article $1 has been created","Článek $1 byl vytvořen");
regGS("The article $1 could not be created","Článek $1 nemohl být vytvořen");
regGS("Do you want to edit the article?","Chcete editovat článek?");
regGS("Article $1 added to $2. $3 from $4. $5 of $6","Článek $1 byl přidán do $2. $3 z $4. $5 z $6");
regGS("Delete article","Smazat článek");
regGS("You do not have the right to delete articles.","Nemáte právo mazat články");
regGS("Are you sure you want to delete the article $1 ($2)?","Určitě chcete smazat článek $1 ($2)?");
regGS("Deleting article","Mazání článku");
regGS("The article $1 ($2) has been deleted.","Článek $1 ($2) byl smazán");
regGS("The article $1 ($2) could not be deleted.","Článek $1 ($2) nemohl být smazán");
regGS("Article $1 ($2) deleted from $3. $4 from $5. $6 ($7) of $8","Článek $1 ($2) byl smazán z $3. 4$ z $5. $6 ($7) z $8");
regGS("Change article status","Změnit stav článku");
regGS("Change the status of article $1 ($2) from $3 to","Změnit stav článku $1 ($2) z $3");
regGS("Changing article status","Změna stavu článku");
regGS("Status of the article $1 ($2) has been changed from $3 to $4.","Stav článku $1 ($2) byl změněn z $3 na $4.");
regGS("Status of the article $1 ($2) could not be changed.","Stav článku $1 ($2) nemohl být změněn");
regGS("You do not have the right to change this article status. Once submitted an article can only changed by authorized users.","Nemáte právo měnit stav tohoto článku. Podané články mohou být změněny pouze autorizovanými uživateli.");
regGS("Article $1 status from $2. $3 from $4. $5 ($6) of $7 changed","Stav článku $1z $2. $3 z $4. $5 ($6) z $7 byl změněn");
regGS("Translate article","Překlat článku");
regGS("You do not have the right to change this article.  You may only edit your own articles and once submitted an article can only changed by authorized users.","Nemáte právo změnit tento článek. Můžete pouze editova své vlastní články. Podané články mohou být změněny pouze autorizovanými uživateli.");
regGS("Edit article details","Editovat detaily článku");
regGS("Simple editor","Jednoduchý editační program");
regGS("Advanced editor","Pokročilý editační program");
regGS("Allow users without subscriptions to view the article","Povolit náhled článku uživatelům bez předplatného");
regGS("Unlocking article","Odemknout článek");
regGS("The article has been unlocked.","Článek byl úspěšně odemknut");
regGS("The article could not be unlocked.","Článek nemohl být odemknut");
regGS("You do not have the right to unlock the article. Once submitted an article can only changed by authorized users.","Nemáte právo odemknout článek. Podaný článek může být změněn pouze autorizovanými uživateli.");
regGS("Changing article details","Změna detailů článku");
regGS("The article has been updated.","Článek byl obnoven");
regGS("The article cannot be updated or no changes have been made.","Článek nemohl být obnoven nebo nebyla provedena žádná změna");
regGS("Edit field: $1","Editovat pole $1");
regGS("Preview article","Náhled článku");
regGS("This article cannot be previewed. Please make sure it has a <B><I>single article</I></B> template selected.","Nelze provést náhled tohoto článku. Zkontrolujte prosím, zda jste správně zvolili šablonu článku.");
regGS("This article has been locked by $1 ($2) at","Článek byl uzamknut $1 ($2) v ");
regGS("Now is $1","Nyní je $1");
regGS("Are you sure you want to unlock it?","Určitě ho chcete odemknout?");
regGS("Edit Article","Editovat článek");

?>
