<?php 
regGS("Delete article $1","删除文章$1");
regGS("Show article on front page","在首页显示文章");
regGS("Show article on section page","在区页显示文章");
regGS("Enter keywords, comma separated","输入关键词，用逗号隔开");
regGS("Adding new article","正在增加新文章");
regGS("You must select an article type.","您必须选择文章类型");
regGS("The article $1 has been created","文章$1被创建");
regGS("The article $1 could not be created","文章$1不能被创建");
regGS("Do you want to edit the article?","您要编辑文章？");
regGS("Article $1 added to $2. $3 from $4. $5 of $6","文章$1被加到$2，$3来自$4。$6中的$5");
regGS("Delete article","删除文字");
regGS("You do not have the right to delete articles.","您无权限删除文章");
regGS("Are you sure you want to delete the article $1 ($2)?","您要删除文章$1($2)");
regGS("Deleting article","正在删除文章");
regGS("The article $1 ($2) has been deleted.","文章$1($2)已被删除");
regGS("The article $1 ($2) could not be deleted.","文章$1($2)不能被删除");
regGS("Article $1 ($2) deleted from $3. $4 from $5. $6 ($7) of $8","文章 $1 ($2)从$3中删除. $4从$5中. $6 ($7)从$8中");
regGS("Change article status","修改文章状态");
regGS("Change the status of article $1 ($2) from $3 to","改变文章$1 ($2) 的状态从$3到");
regGS("Changing article status","正在改变文章状态");
regGS("Status of the article $1 ($2) has been changed from $3 to $4.","文章$1 ($2) 的状态已从$3改变到$4");
regGS("Status of the article $1 ($2) could not be changed.","文章$1 ($2) 的状态不能被改变");
regGS("You do not have the right to change this article status. Once submitted an article can only changed by authorized users.","您无权改变文章状态。提交的文章只能被审定的用户修改");
regGS("Article $1 status from $2. $3 from $4. $5 ($6) of $7 changed","文章$1 的状态从$2. $3 从$4. $5 ($6)从 $7已改变");
regGS("Translate article","翻译文章");
regGS("You do not have the right to change this article.  You may only edit your own articles and once submitted an article can only changed by authorized users.","您无权修改此文章，你只能编辑自己的文章，提交的文章只能由审定的用户修改");
regGS("Edit article details","编辑文章详情");
regGS("Simple editor","简单编辑");
regGS("Advanced editor","高级编辑");
regGS("Allow users without subscriptions to view the article","允许无订阅的用户阅读文章");
regGS("Unlocking article","正在解锁文章");
regGS("The article has been unlocked.","文章已被解锁");
regGS("The article could not be unlocked.","文章不能被解锁");
regGS("You do not have the right to unlock the article. Once submitted an article can only changed by authorized users.","你没有权限去解锁此文章。提交的文章只能由审定的用户修改");
regGS("Changing article details","正在修改文章详情");
regGS("The article has been updated.","文章已被更新");
regGS("The article cannot be updated or no changes have been made.","文章不能被更新，因此无变化");
regGS("Edit field: $1","编辑字段：$1");
regGS("Preview article","预览文章");
regGS("This article cannot be previewed. Please make sure it has a <B><I>single article</I></B> template selected.","文章不能预览，请确认是否选择了单文章模版");
regGS("This article has been locked by $1 ($2) at","文章已被$1 ($2) 锁定在");
regGS("Now is $1","现在是$1");
regGS("Are you sure you want to unlock it?","你确认要解锁？");
regGS("Edit article","编辑文章");

?>