<?
regGS("Delete article $1","Удалить статью $1:ru");
regGS("You do not have the right to add articles.","Вы не имеете права добавления статей:ru");
regGS("Show article on front page","Показать статью на титульной странице:ru");
regGS("Show article on section page","Показать статью на странице секции:ru");
regGS("Enter keywords, comma separated","Введите ключевые слова, разделяя запятой:ru");
regGS("Adding new article","Добавление новой статьи:ru");
regGS("You must select an article type.","Вы должны выбрать тип статьи.:ru");
regGS("The article $1 has been created","Статья $1 была создана:ru");
regGS("The article $1 could not be created","Невозможно создать статью $1:ru");
regGS("Do you want to edit the article?","Хотите редактировать статью?:ru");
regGS("Article $1 added to $2. $3 from $4. $5 of $6","Статья $1 добавлена к $2. $3 из $4. $5 из $6:ru");
regGS("Delete article","Удалить статью:ru");
regGS("You do not have the right to delete articles.","Вы не имеете права удаления статей.:ru");
regGS("Are you sure you want to delete the article $1 ($2)?","Вы уверены, что хотите удалить статью $1 ($2)?:ru");
regGS("Deleting article","Удалени статьи:ru");
regGS("The article $1 ($2) has been deleted.","Статья $1 ($2) была удалена.:ru");
regGS("The article $1 ($2) could not be deleted.","Невозможно удалить статью $1 ($2).:ru");
regGS("Article $1 ($2) deleted from $3. $4 from $5. $6 ($7) of $8","Статья $1 ($2) удалена из $3. $4 из $5. $6 ($7) из $8:ru");
regGS("Change article status","Изменить статус статьи:ru");
regGS("Change the status of article $1 ($2) from $3 to","Изменить статус статьи $1 ($2) из $3 в:ru");
regGS("Changing article status","Изменение статуса статьи:ru");
regGS("Status of the article $1 ($2) has been changed from $3 to $4.","Статус статьи $1 ($2) был изменен из $3 в $4.:ru");
regGS("Status of the article $1 ($2) could not be changed.","Невозможно изменить статус статьи $1 ($2).:ru");
regGS("You do not have the right to change this article status. Once submitted an article can only changed by authorized users.","Вы не имеете права изменения статуса этой статьи. Будучи отправленной, статья может быть изменена только уполномоченными пользователями.:ru");
regGS("Article $1 status from $2. $3 from $4. $5 ($6) of $7 changed","Изменен статус статьи $1 из $2. $3 из $4. $5 ($6) из $7:ru");
regGS("Translate article","Перевести статью:ru");
regGS("You do not have the right to change this article.  You may only edit your own articles and once submitted an article can only changed by authorized users.","Вы не имеете права изменения этой статьи. Вы можете только редактировать свои собственные статьи и, будучи отправленной, статья может быть изменена только уполномоченными пользователями.:ru");
regGS("Edit article details","Редактировать параметры статьи:ru");
regGS("Simple editor","Простой редактор:ru");
regGS("Advanced editor","Улучшенный редактор:ru");
regGS("Allow users without subscriptions to view the article","Позволить пользователям без подписки просматривать статью:ru");
regGS("Unlocking article","Разблокировка статьи:ru");
regGS("The article has been unlocked.","Статья разблокирована:ru");
regGS("The article could not be unlocked.","Невозможно разблокировать статью:ru");
regGS("You do not have the right to unlock the article. Once submitted an article can only changed by authorized users.","Вы не имеете права разблокирования статьи. Будучи отправленной, статья может изменяться только уполномоченными пользователями.:ru");
regGS("Changing article details","Изменение параметров статьи:ru");
regGS("The article has been updated.","Статья была обновлена:ru");
regGS("The article cannot be updated or no changes have been made.","Статья не может быть обновлена или изменения не были сделаны.:ru");
regGS("Edit field: $1","Редактировать поле $1:ru");
regGS("Preview article","Предварительный просмотр статьи:ru");
regGS("This article cannot be previewed. Please make sure it has a <B><I>single article</I></B> template selected.","Эта статья не может быть просмотрена. Пожалуйста убедитесь, что выбран <B><I>единственный</I></B> шаблон статьи.:ru");
regGS("This article has been locked by $1 ($2) at","Эта статья была заблокирована $1 ($2) с:ru");
regGS("Now is $1","Сейчас $1:ru");
regGS("Are you sure you want to unlock it?","Вы уверены, что уверены разблокировать?:ru");
regGS("Edit Article","Редактировать статью:ru");

?>
