tinyMCE.addI18n('es.campsiteinternallink_dlg',{
    title:"Insertar/editar hiperv\u00EDnculo interno",
    language:"Language",
    section:"Section",
    article:"Article",
    publication:"Publication",
    general_tab:"General",
    general_props:"Propiedades generales",
    issue:"Issue",
    target:"Destino",
    target_same:"Abrir en esta ventana / marco",
    target_parent:"Abrir en ventana padre / marco",
    target_top:"Abrir en el marco superior (reemplaza todos los marcos)",
    target_blank:"Abrir en ventana nueva",
    id:"Id",
    style:"Estilo",
    classes:"Clases",
    target_name:"Nombre del Target",
    langdir:"Direcci\u00F3n del lenguaje",
    target_langcode:"Lenguaje del Target",
    langcode:"C\u00F3digo del lenguaje",
    encoding:"Codificaci\u00F3n de caracteres del Target",
    mime:"Tipo MIME del Target",
    rel:"Relaci\u00F3n p\u00E1gina a target",
    rev:"Relaci\u00F3n target a p\u00E1gina",
    tabindex:"\u00CDndice de tabulaci\u00F3n",
    accesskey:"Tecla de acceso",
    ltr:"Izquierda a derecha",
    rtl:"Derecha a izquierda",
    link_list:"Lista de v\u00EDnculo",
    is_email:"La URL que ha introducido parece ser una direci\u00F3n de correo, \u00BFdesea agregar el prefijo mailto: necesario?",
    is_external:"La URL que ha introducido parece ser un v\u00EDnculo externo, \u00BFdesea agregar el prefijo http:// necesario?"
});
