tinyMCE.addI18n('fr.campsiteinternallink_dlg',{
    title:"Ins\u00E9rer/\u00C9diter lien",
    language:"Language",
    section:"Section",
    article:"Article",
    publication:"Publication",
    general_tab:"G\u00E9n\u00E9ral",
    general_props:"Propri\u00E9t\u00E9s g\u00E9n\u00E9rales",
    issue:"Issue",
    target:"Cible",
    target_same:"Ouvrir dans cette fen\u00EAtre / dans ce cadre",
    target_parent:"Ouvrir dans la fen\u00EAtre / le cadre parent",
    target_top:"Ouvrir dans le cadre principal (Remplace tous les cadres)",
    target_blank:"Ouvrir dans une nouvelle fen\u00EAtre",
    id:"Id",
    style:"Style",
    classes:"Classes",
    target_name:"Nom de la cible",
    langdir:"Sens de lecture",
    target_langcode:"Langue de la cible",
    langcode:"Code de la langue",
    encoding:"Encodage de la cible",
    mime:"Type MIME de la cible",
    rel:"Relation de la page \u00E0 la cible",
    rev:"Relation de la cible \u00E0 la page",
    tabindex:"Tabindex",
    accesskey:"Touche d'acc\u00E8s rapide",
    ltr:"Gauche \u00E0 droite",
    rtl:"Droite \u00E0 gauche",
    link_list:"Liste des liens",
    is_email:"L'url que vous avez entr\u00E9 semble \u00EAtre une adresse e-mail, voulez-vous ajouter le pr\u00E9fixe mailto:\u00A0?",
    is_external:"L'url que vous avez entr\u00E9 semble \u00EAtre une adresse web externe, voulez-vous ajouter le pr\u00E9fixe http://\u00A0?"
});
