tinyMCE.addI18n('it.campsiteinternallink_dlg',{
    title:"Inserisci/modifica link",
    language:"Lingua",
    section:"Sezione",
    article:"Articolo",
    publication:"Pubblicazione",
    general_tab:"Generale",
    general_props:"Propriet\u00E0 generali",
    issue:"Edizione",
    target:"Target",
    target_same:"Apri in questa finestra / cornice",
    target_parent:"Apri nella finestra / cornice genitore",
    target_top:"Apri nella cornice superiore (sostituisce tutte le cornici)",
    target_blank:"Apri in una nuova finestra",
    id:"Id",
    style:"Stile",
    classes:"Classe",
    target_name:"Nome target",
    langdir:"Direzione del testo",
    target_langcode:"Lingua del target",
    langcode:"Lingua",
    encoding:"Codifica carattere del target",
    mime:"Tipo MIME del target",
    rel:"Relazione da pagina a target",
    rev:"Relazione da target a pagina",
    tabindex:"Indice tabulazione",
    accesskey:"Carattere di accesso",
    ltr:"Sinistra verso destra",
    rtl:"Destra verso sinistra",
    link_list:"Lista collegamenti",
    is_email:"L'URL inserito sembra essere un indirizzo email. Aggiungere il necessario prefisso mailto: ?",
    is_external:"L'URL inserito sembra essere un link esterno. Aggiungere il necessario prefisso http:// ?"
});
