tinyMCE.addI18n('pt.campsiteinternallink_dlg',{
    title:"Inserir/editar hyperlink",
    language:"Language",
    section:"Section",
    article:"Article",
    publication:"Publication",
    general_tab:"Geral",
    general_props:"Propriedades gerais",
    issue:"Issue",
    target:"Alvo",
    target_same:"Abrir nessa janela/quadro",
    target_parent:"Abrir na janela/quadro pai",
    target_top:"Abrir na p\u00E1gina inteira (substitui todos os quadros)",
    target_blank:"Abrir em nova janela",
    id: "Id",
    style:"Estilo",
    classes:"Classes",
    target_name:"Nome do alvo",
    langdir:"Dire\u00E7\u00E3o do texto",
    target_langcode:"linguagem alvo",
    langcode:"C\u00F3digo da linguagem",
    encoding:"Codifica\u00E7\u00E3o de caracteres",
    mime:"Tipo MIME alvo",
    rel:"Rela\u00E7\u00E3o p\u00E1gina/alvo",
    rev:"Rela\u00E7\u00E3o alvo/p\u00E1gina",
    tabindex:"Tabindex",
    accesskey:"Chave de acesso",
    ltr:"Esquerda para direita",
    rtl:"Direita para esquerda",
    link_list:"Lista de hyperlinks",
    is_email:"A URL digitada parece ser um endere\u00E7o de e-mail. Deseja acrescentar o (necess\u00E1rio) prefixo mailto:?",
    is_external:"A URL digitada parece conduzir a um link externo. Deseja acrescentar o (necess\u00E1rio) prefixo http://?"
});
