tinyMCE.addI18n('sr.campsiteinternallink_dlg',{
    title:"Umetni/uredi poveznicu",
    language:"Language",
    section:"Section",
    article:"Article",
    publication:"Publication",
    general_tab:"Osnovno",
    general_props:"Osnovna svojstva",
    issue:"Issue",
    target:"Meta",
    target_same:"Otovori u novom prozoru / okviru",
    target_parent:"Otvori u izvornom prozoru / okvir",
    target_top:"Otvori u gornjem okviru (zamjenjuje sve okvire)",
    target_blank:"Otvori u novom prozoru",
    id:"Id",
    style:"Stil",
    classes:"Klasa",
    target_name:"Ime mete",
    langdir:"Smjer jezika",
    target_langcode:"Jezik",
    langcode:"Kod jezika",
    encoding:"Kodiranje znakova",
    mime:"MIME tip",
    rel:"Odnos stranice prema meti",
    rev:"Odnos mete prema stranici",
    tabindex:"Tabindex",
    accesskey:"Accesskey",
    ltr:"S leva na desno",
    rtl:"S desna na levo",
    link_list:"Lista poveznica",
    is_email:"URL koji ste uneli izgleda kao e-mail adresa, \u017Eelite li dodati potrebni mailto: prefiks?",
    is_external:"URL koji ste uneli izgleda kao vanjska poveznica, \u017Eelite li dodati potrebni http:// prefiks?"
});
