<?php 
$translator = \Zend_Registry::get('container')->getService('translator');
$this->placeholder('title')->set($translator->trans('Subscriptions')); 
?>
<header>
    <h1><?php echo $translator->trans('Subscriptions'); ?></h1>
    <button id="close-button" class="prime"><?php echo $translator->trans('Done'); ?></button>
</header>

<section>
    <div id="app"></div>
</section>

<script type="text/javascript" src="<?php echo $this->baseUrl('/js/underscore.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('/js/backbone.js'); ?>"></script>
<script type="text/template" id="subscription-list-template">
<a class="add-new" href="#subscription/new"><?php echo $translator->trans('Add new'); ?></a>
<table id="subscription-table">
    <thead>
        <tr>
            <th><?php echo $translator->trans('Publication'); ?></th>
            <th><?php echo $translator->trans('Left to pay'); ?></th>
            <th><?php echo $translator->trans('Type'); ?></th>
            <th><?php echo $translator->trans('Active'); ?></th>
            <th><?php echo $translator->trans('Delete'); ?></th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>
</script>

<script type="text/template" id="ips-list-template">
<h3><?php echo $translator->trans('User IP access list management', array(), 'user_subscriptions'); ?></h3>
<a class="add-new" href="#"><?php echo $translator->trans('Add new'); ?></a>
<table id="ips-table">
    <thead>
        <tr>
            <th><?php echo $translator->trans('Start IP', array(), 'user_subscriptions'); ?></th>
            <th><?php echo $translator->trans('Number of addresses', array(), 'user_subscriptions'); ?></th>
            <th><?php echo $translator->trans('Delete'); ?></th>
        </tr>
    </thead>
    <tbody></tbody>
</table>
</script>

<script type="text/template" id="new-ip-list-template">
<tr class="new">
    <td><input type="number" name="ip[]" min="1" max="255" class="ip" />.<input type="number" name="ip[]" min="0" max="255" class="ip" />.<input type="number" name="ip[]" min="0" max="255" class="ip" />.<input type="number" name="ip[]" min="0" max="255" class="ip" /></td>
    <td><input type="number" name="number" min="1" /></td>
    <td><button class="save"><?php echo $translator->trans('Add new'); ?></button> <button class="cancel"><?php echo $translator->trans('Cancel'); ?></button></td>
</tr>
</script>

<script type="text/template" id="ip-template">
<td><%= ip %></td>
<td><%= number %></td>
<td><button><?php echo $translator->trans('Delete'); ?></button></td>
</script>

<script type="text/template" id="subscription-row-template">
<td class="publication"><a href="<%= link.href %>"><%= publication.name %></a></td>
<td class="toPay"><input type="number" step="0.01" min="0" value="<%= toPay.toFixed(1) %>" /></td>
<td class="type"><%= type === 'P' ? <?php echo json_encode($translator->trans('Paid', array(), 'user_subscriptions')), ':', json_encode($translator->trans('Trial', array(), 'user_subscriptions')); ?> %></td>
<td class="active"><%= active ? <?php echo json_encode($translator->trans('Yes')), ':', json_encode($translator->trans('No')); ?> %></td>
<td class="delete"><button><?php echo $translator->trans('Delete'); ?></button></td>
</script>

<script type="text/template" id="new-subscription-template">
<form method="POST" id="add-view-form">
<dl class="zend_form">
    <dt><?php echo $translator->trans('Publication:'); ?></dt>
    <dd><select name="publication" id="pubs"></select></dd>
    <dt><?php echo $translator->trans('Languages:', array(), 'user_subscriptions'); ?></dt>
    <dd>
        <input type="checkbox" name="individual_languages" value="true" id="il" checked /> <label for="il"><?php echo $translator->trans('Individual languages', array(), 'user_subscriptions'); ?></label><br />
        <select name="languages" size="5" multiple></select>
    </dd>
    <dt><?php echo $translator->trans('Sections', array(), 'user_subscriptions'); ?></dt>
    <dd>
        <input type="radio" name="add_sections" value="true" checked id="sections_1" /> <label for="sections_1"><?php echo $translator->trans('Add sections now', array(), 'user_subscriptions'); ?></label>
        <input type="radio" name="add_sections" value="false" id="sections_2" /> <label for="sections_2"><?php echo $translator->trans('Add sections later', array(), 'user_subscriptions'); ?></label>
    </dd>
    <dt><?php echo $translator->trans('Start'); ?></dt>
    <dd><input type="date" name="start_date" value="<?php echo date('Y-m-d'); ?>" /></dd>
    <dt><?php echo $translator->trans('Subscription type:', array(), 'user_subscriptions'); ?></dt>
    <dd><select name="type">
        <option value="PN"><?php echo $translator->trans('Paid (confirm payment now)', array(), 'user_subscriptions'); ?></option>
        <option value="P"><?php echo $translator->trans('Paid (payment will be confirmed later)', array(), 'user_subscriptions'); ?></option>
        <option value="T"><?php echo $translator->trans('Trial', array(), 'user_subscriptions'); ?></option>
    </select></dd>
    <dt><?php echo $translator->trans('Days:', array(), 'user_subscriptions'); ?></dt>
    <dd><input type="number" name="days" min="1" value="1" /></dd>
    <dt></dt>
    <dd><input type="checkbox" name="active" value="1" checked id="active" /> <label for="active"><?php echo $translator->trans('Active'); ?></label></dd>
    <dt></dt>
    <dd><button class="save"><?php echo $translator->trans('Save'); ?></button> <button class="cancel"><?php echo $translator->trans('Cancel') ?></button></dd>
</dl>
</form>
</script>

<script type="text/javascript">
(function($) {
    var Publication = Backbone.Model.extend({
    });

    var PublicationCollection = Backbone.Collection.extend({model: Publication});

    var Subscription = Backbone.Model.extend({
        initialize: function(attributes) {
            this.sections = new SectionCollection(attributes.sections);
        },

        defaults: {
            publication: null,
            start_date: <?php echo json_encode(date('Y-m-d')); ?>,
            type: '',
            days: 1,
            active: true,
            user: <?php echo json_encode($this->user); ?>,
            toPay: 0.0,
            add_sections: false,
            individual_languages: false,
            languages: [],
            active: false
        },

        parse: function(response) {
            this.sections.reset(response.sections);
            return response;
        },

        validate: function(attrs) {
            if (!attrs.start_date) {
                throw "Provide start date";
            }

            if (!attrs.days || attrs.days < 1) {
                throw "Days must be > 0";
            }

            if (attrs.individual_languages && attrs.languages.length == 0) {
                throw "You must select a languages for individual subscription.";
            }
        }
    });

    var SubscriptionCollection = Backbone.Collection.extend({
        model: Subscription,
        url: <?php echo json_encode($this->url(array('module' => 'admin', 'controller' => 'subscription-rest'), 'rest')); ?>
    });

    var Section = Backbone.Model.extend({
    });

    var SectionCollection = Backbone.Collection.extend({
        model: Section
    });

    var Ip = Backbone.Model.extend({
        defaults: {
            user: <?php echo json_encode($this->user); ?>
        },

        validate: function(attrs) {
            var ip = attrs.ip.split('.');
            <?php foreach (array($translator->trans('first', array(), 'user_subscriptions'), $translator->trans('second', array(), 'user_subscriptions'), $translator->trans('third', array(), 'user_subscriptions'), $translator->trans('forth', array(), 'user_subscriptions')) as $id => $order) { ?>
            if (isNaN(parseInt(ip[<?php echo $id; ?>])) || parseInt(ip[<?php echo $id; ?>]) < 1 || parseInt(ip[<?php echo $id; ?>]) > 255) {
                throw <?php echo json_encode($translator->trans("You must input a number between 0 and 255 into the Start IP address' $1 field.", array('$1' => $order), 'user_subscriptions')); ?>;
            }
            <?php } ?>

            if (isNaN(attrs.number) || attrs.number < 1) {
                throw <?php echo json_encode($translator->trans("You must input a number greater than 0 into the Number of addresses field.", array(), 'user_subscriptions')); ?>;
            }

            if (window.ips.where({ip: attrs.ip}).length) {
                throw <?php echo json_encode($translator->trans("The IP address group conflicts with another existing group.", array(), 'user_subscriptions')); ?>;
            }
        }
    });

    var IpsCollection = Backbone.Collection.extend({
        model: Ip,
        url: <?php echo json_encode($this->url(array('module' => 'admin', 'controller' => 'subscription-ip-rest'), 'rest')); ?>
    });

    var SubscriptionRowView = Backbone.View.extend({
        tagName: "tr",

        events: {
            'click .active': 'toggleActive',
            'click .delete': 'delete',
            'blur input': 'saveToPay'
        },

        initialize: function() {
            this.model.bind('change', this.render, this);
            this.model.bind('sync', this.render, this);
            this.template = _.template($('#subscription-row-template').html());
        },

        render: function() {
            $(this.el).html(this.template(this.model.toJSON()));

            if (this.model.get('active')) {
                $(this.el).addClass('active');
            } else {
                $(this.el).removeClass('active');
            }

            return this;
        },

        toggleActive: function() {
            this.model.save({active: !this.model.get('active')});
        },

        delete: function() {
            this.model.destroy();
            this.collection.remove(this.model);
        },

        saveToPay: function() {
            this.model.save({
                toPay: parseFloat($(this.el).find('input').val())
            });
        }
    });

    var TableView = Backbone.View.extend({
        initialize: function() {
            this.collection.bind('remove', this.render, this);
            this.collection.bind('add', this.render, this);
            this.template = _.template($('#subscription-list-template').html());
        },

        render: function() {
            $(this.el).html(this.template());

            var collection = this.collection;
            var tbody = $(this.el).find('tbody').empty();
            this.collection.each(function(subscription) {
                view = new SubscriptionRowView({model: subscription, collection: collection});
                tbody.append(view.render().el);
            });

            if (this.collection.length === 0) {
                tbody.html('<tr><td colspan="5">' + <?php echo json_encode($translator->trans('No subscriptions', array(), 'user_subscriptions')); ?> + '</td></tr>');
            }

            return this;
        }
    });

    var PublicationSelectView = Backbone.View.extend({
    });


    var EditView = Backbone.View.extend({
        events: {
            'click #save-sections': 'save'
        },

        initialize: function() {
            this.template = _.template($('#edit-subscription-template').html());

            this.model.sections.bind('add', this.renderTable, this);
            this.model.sections.bind('remove', this.renderTable, this);
            this.model.sections.bind('reset', this.renderTable, this);
        },

        render: function() {
            $(this.el).html(this.template(this.model.toJSON()));
            this.renderTable();
            return this;
        },

        renderTable: function() {
            var table = $(this.el).find('tbody').empty();
            var sections = this.model.sections;
            this.model.sections.each(function(section) {
                var view = new SectionView({model: section, sections: sections});
                table.append(view.render().el);
            });
        },

        save: function() {
            this.model.save({sections: this.model.sections.toJSON()});
            window.router.navigate('', true);
        }
    });

    var AddView = Backbone.View.extend({
        events: {
            'click button.save': 'save',
            'click button.cancel': 'cancel',
            'change #pubs': 'renderLanguages',
            'change #il': 'toggleLanguages'
        },

        initialize: function() {
            this.template = _.template($('#new-subscription-template').html());
        },

        render: function(publications) {
            this.options.publications = publications;

            $(this.el).html(this.template());

            var select = $(this.el).find('select[name="publication"]');
            this.options.publications.each(function(publication) {
                select.append($('<option />').attr('value', publication.get('id')).text(publication.get('name')));
            });

            this.renderLanguages();

            return this;
        },

        renderLanguages: function() {
            var select = $(this.el).find('select[name="languages"]').empty();
            var selectedId = $(this.el).find('select[name="publication"]').val();
            this.options.publications.each(function(publication) {
                if (publication.get('id') == selectedId) {
                    _.each(publication.get('languages'), function(language) {
                        select.append($('<option />').attr('value', language.id).text(language.name));
                    });
                }
            });
        },

        save: function(e) {
            e.preventDefault();

            try {
                window.subscriptions.create({
                    publication: parseInt($(this.el).find('select[name="publication"]').val()),
                    active: $(this.el).find('input[name="active"]:checked').size() == 1,
                    start_date: $(this.el).find('input[name="start_date"]').val(),
                    type: $(this.el).find('select[name="type"]').val(),
                    days: parseInt($(this.el).find('input[name="days"]').val()),
                    add_sections: $(this.el).find('input[name="add_sections"]:checked').val() == 'true',
                    individual_languages: $(this.el).find('input[name="individual_languages"]:checked').val() == 'true',
                    languages: $(this.el).find('select[name="languages"]').val() || []
                }, {wait: true});

                router.navigate('', true);
            } catch (error) {
                alert(error);
            }
        },
        
        cancel: function() {
            router.navigate('', true);
        },

        toggleLanguages: function(e) {
            if (e.target.checked) {
                $(this.el).find('select[name="languages"]').show();
            } else {
                $(this.el).find('select[name="languages"]').hide();
            }
        }
    });

    var SectionView = Backbone.View.extend({
        tagName: "tr",

        events: {
            'click button.delete': 'delete'
        },

        initialize: function() {
            this.template = _.template($('#section-row-template').html());
        },

        render: function() {
            $(this.el).html(this.template(this.model.toJSON()));
            return this;
        },

        delete: function() {
            this.options.sections.remove(this.model);
            this.remove();
        }
    });

    var IpView = Backbone.View.extend({
        tagName: "tr",
        template: _.template($('#ip-template').html()),

        events: {
            'click button': 'delete'
        },

        render: function() {
            $(this.el).html(this.template(this.model.toJSON()));
            return this;
        },

        delete: function() {
            this.model.destroy();
            this.remove();
        }
    });

    var IpsView = Backbone.View.extend({
        events: {
            'click .add-new': 'add',
            'click .save': 'save',
            'click .cancel': 'cancel'
        },

        template: _.template($('#ips-list-template').html()),

        initialize: function() {
            this.collection.bind('add', this.render, this);
            this.collection.bind('remove', this.render, this);
        },

        render: function() {
            $(this.el).html(this.template());
            var tbody = $(this.el).find('tbody').empty();
            this.collection.each(function(ip) {
                var view = new IpView({model: ip});
                tbody.append(view.render().el);
            });

            if (this.collection.length === 0) {
                tbody.append('<tr />').html('<td colspan="3">' + <?php echo json_encode($translator->trans('No records.', array(), 'user_subscriptions')); ?> + '</td>');
            }

            return this;
        },

        add: function(e) {
            var template = _.template($('#new-ip-list-template').html());
            $(this.el).find('tbody').append(template());
        },

        save: function() {
            var ip = [];
            $(this.el).find('tr.new td:first input').each(function() {
                ip.push(parseInt($(this).val()));
            });

            try {
                this.collection.create({
                    ip: ip.join('.'),
                    number: parseInt($(this.el).find('tr.new input[name="number"]').val())
                }, {wait: true});
                $(this.el).find('tr.new').detach();
            } catch (err) {
                alert(err);
            }
        },
        
        cancel: function() {
            $(this.el).find('.new').detach();
        }
    });

    var Workspace = Backbone.Router.extend({
        routes: {
            'subscription/new': 'new',
            '': 'index'
        },

        initialize: function() {
            this.tableView = new TableView({collection: window.subscriptions});
            this.ipsView = new IpsView({collection: window.ips});
            this.addView = new AddView();
        },

        index: function() {
            $('#app').html(this.tableView.render().el);
            $('#app').append(this.ipsView.render().el);
            this.ipsView.delegateEvents();
        },

        'new': function() {
            var subscribed = window.subscriptions.map(function(subscription) {
                return subscription.get('publication').id;
            }) || [];

            var available = new PublicationCollection();
            window.publications.each(function(publication) {
                if (subscribed.indexOf(publication.get('id')) === -1) {
                    available.add(publication);
                }
            });

            if (available.length !== 0) {
                $('#app').html(this.addView.render(available).el);
            } else {
                alert(<?php echo json_encode($translator->trans("You have subscription for all available publications", array(), 'user_subscriptions')); ?>);
                this.navigate('');
            }
        }
    });

    $(function() {
        window.subscriptions = new SubscriptionCollection(<?php echo json_encode(array_map(array($this, 'subscriptionJson'), $this->subscriptions)); ?>);
        window.publications = new PublicationCollection(<?php echo json_encode(array_map(function($publication) {
            return array(
                'id' => $publication->getId(),
                'name' => $publication->getName(),
                'languages' => array_map(function($language) {
                    return array(
                        'id' => $language->getId(),
                        'name' => $language->getName(),
                    );
                }, $publication->getLanguages()),
            );
        }, $this->publications)); ?>);
        window.ips = new IpsCollection(<?php echo json_encode(array_map(array($this, 'subscriptionIpJson'), $this->ips)); ?>);
        window.router = new Workspace();
        Backbone.history.start();
        $('#close-button').click(function() {
            parent.$.fancybox.close();
        });
    });
})(jQuery);
</script>
