<?php
regGS("Add section to all subscriptions.", "Agregar secciones a todas las suscripciones.");
regGS("Delete section from all subscriptions.", "Eliminar la sección de todas las suscripciones.");
regGS("A total of $1 subscriptions were updated.", "Un total de $! suscripciones fueron actualizadas.");
regGS("Name<BR><SMALL>(click to see articles)</SMALL>", "Nombre");
regGS("Delete section $1", "Borrar sección $1");
regGS("Adding new section", "Agregando nuevas secciones");
regGS("You do not have the right to add sections.", "No tiene derecho a agregar nuevas secciones");
regGS("The section $1 has been successfuly added.", "La sección $1 ha sido agregada con éxito");
regGS("Please check if another section with the same number does not already exist.", "Favor revise si otra sección con el mismo número no existe ya");
regGS("Select the section", "Seleccionar la sección");
regGS("Section $1 added to issue $2. $3 ($4) of $5", "Sección $1 agregada a edición $2. $3 (4) de $5");
regGS("Delete section", "Borrar sección");
regGS("You do not have the right to delete sections.", "No tiene derecho a borrar secciones");
regGS("Are you sure you want to delete the section $1?", "¿Esta seguro de querer borrar sección $1?");
regGS("Deleting section", "Borrando sección");
regGS("The section $1 has been deleted.", "La sección $1 ha sido borrada");
regGS("Section $1 deleted from issue $2. $3 $4 of $5", "Sección $1 borrada e edición $2. $3 $4 de $5");
regGS("Change section name", "Cambiar nombre de sección");
regGS("You do not have the right to change section details", "No tiene derecho a cambiar detalles de sección");
regGS("Updating section name", "Actualizando nombre de secciones");
regGS("The section $1 has been successfuly modified.", "La sección $1 fue modificada con éxito");
regGS("The section could not be changed.", "La sección no pudo ser cambiada");
regGS("Section $1 updated to issue $2. $3 ($4) of $5", "Sección $1 actualizada a edición $2. 3 ($4) de $5");
regGS("Name<BR><SMALL>(click to add article)</SMALL>", "Nombre");
regGS("Duplicate section", "Seccion Duplicada");
regGS("The destination issue is the same as the source issue.", "La edición destino es la misma que la edición fuente.");
regGS("Destination section number", "Numero de seccion destino");
regGS("Error updating subscriptions.", "Error al actualizar suscripciones.");
regGS("Duplicating section", "Duplicando seccion");
regGS("The section $1 could not be duplicated", "la seccion $1 no puede ser duplicada");
regGS("Section $1 has been duplicated to $2. $3 of $4", "La seccion $1 ha sido duplicada a $2, $3 de $4");
?>