<?php
regGS("Add section to all subscriptions.", "أضف باب لكل الإشتراكات");
regGS("Delete section from all subscriptions.", "إلغ الباب من كل الاشتراكات");
regGS("A total of $1 subscriptions were updated.", "تم تحديث 1$ الاشتراكات");
regGS("Name<BR><SMALL>(click to see articles)</SMALL>", "الاسم <br> (إضغط لترى المقالات)");
regGS("Delete section $1", "الغاء الباب $1");
regGS("Adding new section", "إضافة باب جديد");
regGS("You do not have the right to add sections.", "لا يحق لك إضافة أبواب");
regGS("The section $1 has been successfuly added.", "تمت إضافة الباب $1");
regGS("Please check if another section with the same number does not already exist.", "الرجاء التأكد من عدم وجود باب يحمل الرقم نفسه");
regGS("Select the section", "إختر الباب");
regGS("Section $1 added to issue $2. $3 ($4) of $5", " إضافة الباب $1 إلى الإصدار $2 $3 ($4) من $5");
regGS("Delete section", "إلغ الباب");
regGS("You do not have the right to delete sections.", "لا يحق لك إلغاء الابواب");
regGS("Are you sure you want to delete the section $1?", "هل أنت متأكد من أنك تريد إلغاء الباب $1؟");
regGS("Deleting section", "إلغاء الباب ");
regGS("The section $1 has been deleted.", "تمّ إلغاء الباب $1 ");
regGS("Section $1 deleted from issue $2. $3 $4 of $5", "الغي الباب $1 من الإصدار $2 $3 و$4 من$5");
regGS("Configure section", "إعدادات القسم");
regGS("You do not have the right to change section details", "لا يحق لك تغيير تفاصيل الباب");
regGS("Updating section name", "تحديث اسم الباب");
regGS("The section $1 has been successfuly modified.", "تم تعديل الباب $1");
regGS("The section could not be changed.", "ليس في الإمكان تغيير الباب");
regGS("Section $1 updated to issue $2. $3 ($4) of $5", "تم تحديث الباب $1 الإصدار $2. $3 ($4) من $5");
regGS("Name<BR><SMALL>(click to add article)</SMALL>", "الاسم<br> (إضغط لإضافة المقال)");
regGS("Duplicate section", "كرر القسم");
regGS("The destination issue is the same as the source issue.", "العدد الهدف هو نفسه العدد المصدر");
regGS("Destination section number", "رقم القسم الهدف");
regGS("Error updating subscriptions.", "خطأ في تحديث الاشتراكات");
regGS("Duplicating section", "تكرير القسم");
regGS("The section $1 could not be duplicated", "لم يتم تكرير القسم 1$");
regGS("Section $1 has been duplicated to $2. $3 of $4", "تم تكرير القسم 1$ الى 2$ ، 3$ من 4$");
regGS("You do not have the right to modify sections.", "لا تملك صلاحية تعديل الاقسام");
?>