<?php
regGS("Add section to all subscriptions.", "Додај рубрику у све претплате.");
regGS("Delete section from all subscriptions.", "Обриши рубрику из свих претплата.");
regGS("A total of $1 subscriptions were updated.", "Укупан број измењених претплата: $1.");
regGS("Name<BR><SMALL>(click to see articles)</SMALL>", "Назив");
regGS("Delete section $1", "Обриши рубрику");
regGS("Adding new section", "Додавање нове рубрике");
regGS("You do not have the right to add sections.", "Немате право да додајете рубрике");
regGS("The section $1 has been successfuly added.", "Рубрика $1 успешно је додата");
regGS("Please check if another section with the same number does not already exist.", "Проверите да ли већ не постоји рубрика са истим бројем");
regGS("Select the section", "Изабери рубрику");
regGS("Section $1 added to issue $2. $3 ($4) of $5", "Рубрика $1 додата у издање $2. $3 ($4) од $5");
regGS("Delete section", "Обриши рубрику");
regGS("You do not have the right to delete sections.", "Немате право брисања рубрика");
regGS("Are you sure you want to delete the section $1?", "Да ли сте сигурни да желите да обришете рубрику $1? ");
regGS("Deleting section", "Брисање рубрика");
regGS("The section $1 has been deleted.", "Рубрика $1 је обрисана");
regGS("Section $1 deleted from issue $2. $3 $4 of $5", "Рубрика $1 је обрисана из издања $2. $3 $4 од $5");
regGS("Configure section", "Подеси рубрику");
regGS("You do not have the right to change section details", "Немате право да мењате податке о рубрици");
regGS("Updating section name", "Мењање имена рубрике");
regGS("The section $1 has been successfuly modified.", "Рубрика $1 је успешно измењена");
regGS("The section could not be changed.", "Рубрика не може бити измењена");
regGS("Section $1 updated to issue $2. $3 ($4) of $5", "Рубрика $1 је измењена у издању $2. $3 ($4) од $5");
regGS("Name<BR><SMALL>(click to add article)</SMALL>", "Назив <br><small>(кликните да додате текст)</small>");
regGS("Duplicate section", "Дуплирај рубрику");
regGS("The destination issue is the same as the source issue.", "Циљно издање је исто као матично.");
regGS("Destination section number", "Број циљне рубрике");
regGS("Error updating subscriptions.", "Грешка при мењању претплата.");
regGS("Duplicating section", "Дуплирање рубрике");
regGS("The section $1 could not be duplicated", "Рубрика  $1 не може бити дуплирана");
regGS("Section $1 has been duplicated to $2. $3 of $4", "рубрика $1 је дуплирана у $2. $3 од $4");
regGS("You do not have the right to modify sections.", "Немате право да мењате рубрике.");
?>