<?php
regGS("Add section to all subscriptions.","Add section to all subscriptions.:en");
regGS("Delete section from all subscriptions.","Delete section from all subscriptions.:en");
regGS("A total of $1 subscriptions were updated.","A total of $1 subscriptions were updated.:en");
regGS("Name<BR><SMALL>(click to see articles)</SMALL>","Name <SMALL>(click to see articles)</SMALL>:en");
regGS("Delete section $1","Delete section $1:en");
regGS("Adding new section","Adding new section:en");
regGS("You do not have the right to add sections.","You do not have the right to add sections.:en");
regGS("The section $1 has been successfuly added.","The section $1 has been successfuly added.:en");
regGS("Please check if another section with the same number does not already exist.","Please check if another section with the same number does not already exist.:en");
regGS("Select the section","Select the section:en");
regGS("Section $1 added to issue $2. $3 ($4) of $5","Section $1 added to issue $2. $3 ($4) of $5:en");
regGS("Delete section","Delete section:en");
regGS("You do not have the right to delete sections.","You do not have the right to delete sections.:en");
regGS("Are you sure you want to delete the section $1?","Are you sure you want to delete the section $1?:en");
regGS("Deleting section","Deleting section:en");
regGS("The section $1 has been deleted.","The section $1 has been deleted.:en");
regGS("Section $1 deleted from issue $2. $3 $4 of $5","Section $1 deleted from issue $2. $3 $4 of $5:en");
regGS("Configure section","Configure section:en");
regGS("You do not have the right to change section details","You do not have the right to change section details:en");
regGS("Updating section name","Updating section name:en");
regGS("The section $1 has been successfuly modified.","The section $1 has been successfuly modified.:en");
regGS("The section could not be changed.","The section could not be changed.:en");
regGS("Section $1 updated to issue $2. $3 ($4) of $5","Section $1 updated to issue $2. $3 ($4) of $5:en");
regGS("Name<BR><SMALL>(click to add article)</SMALL>","Name<BR><SMALL>(click to add article)</SMALL>:en");
regGS("Duplicate section", "Duplicate section:en");
regGS("The destination issue is the same as the source issue.", "The destination issue is the same as the source issue.:en");
regGS("Error updating subscriptions.", "Error updating subscriptions.:en");
regGS("Duplicating section", "Duplicating section:en");
regGS("The section $1 could not be duplicated", "The section $1 could not be duplicated:en");
regGS("Section $1 has been duplicated to $2. $3 of $4", "Section $1 has been duplicated to $2. $3 of $4:en");
regGS("You do not have the right to modify sections.", "You do not have the right to modify sections.:en");
regGS("Delete all articles from the section.", "Delete all articles from the section.:en");
regGS("A total of $1 articles were deleted.", "A total of $1 articles were deleted.:en");
regGS("Duplicate Section:", "Duplicate Section::en");
regGS("Existing Section", "Existing Section:en");
regGS("Go to new section", "Go to new section:en");
regGS("Go to source section", "Go to source section:en");
regGS("New Section", "New Section:en");
regGS("Please select either '$1' or '$2'.", "Please select either '$1' or '$2'.:en");
regGS("Select destination section:", "Select destination section::en");
regGS("OR", "OR:en");
regGS("Short Name", "Short Name:en");
regGS("The section number specified already exists, please specify a different value or use the dropdown to find an existing section.", "The section number specified already exists, please specify a different value or use the dropdown to find an existing section.:en");
regGS("Warning", "Warning:en");
regGS("You must select a section.", "You must select a section.:en");
regGS("You must specify a name for the section.", "You must specify a name for the section.:en");
?>