#!/bin/bash

DATABASE_USER=root
DATABASE_PASSWORD=
DATABASE_NAME=newscoop

if [ "$1" != "" ]; then
    DATABASE_NAME=$1
fi
if [ "$DATABASE_PASSWORD" != "" ]; then
    password_string="-p$DATABASE_PASSWORD"
fi

TABLES="
 Aliases\
 ArticleAttachments\
 ArticleAuthors\
 ArticleImages\
 ArticleIndex\
 ArticlePublish\
 ArticleTopics\
 ArticleTypeMetadata\
 Articles\
 Attachments\
 AuthorAliases\
 AuthorAssignedTypes\
 AuthorBiographies\
 AuthorTypes \
 Authors\
 AutoId\
 EnumerationElements\
 Enumerations\
 Images\
 IssuePublish\
 Issues\
 KeywordIndex\
 LocationContents\
 Locations\
 Log\
 MapLocationLanguages\
 MapLocationMultimedia\
 MapLocations\
 Maps\
 Multimedia\
 ObjectTypes\
 Plugins\
 Publications\
 RequestObjects\
 RequestStats\
 Requests\
 Sections\
 SubsDefTime\
 SubsSections\
 Subscriptions\
 Templates\
 TopicFields\
 TopicNames\
 Topics\
 Translations\
 Xlink\
 Xnews\
 Xpage\
 acl_role\
 acl_rule\
 comment\
 comment_commenter\
 comment_acceptance\
 liveuser_grouprights\
 liveuser_groups\
 liveuser_groups_group_id_seq\
 liveuser_groupusers\
 liveuser_perm_users\
 liveuser_perm_users_perm_user_id_seq\
 liveuser_rights\
 liveuser_rights_right_id_seq\
 liveuser_users\
 liveuser_users_auth_user_id_seq\
 output\
 output_issue\
 output_section\
 output_theme\
 plugin_blog_blog\
 plugin_blog_comment\
 plugin_blog_entry\
 plugin_blog_entry_topic\
 plugin_blog_topic\
 plugin_interview_interviews\
 plugin_interview_items\
 plugin_poll\
 plugin_poll_answer\
 plugin_poll_article\
 plugin_poll_issue\
 plugin_poll_publication\
 plugin_poll_section\
 plugin_pollanswer_attachment\
 resource"

mysqldump -u $DATABASE_USER $password_string -t --insert-ignore \
  $DATABASE_NAME $TABLES > campsite_demo_data.sql
mysqldump -u $DATABASE_USER $password_string -d --insert-ignore \
  $DATABASE_NAME $TABLES > campsite_demo_tables.sql
