set names utf8;

TRUNCATE CityLocations;
ALTER TABLE CityLocations DISABLE KEYS;
LOAD DATA LOCAL INFILE 'CityLocations.csv' INTO TABLE CityLocations FIELDS
TERMINATED BY ';' ENCLOSED BY '"';
ALTER TABLE CityLocations ENABLE KEYS;

TRUNCATE CityNames;
ALTER TABLE CityNames DISABLE KEYS;
LOAD DATA LOCAL INFILE 'CityNames.csv' INTO TABLE CityNames FIELDS
TERMINATED BY ';' ENCLOSED BY '"';
ALTER TABLE CityNames ENABLE KEYS;

