ROOT_DIR= .

TPL_CGI=tpl_cgi

all: $(TPL_CGI)

clean:
	rm -f *.o *~ $(TPL_CGI)
	for l in $(LINKS); do rm -f $$l; done

install: all
	mkdir -p $(CGI_BIN)
	cp -f $(TPL_CGI) $(CGI_BIN)

uninstall: dummy
	rm -f $(CGI_BIN)/$(TPL_CGI)

package: all
	mkdir -p $(PACKAGE_DIR)/tpl_cgi
	cp -f Makefile $(PACKAGE_DIR)/tpl_cgi
	cp -f $(TPL_CGI) $(PACKAGE_DIR)/tpl_cgi

dummy:
