#!/bin/sh

################################################################################
#
# CAMPSITE is a Unicode-enabled multilingual web content
# management system for news publications.
# CAMPFIRE is a Unicode-enabled java-based near WYSIWYG text editor.
# Copyright (C)2000,2001  Media Development Loan Fund
# contact: contact@campware.org - http://www.campware.org
# Campware encourages further development. Please let us know.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
################################################################################

#export HTTP_COOKIE="TOL_Debug=on; TOL_Preview=on"

if [ ! -d ./res ]; then
    mkdir ./res
fi

REMOTE_ADDR="192.168.0.54"
DOCUMENT_ROOT="/var/www/html/"
HTTP_COOKIE="TOL_UserId=11; TOL_UserKey=1; TOL_Debug=off; TOL_Preview=off"
REQUEST_METHOD="GET"

let i=0
echo ""
echo -n "Loops: "
while true; do
    let i=$i+1

    PATH_INFO="/look/example/search.tpl"
    QUERY_STRING="IdLanguage=1&IdPublication=1&NrIssue=1&NrSection=2&SearchKeywords=the&search=Search"
    ./run_cgi "$REMOTE_ADDR" "$DOCUMENT_ROOT" "$PATH_INFO" "$REQUEST_METHOD" "$QUERY_STRING" "$HTTP_COOKIE" > ./res/${i}_search_res.html &

    PATH_INFO="/look/example/article.tpl"
    QUERY_STRING="IdLanguage=1&IdPublication=1&NrIssue=1&NrSection=2&NrArticle=4&ST1=content&ST_T1=special&ST_PS1=4&ST_AS1=1&ST_max=1&SrLStart=3"
    ./run_cgi "$REMOTE_ADDR" "$DOCUMENT_ROOT" "$PATH_INFO" "$REQUEST_METHOD" "$QUERY_STRING" "$HTTP_COOKIE" > ./res/${i}_article_res.html &

    PATH_INFO="/look/example/section.tpl"
    QUERY_STRING="IdLanguage=1&IdPublication=1&NrIssue=1&NrSection=1"
    ./run_cgi "$REMOTE_ADDR" "$DOCUMENT_ROOT" "$PATH_INFO" "$REQUEST_METHOD" "$QUERY_STRING" "$HTTP_COOKIE" > ./res/${i}_section1_res.html &

    PATH_INFO="/look/example/section.tpl"
    QUERY_STRING="IdLanguage=1&IdPublication=1&NrIssue=1&NrSection=2"
    ./run_cgi "$REMOTE_ADDR" "$DOCUMENT_ROOT" "$PATH_INFO" "$REQUEST_METHOD" "$QUERY_STRING" "$HTTP_COOKIE" > ./res/${i}_section2_res.html &

    PATH_INFO="/look/example/issue.tpl"
    QUERY_STRING="IdLanguage=1&IdPublication=1&NrIssue=1"
    ./run_cgi "$REMOTE_ADDR" "$DOCUMENT_ROOT" "$PATH_INFO" "$REQUEST_METHOD" "$QUERY_STRING" "$HTTP_COOKIE" > ./res/${i}_issue_res.html &

    PATH_INFO="/look/example/article.tpl"
    QUERY_STRING="IdLanguage=1&IdPublication=1&NrIssue=1&NrSection=1&NrArticle=2&ST1=content&ST_T1=special&ST_max=1"
    ./run_cgi "$REMOTE_ADDR" "$DOCUMENT_ROOT" "$PATH_INFO" "$REQUEST_METHOD" "$QUERY_STRING" "$HTTP_COOKIE" > ./res/${i}_article2_res.html &

#    usleep 100000
    echo -n -e "\rLoops: $i"
done
