#!/bin/bash

force=$1

if [ "$force" != "-f" ]; then
	echo "Please confirm that you want to remove all campsite instances!"
	echo -n "Confirmation (Y/N) [N]: "
	read confirm
	if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
		exit 0
	fi
fi

call_dir=`dirname "$0"`
if [ "$call_dir" != "." ]; then
	call_dir=`dirname "$call_dir"`
fi
. "$call_dir/make.env"
if [ $? -ne 0 ]; then
	exit 1
fi

pushd "$ETC_DIR" > /dev/null
if [ $? -ne 0 ]; then
	exit 1
fi

for inst_name in *; do
	if [ -d "$inst_name" ]; then
		echo -n "Removing instance $inst_name ..."
		"$BIN_DIR/campsite-remove-instance" $inst_name
		echo "done"
	fi
done

popd > /dev/null
