<h1><?php putGS('Logs'); ?></h1>

<?php echo $this->form->setAttrib('class', 'filter'); ?>

<?php
if (empty($this->logs)) { // no logs
    $this->renderMessage(getGS('No logs.'));
    return;
} ?>

<?php echo $this->render('pager.phtml'); ?>

<table>
    <caption><?php putGS('Logs'); ?> <?php if (isset($this->event)) { echo '/ ', $this->event->getName(); } ?></caption>
    <tr>
        <th><?php putGS('Date/Time'); ?></th>
        <th><?php putGS('Severity'); ?></th>
        <th><?php putGS('Description'); ?></th>
        <th><?php putGS('User'); ?></th>
        <th><?php putGS('User IP Address'); ?></th>
    </tr>
    <?php foreach ($this->logs as $log) { ?>
    <tr class="<?php echo $log->getPriority(); ?>">
        <td><?php echo $log->getTimeCreated()->format('Y-m-d H:i:s'); ?></td>
        <td><?php echo $this->priorityNames[$log->getPriority()]; ?></td>
        <td><?php echo $this->escape($log->getText()); ?></td>
        <td><?php echo $log->getUserName(); ?></td>
        <td><?php echo $log->getClientIP(); ?></td>
    </tr>
    <?php } ?>
</table>

<?php echo $this->render('pager.phtml'); ?>
