<?php
regGS("CAMPSITE", "CAMPSITE");
regGS("Home", "Inicio");
regGS("Logout", "Salir");
regGS("Fields", "Campos");
regGS("Delete", "Borrar");
regGS("Type", "Tipo");
regGS("Name", "Nombre");
regGS("Keyword", "Palabra Clave");
regGS("Infotypes", "Infotypes");
regGS("Languages", "Idiomas");
regGS("Native name", "Nombre local");
regGS("Code", "Código");
regGS("Code page", "Página de código");
regGS("Edit", "Editar");
regGS("Countries", "Países");
regGS("Reader", "Lector");
regGS("Access", "Acceso");
regGS("Login", "Entrada");
regGS("Password", "Clave");
regGS("Site", "Sitio");
regGS("Currency", "Moneda");
regGS("Templates", "Plantillas");
regGS("Topics", "Temas");
regGS("Path", "Paso");
regGS("Go up", "Subir");
regGS("Duplicate", "Duplicar");
regGS("Select destination", "Seleccionar Destino");
regGS("No languages", "Sin idioma");
regGS("---Select language---", "---Seleccione idioma---");
regGS("No publications", "Sin publicaciones");
regGS("---Select publication---", "---Seleccione publicacion---");
regGS("No issues", "Sin ediciones");
regGS("---Select issue---", "---Seleccione edición---");
regGS("No sections", "Sin secciones");
regGS("---Select section---", "---Seleccione sección---");
regGS("No articles", "Sin artículos");
regGS("---Select article---", "---Seleccione artículo---");
regGS("Language", "Idioma");
regGS("Keyword infotype", "Palabra clave de infotype");
regGS("Translation", "Traducción");
regGS("Infotype", "Infotype");
regGS("Country", "País");
regGS("User name", "Nombre de usuario");
regGS("Definition", "Definición");
regGS("Publication", "Publicación");
regGS("Default language", "Idioma inicial");
regGS("Time Unit", "Unidad de tiempo");
regGS("Unit Cost", "Costo unitario");
regGS("Subscriptions", "Suscripciones");
regGS("Issue", "Edición");
regGS("Number", "Número");
regGS("Section", "Sección");
regGS("Keywords", "Palabras claves");
regGS("Topic", "Tema");
regGS("Next", "Próximo");
regGS("Previous", "Previo");
regGS("Translate", "Traducir");
regGS("Details", "Detalles");
regGS("View", "Ver");
regGS("days", "días");
regGS("Article Types", "Tipo Artículo");
regGS("User Types", "Tipo Usuario");
regGS("Glossary", "Glosario");
regGS("Keyword infotypes", "Palabra clave infotypes");
regGS("Publications", "Publicaciones");
regGS("Issues", "Ediciones");
regGS("Sections", "Secciones");
regGS("Articles", "Artículos");
regGS("Images", "Imágenes");
regGS("Nr", "No.");
regGS("Change", "Cambiar");
regGS("Add new issue", "Agregar nueva edición");
regGS("Add new topic", "Agregar nuevo tema");
regGS("Delete topic", "Borrar tema");
regGS("Default Language", "Idioma Inicial");
regGS("Subscription Default Time", "Tiempo Subscripción Normal");
regGS("Pay Period", "Período de Pago");
regGS("Info", "Info");
regGS("Trial Period", "Tiempo de Prueba");
regGS("Paid Period", "Período de Pago");
regGS("Preview", "Vista previa");
regGS("You must complete the $1 field.", "Debe completar el campo $1");
regGS("No such language.", "No existe idioma");
regGS("No such infotype.", "No existe infotype");
regGS("No such keyword.", "No existe palabra clave");
regGS("Publication does not exist.", "No existe publicación");
regGS("No such country.", "No existe país");
regGS("No such issue.", "No existe edición");
regGS("Topic does not exist.", "No existe tema");
regGS("You must select a language.", "Debe seleccionar un idioma");
regGS("No such section.", "No existe sección");
regGS("No articles.", "Sin articulos");
regGS("Access denied", "Acceso denegado");
regGS("Invalid article identifier", "Identificar de articulo invalido");
regGS("Invalid destination section selected", "La seccion destino seleccionada es invalida");
regGS("Internal error: identifiers not initialized", "Error interno: Identificadores n o inicializados");
regGS("Internal database error", "Error interno en la base de datos");
regGS("Invalid parameters received", "Los parametros recibidos son invalidos");
regGS("Add new article", "Agregar nuevo articulo");
regGS("Status", "Estatus");
regGS("No such article.", "No existe articulo");
regGS("Published", "Publicado");
regGS("Not published", "No publicado");
regGS("Submitted", "Enviado");
regGS("New", "Nuevo");
regGS("Article", "Artículo");
regGS("Publish", "Publicar");
regGS("Unpublish", "No publicar");
regGS("Unlock", "Desbloquear");
regGS("Uploaded", "Subido");
regGS("(yyyy-mm-dd)", "aaaa-mm-dd");
regGS("YYYY-MM-DD", "AAAA-MM-DD");
regGS("Submit", "Enviar");
regGS("Field", "Campo");
regGS("Edit details", "Editar detalles");
regGS("No such image.", "No existe imagen");
regGS("Image", "Imagen");
regGS("Description", "Descripción");
regGS("Photographer", "Fotógrafo");
regGS("Place", "Lugar");
regGS("Date", "Fecha");
regGS("Publ. no.", "Publ. No.");
regGS("Issue no.", "Edición no.");
regGS("Section no.", "Sección no.");
regGS("Image number", "Número de imagen");
regGS("Users", "Usuarios");
regGS("User is a reader", "Usuario es lector");
regGS("User may add/change publications", "Usuario puede agregar/cambiar publicaciones");
regGS("User may delete publications", "Usuario puede borrar publicaciones");
regGS("User may add/change issues", "Usuario puede agregar/cambiar ediciones");
regGS("User may delete issues", "Usuario puede borrar ediciones");
regGS("User may add/change sections", "Usuario puede agregar/cambiar secciones");
regGS("User may delete sections", "Usuario puede borrar secciones");
regGS("User may add articles", "Usuario puede agregar articulos");
regGS("User may change articles", "Usuario puede cambiar articulos");
regGS("User may delete articles", "Usuario puede borrar articulos");
regGS("User may add images", "Usuario puede agregar imagenes");
regGS("User may change images", "Usuario puede cambiar imagenes");
regGS("User may delete images", "Usuario puede borrar imagenes");
regGS("User may add templates", "Usuario puede agregar plantillas");
regGS("User may delete templates", "Usuario puede borrar plantillas");
regGS("User may add/change user accounts and passwords", "Usuario puede agregar/cambiar cuentas y claves");
regGS("User may delete user accounts", "Usuario puede borrar cuentas");
regGS("User may manage user subscriptions", "Usuario puede manejar suscripciones de usuarios");
regGS("User may manage account types", "Usuario puede manejar tipo de cuentas");
regGS("User may add/change article types", "Usuario puede agregar/cambiar tipo de articulos");
regGS("User may delete article types", "Usuario puede borrar tipo de articulos");
regGS("User may add languages and manage language information", "Usuario puede agregar idiomas y manejar información de idiomas");
regGS("User may delete languages", "Usuario puede borrar idiomas");
regGS("User may manage glossary infotypes", "Usuario puede manejar glosario infotypes");
regGS("User may add/change glossary entries", "Usuario puede agregar/cambiar entradas al glosario");
regGS("User may delete glossary entries", "Usuario puede borrar entradas al glosario");
regGS("User will be notified on several events", "Usuario sera notificado en varios eventos");
regGS("User may view audit logs", "Usuario puede ver historial de auditoria");
regGS("User may add/change country names", "Usuario puede agregar/cambiar nombre de países");
regGS("User may delete country entries", "Usuario puede borrar entrada de países");
regGS("User may manage localizer", "Usuario puede manejar el localizador");
regGS("User may manage indexer", "Usuario puede manejar el Indexador");
regGS("User may publish articles", "Usuario puede publicar artículos");
regGS("User may manage topics", "Usuario puede manejar temas");
regGS("Adding new translation", "Agregar nueva traducción");
regGS("Translate keyword", "Traducir palabra clave");
regGS("No more languages.", "No más idiomas");
regGS("No such keyword infotype.", "No existe palabra clave infotype");
regGS("Adding new keyword infotype", "Agregando nueva palabra clave infotype");
regGS("The infotype has been deleted.", "El infotype ha sido borrado");
regGS("The infotype could not be deleted.", "El infotype no pudo ser borrado");
regGS("Add new publication", "Agregar nueva publicación");
regGS("Upload new template", "Subir nuevo template");
regGS("Add new user account", "Agregar nueva cuenta de usuario");
regGS("Add new user type", "Agregar nuevo tipo de usuario");
regGS("Add new article type", "Agregar nuevo tipo de artículo");
regGS("Add new country", "Agregar nuevo país");
regGS("Add new language", "Agregar nuevo idioma");
regGS("Add new section", "Agregar nueva sección");
regGS("View logs", "Ver historial");
regGS("Change your password", "Cambiar su clave");
regGS("Your articles", "Sus artículos");
regGS("Submitted articles", "Artículos enviados");
regGS("Quick Menu", "Menú Rápido");
regGS("Logs", "Historial");
regGS("There are $1 article(s) left.", "Hay $1 articulo(s) pendiente(s)");
regGS("There are $1 issue(s) left.", "Hay $1 edicion(es) pendiente(s)");
regGS("There are $1 section(s) left.", "Hay $1 seccion(es) pendiente(s)");
regGS("There are $1 publication(s) left.", "Hay $1 publicacion(es) pendiente(s)");
regGS("There are $1 keyword(s) left.", "Hay $1 palabras clave(s) pendiente(s)");
regGS("There are $1 countries left.", "Hay $1 pais(es) pendiente(s)");
regGS("Name<BR><SMALL>(click to edit)</SMALL>", "Nombre");
regGS("User account", "Cuenta de Usuario");
regGS("No such user account.", "No existe cuenta de usuario");
regGS("Add new subscription", "Agregar nueva suscripción");
regGS("You do not have the right to add subscriptions.", "No tiene derecho de acceso para agregar suscripciones");
regGS("Adding subscription", "Agregar suscripciones");
regGS("The section could not be added.", "La sección no pudo ser agregada");
regGS("Delete subscription", "Borrar suscripción");
regGS("You do not have the right to delete subscriptions.", "No tiene derecho a borrar suscripciones");
regGS("Deleting subscription", "Borrando suscripciones");
regGS("No such subscription.", "No existe suscripción");
regGS("The section $1 could not be deleted.", "La sección $1 no pudo ser borrada");
regGS("The topic $1 could not be deleted.", "El tema $1 no pudo ser borrado");
regGS("Yes", "Si");
regGS("No", "No");
regGS("No issues.", "Sin edición");
regGS("Back to article details", "Volver a detalles de articulos");
regGS("Adding new topic", "Agregando nuevo tema");
regGS("Topic $1 added", "Tema $1 agregado");
regGS("The topic could not be added.", "El tema no pudo ser agregado");
regGS("Do you want to delete the topic $1?", "¿Quiere borrar el tema $1?");
regGS("Add another topic", "Agregar otro tema");
regGS("Deleting topic", "Borrando tema");
regGS("There are $1 subtopics left.", "Hay $1 subtema(s) pendiente(s)");
regGS("Topic $1 deleted", "Tema $1 borrado");
regGS("Changing topic name", "Cambiando nombre de tema");
regGS("You do not have the right to change topic name.", "No tiene derecho para cambiar nombre de tema");
regGS("Topic $1 updated", "Tema $1 actualizado");
regGS("The topic name could not be updated.", "El nombre de tema no pudo ser borrado");
regGS("Change topic name", "Cambiar nombre de tema");
regGS("Delete topic $1", "Borrar tema $1");
regGS("No topics", "Sin temas");
regGS("The topic $1 has been successfuly added.", "El tema $1 ha sido exitosamente agregado");
regGS("The topic $1 has been successfuly updated.", "El tema $1 ha sido exitosamente actualizado");
regGS("The topic $1 has been deleted.", "El tema $1 ha sido borrado");
regGS("There are $1 articles using the topic.", "Hay $1 articulo(s) usando el tema");
regGS("You must fill in the $1 field.", "Debe completar el campo $1");
regGS("You do not have the right to add articles.", "No tiene derechos para agregar artículos");
regGS("Start", "Inicio");
regGS("Days", "Dias");
regGS("(YYYY-MM-DD)", "AAAA-MM-DD");
regGS("The sections were added successfully.", "Las secciones fueron agregadas con éxito");
regGS("The sections could not be added successfully. Some of them were already added !", "Las secciones no pudieron ser agregadas con éxito. Algunas de ellas fueron ya agregadas!");
regGS("Add another", "Agregar otro");
regGS("Cancel", "Cancelar");
regGS("Done", "Hecho");
regGS("New field", "Nuevo Campo");
regGS("OK", "OK");
regGS("Save changes", "Guardar Cambios");
regGS("Search", "Buscar");
regGS("Add new field", "Agregar nuevo campo");
?>