<?
regGS("CAMPSITE","CAMPSITE");
regGS("Home","Domů");
regGS("Logout","Odhlásit");
regGS("Fields","Pole");
regGS("Delete","Smazat");
regGS("Type","Typ");
regGS("Name","Název");
regGS("Keyword","Klíčové slovo");
regGS("Infotypes","Infotypy");
regGS("Languages","Jazyk");
regGS("Native name","Jazyk (nepřeložen)");
regGS("Code","Kód");
regGS("Code page","Stránkové kódování");
regGS("Edit","Upravit");
regGS("Countries","Země");
regGS("Reader","Čtenář");
regGS("Access","Přístup");
regGS("Login","Přihlásit se");
regGS("Password","Heslo");
regGS("Site","Site");
regGS("Currency","Měna");
regGS("Templates","Šablony");
regGS("Topics","Témata");
regGS("Path","Cesta");
regGS("Go up","Nahoru");
regGS("Language","Jazyk");
regGS("Keyword infotype","Klíčové slovo (Infotyp)");
regGS("Translation","Překlad");
regGS("Infotype","Infotyp");
regGS("Country","Země");
regGS("User name","Uživatelské jméno");
regGS("Definition","Definice");
regGS("Publication","Publikace");
regGS("Default language","Výchozí jazyk");
regGS("Time Unit","Časová jednotka");
regGS("Unit Cost","Měnová jednotka");
regGS("Subscriptions","Předplatné");
regGS("Issue","Vydání");
regGS("Number","Číslo");
regGS("Section","Oddíl");
regGS("Keywords","Klíčová slova");
regGS("Topic","Téma");
regGS("Next","Další");
regGS("Previous","Předchozí");
regGS("Translate","Překlad");
regGS("Details","Detaily");
regGS("View","Náhled");
regGS("days","dny");
regGS("Article Types","Typ článku");
regGS("User Types","Uživatelské typy");
regGS("Glossary","Glosář");
regGS("Keyword infotypes","Klíčová slova (Infotypy)");
regGS("Publications","Publikace");
regGS("Issues","Vydání");
regGS("Sections","Rubriky");
regGS("Articles","Články");
regGS("Images","Obrázky");
regGS("Nr","č.");
regGS("Change","Změnit");
regGS("Add new issue","Přidat nové vydání");
regGS("Add new topic","Přidat nové téma");
regGS("Delete topic","Smazat téma");
regGS("Default Language","Výchozí jazyk");
regGS("Subscription Default Time","Předplatné období");
regGS("Pay Period","Platební období");
regGS("Info","Irformace");
regGS("Trial Period","Zkušební období");
regGS("Paid Period","Zaplacené období");
regGS("Preview","Náhled");
regGS("You must complete the $1 field.","Vyplňte $1 pole");
regGS("No such language.","Jazyk neexistuje");
regGS("No such infotype.","Infotyp neexistuje");
regGS("No such keyword.","Klíčové slovo neexistuje");
regGS("No such publication.","Publikace neexistuje");
regGS("No such country.","Země neexistuje");
regGS("No such issue.","Vydání neexistuje");
regGS("No such topic.","Téma neexistuje");
regGS("You must select a language.","Vyberte jazyk");
regGS("No such section.","Rubrika neexistuje");
regGS("No articles.","Články neexistují");
regGS("Add new article","Přidat nový článek");
regGS("Status","Status");
regGS("No such article.","Článek neexistuje");
regGS("Published","Zveřejněno");
regGS("Submitted","Podáno");
regGS("New","Nový");
regGS("Article","Článek");
regGS("Publish","Zveřejnit");
regGS("Unpublish","Nezveřejňovat");
regGS("Unlock","Odemknout");
regGS("Uploaded","Nahráno");
regGS("(yyyy-mm-dd)","rrrr-mm-dd");
regGS("YYYY-MM-DD","RRRR-MM-DD");
regGS("Submit","Podat");
regGS("Field","Pole");
regGS("Edit details","Editovat detaily");
regGS("No such image.","Obrázek neexistuje");
regGS("Image","Obrázek");
regGS("Description","Popis");
regGS("Photographer","Fotograf");
regGS("Place","Místo");
regGS("Date","Datum");
regGS("Publ. no.","Publikace č.");
regGS("Issue no.","Vydání č.");
regGS("Section no.","Rubrika č.");
regGS("Image number","Obrázek č.");
regGS("Users","Uživatelé");
regGS("User is a reader","Uživatel může pouze číst");
regGS("User may add/change publications","Uživatel může přidat/změnit publikace");
regGS("User may delete publications","Uživatel může smazat publikace");
regGS("User may add/change issues","Uživatel může přidat/změnit vydání");
regGS("User may delete issues","Uživatel může smazat vydání");
regGS("User may add/change sections","Uživatel může přidat/změnit rubriky");
regGS("User may delete sections","Uživatel může smazat rubriky");
regGS("User may add articles","Uživatel může přidat články");
regGS("User may change articles","Uživatel může změnit články");
regGS("User may delete articles","Uživatel může smazat články");
regGS("User may add images","Uživatel může přidat obrázky");
regGS("User may change images","Uživatel může změnit obrázky");
regGS("User may delete images","Uživatel může smazat obrázky");
regGS("User may add templates","Uživatel může přidat šablony");
regGS("User may delete templates","Uživatel může smazat šablony");
regGS("User may add/change user accounts and passwords","Uživatel může přidat/změnit uživatelské účty a hesla");
regGS("User may delete user accounts","Uživatel může mazat uživatelské účty");
regGS("User may manage user subscriptions","Uživatel může spravovat předplatné");
regGS("User may manage account types","Uživatel může změnit typy účtu");
regGS("User may add/change article types","Uživatel může přidat/změnit typy článku");
regGS("User may delete article types","Uživatel může smazat typy článků");
regGS("User may add languages and manage language information","Uživatel může přidat a spravovat jazyky");
regGS("User may delete languages","Uživatel může mazat jazyky");
regGS("User may manage glossary infotypes","Uživatel může spravovat infotypy glosáře");
regGS("User may add/change glossary entries","Uživatel může přidat/změnit položky ve slovníku");
regGS("User may delete glossary entries","Uživatel může smazat položky ve slovníku");
regGS("User will be notified on several events","Uživatel bude několikrát informován");
regGS("User may view audit logs","Uživatel může nahlížet do logu");
regGS("User may add/change country names","Uživatel může přidat/měnit názvy zemí");
regGS("User may delete country entries","Uživatel může mazat názvy zemí");
regGS("User may manage localizer","Uživatel může spravovat lokalizátor");
regGS("User may manage indexer","Uživatel může spravovat indexátor");
regGS("User may publish articles","Uživatel může zveřejňovat články");
regGS("User may manage topics","Uživatel může spravovat témata");
regGS("Adding new translation","Přidávání nového překladu");
regGS("Translate keyword","Přeložit klíčové slovo");
regGS("No more languages.","Žádné další jazyky");
regGS("No such keyword infotype.","Infotyp klíčového slova neexistuje");
regGS("Adding new keyword infotype","Přidávání infotypu klíčového slova");
regGS("The infotype has been deleted.","Infotyp byl smazán");
regGS("The infotype could not be deleted.","Infotyp nemohl být smazán");
regGS("Add new publication","Přidat novou publikaci");
regGS("Upload new template","Nahrát novou šablonu");
regGS("Add new user account","Přidat uživatelský účet");
regGS("Add new user type","Přidat typ uživatele");
regGS("Add new article type","Přidat nový typ článku");
regGS("Add new country","Přidat novou zemi");
regGS("Add new language","Přidat nový jazyk");
regGS("Add new section","Přidat novou rubriku");
regGS("View logs","Náhled logu");
regGS("Change your password","Změnit heslo");
regGS("Your articles","Tvé články");
regGS("Submitted articles","Podané články");
regGS("Quick Menu","Zkratky");
regGS("Logs","Logy");
regGS("There are $1 article(s) left.","Zbývají články $1");
regGS("There are $1 issue(s) left.","Zbývá článek $1");
regGS("There are $1 section(s) left.","Zbývá rubrika $1");
regGS("There are $1 publication(s) left.","Zbývá publikace $1");
regGS("There are $1 keyword(s) left.","Zbývají klíčová slova $1");
regGS("There are $1 countries left.","Zbývají země $1");
regGS("Name<BR><SMALL>(click to edit)</SMALL>","Název (klikněte pro editaci)");
regGS("User account","Uživatelský účet");
regGS("No such user account.","Uživatelský účet neexistuje");
regGS("Add new subscription","Přidat nové předplatné");
regGS("You do not have the right to add subscriptions.","Nemáte právo přidat předplatné");
regGS("Adding subscription","Přidání předplatného");
regGS("The section could not be added.","Rubrika nemohla být přidána");
regGS("Delete subscription","Smazat předplatné");
regGS("You do not have the right to delete subscriptions.","Nemáte právo smazat předplatné");
regGS("Deleting subscription","Mazání předplatného");
regGS("No such subscription.","Předplatné neexistuje");
regGS("The section $1 could not be deleted.","Rubrika $1 nemohla být smazána");
regGS("The topic $1 could not be deleted.","Téma $1 nemohlo být smazáno");
regGS("Yes","Ano");
regGS("No","Ne");
regGS("No issues.","Vydání neexistuje");
regGS("Adding new topic","Přidání nového témata");
regGS("Topic $1 added","Téma $1 bylo přidáno");
regGS("The topic could not be added.","Téma nemohlo být přidáno");
regGS("Do you want to delete the topic $1?","Určitě chcete smazat téma $1?");
regGS("Add another topic","Přidat další téma");
regGS("Deleting topic","Mazání tématu");
regGS("There are $1 subtopics left.","Zbývá $1 podtémat");
regGS("Topic $1 deleted","Téma $1 bylo smazáno");
regGS("Changing topic name","Změna názvu tématu");
regGS("You do not have the right to change topic name.","Nemáte právo měnit název tématu");
regGS("Topic $1 updated","Téma $1 bylo obnoveno");
regGS("The topic name could not be updated.","Název tématu nemohlo být obnoveno");
regGS("Change topic name","Změnit název témata");
regGS("Delete topic $1","Smazat téma $1");
regGS("No topics","Žádná témata");
regGS("The topic $1 has been successfuly added.","Téma $1 bylo úspěšně přidáno");
regGS("The topic $1 has been successfuly updated.","Téma $1 bylo úspěšně obnoveno");
regGS("The topic $1 has been deleted.","Téma $1 bylo smazáno");
regGS("There are $1 articles using the topic.","$1 článků používá toto téma");
regGS("You must fill in the $1 field.","Musíte vyplnit pole $1");
regGS("Start","Začátek");
regGS("Days","Dny");
regGS("(YYYY-MM-DD)","(RRRR-MM-DD)");
regGS("The sections were added successfully.","Rubriky byly úspěšně přidány");
regGS("The sections could not be added successfully. Some of them were already added !","Rubriky nebyly úspěšně přidány. Některé již byly přidány! ");
regGS("Back to article details","Zpět na detaily článku");

?>
