<?
regGS("CAMPSITE","CAMPSITE");
regGS("Home","Glavna");
regGS("Logout","Izlaz");
regGS("Fields","Polja");
regGS("Delete","Izbriši");
regGS("Type","Tip");
regGS("Name","Ime");
regGS("Keyword","Ključne reči");
regGS("Infotypes","Infotipi");
regGS("Languages","Jezici");
regGS("Native name","Ime u originalu");
regGS("Code","Kod");
regGS("Code page","Kodna stranica");
regGS("Edit","Izmeni");
regGS("Countries","Zemlje");
regGS("Reader","Čitalac");
regGS("Access","Pristup");
regGS("Login","Ulaz");
regGS("Password","Lozinka");
regGS("Site","Sajt");
regGS("Currency","Valuta");
regGS("Templates","Šabloni");
regGS("Topics","Teme");
regGS("Path","Putanja");
regGS("Go up","Gore");
regGS("Language","Jezik");
regGS("Keyword infotype","Infotip za ključnu reč");
regGS("Translation","Prevod");
regGS("Infotype","Infotip");
regGS("Country","Zemlja");
regGS("User name","Korisničko ime");
regGS("Definition","Definicija");
regGS("Publication","Publikacija");
regGS("Default language","Osnovni jezik");
regGS("Time Unit","Vremenska jedinica");
regGS("Unit Cost","Cena jedinice");
regGS("Subscriptions","Pretplata");
regGS("Issue","Izdanje");
regGS("Number","Broj");
regGS("Section","Rubrika");
regGS("Keywords","Ključne reči");
regGS("Topic","");
regGS("Next","Napred");
regGS("Previous","Nazad");
regGS("Translate","Prevedi");
regGS("Details","Detalji");
regGS("View","Prikaz");
regGS("days","Dani");
regGS("Article Types","Tipovi članaka");
regGS("User Types","Vrsta korisnika");
regGS("Glossary","Glosar");
regGS("Keyword infotypes","Infotipi za ključne reči");
regGS("Publications","Publikacije");
regGS("Issues","Izdanja");
regGS("Sections","Rubrike");
regGS("Articles","Članci");
regGS("Images","Slike");
regGS("Nr","Br");
regGS("Change","Izmeni");
regGS("Add new issue","Dodaj novo izdanje");
regGS("Add new topic","");
regGS("Delete topic","");
regGS("Default Language","Osnovni jezik");
regGS("Subscription Default Time","Osnovna dužina pretplate");
regGS("Pay Period","Rok plaćanja");
regGS("Info","Info");
regGS("Trial Period","Probni period");
regGS("Paid Period","Plaćeni period");
regGS("Preview","Vidi kako izgleda");
regGS("You must complete the $1 field.","Morate da ispunite $1 polje");
regGS("No such language.","Nema takvog jezika");
regGS("No such infotype.","Nema takvog infotipa");
regGS("No such keyword.","Nema takve ključne reči");
regGS("No such publication.","Nema takve publikacije");
regGS("No such country.","Nema takve zemlje u databazi");
regGS("No such issue.","Takvo izdanje ne postoji");
regGS("No such topic.","");
regGS("You must select a language.","Morate odabrati jezik");
regGS("No such section.","Takva rubrika ne postoji");
regGS("No articles.","Nema članaka");
regGS("Add new article","Dodaj novi članak");
regGS("Status","Status");
regGS("No such article.","Nema tog članka");
regGS("Published","Objavljen");
regGS("Submitted","Predat");
regGS("New","Nov");
regGS("Article","Članak");
regGS("Publish","Objavi");
regGS("Unpublish","Povuci");
regGS("Unlock","Otključaj");
regGS("Uploaded","Aploudovan");
regGS("(yyyy-mm-dd)","gggg-mm-dd");
regGS("YYYY-MM-DD","GGGG-MM-DD");
regGS("Submit","Predaj");
regGS("Field","Polje");
regGS("Edit details","Izmeni detalje");
regGS("No such image.","Nema te slike");
regGS("Image","Slika");
regGS("Description","Opis");
regGS("Photographer","Fotograf");
regGS("Place","Mesto");
regGS("Date","Datum");
regGS("Publ. no.","Br. pub.");
regGS("Issue no.","Br. izdanja");
regGS("Section no.","Br. rubrike");
regGS("Image number","Br. slike");
regGS("Users","Korisnici");
regGS("User is a reader","Korisnik je čitalac");
regGS("User may add/change publications","Korisnik sme da dodaje/menja publikacije");
regGS("User may delete publications","Korisnik sme da briše publikacije");
regGS("User may add/change issues","Korisnik sme da dodaje/uređuje izdanja");
regGS("User may delete issues","Korisnik sme da briše izdanja");
regGS("User may add/change sections","Korisnik sme da dodaje/uređuje rubrike");
regGS("User may delete sections","Korisnik sme da briše rubrike");
regGS("User may add articles","Korisnik sme da dodaje članke");
regGS("User may change articles","Korisnik sme da uređuje članke");
regGS("User may delete articles","Korisnik sme da briše članke");
regGS("User may add images","Korisnik sme da dodaje slike");
regGS("User may change images","Korisnik sme da menja slike");
regGS("User may delete images","Koriisnik sme da briše slike");
regGS("User may add templates","Korisinik sme da dodaje šablone");
regGS("User may delete templates","Korisnik sme da briše šablone");
regGS("User may add/change user accounts and passwords","Korisnik sme da dodaje/menja korisničke profile i lozinke");
regGS("User may delete user accounts","Korisnik sme da briše korisničke profile");
regGS("User may manage user subscriptions","Korisnik sme da administrira pretplatu");
regGS("User may manage account types","Korisnik sme da uređuje vrste korisničkih profila");
regGS("User may add/change article types","Korisnik sme da dodaje/menja tipove članaka");
regGS("User may delete article types","Korisnik sme da briše tipove članaka");
regGS("User may add languages and manage language information","Korisnik sme da dodaje jezike i menja relevantne informacije");
regGS("User may delete languages","Korisnik sme da briše jezike");
regGS("User may manage glossary infotypes","Korisnik sme da manipuliše infotipovima u glosaru");
regGS("User may add/change glossary entries","Korisnik sme da dodaje/menja jedinice u glosaru");
regGS("User may delete glossary entries","Korisnik sme da briše jedinice u glosaru");
regGS("User will be notified on several events","Korisnik će biti obaveštavan o raznim sistemskim aktivnostima");
regGS("User may view audit logs","Korisnik ima pristup logovima");
regGS("User may add/change country names","Korisnik sme da dodaje/menja imena zemalja");
regGS("User may delete country entries","Korisnik sme da briše zemlje");
regGS("User may manage localizer","Korisnik sme da koristi lokalizator");
regGS("User may manage indexer","Korisnik sme da upravlja indeksatorom");
regGS("User may publish articles","Korisnik sme da objavljuje članke");
regGS("User may manage topics","Korisnik sme da upravlja temama");
regGS("Adding new translation","Dodajem novi prevod");
regGS("Translate keyword","Prevedi ključnu reč");
regGS("No more languages.","Nema više nijednog jezika");
regGS("No such keyword infotype.","Nema takvog infotipa za ključnu reč");
regGS("Adding new keyword infotype","Dodajem novi infotip za ključnu reč");
regGS("The infotype has been deleted.","Infotip je izbrisan");
regGS("The infotype could not be deleted.","Infotip nije mogao da bude izbrisan");
regGS("Add new publication","Dodaj novu publikaciju");
regGS("Upload new template","Aplouduj novi šablon");
regGS("Add new user account","Dodaj novog korisnika");
regGS("Add new user type","Dodaj novi tip korisnika");
regGS("Add new article type","Dodaj novi tip članka");
regGS("Add new country","Dodaj novu zemlju");
regGS("Add new language","Dodaj novi jezik");
regGS("Add new section","Dodaj novu rubriku");
regGS("View logs","Pogledaj log");
regGS("Change your password","Promeni lozinku");
regGS("Your articles","Vaši članci");
regGS("Submitted articles","Predati članci");
regGS("Quick Menu","Prečice");
regGS("Logs","Logovi");
regGS("There are $1 article(s) left.","Preostao-lo je još $1 članak-a");
regGS("There are $1 issue(s) left.","Preostalo-la je(su) još $1 izdanje-a");
regGS("There are $1 section(s) left.","Preostala(o) je još $1 rubrika(e)");
regGS("There are $1 publication(s) left.","Preostala(o) je još $1 publikacija(e) ");
regGS("There are $1 keyword(s) left.","Preostala(e) je (su) još $1 ključna(e) reči");
regGS("There are $1 countries left.","Preostala(le) je (su) još $1 zemlja(e)");
regGS("Name<BR><SMALL>(click to edit)</SMALL>","Ime<br><small>(kliknite da uđete)</small>");
regGS("User account","Korisnički profil");
regGS("No such user account.","Nema takvog korisničkog profila.");
regGS("Add new subscription","Dodaj novu pretplatu");
regGS("You do not have the right to add subscriptions.","Nemate pravo da dodajete nove pretplate");
regGS("Adding subscription","Dodajem pretplatu");
regGS("The section could not be added.","Rubrika nije mogla da bude dodata");
regGS("Delete subscription","Izbriši pretplatu");
regGS("You do not have the right to delete subscriptions.","Nemate pravo da brišete pretplate");
regGS("Deleting subscription","Brišem pretplatu");
regGS("No such subscription.","Nema takve pretplate.");
regGS("The section $1 could not be deleted.","Rubrika $1 nije mogla da se izbriše.");
regGS("The topic $1 could not be deleted.","");
regGS("Yes","Da");
regGS("No","Ne");
regGS("No issues.","Nema nikakvih izdanja.");
regGS("Adding new topic","");
regGS("Topic $1 added","");
regGS("The topic could not be added.","");
regGS("Do you want to delete the topic $1?","");
regGS("Add another topic","");
regGS("Deleting topic","");
regGS("There are $1 subtopics left.","");
regGS("Topic $1 deleted","");
regGS("Changing topic name","");
regGS("You do not have the right to change topic name.","");
regGS("Topic $1 updated","");
regGS("The topic name could not be updated.","");
regGS("Change topic name","");
regGS("Delete topic $1","");
regGS("No topics","");
regGS("The topic $1 has been successfuly added.","");
regGS("The topic $1 has been successfuly updated.","");
regGS("The topic $1 has been deleted.","");
regGS("There are $1 articles using the topic.","");
regGS("You must fill in the $1 field.","");
regGS("Start","");
regGS("Days","");
regGS("(YYYY-MM-DD)","");
regGS("The sections were added successfully.","");
regGS("The sections could not be added successfully. Some of them were already added !","");
regGS("Back to article details","Vrati se na članak");

?>
