<?php 

regGS("CAMPSITE","KEMPSAJT");
regGS("Home","Početak");
regGS("Logout","Odjava");
regGS("Fields","Polja");
regGS("Delete","Obriši");
regGS("Type","Tip");
regGS("Name","Ime");
regGS("Keyword","Ključna reč");
regGS("Infotypes","Infotipi");
regGS("Languages","Jezici");
regGS("Native name","Izvorno ime");
regGS("Code","Kod");
regGS("Code page","Kodna strana");
regGS("Edit","Uredi");
regGS("Countries","Države");
regGS("Reader","Čitalac");
regGS("Access","Pristup");
regGS("Login","Prijava");
regGS("Password","Lozinka");
regGS("Site","Sajt");
regGS("Currency","Valuta");
regGS("Templates","Šabloni");
regGS("Topics","Teme");
regGS("Path","Putanja");
regGS("Go up","Nivo iznad");
regGS("Language","Jezik");
regGS("Keyword infotype","Infotip za ključnu reč");
regGS("Translation","Prevod");
regGS("Infotype","Infotip");
regGS("Country","Država");
regGS("User name","Korisničko ime");
regGS("Definition","Definicija");
regGS("Publication","Publikacija");
regGS("Default language","Osnovni jezik");
regGS("Time Unit","Vremenska jedinica");
regGS("Unit Cost","Cena jedinice");
regGS("Subscriptions","Pretplate");
regGS("Issue","Izdanje");
regGS("Number","Broj");
regGS("Section","Rubrika");
regGS("Keywords","Ključne reči");
regGS("Topic","Tema");
regGS("Next","Sledeći");
regGS("Previous","Prethodni");
regGS("Translate","Prevedi");
regGS("Details","Detalji");
regGS("View","Prikaz");
regGS("days","dana");
regGS("Article Types","Tipovi članaka");
regGS("User Types","Tipovi korisnika");
regGS("Glossary","Glosar");
regGS("Keyword infotypes","Infotipi za ključnu reč");
regGS("Publications","Publikacije");
regGS("Issues","Izdanja");
regGS("Sections","Rubrike");
regGS("Articles","Članci");
regGS("Images","Slike");
regGS("Nr","br.");
regGS("Change","Promeni");
regGS("Add new issue","Dodaj novo izdanje");
regGS("Add new topic","Dodaj novu temu");
regGS("Delete topic","Obriši temu");
regGS("Default Language","Osnovni jezik");
regGS("Subscription Default Time","Osnovna dužina pretplate");
regGS("Pay Period","Rok plaćanja");
regGS("Info","Info");
regGS("Trial Period","Probni period");
regGS("Paid Period","Plaćeni period");
regGS("Preview","Pregled");
regGS("You must complete the $1 field.","Morate popuniti polje $1 ");
regGS("No such language.","Nema tog jezika");
regGS("No such infotype.","Nema takvog infotipa");
regGS("No such keyword.","Nema te ključne reči");
regGS("Publication does not exist.","Nema takve publikacije");
regGS("No such country.","Nema te države");
regGS("No such issue.","Nema tog izdanja");
regGS("Topic does not exist.","Nema takve teme");
regGS("You must select a language.","Morate izabrati jezik");
regGS("No such section.","Ta rubrika ne postoji");
regGS("No articles.","Nema članka");
regGS("Access denied","Zabranjen pristup");
regGS("Add new article","Dodaj novi članak");
regGS("Status","Status");
regGS("No such article.","Nema takvog članka");
regGS("Published","Objavljen");
regGS("Not published","Neobjavljeno");
regGS("Submitted","Poslat");
regGS("New","Novi");
regGS("Article","Članak");
regGS("Publish","Objavi");
regGS("Unpublish","Povuci");
regGS("Unlock","Otključaj");
regGS("Uploaded","Aploudovan");
regGS("(yyyy-mm-dd)","(gggg-mm-dd)");
regGS("YYYY-MM-DD","GGGG-MM-DD");
regGS("Submit","Pošalji");
regGS("Field","Polje");
regGS("Edit details","Uredi detalje");
regGS("No such image.","Nema te slike");
regGS("Image","Slika");
regGS("Description","Opis");
regGS("Photographer","Fotograf");
regGS("Place","Mesto");
regGS("Date","Datum");
regGS("Publ. no.","Br. publikacije");
regGS("Issue no.","Br. izdanja");
regGS("Section no.","Br. rubrike");
regGS("Image number","Broj slike");
regGS("Users","Korisnici");
regGS("User is a reader","Korisnik je čitalac");
regGS("User may add/change publications","Korisnik može da dodaje/menja publikacije");
regGS("User may delete publications","Korisnik može da briše publikacije");
regGS("User may add/change issues","Korisnik može da dodaje/menja izdanja");
regGS("User may delete issues","Korisnik može da briše izdanja");
regGS("User may add/change sections","Korisnik može da dodaje/menja rubrike");
regGS("User may delete sections","Korisnik može da briše rubrike");
regGS("User may add articles","Korisnik može da dodaje članke");
regGS("User may change articles","Korisnik može da menja članke");
regGS("User may delete articles","Korisnik može da briše članke");
regGS("User may add images","Korisnik može da dodaje slike");
regGS("User may change images","Korisnik može da menja slike");
regGS("User may delete images","Korisnik može da briše slike");
regGS("User may add templates","Korisnik može da dodaje šablone");
regGS("User may delete templates","Korisnik može da briše šablone");
regGS("User may add/change user accounts and passwords","Korisnik može da dodaje/menja korisničke naloge i lozinke");
regGS("User may delete user accounts","Korisnik može da briše korisničke naloge");
regGS("User may manage user subscriptions","Korisnik može da administrira pretplate");
regGS("User may manage account types","Korisnik može da administrira tipove naloga");
regGS("User may add/change article types","Korisnik može da dodaje/menja tipove članaka");
regGS("User may delete article types","Korisnik može da briše tipove članaka");
regGS("User may add languages and manage language information","Korisnik može da dodaje jezike i upravlja informacijama o jeziku");
regGS("User may delete languages","Korisnik može da briše jezike");
regGS("User may manage glossary infotypes","Korisnik može da upravlja infotipima glosara");
regGS("User may add/change glossary entries","Korisnik može da dodavaje/menja zapise u glosaru");
regGS("User may delete glossary entries","Korisnik može da briše zapise u glosaru");
regGS("User will be notified on several events","Korisnik će biti obavešten o određenim sistemskim aktivnostima");
regGS("User may view audit logs","Korisnik ima pristup logovima");
regGS("User may add/change country names","Korisnik može da dodaje/menja imena država");
regGS("User may delete country entries","Korisnik može da briše podatke o državama");
regGS("User may manage localizer","Korisnik ima pristup lokalizatoru");
regGS("User may manage indexer","Korisnik ima pristup indekseru");
regGS("User may publish articles","Korisnik može da objavljuje članke");
regGS("User may manage topics","Korisnik može da upravlja temama");
regGS("Adding new translation","Dodavanje novog prevoda");
regGS("Translate keyword","Prevedi ključnu reč");
regGS("No more languages.","Nema više jezika");
regGS("No such keyword infotype.","Nema tog infotipa za ključnu reč");
regGS("Adding new keyword infotype","Dodavanje novog infotipa za ključne reči");
regGS("The infotype has been deleted.","Infotip je izbrisan");
regGS("The infotype could not be deleted.","Infotip ne može biti izbrisan");
regGS("Add new publication","Dodaj novu publikaciju");
regGS("Upload new template","Aplouduj novi šablon");
regGS("Add new user account","Dodaj novog korisnika");
regGS("Add new user type","Dodaj novi tip korisnika");
regGS("Add new article type","Dodaj novi tip članka");
regGS("Add new country","Dodaj državu");
regGS("Add new language","Dodaj jezik");
regGS("Add new section","Dodaj novu rubriku");
regGS("View logs","Prikaži logove");
regGS("Change your password","Promeni lozinku");
regGS("Your articles","Vaši članci");
regGS("Submitted articles","Poslati članci");
regGS("Quick Menu","Prečice");
regGS("Logs","Logovi");
regGS("There are $1 article(s) left.","Preosta(l)o je $1 članak(a)");
regGS("There are $1 issue(s) left.","Preostalo je $1 izdanja");
regGS("There are $1 section(s) left.","Preosta(l)o je $1 rubrika");
regGS("There are $1 publication(s) left.","Preostalo(a) je $1 publikacija");
regGS("There are $1 keyword(s) left.","Preostalo je $1 ključnih reči");
regGS("There are $1 countries left.","Preostalo je $1 država");
regGS("Name<BR><SMALL>(click to edit)</SMALL>","Ime<br><small>(kliknite za uređivanje)</small>");
regGS("User account","Korisnički nalog");
regGS("No such user account.","Nema takvog korisničkog naloga");
regGS("Add new subscription","Dodaj novu pretplatu");
regGS("You do not have the right to add subscriptions.","Nemate pravo da dodajete pretplate");
regGS("Adding subscription","Dodavanje pretplate");
regGS("The section could not be added.","Rubrika ne može biti dodata");
regGS("Delete subscription","Obriši pretplatu");
regGS("You do not have the right to delete subscriptions.","Nemate pravo da brišete pretplate");
regGS("Deleting subscription","Brisanje pretplate");
regGS("No such subscription.","Nema takve pretplate");
regGS("The section $1 could not be deleted.","Rubrika $1 ne može biti obrisana");
regGS("The topic $1 could not be deleted.","Tema $1 ne može biti obrisana");
regGS("Yes","Da");
regGS("No","Ne");
regGS("No issues.","Nema izdanja");
regGS("Back to article details","Nazad na detalje članka");
regGS("Adding new topic","Dodavanje nove teme");
regGS("Topic $1 added","Tema $1 je dodata");
regGS("The topic could not be added.","Tema ne može biti dodata");
regGS("Do you want to delete the topic $1?","Želite li da obrišete temu $1?");
regGS("Add another topic","Dodaj novu temu");
regGS("Deleting topic","Brisanje teme");
regGS("There are $1 subtopics left.","Preostalo je $1 podtema");
regGS("Topic $1 deleted","Tema $1 je obrisana");
regGS("Changing topic name","Promena imena teme");
regGS("You do not have the right to change topic name.","Nemate pravo da menjate ime teme");
regGS("Topic $1 updated","Tema $1 je izmenjena");
regGS("The topic name could not be updated.","Naziv teme ne može biti izmenjen");
regGS("Change topic name","Promeni naziv teme");
regGS("Delete topic $1","Obriši temu $1");
regGS("No topics","Nema tema");
regGS("The topic $1 has been successfuly added.","Tema $1 je uspešno dodata");
regGS("The topic $1 has been successfuly updated.","Tema $1 je uspešno izmenjena");
regGS("The topic $1 has been deleted.","Tema $1je uspešno obrisana");
regGS("There are $1 articles using the topic.","Preostalo je $1 tekstova koji koriste ovu temu");
regGS("You must fill in the $1 field.","Morate popuniti polje $1");
regGS("Start","Početak");
regGS("Days","Dana");
regGS("(YYYY-MM-DD)","(GGGG-MM-DD)");
regGS("The sections were added successfully.","Rubrike su uspešno dodate");
regGS("The sections could not be added successfully. Some of them were already added !","Rubrike ne mogu biti dodate. Neke od njih već postoje!");
regGS("Add another","Nastavi sa dodavanjem");
regGS("Cancel","Poništi");
regGS("Done","Gotovo");
regGS("New field","Novo polje");
regGS("OK","OK");
regGS("Save changes","Snimi izmene");
regGS("Search","Traži");
regGS("No languages","Nema jezika");
regGS("---Select language---","--- Izaberite jezik ---");
regGS("No publications","Nema publikacija");
regGS("---Select publication---","--- Izaberite publikaciju ---");
regGS("No issues","Nema izdanja");
regGS("---Select issue---","--- Izaberite izdanje ---");
regGS("No sections","Nema rubrika");
regGS("---Select section---","--- Izaberite rubriku ---");
regGS("No articles","Nema članaka");
regGS("---Select article---","--- Izaberite članak ---");
regGS("Duplicate","Dupliraj");
regGS("You do not have the right to add articles.","Nemate pravo da dodajete članke");
regGS("Add new field","Dodaj novo polje");

?>
