<?

regGS("CAMPSITE","كامبسايت");
regGS("Home","الصفحة الرئيسية");
regGS("Logout","خروج");
regGS("Fields","حقول");
regGS("Delete","إلغاء");
regGS("Type","النوع");
regGS("Name","الإسم");
regGS("Keyword","الكلمة المفتاح");
regGS("Infotypes","نوع المعلومات");
regGS("Languages","اللغات");
regGS("Native name","الإسم الاصلي");
regGS("Code","الرمز");
regGS("Code page","الصفحة الرمز");
regGS("Edit","تحرير");
regGS("Countries","البلدان");
regGS("Reader","القارئ");
regGS("Access","المدخل");
regGS("Login","الدخول");
regGS("Password","كلمة السر");
regGS("Site","الموقع");
regGS("Currency","العملة");
regGS("Templates","النماذج");
regGS("Topics","مواضيع");
regGS("Path","الطريق");
regGS("Go up","الى أعلى الصفحة");
regGS("Language","اللغة");
regGS("Keyword infotype","نوع كلمة المفتاح");
regGS("Translation","الترجمة");
regGS("Infotype","نوع المعلومات");
regGS("Country","البلد");
regGS("User name","اسم المستخدم");
regGS("Definition","التعريف");
regGS("Publication","المنشور");
regGS("Default language","اللغة الرئيسية");
regGS("Time Unit","وحدة الوقت");
regGS("Unit Cost","كلفة الوحدة ");
regGS("Subscriptions","إشتراكات");
regGS("Issue","الإصدار");
regGS("Number","رقم");
regGS("Section","الباب");
regGS("Keywords","كلمات مفاتيح");
regGS("Topic","الموضوع");
regGS("Next","التالي");
regGS("Previous","السابق");
regGS("Translate","ترجم");
regGS("Details","التفاصيل");
regGS("View","عرض");
regGS("days","أيام");
regGS("Article Types","نوع المقال");
regGS("User Types","المستخدم");
regGS("Glossary","الفهرس");
regGS("Keyword infotypes","أنواع  الكلمة المفتاح");
regGS("Publications","المنشورات");
regGS("Issues","الإصدارات");
regGS("Sections","الابواب");
regGS("Articles","المقالات");
regGS("Images","الصور");
regGS("Nr","عدد");
regGS("Change","تعديل");
regGS("Add new issue","إضافة إصدار جديد");
regGS("Add new topic","إضافة موضوع جديد");
regGS("Delete topic","إلغاء الموضوع");
regGS("Default Language","اللغة الاساسية");
regGS("Subscription Default Time","مدة الاشتراك الاساسية");
regGS("Pay Period","فترة الدفع");
regGS("Info","معلومات");
regGS("Trial Period","مدة التجربة");
regGS("Paid Period","المدة المدفوعة");
regGS("Preview","معاينة قبل الطباعة");
regGS("You must complete the $1 field.","يجب إكمال الحقل $1");
regGS("No such language.","لغة غير محددة");
regGS("No such infotype.","نوع معلومات غير محدد");
regGS("No such keyword.","كلمة المفتاح غير محددة");
regGS("No such publication.","منشور غير محدد");
regGS("No such country.","بلد غير محدد");
regGS("No such issue.","إصدار غير محدد");
regGS("No such topic.","موضوع غير محدد");
regGS("You must select a language.","يجب إختيار لغة");
regGS("No such section.","باب غير موجود");
regGS("No articles.","ليس هناك مقالات");
regGS("Access denied","ممنوع الدخول");
regGS("Add new article","إضافة مقال جديد");
regGS("Status","الوضع");
regGS("No such article.","مقال غير محدد");
regGS("Published","منشور");
regGS("Not published","غير منشور");
regGS("Submitted","معتمد");
regGS("New","جديد");
regGS("Article","مقال");
regGS("Publish","نشر");
regGS("Unpublish","عدم النشر");
regGS("Unlock","فك القفل");
regGS("Uploaded","محمّل");
regGS("(yyyy-mm-dd)","(يوم- شهر- سنة)");
regGS("YYYY-MM-DD","يوم- شهر- سنة");
regGS("Submit","إعتمد");
regGS("Field","حقل");
regGS("Edit details","معالجة التفاصيل");
regGS("No such image.","صورة غير محددة");
regGS("Image","صورة");
regGS("Description","وصف");
regGS("Photographer","المصور");
regGS("Place","المكان");
regGS("Date","التاريخ");
regGS("Publ. no.","رقم المنشور");
regGS("Issue no.","رقم الإصدار");
regGS("Section no.","رقم الباب");
regGS("Image number","رقم الصورة");
regGS("Users","المستخدمون");
regGS("User is a reader","المستخدم يقرأ");
regGS("User may add/change publications","يستطيع المستخدم إضافة/تعديل المنشورات");
regGS("User may delete publications","يستطيع المستخدم إلغاء المنشورات");
regGS("User may add/change issues","يستطيع المستخدم إضافة/تعديل الإصدارات");
regGS("User may delete issues","يستطيع المستخدم إلغاء الإصدارات");
regGS("User may add/change sections","يستطيع المستخدم إضافة/تعديل المقاطع");
regGS("User may delete sections","يستطيع المستخدم إلغاء الأبواب");
regGS("User may add articles","يستطيع المستخدم إضافة المقالات");
regGS("User may change articles","يستطيع المستخدم تعديل المقالات");
regGS("User may delete articles","يستطيع المستخدم إلغاء المقالات");
regGS("User may add images","يستطيع المستخدم إضافة الصور");
regGS("User may change images","يستطيع المستخدم تعديل الصور");
regGS("User may delete images","يستطيع المستخدم إلغاء الصور");
regGS("User may add templates","يستطيع المستخدم إضافة النماذج");
regGS("User may delete templates","يستطيع المستخدم إلغاء النماذج");
regGS("User may add/change user accounts and passwords","يستطيع المستخدم إضافة/تعديل إشتراكات المستخدمين وكلمات السر");
regGS("User may delete user accounts","يستطيع المستخدم إلغاء حسابات المستخدم");
regGS("User may manage user subscriptions","يستطيع المستخدم إدارة إشتراكات المستخدم");
regGS("User may manage account types","يستطيع المستخدم تعديل أنواع الإشتراكات");
regGS("User may add/change article types","يستطيع المستخدم إضافة/تعديل أنواع المقالات");
regGS("User may delete article types","يستطيع المستخدم إلغاء أنواع المقالات");
regGS("User may add languages and manage language information","يستطيع المستخدم إضافة لغات وتعديلها");
regGS("User may delete languages","يستطيع المستخدم إلغاء لغات");
regGS("User may manage glossary infotypes","يستطيع المستخدم تغيير فهرس نوع المعلومات");
regGS("User may add/change glossary entries","يستطيع المستخدم إضافة/تعديل الفهرس");
regGS("User may delete glossary entries","يستطيع المستخدم إلغاء أبواب من الفهرس");
regGS("User will be notified on several events","يبلَغ المستخدم عن حدوث أي طارئ");
regGS("User may view audit logs","يستطيع المستخدم الإطلاع على بيانات السجلات");
regGS("User may add/change country names","يستطيع المستخدم إضافة/تعديل أسماء البلدان");
regGS("User may delete country entries","يستطيع المستخدم إلغاء معلومات عن البلدان");
regGS("User may manage localizer","يستطيع المستخدم إدارة المترجم");
regGS("User may manage indexer","يستطيع المستخدم إدارة المصنف");
regGS("User may publish articles","يستطيع المستخدم نشر مقالات");
regGS("User may manage topics","يستطيع المستخدم إدارة مواضيع");
regGS("Adding new translation","إضافة ترجمة جديدة");
regGS("Translate keyword","ترجمة كلمة المفتاح");
regGS("No more languages.","لا لغات أخرى");
regGS("No such keyword infotype.","نوع كلمة المفتاح غير محدد***");
regGS("Adding new keyword infotype","إضافة نوع جديد لكلمة مفتاح ***");
regGS("The infotype has been deleted.","تم إلغاء نوع العلومات");
regGS("The infotype could not be deleted.","لا يمكن إلغاء نوع العلومات");
regGS("Add new publication","إضافة منشور جديد");
regGS("Upload new template","تحميل نموذج جديد");
regGS("Add new user account","إضافة مستخدم جديد");
regGS("Add new user type","إضافة نوع مستخدم جديد");
regGS("Add new article type","إضافة نوع مقال جديد");
regGS("Add new country","إضافة بلد جديد");
regGS("Add new language","إضافة لغة جديدة");
regGS("Add new section","إضافة باب جديد");
regGS("View logs","تبيان سجلات الأداء");
regGS("Change your password","تغيير كلمة السر");
regGS("Your articles","مقالاتك");
regGS("Submitted articles","المقالات المعتمدة");
regGS("Quick Menu","القائمة المصغرة");
regGS("Logs","سجلات الاداء");
regGS("There are $1 article(s) left."," $1 مقالات متبقية");
regGS("There are $1 issue(s) left.","  $1 إصدارات متبقية");
regGS("There are $1 section(s) left.","هناك $1 أبواب متبقية");
regGS("There are $1 publication(s) left.","$1 منشورات متبقية");
regGS("There are $1 keyword(s) left.","$1 كلمات مفاتيح متبقية");
regGS("There are $1 countries left.","$1 بلدان متبقية");
regGS("Name<BR><SMALL>(click to edit)</SMALL>","الإسم");
regGS("User account","إسم المستخدم");
regGS("No such user account.","المستخدم غير محدد");
regGS("Add new subscription","إضافة إشتراك جديد");
regGS("You do not have the right to add subscriptions.","لا يحق لك إضافة إشتراكات");
regGS("Adding subscription","إضافة إشتراك");
regGS("The section could not be added.","لا يمكن إضافة هذا الباب");
regGS("Delete subscription","إلغاء إشتراك");
regGS("You do not have the right to delete subscriptions.","لا يحق لك إلغاء إشتراكات");
regGS("Deleting subscription","إلغاء الإشتراك");
regGS("No such subscription."," إشترك غير محدد");
regGS("The section $1 could not be deleted.","لا يمكن إلغاء الباب $1");
regGS("The topic $1 could not be deleted.","لا يمكن إلغاء الموضوع $1");
regGS("Yes","نعم");
regGS("No","كلا");
regGS("No issues.","لا إصدارات");
regGS("Back to article details","العودة إلى تفاصيل المقال");
regGS("Adding new topic","إضافة موضوع جديد");
regGS("Topic $1 added","تمت إضافة موضوع $1");
regGS("The topic could not be added.","لا يمكن إضافة الموضوع");
regGS("Do you want to delete the topic $1?","هل تريد إلغاء الموضوع $1");
regGS("Add another topic","إضافة موضوع جديد ***");
regGS("Deleting topic","إلغاء الموضوع");
regGS("There are $1 subtopics left.","$1 مواضيع ثانوية متبقية");
regGS("Topic $1 deleted","موضوع $1 ملغى");
regGS("Changing topic name","تغير إسم الموضوع");
regGS("You do not have the right to change topic name.","لا يمكن تغيير إسم الموضوع");
regGS("Topic $1 updated","تم تحديث الموضوع $1");
regGS("The topic name could not be updated.","لا يمكن تحديث إسم الموضوع");
regGS("Change topic name","تغيير إسم الموضوع");
regGS("Delete topic $1","إلغاء الموضوع $1");
regGS("No topics","لا مواضيع");
regGS("The topic $1 has been successfuly added.","تمت إضافة موضوع $1");
regGS("The topic $1 has been successfuly updated.","تم تحديث الموضوع $1");
regGS("The topic $1 has been deleted.","تم إلغاء الموضوع $1");
regGS("There are $1 articles using the topic.","$1 مقالات تستعمل الموضوع");
regGS("You must fill in the $1 field.","يجب تعبئة حقل $1");
regGS("Start","بداية ***");
regGS("Days","أيام");
regGS("(YYYY-MM-DD)","(يوم- شهر- سنة)");
regGS("The sections were added successfully.","تمت إضافة الباب");
regGS("The sections could not be added successfully. Some of them were already added !","لا يمكن إضافة الابواب. البعض منها أضيف سابقاً");
regGS("Add another","إضافة آخرى ***");
regGS("Cancel","إلغاء");
regGS("Done","تمّ ***");
regGS("New field","حقل جديد");
regGS("OK","موافقة");
regGS("Save changes","حفظ التغييرات");
regGS("Search","بحث");


?>