<?php
regGS("CAMPSITE", "КЕМПСАЈТ");
regGS("Home", "Почетак");
regGS("Logout", "Одјава");
regGS("You are logged in as $1", "Улоговани сте као $1");
regGS("More...", "Даље...");
regGS("Content", "Садржаји");
regGS("Obsolete", "Старо гвожђе");
regGS("Publishing environment", "Издавачко окружење");
regGS("Infotypes", "Инфотипи");
regGS("Languages", "Језици");
regGS("Countries", "Државе");
regGS("Templates", "Шаблони");
regGS("Topics", "Теме");
regGS("Configure", "Подешавања");
regGS("Image Archive", "Фото архива");
regGS("Add Article", "Додај чланак");
regGS("Fields", "Поља");
regGS("Delete", "Обриши");
regGS("Type", "Тип");
regGS("Name", "Име");
regGS("Keyword", "Кључна реч");
regGS("Native name", "Изворно име");
regGS("Code", "Код");
regGS("Code page", "Кодна страна");
regGS("Edit", "Уреди");
regGS("Reader", "Читалац");
regGS("Access", "Приступ");
regGS("Login", "Пријава");
regGS("Password", "Лозинка");
regGS("Site", "Сајт");
regGS("Currency", "Валута");
regGS("Path", "Путања");
regGS("Go up", "Ниво изнад");
regGS("URL", "УРЛ");
regGS("Order", "Редослед");
regGS("Hide", "Сакриј");
regGS("Duplicate", "Дуплирај");
regGS("Select destination", "Изабери дестинацију");
regGS("No languages", "Нема језика");
regGS("---Select language---", "--- Изабери језик ---");
regGS("No publications", "Нема публикација");
regGS("---Select publication---", "--- Изабери публикацију ---");
regGS("No issues", "Нема издања");
regGS("---Select issue---", "--- Изабери издање ---");
regGS("No sections", "Нема рубрика");
regGS("---Select section---", "--- Изабери рубрику ---");
regGS("No articles", "Нема чланака");
regGS("---Select article---", "--- Изабери чланак ---");
regGS("Language", "Језик");
regGS("Keyword infotype", "Инфотип за кључну реч");
regGS("Translation", "Превод");
regGS("Infotype", "Инфотип");
regGS("Country", "Држава");
regGS("User name", "Корисничко име");
regGS("Definition", "Дефиниција");
regGS("Publication", "Публикација");
regGS("Default language", "Основни језик");
regGS("Time Unit", "Временска јединица");
regGS("Unit Cost", "Цена по комаду");
regGS("Subscriptions", "Претплате");
regGS("Issue", "Издање");
regGS("Number", "Број");
regGS("Section", "Рубрика");
regGS("Keywords", "Кључне речи");
regGS("Topic", "Тема");
regGS("URL Name", "Скраћено име");
regGS("Next", "Следећи");
regGS("Previous", "Претходни");
regGS("Translate", "Преведи");
regGS("Details", "Детаљи");
regGS("View", "Приказ ");
regGS("Scheduled Publishing", "Аутоматско објављивање");
regGS("Time", "Време");
regGS("Action", "Акција");
regGS("Schedule a new publish action", "Закажи нову акцију објављивања");
regGS("No entries.", "Нема уноса");
regGS("Scheduling a new publish action", "Закажи нову акцију објављивања");
regGS("Delete scheduled publish action", "Обриши заказану акцију објављивања");
regGS("The action scheduled on $1 has been deleted.", "Акција заказана за $1 је обрисана.");
regGS("The $1 action has been scheduled on $2", "Акција $1 је заказана за $2");
regGS("Date/Time", "Датум/време");
regGS("You must select an action.", "Морате изабрати акцију");
regGS("There was an error scheduling the $1 action on $2", "Дошло је до грешке у заказивању акције $1 за $2");
regGS("You do not have the right to schedule issues or articles for automatic publishing.", "Немате право да заказујете аутоматско објављивање издања и чланака.");
regGS("The action scheduled on $1 could not be deleted.", "Акција заказана за $1 не може бити обрисана.");
regGS("Front page", "Почетна страна");
regGS("Section page", "Страна рубрике");
regGS("Show on front page", "Прикажи на почетној страни");
regGS("Remove from front page", "Повуци са почетне стране");
regGS("Show on section page", "Прикажи на страни рубрике");
regGS("Remove from section page", "Повуци са стране рубрике");
regGS("Actions", "Акције");
regGS("Publishing", "Објављивање");
regGS("Show", "Прикажи");
regGS("Remove", "Уклони");
regGS("The $1 actions have been scheduled on $2", "$1 акција је предвиђено за $2");
regGS("days", "Дана");
regGS("Article Types", "Типови чланака");
regGS("User Types", "Типови корисника");
regGS("Glossary", "Глосар");
regGS("Keyword infotypes", "Инфотипи за кључну реч");
regGS("Publications", "Публикације");
regGS("Issues", "Издања");
regGS("Sections", "Рубрике");
regGS("Articles", "Чланци");
regGS("Images", "Слике");
regGS("Nr", "бр.");
regGS("Change", "Промени");
regGS("Add new issue", "Додај ново издање");
regGS("Add new topic", "Додај нову тему");
regGS("Delete topic", "Обриши тему");
regGS("Edit languages", "Прикажи језике");
regGS("Section Template", "Шаблон рубрике");
regGS("Article Template", "Шаблон чланка");
regGS("Default Language", "Основни језик");
regGS("Countries Subscription Default Time", "Основна дужина претплате за државе");
regGS("Pay Period", "Рок плаћања");
regGS("Info", "Инфо");
regGS("Trial Period", "Пробни период");
regGS("Paid Period", "Плаћени период");
regGS("Preview", "Преглед");
regGS("You must complete the $1 field.", "Морате попунити поље $1 ");
regGS("Error", "Грешка");
regGS("Invalid input: $1", "Погрешан унос: $1");
regGS("Language does not exist.", "Нема тог језика.");
regGS("Infotype does not exist.", "Нема таквог инфотипа.");
regGS("Keyword does not exist.", "Нема те кључне речи.");
regGS("Publication does not exist.", "Нема такве публикације.");
regGS("Country does not exist.", "Нема те државе.");
regGS("Issue does not exist.", "Нема тог издања.");
regGS("Topic does not exist.", "Нема такве теме.");
regGS("You must select a language.", "Морате изабрати језик.");
regGS("Section does not exist.", "Та рубрика не постоји.");
regGS("No articles.", "Нема чланака");
regGS("Article does not exist.", "Чланак не постоји.");
regGS("Image does not exist.", "Слика не постоји.");
regGS("Access denied", "Забрањен приступ");
regGS("There was an error reading the language parameter.", "Дошло је до грешке при читању параметра језика.");
regGS("There was an error reading the publication parameter.", "Дошло је до грешке при читању параметрапубликације.");
regGS("There was an error reading the issue parameter.", "Дошло је до грешке при читању параметра издања.");
regGS("There was an error reading request parameters.", "Дошло је до грешке при читању тражених параметара.");
regGS("Invalid article identifier", "Погрешан идентификатор чланка");
regGS("Invalid destination section selected", "Изабрана је погрешна крајња рубрика");
regGS("Internal error: identifiers not initialized", "Интерна грешка: идентификатори нису постављени");
regGS("Internal database error", "Интерна грешка у бази");
regGS("Invalid parameters received", "Примљени су погрешни параметри");
regGS("Add new article", "Додај нови чланак");
regGS("Status", "Статус");
regGS("No such article.", "Нема таквог чланка");
regGS("Published", "Објављен");
regGS("Not published", "Необјављено");
regGS("Submitted", "Предат");
regGS("New", "Нови");
regGS("Article", "Чланак");
regGS("Publish", "Објави");
regGS("Unpublish", "Повуци");
regGS("Unlock", "Откључај");
regGS("Uploaded", "Аплоудован");
regGS("(yyyy-mm-dd)", "(гггг-мм-дд)");
regGS("YYYY-MM-DD", "ГГГГ-ММ-ДД");
regGS("Submit", "Пошаљи");
regGS("Field", "Поље");
regGS("Edit details", "Уреди детаље");
regGS("No such image.", "Нема те слике");
regGS("Image", "Слика");
regGS("Description", "Опис");
regGS("Photographer", "Фотограф");
regGS("Place", "Место");
regGS("Date", "Датум");
regGS("Thumbnail", "Мала слика");
regGS("In use", "Употребљен");
regGS("Identifier", "Идентификатор");
regGS("Uploaded by", "Аплоудовао/ла");
regGS("Additional searches", "Додатне претраге");
regGS("Most Recently Added", "Најновије додате");
regGS("Most Recently Modified", "Најскорије мењане");
regGS("$1 images found", "Пронађено/а је $1 слика");
regGS("Reset search conditions", "Поништи услове претраге");
regGS("Preview issue", "Преглед издања");
regGS("Publ. no.", "Бр. публикације");
regGS("Issue no.", "Бр. издања");
regGS("Section no.", "Бр. рубрике");
regGS("Image number", "Број слике");
regGS("Users", "Корисници");
regGS("User is a reader", "Корисник је читалац");
regGS("User may add/change publications", "Корисник може да додаје/мења публикације");
regGS("User may delete publications", "Корисник може да брише публикације");
regGS("User may add/change issues", "Корисник може да додаје/мења издања");
regGS("User may delete issues", "Корисник може да брише издања");
regGS("User may add/change sections", "Корисник може да додаје/мења рубрике");
regGS("User may delete sections", "Корисник може да брише рубрике");
regGS("User may add articles", "Корисник може да додаје чланке");
regGS("User may change articles", "Корисник може да мења чланке");
regGS("User may delete articles", "Корисник може да брише чланке");
regGS("User may add images", "Корисник може да додаје слике");
regGS("User may change images", "Корисник може да мења слике");
regGS("User may delete images", "Корисник може да брише слике");
regGS("User may add templates", "Корисник може да додаје шаблоне");
regGS("User may delete templates", "Корисник може да брише шаблоне");
regGS("User may add/change user accounts and passwords", "Корисник може да додаје/мења корисничке налоге и лозинке");
regGS("User may delete user accounts", "Корисник може да брише корисничке налоге");
regGS("User may manage user subscriptions", "Корисник може да администрира претплатама");
regGS("User may manage account types", "Корисник може да администрира типовима налога");
regGS("User may add/change article types", "Корисник може да додаје/мења типове чланака");
regGS("User may delete article types", "Корисник може да брише типове чланака");
regGS("User may add languages and manage language information", "Корисник може да додаје језике и управља информацијама о језику");
regGS("User may delete languages", "Корисник може да брише језике");
regGS("User may manage glossary infotypes", "Корисник може да управља инфотипима глосара ");
regGS("User may add/change glossary entries", "Корисник може да додаје/мења записе у глосару");
regGS("User may delete glossary entries", "Корисник може да брише записе у глосару");
regGS("User will be notified on several events", "Корисник ће бити обавештен о одређеним системским активностима");
regGS("User may view audit logs", "Корисник има приступ логовима");
regGS("User may add/change country names", "Корисник може да додаје/мења имена држава");
regGS("User may delete country entries", "Корисник може да брише податке о државама");
regGS("User may manage localizer", "Корисник има приступ лакализатору");
regGS("User may manage indexer", "Корисник има приступ индексеру");
regGS("User may publish articles", "Корисник може да објављује чланке");
regGS("User may manage topics", "Корисник може да управља темама");
regGS("User may use bold", "Корисник може да користи масна слова (болд)");
regGS("User may use italic", "Корисник може да користи курзив (италик)");
regGS("User may use underline", "Корисник може да користи подвучена слова");
regGS("User may use strikethrough", "Корисник може да користи прецртана слова");
regGS("User may change text alignment", "Корисник може да мења равнање текста");
regGS("User may copy, cut, and paste", "Корисник може да корсити копирање, лепљење и сечење");
regGS("User may undo/redo", "Корисник може да користи undo/redo");
regGS("User may change text direction", "Корисник може да мења правац текста");
regGS("User may set indents", "Корисник може да подешава увлачења");
regGS("User may add links", "Корисник може да додаје линкове");
regGS("User may add subheads", "Корисник може да додаје међунаслове");
regGS("User may insert images", "Корисник може да убацује слике");
regGS("User may view the HTML source", "Корисник има право прегледа ХТМЛ кода");
regGS("User may enlarge the editor", "Корисник може да повећава едитор");
regGS("User may change the font face", "Корисник може да мења фонтове");
regGS("User may change the font size", "Корисник може да мења величину текста");
regGS("User may create bulleted lists", "Корисник може да прави листе без редних бројева (bullet)");
regGS("User may create numbered lists", "Корисник може да прави листе са редним бројевима");
regGS("User may insert tables", "Корисник може да додаје табеле");
regGS("User may insert horizontal rules", "Корисник може да додаје хоризонталне линије");
regGS("User may change the font color", "Корисник може да мења боју слова");
regGS("User may use superscripts", "Корисник може да користи суперскрипт");
regGS("User may use subscripts", "Корисник може да корсити сабскрипт");
regGS("Updating user types permissions", "Мењање права  за тип корисника");
regGS("Adding new translation", "Додавање новог превода");
regGS("Translate keyword", "Преведи кључну реч");
regGS("No more languages.", "Нема више језика");
regGS("No such keyword infotype.", "Нема тог инфотипа за кључну реч ");
regGS("Adding new keyword infotype", "Додавање новог инфотипа за кључне речи");
regGS("The infotype has been deleted.", "Инфотип је избрисан");
regGS("The infotype could not be deleted.", "Инфотип не може бити избрисан");
regGS("The $1 field may only contain letters, digits and underscore (_) character.", "Поље $1 може садржати искључиво слова, бројке и доњу црту (_).");
regGS("Add new publication", "Додај нову публикацију");
regGS("Upload new template", "Аплоудуј нови шаблон");
regGS("Add new user account", "Додај новог корисника");
regGS("Add new user type", "Додај нови тип корисника");
regGS("Add new article type", "Додај нови тип чланка");
regGS("Add new country", "Додај државу");
regGS("Add new language", "Додај језик");
regGS("Add new section", "Додај нову рубрику");
regGS("View logs", "Прикажи логове");
regGS("Change your password", "Промени лозинку");
regGS("Your articles", "Твоји чланци");
regGS("Submitted articles", "Предати чланци");
regGS("Quick Menu", "Пречице");
regGS("Logs", "Логови");
regGS("There are $1 article(s) left.", "Преоста(л)о је $1 чланак(а)");
regGS("There are $1 issues(s) left.", "Преостало је $1 издања");
regGS("There are $1 section(s) left.", "Преоста(л)о је $1 рубрика");
regGS("There are $1 publication(s) left.", "Преостало(а) је $1 публикација");
regGS("There are $1 keywords(s) left.", "Преостало је $1 кључних речи");
regGS("There are $1 countries left.", "Преостало је $1 држава");
regGS("Name <SMALL>(click to edit)</SMALL>", "Име<br><small>(клик за уређивање)</small>");
regGS("User account", "Kориснички налог");
regGS("No such user account.", "Нема таквог корисничког налога");
regGS("Add new subscription", "Додај нову претплату");
regGS("You do not have the right to add subscriptions.", "Немате право да додајете претплате");
regGS("Adding subscription", "Додавање претплате");
regGS("The section could not be added.", "Рубрика не може бити додата");
regGS("Delete subscription", "Обриши претплату");
regGS("You do not have the right to delete subscriptions.", "Немате право да бришете претплате");
regGS("Deleting subscription", "Брисање претплате");
regGS("No such subscription.", "Нема такве претплате");
regGS("The section $1 could not be deleted.", "Рубрика $1 не може бити обрисана");
regGS("The topic $1 could not be deleted.", "Тема $1 не може бити обрисана");
regGS("Yes", "Да");
regGS("No", "Не");
regGS("Close", "Затвори");
regGS("No issues.", "Нема издања");
regGS("Back to Edit Article", "Назад на детаље чланка");
regGS("Adding new topic", "Додавање нове теме");
regGS("Topic $1 added", "Тема $1 је додата");
regGS("The topic could not be added.", "Тема не може бити додата");
regGS("Do you want to delete the topic $1?", "Желите ли да обришете тему $1?");
regGS("Add another topic", "Додај нову тему");
regGS("Deleting topic", "Брисање теме");
regGS("There are $1 subtopics left.", "Преостало је $1 подтема");
regGS("Topic $1 deleted", "Тема $1 је обрисана");
regGS("Changing topic name", "Промена имена теме");
regGS("You do not have the right to change topic name.", "Немате право да мењате име теме");
regGS("Topic $1 updated", "Тема $1 измењена");
regGS("The topic name could not be updated.", "Назив теме не може бити измењен");
regGS("Change topic name", "Промени назив теме");
regGS("Delete topic $1", "Обриши тему $1");
regGS("No topics", "Нема тема");
regGS("The topic $1 has been successfuly added.", "Тема $1 је успешно додата");
regGS("The topic $1 has been successfuly updated.", "Тема $1 је успешно измењена");
regGS("The topic $1 has been deleted.", "Тема $1 је успешно обрисана");
regGS("There are $1 articles using the topic.", "Преостало је $1 текстова који користе ову тему");
regGS("You must fill in the $1 field.", "Морате попунити поље $1");
regGS("You do not have the right to add articles.", "Немате право да додајете чланке");
regGS("Start", "Почетак");
regGS("Days", "Дана");
regGS("(YYYY-MM-DD)", "(ГГГГ-ММ-ДД)");
regGS("The sections were added successfully.", "Рубрике су успешно додате");
regGS("The sections could not be added successfully. Some of them were already added !", "Рубрике не могу бити додате. Неке од њих већ постоје!");
regGS("This article cannot be previewed. Please make sure it has the article template selected.", "Чланак не може бити прегелдан. Проверите да ли је одређен шаблон за приказ чланка.");
regGS("This article cannot be previewed. Please make sure it has the front page template selected.", "Овај чланак не може бити приказан. Проверите да ли је одређен шаблон за приказ почетне стране. ");
regGS("Add another", "Настави са додавањем");
regGS("Cancel", "Поништи");
regGS("Done", "Готово");
regGS("New Field", "Ново поље");
regGS("OK", "OK");
regGS("Save", "Сними измене");
regGS("Search", "Тражи");
regGS("Add New Field", "Додај ново поље");
?>