<?
regGS("User management","Управление пользователями:ru");
regGS("Set","Установить:ru");
regGS("Update","Обновить:ru");
regGS("Rights","Права:ru");
regGS("IP Access","IP-доступ:ru");
regGS("User Name","Имя пользователя:ru");
regGS("Full Name","Полное имя:ru");
regGS("Staff","Персонал:ru");
regGS("Delete user $1","Удалить пользователя $1:ru");
regGS("You do not have the right to create user accounts.","Вы не имеете права создания учетных записей пользователей.:ru");
regGS("Title","Заголовок:ru");
regGS("Gender","Пол:ru");
regGS("Mr.","г-н:ru");
regGS("Mrs.","г-жа:ru");
regGS("Ms.","г-жа:ru");
regGS("Dr.","д-р.:ru");
regGS("Male","Муж.:ru");
regGS("Female","Жен.:ru");
regGS("under 18","до 18 лет:ru");
regGS("65 or over","65 и старше:ru");
regGS("Age","Возраст:ru");
regGS("Confirm password","Подтвердите пароль:ru");
regGS("E-Mail","E-Mail:ru");
regGS("City","Город:ru");
regGS("Street Address","Адрес:ru");
regGS("Postal Code","Почтовый индекс:ru");
regGS("State","Страна:ru");
regGS("Phone","Телефон:ru");
regGS("Fax","Факс:ru");
regGS("Contact Person","Контактное лицо:ru");
regGS("Second Phone","Второй телефон:ru");
regGS("Employer","Работодатель:ru");
regGS("Employer Type","Типа работодателя:ru");
regGS("Corporate","Коммерческая организация:ru");
regGS("Non-Governmental Organisation","НКО:ru");
regGS("Government Agency","Правительственная организация:ru");
regGS("Academic","Учебное заведение:ru");
regGS("Media","СМИ:ru");
regGS("Position","Должность:ru");
regGS("Adding new user account","Добавление новой учетной записи:ru");
regGS("You must select a $1","Вы должны выбрать $1:ru");
regGS("The password must be at least 6 characters long and both passwords should match.","Пароль должен состоять не менее, чем из 6-ти символов. Оба пароля должны совпадать.:ru");
regGS("You must select an user type.","Вы должны выбрать тип пользователя.:ru");
regGS("The user account $1 has been created.","Создана учетная запись пользователя $1.:ru");
regGS("The user account could not be created.","Невозможно создать учетную запись пользователя.:ru");
regGS("Please check if an account with the same user name does not already exist.","Пожалуйста проверьте, что учетная запись с таким именем пользователя еще не существует.:ru");
regGS("User account $1 created","Создана учетная запись пользователя $1:ru");
regGS("Change user password","Изменить пароль пользователя:ru");
regGS("You do not have the right to change user passwords.","Вы не имеете права изменять пароли пользователей.:ru");
regGS("Changing user password","Изменение пароля пользователя:ru");
regGS("The password could not be changed.","Невозможно изменит пароль пользователя.:ru");
regGS("Password changed for $1","Изменен пароль для $1:ru");
regGS("The password has been changed.","Пароль был изменен.:ru");
regGS("User may manage templates","Пользователь может управлять шаблонами:ru");
regGS("User may add/change country entries","Пользователь может добавлять/изменять записи о странах:ru");
regGS("Edit user account permissions","Редактировать права учетной записи пользователя:ru");
regGS("You do not have the right to change user account permissions.","Вы не имеете права изменятьправа учетной записи пользователя.:ru");
regGS("This user account does not have permissions information.","Эта учетная запись не имеет информации о правах.:ru");
regGS("Updating user account permissions","Обновление прав учетной записи пользователя:ru");
regGS("Permissions for $1 changed","Изменены права для $1:ru");
regGS("User account permissions have been successfuly updated.","Права учетной записи пользователя были успешно обновлены.:ru");
regGS("User account permissions could not be updated.","Невозможно обновить права учетной записи пользователя.:ru");
regGS("Change user account information","Изменить информацию об учетной записи пользователя:ru");
regGS("You do not have the right to change user account information.","Вы не имеете права изменения информации об учетной записи пользователя.:ru");
regGS("Changing user account information","Изменение информации об учетной записи пользователя:ru");
regGS("User account information has been changed.","Информации об учетной записи пользователя изменена.:ru");
regGS("User account information could not be changed.","Невозможно изменить информацию об учетной записи пользователя.:ru");
regGS("User account information changed for $1","Информация об учетной записи пользователя изменена для $1:ru");
regGS("Old password","Старый пароль:ru");
regGS("New password","Новый пароль:ru");
regGS("Confirm new password","Подтвердите новый пароль:ru");
regGS("Changing your password","Изменение вашего пароля:ru");
regGS("The password you typed is incorrect.","Вы ввели неверный пароль.:ru");
regGS("User $1 changed his password","Пользователь $1 изменил свой пароль:ru");
regGS("Delete user account","Удалить учетную запись пользователя:ru");
regGS("You do not have the right to delete user accounts.","Вы не имеете права удаления учетных записей пользователей.:ru");
regGS("Are you sure you want to delete the user account $1 ?","Вы уверены, что хотите удалить учетную запись пользователя $1 ?:ru");
regGS("Deleting user account","Удаление учетной записи пользователя:ru");
regGS("The user account $1 has been deleted.","Учетная запись пользователя $1 удалена.:ru");
regGS("The user account $1 could not be deleted.","Невозможно удалить учетную запись пользователя $1.:ru");
regGS("No such user.","Нет такого пользователя:ru");
regGS("User IP access list management","Управление списком IP-доступа пользователей:ru");
regGS("Add new IP address group","Добавление новой группы IP-адресов:ru");
regGS("No records.","Нет записей.:ru");
regGS("Delete IP Group $1","Удалить группу IP-адресов $1:ru");
regGS("You do not have the right to add IP address groups.","Вы не имеете права добавления групп IP-адресов.:ru");
regGS("Start IP","Начальный IP:ru");
regGS("Number of addresses","Количество адресов:ru");
regGS("IP Access List","Список IP-доступа:ru");
regGS("Adding new IP Group","Добавление новой группы IP-адресов:ru");
regGS("The IP Group $1 has been created.","Создана группа IP-адресов $1.:ru");
regGS("IP Group $1 added for user $2","Группа IP-адресов $1 добавлена для пользователя $2:ru");
regGS("The IP Group could not be created.","Невозможно создать группу IP-адресов:ru");
regGS("Please check if an account with the same IP Group does not already exist.","Пожалуйста проверьте, что еще не существует учетной записи пользователя с такой же группой IP-адресов.:ru");
regGS("Delete IP Group","Удалить группу IP-адресов:ru");
regGS("You do not have the right to delete IP Groups.","Вы не имеете права удаления группы IP-адресов:ru");
regGS("Are you sure you want to delete the IP Group $1?","Вы уверены, что хотите удалить группу IP-адресов $1:ru");
regGS("No such IP Group.","Нет такой группы IP-адресов.:ru");
regGS("Deleting IP Group","Удаление группы IP-адресов:ru");
regGS("The IP address group $1 has been deleted.","Группа IP-адресов $1 была удалена.:ru");
regGS("The IP Group could not be deleted.","Невзможно удалить группу IP-адресов.:ru");

?>
