<?php
regGS("You do not have the right to add IP address groups.", "Вы не имеете права добавления групп IP-адресов.");
regGS("Readers", "Читатели");
regGS("Edit reader data", "Редактировать данные читателя");
regGS("Add new IP address group", "Добавление новой группы IP-адресов");
regGS("Staff management", "Управление персоналом");
regGS("Subscribers management", "Управление подписчиками");
regGS("Edit user rights", "Редактировать права пользователей");
regGS("User Name", "Имя пользователя");
regGS("Full Name", "Полное имя");
regGS("Delete user $1", "Удалить пользователя $1");
regGS("User list is empty.", "Список пользователей пуст.");
regGS("You do not have the right to create user accounts.", "Вы не имеете права создавать учетные записи пользователей.");
regGS("Title", "Заголовок");
regGS("Gender", "Пол");
regGS("Mr.", "г-н");
regGS("Mrs.", "г-жа");
regGS("Ms.", "г-жа");
regGS("Dr.", "д-р.");
regGS("Male", "Муж.");
regGS("Female", "Жен.");
regGS("under 18", "до 18 лет");
regGS("65 or over", "65 и старше");
regGS("Age", "Возраст");
regGS("Confirm password", "Подтвердите пароль");
regGS("E-Mail", "E-Mail");
regGS("City", "Город");
regGS("Street Address", "Адрес");
regGS("Postal Code", "Почтовый индекс");
regGS("State", "Страна");
regGS("Phone", "Телефон");
regGS("Fax", "Факс");
regGS("Contact Person", "Контактное лицо");
regGS("Second Phone", "Второй телефон");
regGS("Employer", "Компания");
regGS("Employer Type", "Тип компании");
regGS("Corporate", "Коммерческая организация");
regGS("Non-Governmental Organisation", "НКО");
regGS("Government Agency", "Правительственная организация");
regGS("Academic", "Учебное заведение");
regGS("Media", "СМИ");
regGS("Position", "Должность");
regGS("Show more user details", "Показать подробности о пользователе");
regGS("Hide user details", "Спрятать подробности о пользователе");
regGS("You must select a $1", "Вы должны выбрать $1");
regGS("The password must be at least 6 characters long and both passwords should match.", "Пароль должен состоять не менее, чем из 6-ти символов. Оба пароля должны совпадать.");
regGS("The user account could not be created.", "Невозможно создать учетную запись пользователя.");
regGS("User account $1 was created successfully.", "Учетная запись пользователя $1 была успешно создана.");
regGS("User account $1 created", "Создана учетная запись пользователя $1");
regGS("Click here to change password", "Щелкните здесь для смены пароля");
regGS("Old Password", "Старый пароль");
regGS("Password changed for $1", "Изменен пароль для $1");
regGS("You do not have the right to change user account permissions.", "Вы не имеете права изменятьправа учетной записи пользователя.");
regGS("Permissions for $1 changed", "Изменены права для $1");
regGS("You do not have the right to change user account information.", "Вы не имеете права изменения информации об учетной записи пользователя.");
regGS("Click here to customize user permissions", "Щелкните здесь для персональной настройки прав пользователя");
regGS("Click here to use existing user type permissions (discard customization)", "Щелкните здесь для использования прав существующего типа пользователей (отмена персонализации)");
regGS("Click here to leave password unchanged", "Щелкните здесь, чтобы оставить пароль без изменений");
regGS("User account information changed for $1", "Информация об учетной записи пользователя изменена для $1");
regGS("The password you typed is incorrect.", "Вы ввели неверный пароль.");
regGS("You do not have the right to delete user accounts.", "Вы не имеете права удаления учетных записей пользователей.");
regGS("Are you sure you want to delete the user account $1 ?", "Вы уверены, что хотите удалить учетную запись пользователя $1?");
regGS("User account $1 was deleted successfully.", "Учетная запись пользователя $1 успешно удалена");
regGS("The user account $1 has been deleted.", "Учетная запись пользователя $1 удалена.");
regGS("User IP access list management", "Управление списком IP-доступа пользователей");
regGS("No records.", "Нет записей.");
regGS("Start IP", "Начальный IP");
regGS("Number of addresses", "Количество адресов");
regGS("The IP Group $1 has been created.", "IP-группа $1 была создана");
regGS("IP Group $1 added for user $2", "Группа IP-адресов $1 добавлена для пользователя $2");
regGS("There was an error creating the IP address group.", "Ошибка создания группы IP адресов.");
regGS("An IP address group having the $1 start address already exists.", "Группа IP адресов со стартовым адресом $1 уже существует.");
regGS("Are you sure you want to delete the IP Group $1?", "Вы уверены, что хотите удалить группу IP-адресов $1");
regGS("The IP address group $1 has been deleted.", "Группа IP-адресов $1 была удалена.");
regGS("User '$1' information was changed successfully.", "Информация пользователя '$1' была успешно изменена.");
regGS("IP address", "IP-адрес");
regGS("fill in from left to right at least one input box", "Заполните слева направо хотя бы одно поле ввода");
regGS("User Type", "Тип пользователя");
regGS("You must input a valid EMail address.", "Вы должны ввести правильный адрес Е-mail.");
regGS("The confirm password must be at least 6 characters long and both passwords should match.", "Подтверждающий пароль должен состоять как минимум из 6 символов и оба пароля должны совпадать.");
regGS("You must input a number between 0 and 255 into the Start IP address' $1 field.", "Вы должны ввести число между 0 и 255 в поле $1 начала IP-адресов");
regGS("Delete subscriptions to $1", "Удалить подписку для $1");
regGS("Change user account information", "Изменить информацию учетной записи пользовтеля");
regGS(" management", "");
regGS("Change password", "Изменить пароль пользователя");
regGS("You do not have the right to change user passwords.", "Вы не имеете права изменять пароли пользователей.");
regGS("The password could not be changed.", "Невозможно изменит пароль пользователя.");
regGS("The password has been changed.", "Пароль был изменен.");
regGS("Edit user account permissions", "Редактировать права учетной записи пользователя");
regGS("Old password", "Старый пароль");
regGS("New password", "Новый пароль");
regGS("Confirm new password", "Подтвердите новый пароль");
regGS("Changing your password", "Изменение вашего пароля");
regGS("User $1 changed his password", "Пользователь $1 изменил свой пароль");
regGS("Delete user account", "Удалить учетную запись пользователя");
regGS("IP Access List", "Список IP-доступа");
regGS("Delete IP Group", "Удалить группу IP-адресов");
regGS("You do not have the right to delete IP Groups.", "Вы не имеете права удаления группы IP-адресов");
regGS("No such IP Group.", "Нет такой группы IP-адресов.");
regGS("User management", "Управление пользователями:ru");
regGS("Staff", "Персонал:ru");
regGS("User may manage templates", "Пользователь может управлять шаблонами:ru");
regGS("User may add/change country entries", "Пользователь может добавлять/изменять записи о странах:ru");
?>