<?php
regGS("Staff management","Staff management:en");
regGS("Subscribers management","Subscribers management:en");
regGS("Edit user rights","Edit user rights:en");
regGS("User Name","User Name:en");
regGS("Full Name","Full Name:en");
regGS("Delete user $1","Delete user $1:en");
regGS("User list is empty.","User list is empty.");
regGS("You do not have the right to create user accounts.","You do not have the right to create user accounts.:en");
regGS("Title","Title:en");
regGS("Gender","Gender:en");
regGS("Mr.","Mr.:en");
regGS("Mrs.","Mrs.:en");
regGS("Ms.","Ms.:en");
regGS("Dr.","Dr.:en");
regGS("Male","Male:en");
regGS("Female","Female:en");
regGS("under 18","under 18:en");
regGS("65 or over","65 or over:en");
regGS("Age","Age:en");
regGS("Confirm password","Confirm password:en");
regGS("E-Mail","E-Mail:en");
regGS("City","City:en");
regGS("Street Address","Street Address:en");
regGS("Postal Code","Postal Code:en");
regGS("State","State:en");
regGS("Phone","Phone:en");
regGS("Fax","Fax:en");
regGS("Contact Person","Contact Person:en");
regGS("Second Phone","Second Phone:en");
regGS("Employer","Employer:en");
regGS("Employer Type","Employer Type:en");
regGS("Corporate","Corporate:en");
regGS("Non-Governmental Organisation","Non-Governmental Organisation:en");
regGS("Government Agency","Government Agency:en");
regGS("Academic","Academic:en");
regGS("Media","Media:en");
regGS("Position","Position:en");
regGS("Show more user details", "Show more user details:en");
regGS("Hide user details", "Hide user details:en");
regGS("You must select a $1","You must select a $1:en");
regGS("The password must be at least 6 characters long and both passwords should match.","The password must be at least 6 characters long and both passwords should match.:en");
regGS("The user account could not be created.","The user account could not be created.:en");
regGS("User account $1 was created successfully.", "User account $1 was created successfully.:en");
regGS("User account $1 created","User account $1 created:en");
regGS("Click here to change password","Click here to change password:en");
regGS("Old Password", "Old Password:en");
regGS("Password changed for $1","Password changed for $1:en");
regGS("You do not have the right to change user account permissions.","You do not have the right to change user account permissions.:en");
regGS("Permissions for $1 changed","Permissions for $1 changed:en");
regGS("You do not have the right to change user account information.","You do not have the right to change user account information.:en");
regGS("Click here to customize user permissions","Click here to customize user permissions:en");
regGS("Click here to use existing user type permissions (discard customization)","Click here to use existing user type permissions (discard customization):en");
regGS("Click here to leave password unchanged","Click here to leave password unchanged:en");
regGS("User account information changed for $1","User account information changed for $1:en");
regGS("The password you typed is incorrect.","The password you typed is incorrect.:en");
regGS("You do not have the right to delete user accounts.","You do not have the right to delete user accounts.:en");
regGS("Are you sure you want to delete the user account $1 ?","Are you sure you want to delete the user account $1 ?:en");
regGS("User account $1 was deleted successfully.", "User account $1 was deleted successfully.:en");
regGS("The user account $1 has been deleted.","The user account $1 has been deleted.:en");
regGS("User IP access list management","User IP access list management:en");
regGS("No records.","No records.:en");
regGS("Start IP","Start IP:en");
regGS("Number of addresses","Number of addresses:en");
regGS("The IP Group $1 has been created.","The IP Group $1 has been created.:en");
regGS("IP Group $1 added for user $2","IP Group $1 added for user $2:en");
regGS("There was an error creating the IP address group.", "There was an error creating the IP address group.:en");
regGS("An IP address group having the $1 start address already exists.", "An IP address group having the $1 start address already exists.:en");
regGS("Are you sure you want to delete the IP Group $1?","Are you sure you want to delete the IP Group $1?:en");
regGS("The IP address group $1 has been deleted.","The IP address group $1 has been deleted.:en");
regGS("User '$1' information was changed successfully.", "User '$1' information was changed successfully.:en");
regGS("IP address", "IP address:en");
regGS("fill in from left to right at least one input box", "fill in from left to right at least one input box:en");
regGS("User Type", "User Type:en");
regGS("You must input a valid EMail address.", "You must input a valid EMail address.:en");
regGS("The confirm password must be at least 6 characters long and both passwords should match.", "The confirm password must be at least 6 characters long and both passwords should match.:en");
regGS("You must input a number between 0 and 255 into the Start IP address' $1 field.", "You must input a number between 0 and 255 into the Start IP address' $1 field.:en");
regGS("Delete subscriptions to $1", "Delete subscriptions to $1:en");
regGS("Change user account information", "Change user account information:en");
?>