<?php
regGS("Create new folder", "Создать новую папку");
regGS("Upload template", "Загрузить шаблон");
regGS("Creating new folder", "Создание новой папки");
regGS("You do not have the right to create new folders.", "Вы не имеете права создания новых папок.");
regGS("The folder $1 has been created", "Папка $1 была создана");
regGS("The folder $1 could not be created", "Невозможно создать папку $1");
regGS("A file or folder having the name $1 already exists", "Файл или папка с названием $1 уже существует");
regGS("Delete templates", "Удалить шаблоны");
regGS("Delete folders", "Удалить папки");
regGS("You do not have the right to delete templates.", "Вы не имеете права удаления шаблонов.");
regGS("Are you sure you want to delete the folder $1 from $2?", "Вы уверены, что хотите удалить папку $1 из $2?");
regGS("Are you sure you want to delete the template $1 from folder $2?", "Вы уверены, что хотите удалить шаблон $1 из папки $2?");
regGS("Deleting template", "Удаление шаблона");
regGS("Deleting folder", "Удаление папки");
regGS("Template $1 was deleted", "Шаблон $1 был удален");
regGS("Delete folder", "Удалить папку");
regGS("Folders", "Папки");
regGS("No folders.", "Нет папок.");
regGS("Files", "Файлы");
regGS("No templates.", "Нет шаблонов");
regGS("Uploading template", "Загрузка шаблонов");
regGS("File", "Файл");
regGS("File $1 already exists.", "Файл $1 уже существует.");
regGS("File $1 already exists. Old version deleted !", "Файл $1 уже существует. Старая версия удалена!");
regGS("The upload of $1 was successful !", "Загрузка $1 была успешной!");
regGS("Template $1 uploaded", "Загружен шаблон $1");
regGS("Create new template", "Создать новый шаблон");
regGS("Creating new template", "Создание нового шаблона");
regGS("Duplicate template", "Дублировать шаблон");
regGS("Edit template", "Редактировать шаблон");
regGS("Template", "Шаблон");
regGS("The template could not be saved", "Невозможно сохранить шаблон");
regGS("The template has been saved.", "Шаблон был сохранен.");
regGS("The template $1 has been created.", "Шаблон $1 был создан.");
regGS("Do you want to edit the template ?", "Хотите ли вы редактировать шаблон?");
regGS("The template $1 could not be created.", "Невозможно создать шаблон $1");
regGS("Template $1 was changed", "Шаблон $1 был изменен");
regGS("New template $1 was created", "Был создан новый шаблон $1");
regGS("Template $1 was duplicated into $2", "Шаблон $1 был дублирован в $2");
regGS("Error converting the template to UTF-8 charset.", "Ошибка конвертации шаблона в UTF-8");
regGS("Template charset", "Кодовая таблица шаблона");
regGS("Select a language/character set", "Выберите язык/кодовую таблицу");
regGS("All languages", "Все языки");
regGS("You do not have the right to modify templates.", "Вы не имеет а права модифицировать шаблон.");
regGS("Invalid template file $1", "Неправильный шаблон $1");
regGS("You do not have the right to create folders.", "Вы не имеет а права создавать папки.");
regGS("You do not have the right to upload templates.", "Вы не имеет а права загружать шаблоны.");
regGS("You do not have the right to delete folders.", "Вы не имеет а права удалять папки");
regGS("You do not have the right to create templates.", "Вы не имеет а права создавать шаблоны.");
regGS("Duplicate file", "Дублировать файл");
regGS("Delete file", "Удалить файл");
?>