<?php
regGS("Create new folder", "Neuen Ordner erstellen");
regGS("Upload template", "Template hochladen");
regGS("Creating new folder", "Neuer Ordner wird erstellt");
regGS("You do not have the right to create new folders.", "Keine Berechtigung neuen Ordner zu erstellen");
regGS("The folder $1 has been created", "Ordner $1 wurde erstellt");
regGS("The folder $1 could not be created", "Ordner $1 konnte nicht erstellt werden");
regGS("A file or folder having the name $1 already exists", "");
regGS("Delete templates", "Templates löschen");
regGS("Delete folders", "Ordner löschen");
regGS("You do not have the right to delete templates.", "Keine Berechtigung Templates zu löschen");
regGS("Are you sure you want to delete the folder $1 from $2?", "Ordner $1 aus $2 wirklich löschen?");
regGS("Are you sure you want to delete the template $1 from folder $2?", "Template $1 aus Ordner $2 wirklich löschen?");
regGS("The template $1 is in use and can not be deleted.", "");
regGS("Deleting template", "Template wird gelöscht");
regGS("Deleting folder", "Ordner wird gelöscht");
regGS("The folder has been deleted.", "Ordner wurde gelöscht");
regGS("The folder could not be deleted.", "Ordner konnte nicht gelöscht werden");
regGS("The template has been deleted.", "Template wurde gelöscht");
regGS("The template could not be deleted.", "Template konnte nicht gelöscht werden");
regGS("Template $1 was deleted", "");
regGS("Delete folder", "Ordner löschen");
regGS("Folders", "Ordner");
regGS("No folders.", "Keine Ordner");
regGS("Files", "Dateien");
regGS("No templates.", "Keine Templaters");
regGS("Uploading template", "Template wird hochgeladen");
regGS("File", "Datei");
regGS("File $1 already exists.", "Datei $1 existiert bereits");
regGS("File $1 already exists. Old version deleted !", "Datei $1 existiert bereits. Alte Version gelöscht");
regGS("The upload of $1 was successful !", "$1 erfolgreich hochgeladen");
regGS("Template $1 uploaded", "Template $1 hochgeladen");
regGS("Create new template", "Neues Template erstellen");
regGS("Creating new template", "Neues Template wird erstellt");
regGS("Duplicate template", "Template Duplizieren");
regGS("Edit template", "Template Bearbeiten");
regGS("Template", "Template");
regGS("Save", "Speichern");
regGS("The template could not be saved", "Template konnte nicht gespeichert werden");
regGS("The template has been saved.", "Template gespeichert");
regGS("The template $1 has been created.", "Template $1 wurde erstellt");
regGS("Do you want to edit the template ?", "Template bearbeiten?");
regGS("The template $1 could not be created.", "Template $1 konnte nicht erstellt werden");
regGS("Template $1 was changed", "Template $1 wurde geändert");
regGS("New template $1 was created", "Neues Template $1 wurde erstellt");
regGS("Template $1 was duplicated into $2", "Template $1 wurde in $2 dupliziert???");
regGS("Error converting the template to UTF-8 charset.", "Fehler bei der Umwandlung des Templates in UTF-8 Unicode.");
regGS("Template charset", "Template Charset");
regGS("Select a language/character set", "Sprache / Zeichensatz auswählen");
regGS("All languages", "Alle Sprachen");
regGS("You do not have the right to modify templates.", "");
regGS("Invalid template file $1", "");
?>