<?php 
regGS("Create new folder","Create new folder:en");
regGS("Upload template","Upload template:en");
regGS("Creating new folder","Creating new folder:en");
regGS("You do not have the right to create new folders.","You do not have the right to create new folders.:en");
regGS("The folder $1 has been created","The folder $1 has been created:en");
regGS("The folder $1 could not be created","The folder $1 could not be created:en");
regGS("A file or folder having the name $1 already exists","A file or folder having the name $1 already exists:en");
regGS("Delete templates","Delete templates:en");
regGS("Delete folders","Delete folders:en");
regGS("You do not have the right to delete templates.","You do not have the right to delete templates.:en");
regGS("Are you sure you want to delete the folder $1 from $2?","Are you sure you want to delete the folder $1 from $2?:en");
regGS("Are you sure you want to delete the template $1 from folder $2?","Are you sure you want to delete the template $1 from folder $2?:en");
regGS("Deleting template","Deleting template:en");
regGS("Deleting folder","Deleting folder:en");
regGS("Template $1 was deleted","Template $1 was deleted:en");
regGS("Delete folder","Delete folder:en");
regGS("Folders","Folders:en");
regGS("No folders.","No folders.:en");
regGS("Files","Files:en");
regGS("No templates.","No templates.:en");
regGS("Uploading template","Uploading template:en");
regGS("File","File:en");
regGS("File $1 already exists.", "File $1 already exists.:en");
regGS("File $1 already exists. Old version deleted !", "File $1 already exists. Old version deleted !:en");
regGS("The upload of $1 was successful !", "The upload of $1 was successful !:en");
regGS("Template $1 uploaded", "Template $1 uploaded:en");
regGS("Create new template", "Create new template:en");
regGS("Creating new template", "Creating new template:en");
regGS("Duplicate template", "Duplicate template:en");
regGS("Edit template", "Edit template:en");
regGS("Template", "Template:en");
regGS("The template could not be saved", "The template could not be saved:en");
regGS("The template has been saved.","The template has been saved.:en");
regGS("The template $1 has been created.", "The template $1 has been created.:en");
regGS("Do you want to edit the template ?", "Do you want to edit the template ?:en");
regGS("The template $1 could not be created.", "The template $1 could not be created.:en");
regGS("Template $1 was changed", "Template $1 was changed:en");
regGS("New template $1 was created", "New template $1 was created:en");
regGS("Template $1 was duplicated into $2", "Template $1 was duplicated into $2:en");
regGS("Error converting the template to UTF-8 charset.", "Error converting the template to UTF-8 charset.");
regGS("Template charset", "Template charset");
regGS("Select a language/character set", "Select a language/character set");
regGS("All languages", "All languages");
regGS("You do not have the right to modify templates.","You do not have the right to modify templates.:en");
regGS("Invalid template file $1", "Invalid template file $1:en");
regGS("You do not have the right to create folders.", "You do not have the right to create folders.:en");
regGS("You do not have the right to upload templates.", "You do not have the right to upload templates.:en");
regGS("You do not have the right to delete folders.", "You do not have the right to delete folders.:en");
regGS("You do not have the right to create templates.", "You do not have the right to create templates.:en");
regGS("Duplicate file", "Duplicate file:en");
regGS("Delete file", "Delete file:en");
?>