<?php
regGS("Create new folder", "Crear nuevo directorio");
regGS("Upload template", "Subir plantilla");
regGS("Creating new folder", "Crear nuevo directorio");
regGS("You do not have the right to create new folders.", "No tiene derecho para crear nuevos directorios");
regGS("The folder $1 has been created", "EL directorio $1 ha sido creado");
regGS("The folder $1 could not be created", "El directorio $1 no pudo ser creado");
regGS("A file or folder having the name $1 already exists", "");
regGS("Delete templates", "Borrar plantillas");
regGS("Delete folders", "Borrar directorios");
regGS("You do not have the right to delete templates.", "No tiene derechos para borrar plantillas");
regGS("Are you sure you want to delete the folder $1 from $2?", "Esta seguro que desea borrar el directorio $1 de $2?");
regGS("Are you sure you want to delete the template $1 from folder $2?", "Esta seguro que desea borrar la plantilla $1 del directorio $2?");
regGS("The template $1 is in use and can not be deleted.", "");
regGS("Deleting template", "Borrando plantillas");
regGS("Deleting folder", "Borrando directorios");
regGS("The folder has been deleted.", "El directorio ha sido borrado");
regGS("The folder could not be deleted.", "El directorio no pudo ser borrado");
regGS("The template has been deleted.", "La plantilla ha sido borrada");
regGS("The template could not be deleted.", "La plantilla no pudo ser borrada");
regGS("Template $1 was deleted", "");
regGS("Delete folder", "Borrar directorio");
regGS("Folders", "Directorios");
regGS("No folders.", "Sin directorios");
regGS("Files", "Archivos");
regGS("No templates.", "Sin plantillas");
regGS("Uploading template", "Subiendo plantillas");
regGS("File", "Archivo");
regGS("File $1 already exists.", "Archivo $1 ya existe");
regGS("File $1 already exists. Old version deleted !", "Archivo $1 ya existe.  ¡Vieja versión borrada!");
regGS("The upload of $1 was successful !", "¡Subida de $1 fue con éxito!");
regGS("Template $1 uploaded", "Plantilla $1 subida");
regGS("Create new template", "Crear nueva plantilla");
regGS("Creating new template", "Creando nuevas plantillas");
regGS("Duplicate template", "Duplicar plantilla");
regGS("Edit template", "Editar plantilla");
regGS("Template", "Plantilla");
regGS("Save", "Grabar");
regGS("The template could not be saved", "La plantilla no pudo ser grabada");
regGS("The template has been saved.", "La plantilla ha sido grabada");
regGS("The template $1 has been created.", "La plantilla $1 ha sido creada");
regGS("Do you want to edit the template ?", "¿Desea editar la plantilla?");
regGS("The template $1 could not be created.", "La plantilla $1 no pudo ser creada");
regGS("Template $1 was changed", "La plantilla $1 fue cambiada");
regGS("New template $1 was created", "Nueva plantilla $1 fue creada");
regGS("Template $1 was duplicated into $2", "Plantilla $1 fue duplicada a $2");
regGS("Error converting the template to UTF-8 charset.", "Error convirtiendo plantilla a UTF-8 charset");
regGS("Template charset", "Plantilla charset");
regGS("Select a language/character set", "Seleccione un idioma/charset");
regGS("All languages", "Todos los idiomas");
regGS("You do not have the right to modify templates.", "");
regGS("Invalid template file $1", "");
?>