<?php
regGS("Publication<BR><SMALL>(click to see sections)</SMALL>", "Publicación");
regGS("Left to pay", "Pendiende de pago");
regGS("Active", "Activo");
regGS("Delete subscriptions to $1", "Borrar suscripción a $1");
regGS("No subscriptions.", "Sin suscripciones");
regGS("Paid subscription", "Suscripción pagada");
regGS("Trial subscription", "Suscripción de prueba");
regGS("Are you sure you want to delete the subscription to the publication $1?", "¿Esta seguro que desea borrar la suscripción a la publicación $1?");
regGS("The subscription has been deleted.", "La suscripcion ha sido borrada");
regGS("The subscription could not be deleted.", "La suscripcion no pudo ser borrada");
regGS("Add sections now", "Agregar secciones ahora");
regGS("Add sections later", "Agregar secciones despues");
regGS("Subscription Type", "Tipo de suscripción");
regGS("Paid (payment will be confirmed later)", "Pagado ( pago sera confirmado luego )");
regGS("Paid (confirm payment now)", "Pagado ( confirmar pago ahora )");
regGS("Trial", "Prueba");
regGS("The subscription has been added successfully.", "La suscripción ha sido agregada con exito");
regGS("The subscription could not be added.", "La suscripción no puedo ser agregada");
regGS("Please check if there isn't another subscription to the same publication.", "Favor revise si no existe otra suscripción a la misma publicacion");
regGS("Change subscription status", "Cambiar estatus de suscripción ");
regGS("You do not have the right to change subscriptions status.", "No tiene derecho a cambiar estatus de suscripción");
regGS("Are you sure you want to deactivate the subscription?", "¿Esta seguro que desea desactivar la suscripción?");
regGS("Are you sure you want to activate the subscription?", "¿Esta seguro que desea activar la suscripción?");
regGS("Changing subscription status", "Cambiando estatus de suscripción");
regGS("The subscription has been activated.", "La suscripción ha sido activada");
regGS("The subscription has been deactivated.", "La suscripción ha sido desactivada");
regGS("Subscription status could not be changed.", "Estatus de suscripción no pudo ser cambiado");
regGS("Update payment", "Actualizar pago");
regGS("The subscription payment was updated.", "El pago de suscripción fue actualizado");
regGS("Subscription payment could not be changed.", "El pago de suscripción no pudo ser cambiado");
?>