<?php
regGS("Publication<BR><SMALL>(click to see sections)</SMALL>", "Publicação <br> (Carregue para ver secções)");
regGS("Left to pay", "");
regGS("Active", "Activo");
regGS("Delete subscriptions to $1", "Eliminar assinaturas para $1");
regGS("No subscriptions.", "Não existem assinaturas");
regGS("Paid subscription", "Assinatura");
regGS("Trial subscription", "Periodo Gratuito");
regGS("Are you sure you want to delete the subscription to the publication $1?", "Eliminar assinatura da publicação $1?");
regGS("The subscription has been deleted.", "Assinatura eliminada.");
regGS("The subscription could not be deleted.", "Assinatura não pode ser eliminada");
regGS("Add sections now", "Adicionar agora Secções");
regGS("Add sections later", "Adicionar Secções posteriormente");
regGS("Subscription Type", "Tipo de Assinatura");
regGS("Paid (payment will be confirmed later)", "Paga (pagamento será confirmado mais tarde)");
regGS("Paid (confirm payment now)", "Paga (confirme pagamente neste momento)");
regGS("Trial", "Periodo Gratuito");
regGS("The subscription has been added successfully.", "Assinatura aceite");
regGS("The subscription could not be added.", "Não é possivel aceitar assinatura");
regGS("Please check if there isn't another subscription to the same publication.", "Verifique se a assinatura não é duplicada");
regGS("Change subscription status", "Alterar status da Assinatura");
regGS("You do not have the right to change subscriptions status.", "não tem permissões para alterar o Status de Assinaturas");
regGS("Are you sure you want to deactivate the subscription?", "Suspender Assinatura?");
regGS("Are you sure you want to activate the subscription?", "Activar Assinatura");
regGS("Changing subscription status", "Alterando o Status da Assinatura");
regGS("The subscription has been activated.", "A Assinatura foi activada");
regGS("The subscription has been deactivated.", "A Assinatura foi suspensa");
regGS("Subscription status could not be changed.", "O Status da Assinatura não pode ser alterado");
regGS("Update payment", "Actualizar Pagamento");
regGS("The subscription payment was updated.", "O periodo de vigencia da Assinatura foi alterado");
regGS("Subscription payment could not be changed.", "O periodo de vigencia da Assinatura não pode ser alterado");
?>