<?php
regGS("Publication<BR><SMALL>(click to see sections)</SMALL>", "Publikation (anklicken um Rubriken zu betrachten)");
regGS("Left to pay", "Noch zu zahlen");
regGS("Active", "Aktiv");
regGS("Delete subscriptions to $1", "Abonoment an $1 löschen");
regGS("No subscriptions.", "Keine Abonoments");
regGS("Paid subscription", "Volles Abonnement");
regGS("Trial subscription", "Probe-Abonnement");
regGS("Are you sure you want to delete the subscription to the publication $1?", "Abonoment an Publikation $1 wirklich löschen?");
regGS("The subscription has been deleted.", "Abonoment wurde gelöscht");
regGS("The subscription could not be deleted.", "Abonoment konnte nicht gelöscht werden");
regGS("Add sections now", "Rubriken jetzt hinzufügen");
regGS("Add sections later", "Rubriken später hinzufügen");
regGS("Subscription Type", "Abonnementen-Art");
regGS("Paid (payment will be confirmed later)", "Bezahlt (Bezahlung wird später bestätigt)");
regGS("Paid (confirm payment now)", "Bezahlt (Bezahlung jetzt bestätigen)");
regGS("Trial", "Probe");
regGS("The subscription has been added successfully.", "Abonoment wurde erfolgreich hinzugefügt");
regGS("The subscription could not be added.", "Abonoment konnte nicht hinzugefügt werden");
regGS("Please check if there isn't another subscription to the same publication.", "Bitte überprüfen, ob ein weiters Abonoment für dieselbe Publikation exitiert");
regGS("Change subscription status", "Abonomentstatus ändern");
regGS("You do not have the right to change subscriptions status.", "Keine Berechtigung den Abonomentstatus zu ändern");
regGS("Are you sure you want to deactivate the subscription?", "Abonoment wirklich deaktivieren?");
regGS("Are you sure you want to activate the subscription?", "Abonoment wirklich aktivieren?");
regGS("Changing subscription status", "Abonomentstatus wird geändert");
regGS("The subscription has been activated.", "Abonoment wurde aktiviert");
regGS("The subscription has been deactivated.", "Abonoment wurde deaktiviert");
regGS("Subscription status could not be changed.", "Abonomentstatus konnte nicht geändert werden");
regGS("Update payment", "Zahlung aktualisieren");
regGS("The subscription payment was updated.", "Abonomentzahlung wurde aktualisiert");
regGS("Subscription payment could not be changed.", "Abonomentzahlung konnte nicht geändert werden");
?>