<?php
regGS("Publication<BR><SMALL>(click to see sections)</SMALL>", "Publikace ");
regGS("Left to pay", "Zbývá zaplatit");
regGS("Active", "Aktivovat");
regGS("Delete subscriptions to $1", "Smazat předplatné $1 ");
regGS("No subscriptions.", "Žádné předplatné");
regGS("Paid subscription", "Zaplacené předplatné");
regGS("Trial subscription", "Zkušební předplatné");
regGS("Are you sure you want to delete the subscription to the publication $1?", "Určite chcete smazat předplatné k publikaci $1?");
regGS("The subscription has been deleted.", "Předplatné bylo smazáno");
regGS("The subscription could not be deleted.", "Předplatné nemohlo být smazáno");
regGS("Add sections now", "Přidat rubriku nyní");
regGS("Add sections later", "Přidat rubriku později");
regGS("Subscription Type", "Typ předplatného");
regGS("Paid (payment will be confirmed later)", "Zaplaceno (platba bude potvrzena později)");
regGS("Paid (confirm payment now)", "Zaplaceno (potvrďte nyní)");
regGS("Trial", "Zkušební");
regGS("The subscription has been added successfully.", "Předplatné bylo úspěšně přidáno");
regGS("The subscription could not be added.", "Předplatné nemohlo být přidáno");
regGS("Please check if there isn't another subscription to the same publication.", "Zkontrolujte, zda již neexistuje předplatné ke stejné publikaci");
regGS("Change subscription status", "Změnit stav předplatného");
regGS("You do not have the right to change subscriptions status.", "Nemáte právo měnit stav předplatného");
regGS("Are you sure you want to deactivate the subscription?", "Určitě chcete deaktivovat předplatné?");
regGS("Are you sure you want to activate the subscription?", "Určitě chcete aktivovat předplatné?");
regGS("Changing subscription status", "Změna stavu předplatného");
regGS("The subscription has been activated.", "Předplatné bylo aktivováno");
regGS("The subscription has been deactivated.", "Předplatné bylo deaktivováno");
regGS("Subscription status could not be changed.", "Předplatné nemohlo být změněno");
regGS("Update payment", "Obnovit platby");
regGS("The subscription payment was updated.", "Platba předplatného byla obnovena");
regGS("Subscription payment could not be changed.", "Platba předplatného nemohla být změněna");
?>