<?php 
$translator = \Zend_Registry::get('container')->getService('translator');
$this->placeholder('title')->set($translator->trans('Add new subscription section', array(), 'user_subscription_sections')); ?>

<?php echo $this->form; ?>

<script type="text/javascript">
$(function() {
    $('select#language').change(function() {
        var active = $(this).val();
        $('dt[id^="sections_"],dd[id^="sections_"]').hide();
        $('dt[id^="sections_'+active+'"],dd[id^="sections_'+active+'"]').show();
    }).change();
});
</script>
