<?php $this->placeholder('title')->set(getGS('Add new subscription section')); ?>

<?php echo $this->form; ?>

<script type="text/javascript">
$(function() {
    $('select#language').change(function() {
        var active = $(this).val();
        $('dt[id^="sections_"],dd[id^="sections_"]').hide();
        $('dt[id^="sections_'+active+'"],dd[id^="sections_'+active+'"]').show();
    }).change();
});
</script>
