<?php 
$translator = \Zend_Registry::get('container')->getService('translator');
$this->placeholder('title')->set($translator->trans('Subscribed sections: $1', array('$1' => $this->subscription->getPublicationName()), 'user_subscription_sections')); 
?>

<?php $this->renderActions(); ?>

<table>
<tr>
    <th><?php echo $translator->trans('Section'); ?></th>
    <th><?php echo $translator->trans('Language'); ?></th>
    <th><?php echo $translator->trans('Start Date', array(), 'user_subscriptions'); ?></th>
    <th><?php echo $translator->trans('Days', array(), 'user_subscriptions'); ?></th>
    <th><?php echo $translator->trans('Paid Days', array(), 'user_subscriptions'); ?></th>
    <th><?php echo $translator->trans('Delete'); ?></th>
</tr>
<?php foreach ($this->subscription->getSections() as $section) { ?>
<tr>
    <td><a href="<?php echo $this->url(array(
        'action' => 'edit',
        'section' => $section->getId(),
    )); ?>"><?php echo $this->sections[$section->getSectionNumber()]; ?></a></td>
    <td><?php echo $section->getLanguageName() ?: $translator->trans('All languages', array(), 'user_subscription_sections'); ?></td>
    <td><?php echo $section->getStartDate()->format('Y-m-d'); ?></td>
    <td><?php echo $section->getDays(); ?></td>
    <td><?php echo $section->getPaidDays(); ?></td>
    <td><a href="<?php echo $this->url(array(
        'action' => 'delete',
        'section' => $section->getId(),
    )); ?>"><?php echo $translator->trans('Delete'); ?></a></td>
</tr>
<?php } ?>
</table>
