<?php
regGS("CAMPSITE", "KEMPSAJT");
regGS("Home", "Početak");
regGS("Logout", "Odjava");
regGS("You are logged in as $1", "Ulogovani ste kao $1");
regGS("More...", "Dalje...");
regGS("Content", "Sadržaji");
regGS("Obsolete", "Staro gvožđe");
regGS("Publishing environment", "Izdavačko okruženje");
regGS("Infotypes", "Infotipi");
regGS("Languages", "Jezici");
regGS("Countries", "Države");
regGS("Templates", "Šabloni");
regGS("Topics", "Teme");
regGS("Configure", "Podešavanja");
regGS("Image Archive", "Foto arhiva");
regGS("Add Article", "Dodaj članak");
regGS("Fields", "Polja");
regGS("Delete", "Obriši");
regGS("Type", "Tip");
regGS("Name", "Ime");
regGS("Keyword", "Ključna reč");
regGS("Native name", "Izvorno ime");
regGS("Code", "Kod");
regGS("Code page", "Kodna strana");
regGS("Edit", "Uredi");
regGS("Reader", "Čitalac");
regGS("Access", "Pristup");
regGS("Login", "Prijava");
regGS("Password", "Lozinka");
regGS("Site", "Sajt");
regGS("Currency", "Valuta");
regGS("Path", "Putanja");
regGS("Go up", "Nivo iznad");
regGS("URL", "URL");
regGS("Order", "Poredak");
regGS("Hide", "Sakrij");
regGS("Duplicate", "Dupliraj");
regGS("Select destination", "Izaberi destinaciju");
regGS("No languages", "Nema jezika");
regGS("---Select language---", "--- Izaberi jezik ---");
regGS("No publications", "Nema publikacija");
regGS("---Select publication---", "--- Izaberi publikaciju ---");
regGS("No issues", "Nema izdanja");
regGS("---Select issue---", "--- Izaberi izdanje ---");
regGS("No sections", "Nema rubrika");
regGS("---Select section---", "--- Izaberi rubriku ---");
regGS("No articles", "Nema članaka");
regGS("---Select article---", "--- Izaberi članak ---");
regGS("Language", "Jezik");
regGS("Keyword infotype", "Infotip za ključnu reč");
regGS("Translation", "Prevod");
regGS("Infotype", "Infotip");
regGS("Country", "Država");
regGS("User name", "Korisničko ime");
regGS("Definition", "Definicija");
regGS("Publication", "Publikacija");
regGS("Default language", "Osnovni jezik");
regGS("Time Unit", "Vremenska jedinica");
regGS("Unit Cost", "Cena jedinice");
regGS("Subscriptions", "Pretplate");
regGS("Issue", "Izdanje");
regGS("Number", "Broj");
regGS("Section", "Rubrika");
regGS("Keywords", "Ključne reči");
regGS("Topic", "Tema");
regGS("URL Name", "Skrađeni naziv");
regGS("Next", "Sledeći");
regGS("Previous", "Prethodni");
regGS("Translate", "Prevedi");
regGS("Details", "Detalji");
regGS("View", "Prikaz");
regGS("Scheduled Publishing", "Automatsko objavljivanje");
regGS("Time", "Vreme");
regGS("Action", "Akcija");
regGS("Schedule a new publish action", "Zakaži novu akciju objavljivanja");
regGS("No entries.", "Nema unosa");
regGS("Scheduling a new publish action", "Zakazivanje nove akcije objavljivanja");
regGS("Delete scheduled publish action", "Obriši zakazanu akciju objavljivanja");
regGS("The action scheduled on $1 has been deleted.", "Akcija predviđena za $1 je obrisana");
regGS("The $1 action has been scheduled on $2", "Akcija $1 je zakazana za $2");
regGS("Date/Time", "Datum/vreme");
regGS("You must select an action.", "Moraš izabrati neku akciju");
regGS("There was an error scheduling the $1 action on $2", "došlo je do greške pri zakazivanju akcije $1 za $2");
regGS("You do not have the right to schedule issues or articles for automatic publishing.", "Nemate pravo zakazivanja akcija automatskog objavljivanja izdanja i članaka ");
regGS("The action scheduled on $1 could not be deleted.", "Akcija predviđena za $1 ne može biti obrisana");
regGS("Front page", "Prva strana");
regGS("Section page", "Strana rubrike");
regGS("Show on front page", "Prikaži na prvoj strani");
regGS("Remove from front page", "Povuci sa prve strane");
regGS("Show on section page", "Prikaži na strani rubrike");
regGS("Remove from section page", "Povuci sa strane rubrike");
regGS("Actions", "Akcije");
regGS("Publishing", "Objavljivanje");
regGS("Show", "Prikaži");
regGS("Remove", "Ukloni");
regGS("The $1 actions have been scheduled on $2", "$1 akcija je predviđeno za $2");
regGS("days", "dana");
regGS("Article Types", "Tipovi članaka");
regGS("User Types", "Tipovi korisnika");
regGS("Glossary", "Glosar");
regGS("Keyword infotypes", "Infotipi za ključnu reč");
regGS("Publications", "Publikacije");
regGS("Issues", "Izdanja");
regGS("Sections", "Rubrike");
regGS("Articles", "Članci");
regGS("Images", "Slike");
regGS("Nr", "br.");
regGS("Change", "Promeni");
regGS("Add new issue", "Dodaj novo izdanje");
regGS("Add new topic", "Dodaj novu temu");
regGS("Delete topic", "Obriši temu");
regGS("Edit languages", "Uredi jezike");
regGS("Section Template", "Šablon strane rurike");
regGS("Article Template", "Šablon članka");
regGS("Default Language", "Osnovni jezik");
regGS("Countries Subscription Default Time", "Dužina trajanja pretplate ");
regGS("Pay Period", "Rok plaćanja");
regGS("Info", "Info");
regGS("Trial Period", "Probni period");
regGS("Paid Period", "Plaćeni period");
regGS("Preview", "Pregled");
regGS("You must complete the $1 field.", "Morate popuniti polje $1 ");
regGS("Error", "Greška");
regGS("Invalid input: $1", "Pogrešan unos: $1");
regGS("Language does not exist.", "Nema tog jezika");
regGS("Infotype does not exist.", "Nema takvog infotipa");
regGS("Keyword does not exist.", "Nema te ključne reči");
regGS("Publication does not exist.", "Nema takve publikacije");
regGS("Country does not exist.", "Nema te države");
regGS("Issue does not exist.", "Nema tog izdanja");
regGS("Topic does not exist.", "Nema takve teme");
regGS("You must select a language.", "Moraš izabrati jezik");
regGS("Section does not exist.", "Ta rubrika ne postoji");
regGS("No articles.", "Nema članaka");
regGS("Article does not exist.", "Članak ne postoji");
regGS("Image does not exist.", "Slika ne postoji");
regGS("Access denied", "Zabranjen pristup");
regGS("There was an error reading the language parameter.", "Greška pri čitanju parametra jezika");
regGS("There was an error reading the publication parameter.", "Greška pri čitanju parametra publikacije");
regGS("There was an error reading the issue parameter.", "Greška pri čitanju parametra izdanja");
regGS("There was an error reading request parameters.", "Greška pri čitanju traženih parametara");
regGS("Invalid article identifier", "Pogrešan parametar članka");
regGS("Invalid destination section selected", "Izabrana je pogrešna krajnja rubrika");
regGS("Internal error: identifiers not initialized", "Interna greška: parametri nisu postavljeni");
regGS("Internal database error", "Greška u bazi");
regGS("Invalid parameters received", "Primljeni pogrešni parametri");
regGS("Add new article", "Dodaj novi članak");
regGS("Status", "Status");
regGS("No such article.", "Nema takvog članka");
regGS("Published", "Objavljen");
regGS("Not published", "Neobjavljen");
regGS("Submitted", "Predat");
regGS("New", "Novi");
regGS("Article", "Članak");
regGS("Publish", "Objavi");
regGS("Unpublish", "Povuci");
regGS("Unlock", "Otključaj");
regGS("Uploaded", "Aploudovan");
regGS("(yyyy-mm-dd)", "(gggg-mm-dd)");
regGS("YYYY-MM-DD", "GGGG-MM-DD");
regGS("Submit", "Pošalji");
regGS("Field", "Polje");
regGS("Edit details", "Uredi detalje");
regGS("No such image.", "Nema takve slike");
regGS("Image", "Slika");
regGS("Description", "Opis");
regGS("Photographer", "Fotograf");
regGS("Place", "Mesto");
regGS("Date", "Datum");
regGS("Thumbnail", "Mala slika");
regGS("In use", "Korišćena");
regGS("Identifier", "Identifikator");
regGS("Uploaded by", "Aploudovao");
regGS("Additional searches", "Dodatne pretrage");
regGS("Most Recently Added", "Najnovije dodate ");
regGS("Most Recently Modified", "Poslednje menjane");
regGS("$1 images found", "Pronađeno je $1 slike/a");
regGS("Reset search conditions", "Poništi uslove pretrage");
regGS("Preview issue", "Pregled izdanja");
regGS("Publ. no.", "Br. publikacije");
regGS("Issue no.", "Br. izdanja");
regGS("Section no.", "Br. rubrike");
regGS("Image number", "Broj slike");
regGS("Users", "Korisnici");
regGS("User is a reader", "Korisnik je čitalac");
regGS("User may add/change publications", "Korisnik može da dodaje/menja publikacije");
regGS("User may delete publications", "Korisnik može da briše publikacije");
regGS("User may add/change issues", "Korisnik može da dodaje/menja izdanja");
regGS("User may delete issues", "Korisnik može da briše izdanja");
regGS("User may add/change sections", "Korisnik može da dodaje/menja rubrike");
regGS("User may delete sections", "Korisnik može da briše rubrike");
regGS("User may add articles", "Korisnik može da dodaje članke");
regGS("User may change articles", "Korisnik može da menja članke");
regGS("User may delete articles", "Korisnik može da briše članke");
regGS("User may add images", "Korisnik može da dodaje slike");
regGS("User may change images", "Korisnik može da menja slike");
regGS("User may delete images", "Korisnik može da briše slike");
regGS("User may add templates", "Korisnik može da dodaje šablone");
regGS("User may delete templates", "Korisnik može da briše šablone");
regGS("User may add/change user accounts and passwords", "Korisnik može da dodaje/menja korisničke naloge i lozinke");
regGS("User may delete user accounts", "Korisnik može da briše korisničke naloge");
regGS("User may manage user subscriptions", "Korisnik može da administrira pretplate");
regGS("User may manage account types", "Korisnik može da administrira tipove naloga");
regGS("User may add/change article types", "Korisnik može da dodaje/menja tipove članaka");
regGS("User may delete article types", "Korisnik može da briše tipove članaka");
regGS("User may add languages and manage language information", "Korisnik može da dodaje jezike i upravlja informacijama o jeziku");
regGS("User may delete languages", "Korisnik može da briše jezike");
regGS("User may manage glossary infotypes", "Korisnik može da upravlja infotipima glosara");
regGS("User may add/change glossary entries", "Korisnik može da dodavaje/menja zapise u glosaru");
regGS("User may delete glossary entries", "Korisnik može da briše zapise u glosaru");
regGS("User will be notified on several events", "Korisnik će biti obavešten o određenim sistemskim aktivnostima");
regGS("User may view audit logs", "Korisnik ima pristup logovima");
regGS("User may add/change country names", "Korisnik može da dodaje/menja imena država");
regGS("User may delete country entries", "Korisnik može da briše podatke o državama");
regGS("User may manage localizer", "Korisnik ima pristup lokalizatoru");
regGS("User may manage indexer", "Korisnik ima pristup indekseru");
regGS("User may publish articles", "Korisnik može da objavljuje članke");
regGS("User may manage topics", "Korisnik može da upravlja temama");
regGS("User may use bold", "Korisnik može da koristi masna slova (bold)");
regGS("User may use italic", "Korisnik može da koristi kurziv (italic)");
regGS("User may use underline", "Korisnik može da koristi podvučena slova (underline)");
regGS("User may use strikethrough", "Korisnik može da koristi precrtana slova (strikethrough)");
regGS("User may change text alignment", "Korisnik može da koristi poravnavanje teksta");
regGS("User may copy, cut, and paste", "Korisnik može da koristi kopiraj/zalepi/iseci (copy/paste/cut)");
regGS("User may undo/redo", "Korisnik može da koristi  undo/redo");
regGS("User may change text direction", "Korisnik može da koristi pravac teksta");
regGS("User may set indents", "Korisnik može da podešava uvlačenje");
regGS("User may add links", "Korisnik može da dodaje linkove");
regGS("User may add subheads", "Korisnik može da pravi međunaslove");
regGS("User may insert images", "Korisnik može da ubacuje slike");
regGS("User may view the HTML source", "Korisnik ima pristup HTML kodu");
regGS("User may enlarge the editor", "Korisnik može da uvećava editor");
regGS("User may change the font face", "Korisnik može da menja fontove");
regGS("User may change the font size", "Korisnik može da menja veličinu slova");
regGS("User may create bulleted lists", "Korisnik može da pravi liste bez rednih brojeva");
regGS("User may create numbered lists", "Korisnik može da pravi liste sa rednim brojevima");
regGS("User may insert tables", "Korisnik može da dodaje tabele");
regGS("User may insert horizontal rules", "Korisnik može da ubacuje horizontalne linije");
regGS("User may change the font color", "Korisnik može da menja boju slova");
regGS("User may use superscripts", "Korisink može da koristi superskript");
regGS("User may use subscripts", "Korisink može da koristi sabskript");
regGS("Updating user types permissions", "Menjanje odobrenja za tipove korisnika");
regGS("Adding new translation", "Dodavanje novog prevoda");
regGS("Translate keyword", "Prevedi ključnu reč");
regGS("No more languages.", "Nema više jezika");
regGS("No such keyword infotype.", "Nema tog infotipa za ključnu reč");
regGS("Adding new keyword infotype", "Dodavanje novog infotipa za ključne reči");
regGS("The infotype has been deleted.", "Infotip je izbrisan");
regGS("The infotype could not be deleted.", "Infotip ne može biti izbrisan");
regGS("The $1 field may only contain letters, digits and underscore (_) character.", "Ime polja $1 može sadržati isključivo slova, brojke i donju crtu (_)");
regGS("Add new publication", "Dodaj novu publikaciju");
regGS("Upload new template", "Aplouduj novi šablon");
regGS("Add new user account", "Dodaj novog korisnika");
regGS("Add new user type", "Dodaj novi tip korisnika");
regGS("Add new article type", "Dodaj novi tip članka");
regGS("Add new country", "Dodaj državu");
regGS("Add new language", "Dodaj jezik");
regGS("Add new section", "Dodaj novu rubriku");
regGS("View logs", "Prikaži logove");
regGS("Change your password", "Promeni lozinku");
regGS("Your articles", "Tvoji članci");
regGS("Submitted articles", "Predati članci");
regGS("Quick Menu", "Prečice");
regGS("Logs", "Logovi");
regGS("There are $1 article(s) left.", "Preosta(l)o je $1 članak(a)");
regGS("There are $1 issues(s) left.", "Preostalo je $1 izdanja");
regGS("There are $1 section(s) left.", "Preosta(l)o je $1 rubrika");
regGS("There are $1 publication(s) left.", "Preostalo(a) je $1 publikacija");
regGS("There are $1 keywords(s) left.", "Preostalo je $1 ključnih reči");
regGS("There are $1 countries left.", "Preostalo je $1 država");
regGS("Name <SMALL>(click to edit)</SMALL>", "Ime<br><small>(kliknite za uređivanje)</small>");
regGS("User account", "Korisnički nalog");
regGS("No such user account.", "Nema takvog korisničkog naloga");
regGS("Add new subscription", "Dodaj novu pretplatu");
regGS("You do not have the right to add subscriptions.", "Nemate pravo da dodajete pretplate");
regGS("Adding subscription", "Dodavanje pretplate");
regGS("The section could not be added.", "Rubrika ne može biti dodata");
regGS("Delete subscription", "Obriši pretplatu");
regGS("You do not have the right to delete subscriptions.", "Nemate pravo da brišete pretplate");
regGS("Deleting subscription", "Brisanje pretplate");
regGS("No such subscription.", "Nema takve pretplate");
regGS("The section $1 could not be deleted.", "Rubrika $1 ne može biti obrisana");
regGS("The topic $1 could not be deleted.", "Tema $1 ne može biti obrisana");
regGS("Yes", "Da");
regGS("No", "Ne");
regGS("Close", "Zatvori");
regGS("No issues.", "Nema izdanja");
regGS("Back to Edit Article", "Nazad na detalje članka");
regGS("Adding new topic", "Dodavanje nove teme");
regGS("Topic $1 added", "Tema $1 je dodata");
regGS("The topic could not be added.", "Tema ne može biti dodata");
regGS("Do you want to delete the topic $1?", "Želite li da obrišete temu $1?");
regGS("Add another topic", "Dodaj novu temu");
regGS("Deleting topic", "Brisanje teme");
regGS("There are $1 subtopics left.", "Preostalo je $1 podtema");
regGS("Topic $1 deleted", "Tema $1 je obrisana");
regGS("Changing topic name", "Promena imena teme");
regGS("You do not have the right to change topic name.", "Nemate pravo da menjate ime teme");
regGS("Topic $1 updated", "Tema $1 je izmenjena");
regGS("The topic name could not be updated.", "Naziv teme ne može biti izmenjen");
regGS("Change topic name", "Promeni naziv teme");
regGS("Delete topic $1", "Obriši temu $1");
regGS("No topics", "Nema tema");
regGS("The topic $1 has been successfuly added.", "Tema $1 je uspešno dodata");
regGS("The topic $1 has been successfuly updated.", "Tema $1 je uspešno izmenjena");
regGS("The topic $1 has been deleted.", "Tema $1je uspešno obrisana");
regGS("There are $1 articles using the topic.", "Preostalo je $1 tekstova koji koriste ovu temu");
regGS("You must fill in the $1 field.", "Morate popuniti polje $1");
regGS("You do not have the right to add articles.", "Nemate pravo da dodajete članke");
regGS("Start", "Početak");
regGS("Days", "Dana");
regGS("(YYYY-MM-DD)", "(GGGG-MM-DD)");
regGS("The sections were added successfully.", "Rubrike su uspešno dodate");
regGS("The sections could not be added successfully. Some of them were already added !", "Rubrike ne mogu biti dodate. Neke od njih već postoje!");
regGS("This article cannot be previewed. Please make sure it has the article template selected.", "Članak ne može biti pregledan. Proverite da li je odabran šablon za članak.");
regGS("This article cannot be previewed. Please make sure it has the front page template selected.", "Članak ne može biti pregledan. Proverite da li je odabran šablon za prvu stranu.");
regGS("Add another", "Nastavi sa dodavanjem");
regGS("Cancel", "Poništi");
regGS("Done", "Gotovo");
regGS("New Field", "Novo polje");
regGS("OK", "OK");
regGS("Save", "Snimi izmene");
regGS("Search", "Traži");
regGS("Add New Field", "Dodaj novo polje");
?>