<?
regGS("CAMPSITE","CAMPSITE:ru");
regGS("Home","Начало:ru");
regGS("Logout","Выход:ru");
regGS("Fields","Поля:ru");
regGS("Delete","Удалить:ru");
regGS("Type","Тип:ru");
regGS("Name","Имя:ru");
regGS("Keyword","Ключевое слово:ru");
regGS("Infotypes","Классы:ru");
regGS("Languages","Язык:ru");
regGS("Native name","Исходное имя:ru");
regGS("Code","Код:ru");
regGS("Code page","Кодовая страница:ru");
regGS("Edit","Правка:ru");
regGS("Countries","Страны:ru");
regGS("Reader","Читатель:ru");
regGS("Access","Доступ:ru");
regGS("Login","Логин:ru");
regGS("Password","Пароль:ru");
regGS("Site","Сайт:ru");
regGS("Currency","Валюта:ru");
regGS("Templates","Шаблоны:ru");
regGS("Topics","Темы:ru");
regGS("Path","Путь:ru");
regGS("Go up","Наверх:ru");
regGS("Language","Язык:ru");
regGS("Keyword infotype","Класс ключевых слов:ru");
regGS("Translation","Перевод:ru");
regGS("Infotype","Класс:ru");
regGS("Country","Страна:ru");
regGS("User name","Пользователь:ru");
regGS("Definition","Описание:ru");
regGS("Publication","Публикация:ru");
regGS("Default language","Язык по умолчанию");
regGS("Time Unit","Единица времени:ru");
regGS("Unit Cost","Стоимость единицы:ru");
regGS("Subscriptions","Подписка:ru");
regGS("Issue","Выпуск:ru");
regGS("Number","Номер:ru");
regGS("Section","Секция:ru");
regGS("Keywords","Ключевое слово:ru");
regGS("Topic","Тема");
regGS("Next","Следующ.:ru");
regGS("Previous","Предыдущ.:ru");
regGS("Translate","Перевести:ru");
regGS("Details","Подробности:ru");
regGS("View","Вид:ru");
regGS("days","дней:ru");
regGS("Article Types","Тип статьи:ru");
regGS("User Types","Типы пользователей:ru");
regGS("Glossary","Глоссарий:ru");
regGS("Keyword infotypes","Класс ключевого слова:ru");
regGS("Publications","Публикации:ru");
regGS("Issues","Выпуски:ru");
regGS("Sections","Секции:ru");
regGS("Articles","Статьи:ru");
regGS("Images","Картинки:ru");
regGS("Nr","№:ru");
regGS("Change","Изменить:ru");
regGS("Add new issue","Добавить новый выпуск:ru");
regGS("Add new topic","Добавить новую тему:ru");
regGS("Delete topic","Удалить тему:ru");
regGS("Default Language","Язык по умолчанию:ru");
regGS("Subscription Default Time","Время подписки по умолчанию:ru");
regGS("Pay Period","Период оплаты:ru");
regGS("Info","Информация:ru");
regGS("Trial Period","Пробный период:ru");
regGS("Paid Period","Оплаченный период:ru");
regGS("Preview","Предварительный просмотр:ru");
regGS("You must complete the $1 field.","Вы должны заполнить $1 поле.:ru");
regGS("No such language.","Нет такого языка.:ru");
regGS("No such infotype.","Нет такого класса:ru");
regGS("No such keyword.","Нет такого ключевого слова.:ru");
regGS("No such publication.","Нет такой публикации.:ru");
regGS("No such country.","Нет такой страны.:ru");
regGS("No such issue.","Нет такого выпуска.:ru");
regGS("No such topic.","Нет такой темы.");
regGS("You must select a language.","Вы должны выбрать язык.:ru");
regGS("No such section.","Нет такой секции:ru");
regGS("No articles.","Статьи отсутствуют:ru");
regGS("Add new article","Добавить новую статью:ru");
regGS("Status","Статус:ru");
regGS("No such article.","Нет такой статьи:ru");
regGS("Published","Опубликовано:ru");
regGS("Submitted","Отправлено:ru");
regGS("New","Новая:ru");
regGS("Article","Статья:ru");
regGS("Publish","Опубликовать:ru");
regGS("Unpublish","Убрать:ru");
regGS("Unlock","Разблокировать:ru");
regGS("Uploaded","Загружена:ru");
regGS("(yyyy-mm-dd)","(гггг-мм-дд):ru");
regGS("YYYY-MM-DD","ГГГГ-ММ-ДД:ru");
regGS("Submit","Отправить:ru");
regGS("Field","Поле:ru");
regGS("Edit details","Правка параметров:ru");
regGS("No such image.","Нет такой картинки:ru");
regGS("Image","Картинка:ru");
regGS("Description","Описание:ru");
regGS("Photographer","Фотограф:ru");
regGS("Place","Место:ru");
regGS("Date","Дата:ru");
regGS("Publ. no.","Публ. №:ru");
regGS("Issue no.","Выпуск №:ru");
regGS("Section no.","Секция №:ru");
regGS("Image number","Номер картинки:ru");
regGS("Users","Пользователи:ru");
regGS("User is a reader","Пользователь - это читатель:ru");
regGS("User may add/change publications","Пользователь может добавлять/изменять публикации:ru");
regGS("User may delete publications","Пользователь может удалять публикации:ru");
regGS("User may add/change issues","Пользователь может добавлять/изменять выпуски:ru");
regGS("User may delete issues","Пользователь может удалять выпуски:ru");
regGS("User may add/change sections","Пользователь может добавлять/изменять секции:ru");
regGS("User may delete sections","Пользователь может удалять секции:ru");
regGS("User may add articles","Пользователь может добавлять статьи:ru");
regGS("User may change articles","Пользователь может изменять статьи:ru");
regGS("User may delete articles","Пользователь может удалять статьи:ru");
regGS("User may add images","Пользователь может добавлять картинки:ru");
regGS("User may change images","Пользователь может изменять картинки:ru");
regGS("User may delete images","Пользователь может удалять картинки:ru");
regGS("User may add templates","Пользователь может добавлять шаблоны:ru");
regGS("User may delete templates","Пользователь может удалять шаблоны:ru");
regGS("User may add/change user accounts and passwords","Пользователь может добавлять/изменять учетные записи и пароли:ru");
regGS("User may delete user accounts","Пользователь может удалять учетные записи:ru");
regGS("User may manage user subscriptions","Пользователь может управлять пользовательскими подписками:ru");
regGS("User may manage account types","Пользователь может управлять типами учетных записей:ru");
regGS("User may add/change article types","Пользователь может добавлять/изменять типы статей:ru");
regGS("User may delete article types","Пользователь может удалять типы статей:ru");
regGS("User may add languages and manage language information","Пользователь может добавлять языки и управлять информаций о языках:ru");
regGS("User may delete languages","Пользователь может удалять языки:ru");
regGS("User may manage glossary infotypes","Пользователь может управлять классами глоссария:ru");
regGS("User may add/change glossary entries","Пользователь может добавлять/изменять записи словаря:ru");
regGS("User may delete glossary entries","Пользователь может удалять записи словаря:ru");
regGS("User will be notified on several events","Пользователь будет уведомляться о некоторых событиях:ru");
regGS("User may view audit logs","Пользователь может просматривать журнал отчетности:ru");
regGS("User may add/change country names","Пользователь может добавлять/удалять названия стран:ru");
regGS("User may delete country entries","Пользователь может удалять записи о странах:ru");
regGS("User may manage localizer","Пользователь может управлять локализатором:ru");
regGS("User may manage indexer","Пользователь может управлять индексатором:ru");
regGS("User may publish articles","Пользователь может публиковать статьи:ru");
regGS("User may manage topics","Пользователь может управлять темами:ru");
regGS("Adding new translation","Добавление нового перевода:ru");
regGS("Translate keyword","Перевести ключевое слово:ru");
regGS("No more languages.","Больше нет языков:ru");
regGS("No such keyword infotype.","Нет такого класса ключевых слов:ru");
regGS("Adding new keyword infotype","Добавление нового класса ключевых слов:ru");
regGS("The infotype has been deleted.","Класс был удален:ru");
regGS("The infotype could not be deleted.","Класс не может быть удален:ru");
regGS("Add new publication","Добавить новую публикацию:ru");
regGS("Upload new template","Загрузить новый шаблон:ru");
regGS("Add new user account","Добавить новую учетную запись пользователя:ru");
regGS("Add new user type","Добавить новый тип пользователей:ru");
regGS("Add new article type","Добавитьновый тип статей:ru");
regGS("Add new country","Добавить новую страну:ru");
regGS("Add new language","Добавить новый язык:ru");
regGS("Add new section","Добавить новую секцию:ru");
regGS("View logs","Просмотреть журнал:ru");
regGS("Change your password","Изменить ваш пароль:ru");
regGS("Your articles","Ваши статьи:ru");
regGS("Submitted articles","Отправленные статьи:ru");
regGS("Quick Menu","Меню:ru");
regGS("Logs","Журнал:ru");
regGS("There are $1 article(s) left.","Осталось $1 статья(-ей):ru");
regGS("There are $1 issue(s) left.","Осталось $1 выпуск(ов):ru");
regGS("There are $1 section(s) left.","Осталось $1 секция(-ий):ru");
regGS("There are $1 publication(s) left.","Осталось $1 пуликация(-ий):ru");
regGS("There are $1 keyword(s) left.","Осталось $1 ключевое(-ых) слов(о):ru");
regGS("There are $1 countries left.","Осталось $1 стран(а):ru");
regGS("Name<BR><SMALL>(click to edit)</SMALL>","Название<BR><SMALL>(Щелкнуть для правки)</SMALL>:ru");
regGS("User account","Учетная запись пользователя:ru");
regGS("No such user account.","Нет такой учетной записи пользлователя:ru");
regGS("Add new subscription","Добавить новую подписку:ru");
regGS("You do not have the right to add subscriptions.","Вы не имеете прав добавления подписок:ru");
regGS("Adding subscription","Добавление подписки:ru");
regGS("The section could not be added.","Невозможно добавить секцию:ru");
regGS("Delete subscription","Удалить подписку:ru");
regGS("You do not have the right to delete subscriptions.","Вы не имеете прав удаления подписок:ru");
regGS("Deleting subscription","Удаление подписки:ru");
regGS("No such subscription.","Нет такой подписки:ru");
regGS("The section $1 could not be deleted.","Невозможно удлить секцию $1:ru");
regGS("The topic $1 could not be deleted.","Невозможно удалить тему $1.");
regGS("Yes","Да:ru");
regGS("No","Нет:ru");
regGS("No issues.","Нет выпусков:ru");
regGS("Adding new topic","Добавление новой темы:ru");
regGS("Topic $1 added","Добавлена тема $1:ru");
regGS("The topic could not be added.","Невозможно добавить тему.:ru");
regGS("Do you want to delete the topic $1?","Вы уверены, что хотите удалить тему $1?");
regGS("Add another topic","Добавить другую тему:ru");
regGS("Deleting topic","Удаление темы:ru");
regGS("There are $1 subtopics left.","Осталось $1 подтем(ы):ru");
regGS("Topic $1 deleted","Удалена тема $1:ru");
regGS("Changing topic name","Переименование темы:ru");
regGS("You do not have the right to change topic name.","Вы не имеете права переименования тем.:ru");
regGS("Topic $1 updated","Тема $1 обновлена:ru");
regGS("The topic name could not be updated.","Невозможно обновить тему $1:ru");
regGS("Change topic name","Переименовать тему:ru");
regGS("Delete topic $1","Удалить тему $1:ru");
regGS("No topics","Нет тем:ru");
regGS("The topic $1 has been successfuly added.","Тема $1 была успешно добавлена:ru");
regGS("The topic $1 has been successfuly updated.","Тема $1 была успешно обновлена:ru");
regGS("The topic $1 has been deleted.","Тема $1 была удалена:ru");
regGS("There are $1 articles using the topic.","Тема используется в $1 статье(-ях).:ru");
regGS("You must fill in the $1 field.","Вы должны заполнить поле $1.:ru");
regGS("Start","Начало:ru");
regGS("Days","Дней:ru");
regGS("(YYYY-MM-DD)","(ГГГГ-ММ-ДД):ru");
regGS("The sections were added successfully.","Секции были успешно добавлены.:ru");
regGS("The sections could not be added successfully. Some of them were already added !","Секции не могут быть добавлены. Некоторые из них уже были добавлены !:ru");
regGS("Back to article details","Назад к параметрам статьи:ru");

?>
