<div class="controls">
    <?php echo $this->paginator; ?>
</div>

<ul class="users">
    <?php foreach ($this->users as $user) { ?>
    <li>
        <div class="inline-actions">
            <a href="<?php echo $this->url(array(
                'action' => 'delete',
                'user' => $user->getId(),
            )); ?>" class="delete"><?php putGS('Delete'); ?></a>
        </div>
        <a href="<?php echo $this->url(array(
            'action' => 'edit',
            'user' => $user->getId(),
        )); ?>" class="edit"><?php echo $user->getUsername(); ?></a>
        <a href="mailto:<?php echo $user->getEmail(); ?>" class="mailto"><?php echo $user->getEmail(); ?></a>
        <span class="created"><?php echo $user->getCreated()->format('d.m.Y H:i'); ?></span>
    </li>
    <?php } ?>
</ul>
