<div class="controls">
    <?php echo $this->paginator; ?>
</div>

<ul class="users">
    <?php foreach ($this->users as $user) { ?>
    <li>
        <div class="inline-actions">
            <?php if ($user->isPending()) { ?>
            <a href="<?php echo $this->url(array(
                'action' => 'send-confirm-email',
                'user' => $user->getId(),
            )); ?>" class="send-confirm-email"><?php putGS('Send confirm email'); ?></a> |
            <?php } ?>
            <?php if ($user->isActive() || $user->isPending()) { ?>
            <a href="<?php echo $this->url(array(
                'action' => 'delete',
                'user' => $user->getId(),
            )); ?>" class="delete"><?php putGS('Delete'); ?></a>
            <?php } ?>
        </div>
        <?php if ($user->isActive()) { ?>
        <a href="<?php echo $this->url(array(
            'action' => 'edit',
            'user' => $user->getId(),
        )); ?>" class="edit"><?php echo $user->getUsername(); ?></a>
        <?php } else { ?>
        <a class="edit"><?php echo $user->getUsername(); ?></a>
        <?php } ?>
        <a href="mailto:<?php echo $user->getEmail(); ?>" class="mailto"><?php echo $user->getEmail(); ?></a>
        <span class="status s-<?php echo $user->getStatus(); ?>"><?php
            if ($user->isActive()) {
                putGS('Active');
            } else if ($user->isPending()) {
                putGS('Pending');
            } else {
                putGS('Inactive');
            }
        ?></span>
        <span class="created"><?php echo $user->getCreated()->format('d.m.Y'); ?></span>
    </li>
    <?php } ?>
</ul>
