#!/bin/bash

bin_path=`dirname $0`
if [ "$bin_path" = "." ]; then
        script_call="./restore_instance.php"
        ETC_DIR=`./campsite_config --etc_dir`
        PHP=`./campsite_config --php_cli`
elif [ "$bin_path" = "" ]; then
        BIN_DIR=`campsite_config --bin_dir`
        script_call="$BIN_DIR/restore_instance.php"
        ETC_DIR=`campsite_config --etc_dir`
        PHP=`campsite_config --php_cli`
else
        script_call="$bin_path/restore_instance.php"
        ETC_DIR=`$bin_path/campsite_config --etc_dir`
        PHP=`$bin_path/campsite_config --php_cli`
fi

CMD="$PHP -q $script_call $ETC_DIR $*"
$CMD
