#!/bin/bash

bin_path=`dirname $0`
if [ "$bin_path" = "." ] || [ "$bin_path" = "" ]; then
	script_call=./create_instance
	ETC_DIR=`./campsite_config --etc_dir`
else
	script_call=$bin_path/create_instance
	ETC_DIR=`$bin_path/campsite_config --etc_dir`
fi

pushd $ETC_DIR > /dev/null
for i in *; do
        if [ -d $i ]; then
		$script_call --db_name $i
	fi
done
popd > /dev/null
