<?php
regGS("Add section to all subscriptions.", "Добавить секцию ко всем подпискам");
regGS("Delete section from all subscriptions.", "Удалить секцию из вссех подписок");
regGS("A total of $1 subscriptions were updated.", "Было обновлено подписок:");
regGS("Name<BR><SMALL>(click to see articles)</SMALL>", "Название<BR><SMALL>(щелкните для просмотра статей)</SMALL>");
regGS("Delete section $1", "Удалиь секцию $1");
regGS("Adding new section", "Добавление новой секции");
regGS("You do not have the right to add sections.", "Вы не имеете права добавления секций.");
regGS("The section $1 has been successfuly added.", "Секция $1 была успешно добавлена.");
regGS("Please check if another section with the same number does not already exist.", "Пожалуйста проверьте, что еще нет другой секции с таким же номером.");
regGS("Select the section", "Выберите секцию");
regGS("Section $1 added to issue $2. $3 ($4) of $5", "Секция $1 добавлена в выпуск $2. $3 ($4) из $5");
regGS("Delete section", "Удалить секцию");
regGS("You do not have the right to delete sections.", "Вы не имеете права удаления секций");
regGS("Are you sure you want to delete the section $1?", "Вы уверены, что хотите удалить секцию $1?");
regGS("Deleting section", "Удаление секции");
regGS("The section $1 has been deleted.", "Секция $1 была удалена");
regGS("Section $1 deleted from issue $2. $3 $4 of $5", "Секция $1 удалена из выпусков $2 $3 $4 из $5");
regGS("Configure section", "Настроить секцию");
regGS("You do not have the right to change section details", "Вы не имеете права изменения параметров секции");
regGS("Updating section name", "Обновление название секции");
regGS("The section $1 has been successfuly modified.", "Секция $1 была успешно модифицирована.");
regGS("The section could not be changed.", "Невозможно изменить секцию.");
regGS("Section $1 updated to issue $2. $3 ($4) of $5", "Секция $1 обновлена для выпуска $2. $3 ($4) из $5");
regGS("Name<BR><SMALL>(click to add article)</SMALL>", "Название<BR><SMALL>(щелкните для добавления статьи)</SMALL>");
regGS("Duplicate section", "Дублировать секцию");
regGS("The destination issue is the same as the source issue.", "Выпуск источника тот же, что и  получтеля");
regGS("Error updating subscriptions.", "Ошибка обновления подписок");
regGS("Duplicating section", "Дублирование секций");
regGS("The section $1 could not be duplicated", "Секция $1 не может быть продублирована");
regGS("Section $1 has been duplicated to $2. $3 of $4", "Секция $1 была продублирована в $2. $3 из $4");
regGS("You do not have the right to modify sections.", "Вы не имеете права модифицировать секций.");
regGS("Delete all articles from the section.", "Удалить все статьи из секции.");
regGS("A total of $1 articles were deleted.", "Всего удалено статей: $1");
regGS("Duplicate Section:", "Дублировать секцию:");
regGS("Existing Section", "Существующая секция");
regGS("Go to new section", "Перейти к новой секции");
regGS("Go to source section", "Перейти к исходной секции");
regGS("New Section", "Новая секция");
regGS("Please select either '$1' or '$2'.", "Пожалуйста выберите или '$1' или '$2'.");
regGS("Select destination section:", "Выберете секцию назначения:");
regGS("OR", "или");
regGS("Short Name", "Короткое название");
regGS("The section number specified already exists, please specify a different value or use the dropdown to find an existing section.", "Указанный номер секции уже существует, пожалуйста укажите другое значение или используйте выпадающий список для поиска существующей секции.");
regGS("Warning", "Предупреждение");
regGS("You must select a section.", "Вы должны выбрать секцию");
regGS("You must specify a name for the section.", "Вы должны определить название секции");
regGS("No such issue.", "Нет такого выпуска");
regGS("No sections.", "Нет секций.:ru");
regGS("Change section name", "Изменить название секции:ru");
?>