<?php
regGS("Add section to all subscriptions.", "Adicionar Secção a todas as Assinaturas");
regGS("Delete section from all subscriptions.", "Eliminar Secção de todas as Assinaturas");
regGS("A total of $1 subscriptions were updated.", "Um total de $1 Assinaturas foram actualizadas");
regGS("Name<BR><SMALL>(click to see articles)</SMALL>", "Nome<br>(Carregue para ver artigos)");
regGS("Delete section $1", "Eliminar Secção $1");
regGS("Adding new section", "Adicionando Secção");
regGS("You do not have the right to add sections.", "Não tem permissões para adicionar Secções.");
regGS("The section $1 has been successfuly added.", "A Secção $1 foi adicionada com sucesso.");
regGS("Please check if another section with the same number does not already exist.", "Verifique se já não existe uma secção com o mesmo numero.");
regGS("Select the section", "Escolha a Secção");
regGS("Section $1 added to issue $2. $3 ($4) of $5", "Secção $1 adicionada à Edição $2. $3 ($4) de $5.");
regGS("Delete section", "Eliminar Secção");
regGS("You do not have the right to delete sections.", "Não tem permissões para eliminar Secções.");
regGS("Are you sure you want to delete the section $1?", "Confirma o Apagamento da Secção $1?");
regGS("Deleting section", "Eliminando Secção");
regGS("The section $1 has been deleted.", "A Secção $1 foi Eliminada");
regGS("Section $1 deleted from issue $2. $3 $4 of $5", "Secção $1 eliminada da Edição $2. $3 $4 de $5");
regGS("Change section name", "Alterar nome da Secção");
regGS("You do not have the right to change section details", "Não tem permissões para alterar Secções.");
regGS("Updating section name", "Actualizando o nome da Secção");
regGS("The section $1 has been successfuly modified.", "Secção $1 foi alterada com sucesso");
regGS("The section could not be changed.", "Secção $1 não pode ser alterada.");
regGS("Section $1 updated to issue $2. $3 ($4) of $5", "Secção $1 da Edição $2 foi alterada. $3 ($4) de $5.");
regGS("Name<BR><SMALL>(click to add article)</SMALL>", "Nome<br>(Carregue para Adicionar Artigos)");
regGS("Duplicate section", "Duplicar Secção");
regGS("The destination issue is the same as the source issue.", "Destino idêntico à origem.");
regGS("Destination section number", "Numero da Secção de destino");
regGS("Error updating subscriptions.", "Erro na actualização de assinaturas");
regGS("Duplicating section", "Duplicando secção");
regGS("The section $1 could not be duplicated", "A Secção $1 não pode ser duplicada");
regGS("Section $1 has been duplicated to $2. $3 of $4", "A Secção $1 foi duplicada para $2. $3 de $4");
?>