#!/bin/bash

bin_path=`dirname $0`
if [ "$bin_path" = "." ]; then
    script_call="./campsite-backup-instance.php"
    ETC_DIR=`./campsite_config --etc_dir`
    PHP=`./campsite_config --php_cli`
	CAMPSITE_DIR=`./campsite_config --campsite_dir`
elif [ "$bin_path" = "" ]; then
    BIN_DIR=`campsite_config --bin_dir`
    script_call="$BIN_DIR/campsite-backup-instance.php"
    ETC_DIR=`campsite_config --etc_dir`
    PHP=`campsite_config --php_cli`
	CAMPSITE_DIR=`campsite_config --campsite_dir`
else
    script_call="$bin_path/campsite-backup-instance.php"
    ETC_DIR=`$bin_path/campsite_config --etc_dir`
    PHP=`$bin_path/campsite_config --php_cli`
	CAMPSITE_DIR=`$bin_path/campsite_config --campsite_dir`
fi

if [ "$1" = "" ] || [ "$1" = "--silent" ] || [ "$1" = "--default_dir" ]; then
    [ "$1" = "--silent" ] && exit 1
    echo "Usage:"
    echo "$0 <instance_name> [--silent] [--default_dir]"
    echo "    <instance_name>: the name of the instance you want to back up; this"
    echo "        parameter is mandatory"
    echo "Optional parameters:"
    echo "    --silent: don't display any message, whether successful or not"
    echo "    --default_dir: save the backup archive in the backup default directory:"
    echo "        $CAMPSITE_DIR/backup/<instance_name>"
    echo "    By default the backup archive is saved in the current directory."
    exit 1
fi

CMD="$PHP -q $script_call $ETC_DIR $*"
$CMD
exit $?
