#!/bin/sh

mkdir -p $BIN_DIR
cp -f gather $BIN_DIR
chown $ROOT_USER.$ROOT_GROUP $BIN_DIR/gather
chmod 750 $BIN_DIR/gather
[ $? -ne 0 ] && exit 1
. ${INSTALL_CONF}/cron_functions
if [ -f /etc/crontab ]; then
    uninstall_cron_task "$BIN_DIR/gather" /etc/crontab
fi
install_cron_task "0" "*/4" "*" "*" "*" "$ROOT_USER" "$BIN_DIR/gather" /etc/cron.d/${APP_NAME}_gather -c || exit 1
restart_cron || exit 1
exit 0
