<?php
regGS("Create new folder", "Napravi novu mapu");
regGS("Upload template", "Osvježi predložak");
regGS("Creating new folder", "Kreiranje nove mape");
regGS("You do not have the right to create new folders.", "Nemate pravo kreirati nove mape");
regGS("The folder $1 has been created", "Mapa $1 je kreirana");
regGS("The folder $1 could not be created", "Mapa $1 ne može biti kreirana");
regGS("A file or folder having the name $1 already exists", "");
regGS("Delete templates", "Izbriši predloške");
regGS("Delete folders", "Izbriši mape");
regGS("You do not have the right to delete templates.", "Nemate pravo brisati predloške");
regGS("Are you sure you want to delete the folder $1 from $2?", "Sigurno želite izbrisati mapu $1 iz $2?");
regGS("Are you sure you want to delete the template $1 from folder $2?", "Sigurno želite izbrisati predložak $1 iz mape $2?");
regGS("The template $1 is in use and can not be deleted.", "");
regGS("Deleting template", "Brisanje predloška");
regGS("Deleting folder", "Brisanje mape");
regGS("The folder has been deleted.", "Mapa je izbrisana");
regGS("The folder could not be deleted.", "Mapa se ne može brisati");
regGS("The template has been deleted.", "Predložak je izbrisan");
regGS("The template could not be deleted.", "Predložak ne može biti izbrisan");
regGS("Template $1 was deleted", "");
regGS("Delete folder", "Izbriši mapu");
regGS("Folders", "Mape");
regGS("No folders.", "Nema mapa");
regGS("Files", "Datoteke");
regGS("No templates.", "Nema predložaka");
regGS("Uploading template", "Osvježavanje predloška");
regGS("File", "Datoteka");
regGS("File $1 already exists.", "Datoteka $1 već postoji");
regGS("File $1 already exists. Old version deleted !", "Datoteka $1 već postoji. Izbrisana stara verzija!");
regGS("The upload of $1 was successful !", "Osvježavanje $1 uspjelo!");
regGS("Template $1 uploaded", "Predložak $1 je osvježen");
regGS("Create new template", "Napravi novi predložak");
regGS("Creating new template", "Kreiranje novog predloška");
regGS("Duplicate template", "Napravi kopiju predloška");
regGS("Edit template", "Uredi predložak");
regGS("Template", "Predložak");
regGS("Save", "Spremi");
regGS("The template could not be saved", "Predložak se ne može spremiti");
regGS("The template has been saved.", "Predložak je spremljen");
regGS("The template $1 has been created.", "Predložak $1 je napravljen");
regGS("Do you want to edit the template ?", "Želite li urediti predložak");
regGS("The template $1 could not be created.", "Predložak $1 se ne može napraviti");
regGS("Template $1 was changed", "Predložak $1 je promijenjen");
regGS("New template $1 was created", "Novi predložak $1 je napravljen");
regGS("Template $1 was duplicated into $2", "Predložak $1 je dupliciran u $2");
regGS("Error converting the template to UTF-8 charset.", "Greška kod konverzije predloška u UTF-8 kodnu stranu.");
regGS("Template charset", "Kodna strana predloška");
regGS("Select a language/character set", "Izaberi jezik/kodnu stranu");
regGS("All languages", "Svi jezici");
regGS("You do not have the right to modify templates.", "");
regGS("Invalid template file $1", "");
?>