<?
regGS("Select template","Выберите шаблон:ru");
regGS("Templates management","Управление шаблонами:ru");
regGS("You do not have the right to change default templates.","Вы не имеете права изменять шаблоны по умолчанию.:ru");
regGS("Create new folder","Создать новую папку:ru");
regGS("Upload template","Загрузить шаблон:ru");
regGS("Select the template for displaying the front page.","Выберите шаблон для отображения титульной странице.:ru");
regGS("Select the template for displaying a single article.","Выберите шаблон для отображения отдельной статьи.:ru");
regGS("Creating new folder","Создание новой папки:ru");
regGS("You do not have the right to create new folders.","Вы не имеете права создания новых папок.:ru");
regGS("The folder $1 has been created","Папка $1 была создана:ru");
regGS("The folder $1 could not be created","Невозможно создать папку $1:ru");
regGS("Delete templates","Удалить шаблоны:ru");
regGS("Delete folders","Удалить папки:ru");
regGS("You do not have the right to delete templates.","Вы не имеете права удаления шаблонов.:ru");
regGS("Are you sure you want to delete the folder $1 from $2?","Вы уверены, что хотите удалить папку $1 из $2?:ru");
regGS("Are you sure you want to delete the template $1 from folder $2?","Вы уверены, что хотите удалить шаблон $1 из папки $2?:ru");
regGS("Deleting template","Удаление шаблона:ru");
regGS("Deleting folder","Удаление папки:ru");
regGS("The folder has been deleted.","Папка была удалена.:ru");
regGS("The folder could not be deleted.","Невозможно удалить папку.:ru");
regGS("The template has been deleted.","Шаблон был удален.:ru");
regGS("The template could not be deleted.","Невозможно удалить шаблон:ru");
regGS("Templates deleted from $1","Шаблоны удалены из $1:ru");
regGS("Delete folder","Удалить папку:ru");
regGS("Folders","Папки:ru");
regGS("No folders.","Нет папок.:ru");
regGS("Files","Файлы:ru");
regGS("No templates.","Нет шаблонов:ru");
regGS("Uploading template","Загрузка шаблонов:ru");
regGS("File","Файл:ru");
regGS("Select","Выберите:ru");
regGS("Set template","Установить шаблон:ru");
regGS("File $1 already exists.","Файл $1 уже существует.:ru");
regGS("File $1 already exists. Old version deleted !","Файл $1 уже существует. Старая версия удалена !:ru");
regGS("The upload of $1 was successful !","Загрузка $1 была успешной !:ru");
regGS("Template $1 uploaded","Загружен шаблон $1:ru");
regGS("Create new template","Создать новый шаблон:ru");
regGS("Creating new template","Создание нового шаблона:ru");
regGS("Duplicate","Дублировать:ru");
regGS("Duplicate template","Дублировать шаблон:ru");
regGS("Edit template","Редактировать шаблон:ru");
regGS("Template","Шаблон:ru");
regGS("Save","Сохранить:ru");
regGS("Download","Загрузить:ru");
regGS("The template could not be saved","Невозможно сохранить шаблон:ru");
regGS("The template has been saved.","Шаблон был сохранен.:ru");
regGS("The template $1 has been created.","Шаблон $1 был создан.:ru");
regGS("Do you want to edit the template ?","Хотите ли вы редактировать шаблон ?:ru");
regGS("The template $1 could not be created.","Невозможно создать шаблон $1:ru");
regGS("Template $1 was changed","Шаблон $1 был изменен:ru");
regGS("New template $1 was created","Был создан новый шаблон $1:ru");
regGS("Template $1 was duplicated into $2","Шаблон $1 был дублирован в $2:ru");

?>
