<?

regGS("Select template","إختر نموذجا");
regGS("Templates management","إدارة النماذج");
regGS("You do not have the right to change default templates.","لا يحق لك تغيير النماذج الرئيسية");
regGS("Create new folder","إخلق ملفا جديدا");
regGS("Upload template","تحميل النموذج");
regGS("Select the template for displaying the front page.","إختر النموذج لعرض الصفحة الأولى");
regGS("Select the template for displaying a single article.","إختر النموذج لعرض مقال منفرد");
regGS("You do no have access to the $1 directory!"," يمكنك الدخول إلى الدليل $1");
regGS("Creating new folder","ضع ملف جديد");
regGS("You do not have the right to create new folders.","لا يحق لك وضع ملفات جديدة");
regGS("The folder $1 has been created","تمّ وضع الملف $1");
regGS("The folder $1 could not be created","لا يمكن وضع الملف $1");
regGS("Delete templates","إلغاء النماذج ");
regGS("Delete folders","إلغاء الملفات");
regGS("You do not have the right to delete templates.","لا يحق لك إلغاء النماذج");
regGS("Are you sure you want to delete the folder $1 from $2?","هل أنت متأكد من أنك تريد إلغاء الملف  $1 من $2؟");
regGS("Are you sure you want to delete the template $1 from folder $2?","هل أنت متأكد من أنك تريد إلغاء النموذج $1 من $2؟");
regGS("Deleting template","إلغاء النموذج");
regGS("Deleting folder","إلغاء الملف");
regGS("The folder has been deleted.","تم إلغاء الملف");
regGS("The folder could not be deleted.","لا يمكن إلغاء الملف");
regGS("The template has been deleted.","تم إلغاء النموذج");
regGS("The template could not be deleted.","لا يمكن إلغاء النموذج");
regGS("Templates deleted from $1"," إلغاء النماذج من $1");
regGS("Delete folder","إلغاء الملف");
regGS("Folders","الملفات");
regGS("No folders.","لا ملفات");
regGS("Files","ملفات");
regGS("No templates.","لا نماذج");
regGS("Uploading template","تحميل النموذج");
regGS("File","ملف");
regGS("Select","اختيار ");
regGS("Set template","وضع النموذج");
regGS("File $1 already exists.","الملف 1$ موجود");
regGS("File $1 already exists. Old version deleted !","الملف 1$ موجود. تم إلغاء النسخة القديمة");
regGS("The upload of $1 was successful !","تم التحميل 1$ ");
regGS("Template $1 uploaded","تم تحميل النموذج 1$");
regGS("Create new template","ضع نموذج جديد");
regGS("Creating new template","وضع نموذج جديد");
regGS("Duplicate","نسخة");
regGS("Duplicate template","نموذج مزدوج");
regGS("Edit template","تحرير النموذج");
regGS("Template","النموذج");
regGS("Save","حفظ");
regGS("Download","تحميل");
regGS("The template could not be saved","لا يمكن حفظ النموذج");
regGS("The template has been saved.","تم حفظ النموذج");
regGS("The template $1 has been created.","تمّ وضع النموذج 1$");
regGS("Do you want to edit the template ?"," هل تريد تحرير النموذج؟");
regGS("The template $1 could not be created.","لا يمكن وضع النموذج 1$");
regGS("Template $1 was changed","تمّ تغيير النموذج 1$");
regGS("New template $1 was created","تمّ وضع نموذج جديد 1$");
regGS("Template $1 was duplicated into $2","تمّ نسخ النموذج 1$");
regGS("Error converting the template to UTF-8 charset."," UTFخطأ في تبديل النموذج إلى 8 ");
regGS("Template charset"," نموذج");
regGS("Select a language/character set","إختر لغة أو احرف اللغة");
regGS("All languages","اللغات كلها");


?>