<?php
regGS("Create new folder", "Vytvořit novou složku");
regGS("Upload template", "Obnovit šablonu");
regGS("Creating new folder", "Vytváření nové složky");
regGS("You do not have the right to create new folders.", "Nemáte právo vytvářet nové složky");
regGS("The folder $1 has been created", "Složka $1 byla vytvořena");
regGS("The folder $1 could not be created", "Složka $1 nemohla být vytvořena");
regGS("A file or folder having the name $1 already exists", "");
regGS("Delete templates", "Smazat šablony");
regGS("Delete folders", "Smazat složky");
regGS("You do not have the right to delete templates.", "Nemáte právo mazat šablony");
regGS("Are you sure you want to delete the folder $1 from $2?", "Určitě chcete smazat složku $1 z $2?");
regGS("Are you sure you want to delete the template $1 from folder $2?", "Určitě chcete smazat šablonu $1 ze složky $2?");
regGS("The template $1 is in use and can not be deleted.", "");
regGS("Deleting template", "Mazání šablony");
regGS("Deleting folder", "Mazání složky");
regGS("The folder has been deleted.", "Složka byla smazána");
regGS("The folder could not be deleted.", "Složka nemohla být smazána");
regGS("The template has been deleted.", "Šablona byla smazána");
regGS("The template could not be deleted.", "Šablona nemohla být smazána");
regGS("Template $1 was deleted", "");
regGS("Delete folder", "Smazat složku");
regGS("Folders", "Složky");
regGS("No folders.", "Žádné složky");
regGS("Files", "Soubory");
regGS("No templates.", "Žádné šablony");
regGS("Uploading template", "Nahrát šablonu");
regGS("File", "Soubor");
regGS("File $1 already exists.", "Soubor $1 již existuje");
regGS("File $1 already exists. Old version deleted !", "Soubor $1 již existuje. Stará verze smazána!");
regGS("The upload of $1 was successful !", "Nahrání $1 proběhlo úspěšně!");
regGS("Template $1 uploaded", "Šablona $1 byla nahrána");
regGS("Create new template", "Vytvořit novou šablonu");
regGS("Creating new template", "Vytváření nové šablony");
regGS("Duplicate template", "Duplikovat šablonu");
regGS("Edit template", "Editovat šablonu");
regGS("Template", "Šablona");
regGS("Save", "Uložit");
regGS("The template could not be saved", "Šablona nemohla být uložena");
regGS("The template has been saved.", "Šablona byla uložena");
regGS("The template $1 has been created.", "Šablona $1 byla vytvořena");
regGS("Do you want to edit the template ?", "Chcete editovat šablonu?");
regGS("The template $1 could not be created.", "Šablona $1 nemohla být vytvořena");
regGS("Template $1 was changed", "Šablona $1 byla změněna");
regGS("New template $1 was created", "Byla vytvořena nová šablona $1");
regGS("Template $1 was duplicated into $2", "Šablona $1 byla duplikována do $2");
regGS("Error converting the template to UTF-8 charset.", "Chyba při změně kódování šablony na UTF-8");
regGS("Template charset", "Kódová stránka šablony");
regGS("Select a language/character set", "Vyberte jazyk/kódové stránky");
regGS("All languages", "Všechny jazyky");
regGS("You do not have the right to modify templates.", "");
regGS("Invalid template file $1", "");
?>