<?
regGS("Select template","选择模版");
regGS("Templates management","模版管理");
regGS("You do not have the right to change default templates.","您无权改变默认模版");
regGS("Create new folder","建新文件夹");
regGS("Upload template","上载模版");
regGS("Select the template for displaying the front page.","选择显示在首页的模版");
regGS("Select the template for displaying a single article.","选择显示单文章的模版");
regGS("You do no have access to the $1 directory!","您不能访问$1目录!");
regGS("Creating new folder","正在建新文件夹");
regGS("You do not have the right to create new folders.","您无权产生新文件夹");
regGS("The folder $1 has been created","已建立文件夹$1");
regGS("The folder $1 could not be created","文件夹$1不能创建");
regGS("Delete templates","删除模版");
regGS("Delete folders","删除文件夹");
regGS("You do not have the right to delete templates.","您无权删除模版");
regGS("Are you sure you want to delete the folder $1 from $2?","您确定要从$2中删除文件夹$1？");
regGS("Are you sure you want to delete the template $1 from folder $2?","您确认要从文件夹$2中删除模版$1？");
regGS("Deleting template","正在删除模版");
regGS("Deleting folder","正在删除文件夹");
regGS("The folder has been deleted.","文件夹已被删除");
regGS("The folder could not be deleted.","文件夹不能删除");
regGS("The template has been deleted.","模版已被删除");
regGS("The template could not be deleted.","模版不能删除");
regGS("Templates deleted from $1","模版从$1中删除");
regGS("Delete folder","删除文件夹");
regGS("Folders","文件夹");
regGS("No folders.","无文件夹");
regGS("Files","文件");
regGS("No templates.","无模版");
regGS("Uploading template","正在上载模版");
regGS("File","文件");
regGS("Select","选择");
regGS("Set template","设置模版");
regGS("File $1 already exists.","文件$1已经存在");
regGS("File $1 already exists. Old version deleted !","文件$1已经存在，旧版本已被删除！");
regGS("The upload of $1 was successful !","上载$1成功！");
regGS("Template $1 uploaded","模版$1已上载");
regGS("Create new template","建立新模版");
regGS("Creating new template","正在建新模版");
regGS("Duplicate template","复制模版");
regGS("Edit template","编辑模版");
regGS("Template","模版");
regGS("Save","保存");
regGS("Download","下载");
regGS("The template could not be saved","模版不能保存");
regGS("The template has been saved.","模版已保存");
regGS("The template $1 has been created.","模版$1已建立");
regGS("Do you want to edit the template ?","您要编辑模版？");
regGS("The template $1 could not be created.","模版$1不能被建立");
regGS("Template $1 was changed","模版$1被改变");
regGS("New template $1 was created","新模版$1被建立");
regGS("Template $1 was duplicated into $2","模版$1被复制到$2");
regGS("Error converting the template to UTF-8 charset.","将模版转换为UTF-8 时发生错误");
regGS("Template charset","模版字符");
regGS("Select a language/character set","选择语言/字符");
regGS("All languages","所有语言");

?>