<?php
// Call ArticleAttachmentTest::main() if this source file is executed directly.
if (!defined("PHPUnit_MAIN_METHOD")) {
    define("PHPUnit_MAIN_METHOD", "ArticleAttachmentTest::main");
}

require_once('PHPUnit/Framework/TestCase.php');
require_once('PHPUnit/Framework/TestSuite.php');

require_once('template_engine/classes/ComparisonOperation.php');
require_once('template_engine/classes/Operator.php');
require_once('classes/ArticleAttachment.php');

require_once('set_path.php');
require_once('db_connect.php');

/**
 * Test class for ArticleAttachment.
 * Generated by PHPUnit_Util_Skeleton on 2007-07-02 at 13:27:00.
 */
class ArticleAttachmentTest extends PHPUnit_Framework_TestCase
{
    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main()
    {
        require_once('PHPUnit/TextUI/TestRunner.php');

        $suite  = new PHPUnit_Framework_TestSuite('ArticleAttachmentTest');
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture, for example, open a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, close a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    public function testGetList()
    {
        global $g_ado_db;

        // builds the constraint
        $leftOperand = 'ArticleAttachments.fk_article_number';
        $rightOperand = '39';
        $operator = new Operator('is', 'sql');
        $comparisonOperationObj = new ComparisonOperation($leftOperand,
                                                          $operator,
                                                          $rightOperand);

        // sets the params for ArticleAttachment::GetList()
        $params = array($comparisonOperationObj);
        $order = array();
        $limitStart = 0;
        $limitOffset = 0;

        // gets the list of article attachments
        $attachmentsList = ArticleAttachment::GetList($params, $order, $limitStart, $limitOffset);

        $aList = array();
        $sql = "SELECT * FROM ArticleAttachments WHERE fk_article_number = 39";
        $attachments = $g_ado_db->GetAll($sql);
        foreach ($attachments as $attachment) {
            $aList[] = new ArticleAttachment($attachment['fk_article_number'],
                                             $attachment['fk_attachment_id']);
        }

        $this->assertEquals(sizeof($aList), sizeof($attachmentsList));

        $i = 0;
        foreach ($attachmentsList as $attachment) {
            $this->assertEquals($aList[$i]->getAttachmentId(), $attachment->getAttachmentId());
            $i++;
        }
    } // fn testGetList

    public function testGetListBadParameter()
    {
        global $g_ado_db;

        // builds the constraint
        $leftOperand = 'Attachment.file_name';
        $rightOperand = 'Robotic submarine reaches new depths';
        $operator = new Operator('not', 'sql');
        $comparisonOperationObj = new ComparisonOperation($leftOperand,
                                                          $operator,
                                                          $rightOperand);

        // sets the params for ArticleAttachment::GetList()
        $params = array($comparisonOperationObj);
        $order = array();
        $limitStart = 0;
        $limitOffset = 0;

        $this->assertEquals(null, ArticleAttachment::GetList($params, $order, $limitStart, $limitOffset));
    } // fn testGetListBadParameter

} // class ArticleAttachmentTest

// Call ArticleAttachmentTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == "ArticleAttachmentTest::main") {
    ArticleAttachmentTest::main();
}
?>