<?php
// Call CampDatabaseTest::main() if this source file is executed directly.
if (!defined("PHPUnit_MAIN_METHOD")) {
    define("PHPUnit_MAIN_METHOD", "CampDatabaseTest::main");
}

require_once('PHPUnit/Framework/TestCase.php');
require_once('PHPUnit/Framework/TestSuite.php');

require_once('template_engine/classes/CampDatabase.php');

require_once('set_path.php');

/**
 * Test class for CampDatabase.
 * Generated by PHPUnit_Util_Skeleton on 2007-07-20 at 11:22:00.
 */
class CampDatabaseTest extends PHPUnit_Framework_TestCase
{
    /**
	 * ADODB object
	 *
	 * @var object
	 */
	protected $m_dbObj = null;


    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main()
    {
        require_once('PHPUnit/TextUI/TestRunner.php');

        $suite  = new PHPUnit_Framework_TestSuite('CampDatabaseTest');
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture, for example, open a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
   	{
    }

    /**
     * Tears down the fixture, for example, close a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    public function testIsConnected()
    {
    	global $g_ado_db;

        $this->m_dbObj = CampDatabase::singleton();
    	$this->assertEquals(true, $this->m_dbObj->m_db->IsConnected());
    	$g_ado_db = $this->m_dbObj->m_db;
    	$this->assertEquals(true, $g_ado_db->IsConnected());
    }
}

// Call CampDatabaseTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == "CampDatabaseTest::main") {
    CampDatabaseTest::main();
}
?>
