#!/bin/bash

# remove the utility from the older versions
rm -f "$BIN_DIR/gather"

# install our binary
mkdir -p $SBIN_DIR
install -o $ROOT_USER -g $APACHE_GROUP -m 750 campsite_indexer "$SBIN_DIR"
[ $? -ne 0 ] && exit 1

if $USER_INSTALL; then exit 0; fi

. ${INSTALL_CONF}/cron_functions

# remove cron tasks from older versions
uninstall_cron_task "$BIN_DIR/gather" /etc/cron.d/campsite_gather &> /dev/null
if [ -f /etc/crontab ]; then
    uninstall_cron_task "$BIN_DIR/gather" /etc/crontab &> /dev/null
fi

# install our cron task
install_cron_task "0" "*/4" "*" "*" "*" "$ROOT_USER" "$SBIN_DIR/campsite_indexer" /etc/cron.d/campsite_indexer -c || exit 1
restart_cron || exit 1

exit 0
