CREATE TABLE OAuthAccessToken (
  id INT AUTO_INCREMENT NOT NULL,
  client_id INT NOT NULL,
  token VARCHAR(255) NOT NULL,
  expires_at INT DEFAULT NULL,
  scope VARCHAR(255) DEFAULT NULL,
  IdPublication INT DEFAULT NULL,
  UNIQUE INDEX UNIQ_DDE10DD55F37A13B (token),
  INDEX IDX_DDE10DD519EB6921 (client_id),
  INDEX IDX_DDE10DD55C1FD3F4 (IdPublication),
  PRIMARY KEY(id)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

CREATE TABLE OAuthAuthCode (
  id INT AUTO_INCREMENT NOT NULL,
  client_id INT NOT NULL,
  token VARCHAR(255) NOT NULL,
  redirect_uri LONGTEXT NOT NULL,
  expires_at INT DEFAULT NULL,
  scope VARCHAR(255) DEFAULT NULL,
  IdPublication INT DEFAULT NULL,
  UNIQUE INDEX UNIQ_3DD60F725F37A13B (token),
  INDEX IDX_3DD60F7219EB6921 (client_id),
  INDEX IDX_3DD60F725C1FD3F4 (IdPublication),
  PRIMARY KEY(id)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

CREATE TABLE OAuthClient (
  id INT AUTO_INCREMENT NOT NULL,
  random_id VARCHAR(255) NOT NULL,
  redirect_uris LONGTEXT NOT NULL COMMENT '(DC2Type:array)',
  secret VARCHAR(255) NOT NULL,
  allowed_grant_types LONGTEXT NOT NULL COMMENT '(DC2Type:array)',
  name VARCHAR(255) NOT NULL,
  IdPublication INT DEFAULT NULL,
  INDEX IDX_4128BE95C1FD3F4 (IdPublication),
  PRIMARY KEY(id)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

CREATE TABLE OAuthPublicApiResources (
  id INT AUTO_INCREMENT NOT NULL,
  resource VARCHAR(255) NOT NULL,
  PRIMARY KEY(id)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

CREATE TABLE OAuthRefreshToken (
  id INT AUTO_INCREMENT NOT NULL,
  client_id INT NOT NULL,
  token VARCHAR(255) NOT NULL,
  expires_at INT DEFAULT NULL,
  scope VARCHAR(255) DEFAULT NULL,
  IdPublication INT DEFAULT NULL,
  UNIQUE INDEX UNIQ_4A42604C5F37A13B (token),
  INDEX IDX_4A42604C19EB6921 (client_id),
  INDEX IDX_4A42604C5C1FD3F4 (IdPublication),
  PRIMARY KEY(id)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

ALTER TABLE OAuthAccessToken ADD CONSTRAINT FK_DDE10DD519EB6921 FOREIGN KEY (client_id) REFERENCES OAuthClient (id);
ALTER TABLE OAuthAuthCode ADD CONSTRAINT FK_3DD60F7219EB6921 FOREIGN KEY (client_id) REFERENCES OAuthClient (id);
ALTER TABLE OAuthRefreshToken ADD CONSTRAINT FK_4A42604C19EB6921 FOREIGN KEY (client_id) REFERENCES OAuthClient (id);