<?php
$translator = \Zend_Registry::get('container')->getService('translator');
$view = $GLOBALS['controller']->view; ?>
<script type="text/javascript" src="<?php echo $view->baseUrl('/js/newscoop_rest_api.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $view->baseUrl('/js/raphael-min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $view->baseUrl('/js/morris.min.js'); ?>"></script>
<script type="text/javascript">
  var api = new NewscoopRestApi(<?php echo json_encode($view->serverUrl($view->baseUrl('/api'))); ?>);

  api.getResource('/articles', {'type': 'news'})
    .setItemsPerPage(20)
    .setOrder({'published': 'desc'})
    .makeRequest(function(res){
      var data = [];
      var articles = [];
      var maxReads = 1; // fix for division by 0

      $('.diagrams .data').html('<ul></ul>');

      for (var i = res.items.length - 1; i >= 0; i--) {
        maxReads += parseInt(res.items[i].reads);
      };

      for (var i = res.items.length - 1; i >= 0; i--) {
        articles.push(res.items[i]);
      };
      articles.sort(function(a, b) {return a['reads'] - b['reads']});

      for (var i = articles.length - 1; i >= 0; i--) {
        var reads = Math.round((parseInt(articles[i].reads)/maxReads)*100);
        data.push({value: reads, label: articles[i].title});
        $('.diagrams .data ul').append('<li class="singleArticle">'+reads +'% - '+ articles[i].title+'</li>');
      };

      Morris.Donut({
        element: 'article_reads_graph',
        data: data,
        formatter: function (x) { return x + "%"}
      });
    });
</script>

<div class="ui-widget-content" style="padding-left: 8px; padding-top: 8px; border: none">
  <h3><?php echo $translator->trans('Latest 20 articles by popularity', array(), 'extensions'); ?></h3>
  <div class="diagrams">
    <div id="article_reads_graph" style="float:left; margin-right: 10px; width: 55%; height: 320px;"></div>
    <div class="data" style="float:left; width: 43%; font-size: 13px;"><?php echo $translator->trans('Loading...'); ?></div>
  <div>
</div> 
