Document: campsite
Title: Debian campsite Manual
Author: <insert document author here>
Abstract: This manual describes what campsite is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/campsite/campsite.sgml.gz

Format: postscript
Files: /usr/share/doc/campsite/campsite.ps.gz

Format: text
Files: /usr/share/doc/campsite/campsite.text.gz

Format: HTML
Index: /usr/share/doc/campsite/html/index.html
Files: /usr/share/doc/campsite/html/*.html

  
