#!/bin/bash
# Debconf config script for newscoop

set -e

### dbcondig is not yet enabled. ###

. /usr/share/debconf/confmodule

# newscoop-3.5 does not yet support that
#db_input normal newscoop/dbsetup || true
#db_go ||true

db_input high newscoop/apache-setup || true
db_go ||true

db_get newscoop/apache-setup
if [ "$RET" = "dedicated v-host" ]; then
	db_input high newscoop/apache-servername || true
	db_go ||true
	db_input high newscoop/apache-serveradmin || true
	db_go ||true
fi

#db_input high newscoop/cronjob || true
#db_go ||true
#
#db_get newscoop/cronjob
#if [ "$RET" = "true" ]; then
#	db_input high newscoop/cron-email || true
#	db_go ||true
#fi

#DEBHELPER#

exit 0
