#!/bin/sh
# Campsite package configuration script

# Source debconf library -- we have a Depends line
# to make sure it is there...

set -e
. /usr/share/debconf/confmodule
db_version 2.0
db_title Campsite


if [ "$1" = configure ] || [ "$1" = reconfigure ] ; then

STATE=1
while [ "$STATE"  != 0 -a "$STATE" != 19 ]
  do
  case "$STATE" in
      1) 
	  db_input critical campsite/dbserver || true
	  if db_go; then
	      db_get  campsite/dbserver || true
	      if [ ! -z "$RET" ]; then
		  STATE=2
	      fi
	  else
	      STATE=0
	  fi
	  ;;

      2)
	  db_input critical campsite/dbname || true
	  if db_go; then
	      db_get campsite/dbname || true
	      if [ ! -z "$RET" ]; then
		  STATE=3
	      fi
	  else
	      STATE=2
	  fi
	  ;;

      3)
	  db_input critical campsite/db_admname || true
	  if db_go; then
	      db_get  campsite/db_admname || true
	      if [ ! -z "$RET" ]; then
		  STATE=4
	      fi
	  else
	      STATE=3
	  fi
	  ;;

      4)
	  db_input critical campsite/db_admpassword || true
	  if db_go; then
	      db_get  campsite/db_admpassword || true
		 STATE=5
	  else
	      STATE=2
	  fi
	  ;;

      
      5)
	  db_input critical campsite/dbusername || true
	  if db_go; then
	      db_get  campsite/dbusername || true
		 if [ ! -z "$RET" ]; then
		      STATE=6
		fi
	  else
	      STATE=2
	  fi
	  ;;

      6)
	  db_input critical campsite/db_userpassword || true
	  if db_go; then
	      db_get  campsite/db_userpassword || true
		STATE=7
		
	  else
	      STATE=2
	  fi
	  ;;
       
      7)
	  db_input critical campsite/dbsample || true
	  if db_go; then
	      db_get  campsite/dbsample || true
		 STATE=8
	  else
	      STATE=7
	  fi
	  ;;

      8)
	  db_input critical campsite/url || true
	  if db_go; then
	      db_get  campsite/url || true
		if [ ! -z "$RET" ]; then
	      		STATE=9
		fi
	  else
	      STATE=8
	  fi
	  ;;
	
      9)
	  db_input critical campsite/sitename || true
	  if db_go; then
	      db_get  campsite/sitename || true
		if [ ! -z "$RET" ]; then
	      		STATE=10
		fi
	  else
	      STATE=9
	  fi
	  ;;

     10)
	  db_input critical campsite/email || true
	  if db_go; then
	      db_get  campsite/email || true
		if [ ! -z "$RET" ]; then
	      		STATE=11
		fi
	  else
	      STATE=10
	  fi
	  ;;

     11)
          db_input critical campsite/webserver || true
	  if db_go; then
	      	STATE=12
		
	  else
	      STATE=11
	  fi
	  ;;
	

  esac
done

fi

exit
