#!/bin/sh

# Debconf config script for Campsite

set -e

# Source debconf library
. /usr/share/debconf/confmodule

db_version 2.0
db_title "Campsite Configuration"

STATE=1
while [ "$STATE"  != 0 -a "$STATE" != 13 ]
  do
  case "$STATE" in
      1) 
	  db_input critical campsite/db_server || true
	  if db_go; then
	      db_get campsite/db_server || true
	      if [ ! -z "$RET" ]; then
		  STATE=2
	      fi
	  else
	      STATE=0
	  fi
	  ;;

      2)
          db_input critical campsite/db_adm_name || true
          if db_go; then
              db_get campsite/db_adm_name || true
              if [ ! -z "$RET" ]; then
                  STATE=3
              fi
          else
              STATE=2
          fi
          ;;

      3)
          db_input critical campsite/db_adm_pass || true
          if db_go; then
              db_get campsite/db_adm_pass || true
                 STATE=4
          else
              STATE=3
          fi
          ;;

      4)
	  db_input critical campsite/cs_db_name || true
	  if db_go; then
	      db_get campsite/cs_db_name || true
	      if [ ! -z "$RET" ]; then
		  STATE=5
	      fi
	  else
	      STATE=2
	  fi
	  ;;

      5)
	  db_input critical campsite/cs_db_uname || true
	  if db_go; then
	      db_get campsite/cs_db_uname || true
		 if [ ! -z "$RET" ]; then
		      STATE=6
		fi
	  else
	      STATE=2
	  fi
	  ;;

      6)
	  db_input critical campsite/cs_db_upass || true
	  if db_go; then
	      db_get campsite/cs_db_upass || true
		STATE=7
		
	  else
	      STATE=2
	  fi
	  ;;
       
      7)
	  db_input critical campsite/site_url || true
	  if db_go; then
	      db_get campsite/site_url || true
		 STATE=8
	  else
	      STATE=7
	  fi
	  ;;

      8)
	  db_input critical campsite/site_name || true
	  if db_go; then
	      db_get campsite/site_name || true
		if [ ! -z "$RET" ]; then
	      		STATE=9
		fi
	  else
	      STATE=8
	  fi
	  ;;
	
      9)
	  db_input critical campsite/site_pass || true
	  if db_go; then
	      db_get campsite/site_pass || true
		if [ ! -z "$RET" ]; then
	      		STATE=10
		fi
	  else
	      STATE=9
	  fi
	  ;;

     10)
          db_input critical campsite/site_email || true
          if db_go; then
              db_get campsite/site_email || true
                if [ ! -z "$RET" ]; then
                        STATE=11
                fi
          else
              STATE=10
          fi
          ;;

     11)
	  db_input critical campsite/site_demo || true
	  if db_go; then
	      db_get campsite/site_demo || true
		if [ ! -z "$RET" ]; then
	      		STATE=12
		fi
	  else
	      STATE=11
	  fi
	  ;;

     12)
          db_input critical campsite/webserver || true
	  if db_go; then
              db_get campsite/webserver || true
                if [ ! -z "$RET" ]; then
	      	        STATE=13
                fi
	  else
	      STATE=12
	  fi
	  ;;

  esac
done


exit
