#!/bin/bash
#postrm script for newscoop

set -e

if [ -f /usr/share/debconf/confmodule ]; then
  . /usr/share/debconf/confmodule
fi

# source dbconfig-common
#if [ -f /usr/share/dbconfig-common/dpkg/postrm ]; then
#  . /usr/share/dbconfig-common/dpkg/postrm
#  dbc_go newscoop $@
#fi

if [ "$DPKG_DEBUG" = "developer" ]; then
    set -x
fi

package_name="newscoop"
datadir="/var/lib/${package_name}"
configdir="/etc/newscoop/4.1"

webserver="apache2"
php="php5"

case "$1" in
  purge|remove)

    # Un-configure webservers
    if [ -L /etc/$webserver/conf.d/newscoop.conf ]; then
      rm -f /etc/$webserver/conf.d/newscoop.conf || true
      restart="$webserver $restart"
    fi

    if [ -L /etc/$php/conf.d/newscoop.ini ]; then
      rm -f /etc/$php/conf.d/newscoop.ini || true
      restart="$webserver $restart"
    fi

    if [ -f /etc/$webserver/sites-available/newscoop-vhost ]; then
      a2dissite newscoop-vhost &>/dev/null || true
      # TODO: if newscoop-vhost is not modified -> delete it
      restart="$webserver $restart"
    fi

    servers="apache2"
    # may not exist if package was manually installed
    if [ -r /usr/share/wwwconfig-common/restart.sh ]; then
      . /usr/share/wwwconfig-common/restart.sh
      echo $error
    fi

    # Cron-job
    if [ -L /etc/cron.d/newscoop ]; then
      rm -f /etc/cron.d/newscoop || true
    fi

    # Permissions
    dpkg-statoverride --list $datadir/conf &>/dev/null && \
    dpkg-statoverride --remove $datadir/conf || true
    dpkg-statoverride --list $datadir/install/cron_jobs &>/dev/null && \
    dpkg-statoverride --remove $datadir/install/cron_jobs || true
    dpkg-statoverride --list $datadir/images &>/dev/null && \
    dpkg-statoverride --remove $datadir/images || true
    dpkg-statoverride --list $datadir/themes &>/dev/null && \
    dpkg-statoverride --remove $datadir/themes || true
    #dpkg-statoverride --list $datadir/templates_cache &>/dev/null && \
    #dpkg-statoverride --remove $datadir/templates_cache || true
    dpkg-statoverride --list $datadir/plugins &>/dev/null && \
    dpkg-statoverride --remove $datadir/plugins || true
    dpkg-statoverride --list $datadir/backup &>/dev/null && \
    dpkg-statoverride --remove $datadir/backup || true
    dpkg-statoverride --list $datadir &>/dev/null && \
    dpkg-statoverride --remove $datadir || true

    if [ "$1" = "purge" ]; then
      rm -rf $datadir || true
      rm -f $configdir/newscoop.cron || true
      # newscoop-3.5 does not yet support that
      #rm -f ${dbconfigfile}
      #if which ucf >/dev/null 2>&1; then
      #  ucf --purge ${dbconfigfile}
      #fi
      #
      #db_purge || true
    fi

  ;;

  upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

  ;;

  *)
      echo "postrm called with unknown argument \`$1'" >&2
      exit 1
  ;;
esac

#DEBHELPER#

exit 0
