#!/bin/bash
#postinst script for newscoop

set -e

. /usr/share/debconf/confmodule

#dbc_generate_include='php:/etc/newscoop/dbconfig.php'
#dbc_generate_include_owner='root:www-data'
#dbc_generate_include_perms='640'
#dbc_pgsql_createdb_encoding='UTF8'
#. /usr/share/dbconfig-common/dpkg/postinst
#dbc_go newscoop

if [ "$DPKG_DEBUG" = "developer" ]; then
    set -x
fi

WEB_USER=www-data
WEB_GROUP=www-data

package_name="newscoop"
datadir="/var/lib/${package_name}"
configdir="/etc/newscoop/3.5"
includefile="${configdir}/apache.conf"
a2tplfile="${configdir}/apache.vhost"
phpinifile="${configdir}/newscoop.ini"
OLDVERSION="$2"

if [ "$1" == "reconfigure" ]; then
	true
	# TODO: run postrm ? clean up previous vhosts and /etc/$webserver/conf.d/
fi

case "$1" in
  configure|reconfigure)

    #webserver=`echo $webserver|sed -e 's/,  */ /g'`
    webserver="apache2"
    php="php5"

    db_get newscoop/apache-setup
    if [ "$RET" == "system-wide (all vhosts)" ]; then
        if [ ! -d /etc/$webserver/conf.d/ ]; then
            install -d -m755 /etc/$webserver/conf.d/
        fi
        if [ ! -e /etc/$webserver/conf.d/newscoop.conf ]; then
          ln -s ${includefile} /etc/$webserver/conf.d/newscoop.conf
          a2enmod rewrite &>/dev/null || true
          restart="$webserver $restart"
        fi

        if [ ! -d /etc/$php/conf.d/ ]; then
          install -d -m755 /etc/$php/conf.d/
        fi
        if [ ! -e /etc/$php/conf.d/newscoop.ini ]; then
          ln -s ${phpinifile} /etc/$php/conf.d/newscoop.ini
          restart="$webserver $restart"
        fi
    elif [ "$RET" == "dedicated v-host" ]; then
        db_get newscoop/apache-servername
        SN=$RET
        db_get newscoop/apache-serveradmin
        SA=$RET
        
        if [ ! -d /etc/$webserver/sites-available/ ]; then
            install -d -m755 /etc/$webserver/sites-available/
        fi
        sed -e "s/__SERVER_ADMIN__/${SA}/;s/__SERVER_NAME__/${SN}/" \
          ${a2tplfile} > /etc/$webserver/sites-available/newscoop-vhost
        a2ensite newscoop-vhost &>/dev/null
        restart="$webserver $restart"
    fi

    # Permissions
    dpkg-statoverride --list $datadir || \
    dpkg-statoverride --add --force --update $WEB_USER $WEB_GROUP 0755 $datadir
    dpkg-statoverride --list $datadir/conf || \
    dpkg-statoverride --add --force --update $WEB_USER $WEB_GROUP 0750 $datadir/conf
    dpkg-statoverride --list $datadir/install/cron_jobs || \
    dpkg-statoverride --add --force --update $WEB_USER $WEB_GROUP 0750 $datadir/install/cron_jobs
    dpkg-statoverride --list $datadir/templates || \
    dpkg-statoverride --add --force --update $WEB_USER $WEB_GROUP 0750 $datadir/templates
    dpkg-statoverride --list $datadir/templates_cache || \
    dpkg-statoverride --add --force --update $WEB_USER $WEB_GROUP 0750 $datadir/templates_cache
    dpkg-statoverride --list $datadir/plugins || \
    dpkg-statoverride --add --force --update $WEB_USER $WEB_GROUP 0750 $datadir/plugins
    dpkg-statoverride --list $datadir/backup || \
    dpkg-statoverride --add --force --update $WEB_USER $WEB_GROUP 0750 $datadir/backup

# newscoop-3.5 does not yet support that
#   # database setup
#   db_get newscoop/dbsetup
#   if [ -f /usr/share/dbconfig-common/dpkg/config -a "$RET" == "true" ]; then
#       echo "setting up database.. " >&2
#       dbc_dbtypes="mysql"
#       dbc_dbname=newscoop
#       dbc_dbuser=newscoop
#
#       # source dbconfig-common stuff
#       . /usr/share/dbconfig-common/dpkg/config --debconf-ok
#       dbc_go newscoop $@
#
#       # TODO: save db-account to newscoop-config.
#   fi

    servers="apache2"
    . /usr/share/wwwconfig-common/restart.sh
    echo $error >&2

    db_stop

  ;;

  abort-upgrade|abort-remove|abort-deconfigure)

  ;;

  *)
       echo "postinst called with unknown argument \`$1'" >&2
       exit 1
  ;;
esac

#DEBHELPER#

exit 0
