<div id="mc_embed_signup" class="ui-widget-content" style="width: 360px; padding-left: 8px; padding-top: 8px; border: none">

<h3>Get Sourcefabric newsletter:</h3> 
 
<form action="http://sourcefabric.us2.list-manage.com/subscribe/post?u=6b1ad01fc31dc6604968e6439&amp;id=f5447a7ef4" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank"> 

<fieldset class="plain">
    <ul>
        <li>
            <label for="mce-EMAIL">Your Email Address</label>
            <input type="text" value="" name="EMAIL" class="required email default-value" id="mce-EMAIL" /> 
        </li>
        <li>
            <label class="input-group-label">Email Format</label>
            <input type="radio" value="html" name="EMAILTYPE" id="mce-EMAILTYPE-0" class="input_radio" /><label for="mce-EMAILTYPE-0" class="inline-style left-floated">html</label>
            <input type="radio" value="text" name="EMAILTYPE" id="mce-EMAILTYPE-1" class="input_radio" style="margin-left: 13px" /><label for="mce-EMAILTYPE-1" class="inline-style left-floated">text</label>
            <input type="radio" value="mobile" name="EMAILTYPE" id="mce-EMAILTYPE-2" class="input_radio" style="margin-left: 13px" /><label for="mce-EMAILTYPE-2" class="inline-style left-floated">mobile</label>
        </li>
        <li>
            <label for="privacy-check" id="privacy-check-label">
                <span class="input"><input type="checkbox" name="privacy" id="privacy-check"></span>
                I agree to the <a href="http://www.sourcefabric.org/en/about/policy/" target="_blank">Privacy Policy</a> 
            </label> 
        </li>
        <li>
            <input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="mc_btn" />
        </li>
    </ul>
</fieldset>

</form> 

</div>
