<?php 
$translator = \Zend_Registry::get('container')->getService('translator'); 
$this->placeholder('title')->set($this->escape($this->item->getContentMeta()->getHeadline())); 
?>
<?php $this->placeholder('bodyId')->set('ingest'); ?>

<div class="detail">

<div class="controls">
    <?php if (!$this->item->isPublished() && $this->item->isUsable()) { ?>
    <a href="<?php echo $this->url(array(
        'action' => 'publish',
        'item' => $this->item->getId(),
    )); ?>" title="Push '<?php echo $this->escape($this->item->getContentMeta()->getHeadline()); ?>' to Web" class="publish">Push to Web</a>
    <?php } else if ($this->item->isPublished()) { ?>
    <span class="publish">Pushed to Web (<?php $this->renderDate($this->item->getPublished()); ?>)</span>
    <?php } ?>
</div>

<div class="item">
<?php if ($this->item instanceof \Newscoop\News\PackageItem) { ?>
    <?php $this->renderPackageItem($this->item); ?>
<?php } else { ?>
    <?php $this->renderNewsItem($this->item); ?>
<?php } // /if ?>
</div>

<dl class="meta">
    <dt><?php echo $translator->trans('Slug:', array(), 'article_images'); ?></dt>
    <dd><?php echo $this->item->getContentMeta()->getSlugline(); ?></dd>
    <?php if ($this->item->getContentMeta()->getByline()) { ?>
    <dt><?php echo $translator->trans('By:', array(), 'article_images'); ?></dt>
    <dd><?php echo $this->item->getContentMeta()->getByline(); ?></dd>
    <?php } ?>
    <dt><?php echo $translator->trans('Urgency:', array(), 'article_images'); ?></dt>
    <dd><?php echo $this->item->getContentMeta()->getUrgency(); ?></dd>
    <dt><?php echo $translator->trans('Status:'); ?></dt>
    <dd><?php echo $this->item->getItemMeta()->getPubStatus(); ?></dd>
    <dt><?php echo $translator->trans('Provider:'); ?></dt>
    <dd><?php echo $this->item->getItemMeta()->getProvider(); ?></dd>
    <dt><?php echo $translator->trans('Created:', array(), 'media_archive'); ?></dt>
    <dd><?php echo $this->item->getItemMeta()->getFirstCreated()->format('Y-m-d H:i'); ?></dd>
    <?php if ($this->item->getItemMeta()->getFirstCreated()->getTimestamp() !== $this->item->getItemMeta()->getVersionCreated()->getTimestamp()) { ?>
    <dt><?php echo $translator->trans('Updated:'); ?></dt>
    <dd><?php echo $this->item->getItemMeta()->getVersionCreated()->format('Y-m-d H:i'); ?></dd>
    <?php } ?>
    <dt><?php echo $translator->trans('Description:'); ?></dt>
    <dd><?php echo $this->item->getContentMeta()->getDescription(); ?></dd>
    <dt><?php echo $translator->trans('Copyright:'); ?></dt>
    <dd><?php echo $this->item->getRightsInfo()->first()->getCopyrightNotice(); ?></dd>
</dl>

</div>
