<?php $this->placeholder('title')->set('Newswires'); ?>

<div class="ingest"><div class="control"><div class="w">

<dl class="mode">
    <dt><?php putGS('Publish Mode'); ?></dt>
    <dd class="<?php echo $this->auto_mode ? 'auto' : 'manual'; ?>">
        <a href="<?php echo $this->url(array(
            'action' => 'switch-mode',
        )); ?>" title="Switch mode"><?php echo $this->auto_mode ? getGS('Automatic') : getGS('Manual'); ?></a>
    </dd>
</dl>
    
<h2><?php putGS('Feeds'); ?></h2>
<ul class="feeds">
    <?php foreach ($this->feeds as $feed) { ?>
    <li><?php echo $feed->getTitle(); ?> (<?php putGS('updated'); ?> <?php echo $feed->getUpdated() ? $feed->getUpdated()->format('H:i') : getGS('Never'); ?>)</li>
    <?php } ?>
</ul>

</div></div><div class="main"><div class="w">

<ul class="entries">
    <?php foreach ($this->entries as $entry) { ?>
    <li>
        <span class="date"><?php echo $entry->getUpdated()->format('j.n. H:i'); ?></span>
        <?php if (!$entry->isPublished()) { ?>
        <a href="<?php echo $this->url(array(
            'action' => 'publish',
            'entry' => $entry->getId(),
        )); ?>" title="<?php putGS("Publish '$1'", $entry->getTitle()); ?>" class="publish">Publish</a>
        <a href="<?php echo $this->url(array(
            'action' => 'prepare',
            'entry' => $entry->getId(),
        )); ?>" title="<?php putGS("Prepare '$1' for publishing", $entry->getTitle()); ?>" class="prepare">Prepare</a>
        <a href="<?php echo $this->url(array(
            'action' => 'delete',
            'entry' => $entry->getId(),
        )); ?>" title="<?php putGS("Delete '$1'", $entry->getTitle()); ?>" class="delete">Delete</a>
        <?php } else { ?>
        <em>published: <?php echo $entry->getPublished()->format('d.m.Y H:i:s'); ?></em>
        <?php } ?>
        <span class="title p-<?php echo $entry->getPriority(); ?>"><a href="<?php echo $this->url(array(
            'action' => 'detail',
            'entry' => $entry->getId(),
        )); ?>" class="iframe"><?php echo $entry->getTitle(); ?></a></span><br />
        <small><?php echo $this->sections[$entry->getId()]->getName(); ?></small>
        <p><?php echo $entry->getSummary(); ?></p>
    </li>
    <?php } ?>
</ul>

</div></div></div>

<script>
$('.ingest .title a').fancybox({
    hideOnContentClick: false
});
</script>
