<?php $this->placeholder('title')->set('Filters'); ?>

<a href="<?php echo $this->url(array(
    'action' => 'create-filter',
)); ?>">Create filter</a>

<ul class="filters">
    <?php foreach ($this->filters as $filter) { ?>
    <li>
        <div class="criteria"><?php echo $filter->getCriteria(); ?></div>
        <div class="command"><?php echo $filter->getCommand(); ?></div>
    </li>
    <?php } ?>
</ul>
