<div class="ingest">
<div class="widget"><div class="w">
<?php 
$translator = \Zend_Registry::get('container')->getService('translator');
?>
<ul class="entries">
    <?php foreach ($this->entries as $entry) { ?>
    <li>
        <span class="date"><?php echo $entry->getUpdated()->format('H:i'); ?></span>
        <?php if (!$entry->isPublished()) { ?>
        <a href="<?php echo $this->url(array(
            'controller' => 'ingest',
            'action' => 'publish',
            'entry' => $entry->getId(),
            'return' => 'index',
        )); ?>" title="<?php echo $translator->trans("Publish $1", $entry->getTitle()); ?>" class="publish">Publish</a>
        <a href="<?php echo $this->url(array(
            'controller' => 'ingest',
            'action' => 'prepare',
            'entry' => $entry->getId(),
        )); ?>" title="<?php echo $translator->trans("Prepare $1 for publishing", $entry->getTitle()); ?>" class="prepare">Prepare</a>
        <?php } else { ?>
        <em>published: <?php echo $entry->getPublished()->format('d.m.Y H:i:s'); ?></em>
        <?php } ?>
        <span class="title p-<?php echo $entry->getPriority(); ?>"><a href="<?php echo $this->url(array(
            'controller' => 'ingest',
            'action' => 'detail',
            'entry' => $entry->getId(),
        )); ?>" class="iframe"><?php echo $entry->getTitle(); ?></a></span>
    </li>
    <?php } ?>
    <li><a href="<?php echo $this->url(array(
        'controller' => 'ingest',
        'action' => 'index',
    )); ?>"><?php echo $translator->trans('Go to News Desk'); ?></a></li>
</ul>

</div></div></div>

<script>
$('.ingest .title a').fancybox({
    hideOnContentClick: false
});
</script>
