<?php
$translator = \Zend_Registry::get('container')->getService('translator');
echo $this->paginator; 
?>

<?php if (!empty($this->images)) { ?>
<ul class="thumbnails archive images">
    <?php foreach ($this->images as $image) { ?>
    <li id="image-<?php echo $image->getId(); ?>">
        <figure>
            <div><?php echo $this->thumbnail($image, 150, 150, 'fit')->getImg($this); ?></div>
            <figcaption><?php echo $image->getDescription(); ?> (<?php echo $image->getWidth(), 'x', $image->getHeight(); ?>)</figcaption>
        </figure>
    </li>
    <?php } ?>
</ul>

<?php } else { ?>
<div class="info"><?php echo $translator->trans('No images', array(), 'article_images'); ?></div>
<?php } ?>
