#!/bin/bash

################################################################################
#
# CAMPSITE is a Unicode-enabled multilingual web content
# management system for news publications.
# CAMPFIRE is a Unicode-enabled java-based near WYSIWYG text editor.
# Copyright (C)2000,2001  Media Development Loan Fund
# contact: contact@campware.org - http://www.campware.org
# Campware encourages further development. Please let us know.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
################################################################################

CAMPSITE_SERVER=/usr/local/campsite/campsite_server

test -x $CAMPSITE_SERVER || exit 0

#
#	See how we were called.
#
case "$1" in
  start)
	srv_proc=`ps ax|grep -w campsite_server|grep -v grep|wc -l`
	if [ $srv_proc -ne 0 ]; then
	    exit 0
	fi
	PARAMS=""
	if [ -f /etc/conf.campsite ]; then
	    THREADS=`cat /etc/conf.campsite | grep MAX_THREADS | cut -f 2 -d ':'`
	fi
	if [ "$THREADS" != "" ]; then
	    PARAMS="-t $THREADS"
	fi
	$CAMPSITE_SERVER $PARAMS
	err_code=$?
	if [ $err_code -ne 0 ]; then
	    exit 1
	fi
	srv_proc=`ps ax|grep -w campsite_server|grep -v grep|wc -l`
	if [ $srv_proc -eq 0 ]; then
	    exit 1
	fi
	;;
  stop)
	killall campsite_server > /dev/null 2>&1
	;;
  reload|restart)
	$0 stop
	$0 start
	;;
  status)
	THREADS=`ps ax | grep -w campsite_server| grep -v grep | wc -l`
	if [ $THREADS -gt 0 ]; then
	    echo "campsite server is running"
	else
	    echo "campsite server is not running"
	fi
	;;
  *)
	echo "Usage: $0 {start|stop|restart|reload|status}"
	exit 1
esac

exit 0
