#!/bin/bash

################################################################################
#
# CAMPSITE is a Unicode-enabled multilingual web content
# management system for news publications.
# CAMPFIRE is a Unicode-enabled java-based near WYSIWYG text editor.
# Copyright (C)2000,2001  Media Development Loan Fund
# contact: contact@campware.org - http://www.campware.org
# Campware encourages further development. Please let us know.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
################################################################################

rm -f $BIN_DIR/$CAMPSITE_SERVER
rm -f $BIN_DIR/$CAMPSITECTL

if $USER_INSTALL; then exit 0; fi

RC_INIT=/etc/init.d
if [ -d $RC_INIT ]; then
	test -f $RC_INIT/$CAMPSITEINIT && rm -f $RC_INIT/$CAMPSITEINIT
	test -L /etc/rc3.d/S95$CAMPSITEINIT && rm -f /etc/rc2.d/S95$CAMPSITEINIT
	test -L /etc/rc3.d/S95$CAMPSITEINIT && rm -f /etc/rc3.d/S95$CAMPSITEINIT
	test -L /etc/rc5.d/S95$CAMPSITEINIT && rm -f /etc/rc5.d/S95$CAMPSITEINIT
	test -L /etc/rc0.d/K50$CAMPSITEINIT && rm -f /etc/rc0.d/K50$CAMPSITEINIT
	test -L /etc/rc6.d/K50$CAMPSITEINIT && rm -f /etc/rc6.d/K50$CAMPSITEINIT
elif [ -d /etc/rc.d ]; then
	if [ ! -f /etc/rc.d/rc.local ]; then
	    exit 0
	fi
	rc_copy=$$-campsite-rc.local
	rm -f /tmp/$rc_copy
	cp -f /etc/rc.d/rc.local /tmp/$rc_copy
	grep -v "$BIN_DIR/$CAMPSITECTL" /tmp/$rc_copy > /etc/rc.d/rc.local
fi
exit 0
