<?php
regGS("You must select an article type.", "Вы должны выбрать тип статьи.");
regGS("You do not have the right to delete articles.", "Вы не имеете права удалять статьи.");
regGS("You do not have the right to change this article status. Once submitted an article can only changed by authorized users.", "Вы не имеете права изменять состояние этой статьи. Будучи отправленной статья может быть изменена только уполномоченным пользователем.");
regGS("No such section.", "Нет такой секции.");
regGS("No such issue.", "Нет такого выпуска");
regGS("Name<BR><SMALL>(click to edit)</SMALL>", "Название<BR><SMALL>(щелкните для правки)</SMALL>");
regGS("Could not save the article.  It has been locked by $1 $2 hours and $3 minutes ago.", "Невозможно сохранить статью. Она была заблокирована пользователем $1 $2 часов и $3 минут назад.");
regGS("Back to article details", "Назад к подробностям статьи");
regGS("Article automatic publishing schedule", "Расписание автоматической публикации статей");
regGS("Article Type", "Тип статьи");
regGS("Are you sure you want to delete this scheduled action?", "Вы уверены, что хотитее удалить эту запланированную операцию");
regGS("$1 articles found", "Статей найдено: $1");
regGS("Show article on front page", "Показать статью на титульной странице");
regGS("Show article on section page", "Показать статью на странице секции");
regGS("Enter keywords, comma separated", "Введите ключевые слова, разделяя запятой");
regGS("Article $1 added to $2. $3 from $4. $5 of $6", "Статья $1 добавлена к $2. $3 из $4. $5 из $6");
regGS("Are you sure you want to delete the article $1 ($2)?", "Вы уверены, что хотите удалить статью $1 ($2)?");
regGS("Article $1 ($2) deleted from $3. $4 from $5. $6 ($7) of $8", "Статья $1 ($2) удалена из $3. $4 из $5. $6 ($7) из $8");
regGS("Change article status", "Изменить статус статьи");
regGS("Change the status of article $1 ($2) from $3 to", "Изменить статус статьи $1 ($2) из $3 в");
regGS("Article $1 status from $2. $3 from $4. $5 ($6) of $7 changed", "Изменен статус статьи $1 из $2. $3 из $4. $5 ($6) из $7");
regGS("Translate article", "Перевести статью");
regGS("You do not have the right to change this article.  You may only edit your own articles and once submitted an article can only changed by authorized users.", "Вы не имеете права изменения этой статьи. Вы можете только редактировать свои собственные статьи и, будучи отправленной, статья может быть изменена только уполномоченными пользователями.");
regGS("Edit article details", "Редактировать параметры статьи");
regGS("Allow users without subscriptions to view the article", "Позволить пользователям без подписки просматривать статью");
regGS("The article has been locked by $1 ($2) $3 hour(s) and $4 minute(s) ago.", "Статья была заблокирована пользователем $1 ($2) $3 часа и $4 минут назад.");
regGS("The article has been locked by $1 ($2) $3 minute(s) ago.", "была заблокирована пользователем $1 ($2) $3 минут назад.");
regGS("Are you sure you want to unlock it?", "Вы уверены, что уверены разблокировать?");
regGS("Article is locked", "Статья заблокирована");
regGS("The article has been updated.", "Статья была обновлена");
regGS("The article cannot be updated or no changes have been made.", "Статья не может быть обновлена или изменения не были сделаны.");
regGS("Duplicate article", "Дублировать статью");
regGS("The destination section is the same as the source section.", "Секция назначения та же, что и секция источника");
regGS("The article is new; it is not possible to schedule it for automatic publishing.", "Статья новая, ее невозможно назначить для автоматической публикации.");
?>