<?php $this->placeholder('title')->set(getGS('Support')); ?>

<?php if ($this->first) { ?>
<dl class="zend_form">
    <?php echo(getGS('Because this is your first time logging into the admin panel, you need to fill in support details.')); ?>
</dl><br>
<?php } ?>

<form action="<?php echo($this->form->getAction()); ?>" method="post">
    <dl class="zend_form">
        <?php echo($this->form->agree); ?>
        
        <p>
        <?php echo(getGS('Help Newscoop improve by letting us know you are using it. This info will be collected regularly in order to improve your user experience.')); ?>
        <br>
        <fieldset>
            <legend><?php echo(getGS('Sample support feedback')); ?></legend>
            <div id="feedback" style="overflow: auto; height: 100px;">
                <table style="width: 100%;">
                <?php foreach ($this->stats as $key => $value) { ?>
                <tr>
                    <td><?php echo($key); ?></td>
                    <td><?php echo($value); ?></td>
                </tr>
                <?php } ?>
                </table>
            </div>
        </fieldset>
        </p>
        <?php echo($this->form->save); ?>
        <?php echo($this->form->cancel); ?>
        
    </dl>
</form>

<script>
    function agree() {
        document.getElementById('agree').value = 1;
    }
    function disagree() {
        document.getElementById('agree').value = 0;
    }
</script>