<?php
regGS("Create new folder", "Creaza director");
regGS("Upload template", "Transferă şablon");
regGS("Creating new folder", "Crează director");
regGS("You do not have the right to create new folders.", "Nu aveţi dreptul să creaţi directoare");
regGS("The folder $1 has been created", "Directorul $1 a fost creat");
regGS("The folder $1 could not be created", "Directorul $1 nu poate fi creat");
regGS("A file or folder having the name $1 already exists", "");
regGS("Delete templates", "Şterge şabloane");
regGS("Delete folders", "Şterge directoare");
regGS("You do not have the right to delete templates.", "Nu aveţi dreptul să ştergeţi şabloane");
regGS("Are you sure you want to delete the folder $1 from $2?", "Doriţi să ştergeţi directorul $1 din $2?");
regGS("Are you sure you want to delete the template $1 from folder $2?", "Doriţi să ştergeţi şablonul $1 din $2?");
regGS("The template $1 is in use and can not be deleted.", "");
regGS("Deleting template", "Şterg şablon");
regGS("Deleting folder", "Şterg director");
regGS("The folder has been deleted.", "Directorul a fost şters");
regGS("The folder could not be deleted.", "Directorul nu poate fi şters");
regGS("The template has been deleted.", "Şablonul a fost şters");
regGS("The template could not be deleted.", "Şablonul nu poate fi şters");
regGS("Template $1 was deleted", "");
regGS("Delete folder", "Şterge director");
regGS("Folders", "Directoare");
regGS("No folders.", "Nu există directoare");
regGS("Files", "Fişiere");
regGS("No templates.", "Nu există şabloane");
regGS("Uploading template", "Transfer şablon");
regGS("File", "Fişier");
regGS("File $1 already exists.", "Fişierul $1 există deja");
regGS("File $1 already exists. Old version deleted !", "Fişierul $1 există deja. Versiunea veche a fost ştearsă!");
regGS("The upload of $1 was successful !", "Trasferul fişierului $1 a fost făcut cu succes!");
regGS("Template $1 uploaded", "Fişierul $1 a fost transferat");
regGS("Create new template", "Crează şablon");
regGS("Creating new template", "Creez şablon");
regGS("Duplicate template", "Copiază şablon");
regGS("Edit template", "Editează şablon");
regGS("Template", "Şablon");
regGS("Save", "Salvează");
regGS("The template could not be saved", "Şablonul nu poate fi salvat");
regGS("The template has been saved.", "Şablonul a fost salvat");
regGS("The template $1 has been created.", "Şablonul $1 a fost creat.");
regGS("Do you want to edit the template ?", "Doriţi să editaţi şablonul?");
regGS("The template $1 could not be created.", "Şablonul $1 nu poate fi creat.");
regGS("Template $1 was changed", "Şablonul $1 a fost modificat");
regGS("New template $1 was created", "Şablonul $1 a fost creat");
regGS("Template $1 was duplicated into $2", "Şablonul $1 a fost copiat in $2");
regGS("Error converting the template to UTF-8 charset.", "Eroare la conversia şablonului in setul de caractere UTF-8.");
regGS("Template charset", "Setul de caractere al şablonului");
regGS("Select a language/character set", "Selectaţi limba/set de caractere");
regGS("All languages", "Toate limbile");
regGS("You do not have the right to modify templates.", "");
regGS("Invalid template file $1", "");
?>