<?php
regGS("CAMPSITE", "CAMPSITE");
regGS("Home", "Glavna");
regGS("Logout", "Izlaz");
regGS("Fields", "Polja");
regGS("Delete", "Briši");
regGS("Type", "Vrsta");
regGS("Name", "Ime");
regGS("Keyword", "Ključna riječ");
regGS("Infotypes", "<i>Infotypes</i>");
regGS("Languages", "Jezici");
regGS("Native name", "Izvorno ime");
regGS("Code", "Kod");
regGS("Code page", "Kodna stranica");
regGS("Edit", "Uredi");
regGS("Countries", "Države");
regGS("Reader", "Čitalac");
regGS("Access", "Pristup");
regGS("Login", "Prijava");
regGS("Password", "Lozinka");
regGS("Site", "<i>Site</i>");
regGS("Currency", "Valuta");
regGS("Templates", "Predlošci");
regGS("Topics", "Teme");
regGS("Path", "Putanja");
regGS("Go up", "Gore");
regGS("Language", "Jezik");
regGS("Keyword infotype", "<i>Infotype</i> za ključnu riječ");
regGS("Translation", "Prijevod");
regGS("Infotype", "<i>Infotype</i>");
regGS("Country", "Država");
regGS("User name", "Korisničko ime");
regGS("Definition", "Definicija");
regGS("Publication", "Publikacija");
regGS("Default language", "Osnovni jezik");
regGS("Time Unit", "Vremenska jedinica");
regGS("Unit Cost", "Cijena jedinice");
regGS("Subscriptions", "Pretplata");
regGS("Issue", "Izdanje");
regGS("Number", "Broj");
regGS("Section", "Rubrika");
regGS("Keywords", "Ključne riječi");
regGS("Topic", "Tema");
regGS("Next", "Naprijed");
regGS("Previous", "Nazad");
regGS("Translate", "Prevedi");
regGS("Details", "Detalji");
regGS("View", "Prikaz");
regGS("days", "dani");
regGS("Article Types", "Vrste članaka");
regGS("User Types", "Vrste korisnika");
regGS("Glossary", "<i>Glossary</i>");
regGS("Keyword infotypes", "<i>Infotypes</i> za ključnu riječ");
regGS("Publications", "Publikacije");
regGS("Issues", "Izdanja");
regGS("Sections", "Rubrike");
regGS("Articles", "Članci");
regGS("Images", "Slike");
regGS("Nr", "Br");
regGS("Change", "Izmijeni");
regGS("Add new issue", "Dodaj novo izdanje");
regGS("Add new topic", "Dodaj novu temu");
regGS("Delete topic", "Izbriši temu");
regGS("Default Language", "Osnovni jezik");
regGS("Subscription Default Time", "Osnovna dužina pretplate");
regGS("Pay Period", "Rok plaćanja");
regGS("Info", "Info");
regGS("Trial Period", "Probni period");
regGS("Paid Period", "Plaćeni period");
regGS("Preview", "Pregledaj");
regGS("You must complete the $1 field.", "Morate ispuniti polje $1");
regGS("No such language.", "Nema tog jezika");
regGS("No such infotype.", "Nema tog <i>infotype</i>");
regGS("No such keyword.", "Nema te ključne riječi");
regGS("Publication does not exist.", "Nema te publikacije");
regGS("No such country.", "Nema te države");
regGS("No such issue.", "Nema tog izdanja");
regGS("Topic does not exist.", "Nema te teme");
regGS("You must select a language.", "Morate izasbrati jezik");
regGS("No such section.", "Ta rubrika ne postoji");
regGS("No articles.", "Nema članaka");
regGS("Access denied", "Zabranjen pristup");
regGS("Add new article", "Dodaj novi članak");
regGS("Status", "Status");
regGS("No such article.", "Nema tog članka");
regGS("Published", "Objavljen");
regGS("Not published", "");
regGS("Submitted", "Predan");
regGS("New", "Novi");
regGS("Article", "Članak");
regGS("Publish", "Objavi");
regGS("Unpublish", "Povuci");
regGS("Unlock", "Otključaj");
regGS("Uploaded", "Osvježen");
regGS("(yyyy-mm-dd)", "gggg-mm-dd");
regGS("YYYY-MM-DD", "GGGG-MM-DD");
regGS("Submit", "Predaj");
regGS("Field", "Polje");
regGS("Edit details", "Izmjeni detalje");
regGS("No such image.", "Nema te slike");
regGS("Image", "Slika");
regGS("Description", "Opis");
regGS("Photographer", "Fotograf");
regGS("Place", "Mjesto");
regGS("Date", "Datum");
regGS("Publ. no.", "Br. pub.");
regGS("Issue no.", "Br. izdanja");
regGS("Section no.", "Br. rubrike");
regGS("Image number", "Br. slike");
regGS("Users", "Korisnici");
regGS("User is a reader", "Korisnik je čitalac");
regGS("User may add/change publications", "Korisnik smije dodavati/mjenjati publikacije");
regGS("User may delete publications", "Korisnik smije brisati publikacije");
regGS("User may add/change issues", "Korisnik smije dodavati/uređivati izdanja");
regGS("User may delete issues", "Korisnik smije brisati izdanja");
regGS("User may add/change sections", "Korisnik smije dodavati/uređivati rubrike");
regGS("User may delete sections", "Korisnik smije brisati rubrike");
regGS("User may add articles", "Korisnik smije dodavati članke");
regGS("User may change articles", "Korisnik smije uređivati članke");
regGS("User may delete articles", "Korisnik smije brisati članke");
regGS("User may add images", "Korisnik smije dodavati slike");
regGS("User may change images", "Korisnik smije mijenjati slike");
regGS("User may delete images", "Korisnik smije brisati slike");
regGS("User may add templates", "Korisnik smije dodavati predloške");
regGS("User may delete templates", "Korisnik smije brisati predloške");
regGS("User may add/change user accounts and passwords", "Korisnik smije dodavati/mijenjati korisničke račune i lozinke");
regGS("User may delete user accounts", "Korisnik smije brisati korisničke račune");
regGS("User may manage user subscriptions", "Korisnik smije administrirati pretplatu");
regGS("User may manage account types", "Korisnik smije uređivati vrste korisničkih računa");
regGS("User may add/change article types", "Korisnik smije dodavati/mijenjati tipove članaka");
regGS("User may delete article types", "Korisnik smije brisati tipove članaka");
regGS("User may add languages and manage language information", "Korisnik smije dodavati jezike i mijenjati relevantne informacije");
regGS("User may delete languages", "Korisnik smije brisati jezike");
regGS("User may manage glossary infotypes", "Korisnik smije upravljati <i>glossary infotypes</i>");
regGS("User may add/change glossary entries", "Korisnik smije dodavati/mjenjati <i>glossary</i> zapise");
regGS("User may delete glossary entries", "Korisnik smije brisati <i>glossary</i> zapise");
regGS("User will be notified on several events", "Korisnik će biti informiran o raznim sistemskim aktivnostima");
regGS("User may view audit logs", "Korisnik ima pristup logovima");
regGS("User may add/change country names", "Korisnik smije dodavati/mijenjati imena država");
regGS("User may delete country entries", "Korisnik smije brisati unesene države");
regGS("User may manage localizer", "Korisnik smije koristiti lokalizator");
regGS("User may manage indexer", "Korisnik smije upravljati indekserom");
regGS("User may publish articles", "Korisnik smije objavljivati članke");
regGS("User may manage topics", "Korisnik smije upravljati temama");
regGS("Adding new translation", "Dodavanje novog prijevoda");
regGS("Translate keyword", "Prevedi ključne riječi");
regGS("No more languages.", "Nema više jezika");
regGS("No such keyword infotype.", "Nema tog <i>infotype</i> za ključnu riječ");
regGS("Adding new keyword infotype", "Dodavanje nove ključne riječi <i>infotype</i>");
regGS("The infotype has been deleted.", "<i>Infotype</i> će biti izbrisan");
regGS("The infotype could not be deleted.", "<i>Infotype</i> nije mogao biti izbrisan");
regGS("Add new publication", "Dodaj novu publikaciju");
regGS("Upload new template", "Osvježi novi predložak");
regGS("Add new user account", "Dodaj novog korisnika");
regGS("Add new user type", "Dodaj novu vrstu korisnika");
regGS("Add new article type", "Dodaj novu vrstu članka");
regGS("Add new country", "Dodaj novu zemlju");
regGS("Add new language", "Dodaj novi jezik");
regGS("Add new section", "Dodaj novu rubriku");
regGS("View logs", "Pogledaj log");
regGS("Change your password", "Promijeni lozinku");
regGS("Your articles", "Vaši članci");
regGS("Submitted articles", "Predani članci");
regGS("Quick Menu", "Kratice");
regGS("Logs", "Logovi");
regGS("There are $1 article(s) left.", "Ostao-lo je još $1 članak-a");
regGS("There are $1 issue(s) left.", "Ostalo-la je(su) još $1 izdanje-a");
regGS("There are $1 section(s) left.", "Ostala(o) je još $1 rubrika(e)");
regGS("There are $1 publication(s) left.", "Ostala(o) je još $1 publikacija(e) ");
regGS("There are $1 keyword(s) left.", "Ostalo je još $1 ključne riječi");
regGS("There are $1 countries left.", "Ostala(le) je (su) još $1 zemlja(e)");
regGS("Name<BR><SMALL>(click to edit)</SMALL>", "Ime<br><small>(kliknite za uređivanje)</small>");
regGS("User account", "Korisnički račun");
regGS("No such user account.", "Nema tog korisničkog računa");
regGS("Add new subscription", "Dodaj novu pretplatu");
regGS("You do not have the right to add subscriptions.", "Nemate pravo dodavati nove pretplate");
regGS("Adding subscription", "Dodavanje pretplate");
regGS("The section could not be added.", "Rubrika ne može biti dodana");
regGS("Delete subscription", "Izbriši pretplatu");
regGS("You do not have the right to delete subscriptions.", "Nemate pravo brisati pretplate");
regGS("Deleting subscription", "Brisanje pretplatu");
regGS("No such subscription.", "Nema te pretplate.");
regGS("The section $1 could not be deleted.", "Rubrika $1 se ne može brisati.");
regGS("The topic $1 could not be deleted.", "Tema $1 se ne može brisati.");
regGS("Yes", "Da");
regGS("No", "Ne");
regGS("No issues.", "Nema izdanja.");
regGS("Back to article details", "Vrati se na detalje članka");
regGS("Adding new topic", "Dodaj novu temu");
regGS("Topic $1 added", "Tema $1 je dodana");
regGS("The topic could not be added.", "Tema ne može bit idodana");
regGS("Do you want to delete the topic $1?", "Da li želite brisati temu $1?");
regGS("Add another topic", "Dodaj drugu temu");
regGS("Deleting topic", "Brisanje teme");
regGS("There are $1 subtopics left.", "Ostala je $1 podtema");
regGS("Topic $1 deleted", "Tema $1 je izbrisana");
regGS("Changing topic name", "Izmjena imena teme");
regGS("You do not have the right to change topic name.", "Nemate prava mjenjati ime teme");
regGS("Topic $1 updated", "Tema $1 je osvježena");
regGS("The topic name could not be updated.", "Ime teme ne može biti osvježeno");
regGS("Change topic name", "Izmjena imena teme");
regGS("Delete topic $1", "Briši temu $1");
regGS("No topics", "Nema tema");
regGS("The topic $1 has been successfuly added.", "Tema $1 uspješno je dodana.");
regGS("The topic $1 has been successfuly updated.", "Tema $1 uspješno je osvježena.");
regGS("The topic $1 has been deleted.", "Tema $1 će biti izbrisana.");
regGS("There are $1 articles using the topic.", "Ostalo je $1 članaka koji koriste temu.");
regGS("You must fill in the $1 field.", "Morate popuniti $1 polje");
regGS("Start", "Početak");
regGS("Days", "Dani");
regGS("(YYYY-MM-DD)", "(GGGG-MM-DD)");
regGS("The sections were added successfully.", "Rubrika je uspješno dodana.");
regGS("The sections could not be added successfully. Some of them were already added !", "Rubrika ne može bit uspješno dodana.");
regGS("No languages", "Nema jezika");
regGS("---Select language---", "---Odaberi jezik---");
regGS("No publications", "Nema publikacija");
regGS("---Select publication---", "---Odaberi publikaciju---");
regGS("No issues", "Nema izdanja");
regGS("---Select issue---", "---Odaberi izdanje---");
regGS("No sections", "Nema rubrika");
regGS("---Select section---", "---Odaberi rubriku");
regGS("No articles", "Nema članaka");
regGS("---Select article---", "---Odaberi članak---");
regGS("Duplicate", "Napravi kopiju");
regGS("You do not have the right to add articles.", "Nemate prava kreirati članak");
regGS("Add new field", "Dodaj novo polje");
?>