
all: dummy

clean: dummy
	rm -f smtp_wrapper

install: all
	mkdir -p "$(BIN_DIR)"
#	install -o $(ROOT_USER) -g $(APACHE_GROUP) -m 755 smtp_wrapper "$(BIN_DIR)"

uninstall: dummy
#	rm -f "$(BIN_DIR)/smtp_wrapper"

dummy:

