var country_codes_alpha_2 = [];
country_codes_alpha_2.push('AF');
country_codes_alpha_2.push('AX');
country_codes_alpha_2.push('AL');
country_codes_alpha_2.push('DZ');
country_codes_alpha_2.push('AS');
country_codes_alpha_2.push('AD');
country_codes_alpha_2.push('AO');
country_codes_alpha_2.push('AI');
country_codes_alpha_2.push('AQ');
country_codes_alpha_2.push('AG');
country_codes_alpha_2.push('AR');
country_codes_alpha_2.push('AM');
country_codes_alpha_2.push('AW');
country_codes_alpha_2.push('AU');
country_codes_alpha_2.push('AT');
country_codes_alpha_2.push('AZ');
country_codes_alpha_2.push('BS');
country_codes_alpha_2.push('BH');
country_codes_alpha_2.push('BD');
country_codes_alpha_2.push('BB');
country_codes_alpha_2.push('BY');
country_codes_alpha_2.push('BE');
country_codes_alpha_2.push('BZ');
country_codes_alpha_2.push('BJ');
country_codes_alpha_2.push('BM');
country_codes_alpha_2.push('BT');
country_codes_alpha_2.push('BO');
country_codes_alpha_2.push('BA');
country_codes_alpha_2.push('BW');
country_codes_alpha_2.push('BV');
country_codes_alpha_2.push('BR');
country_codes_alpha_2.push('IO');
country_codes_alpha_2.push('BN');
country_codes_alpha_2.push('BG');
country_codes_alpha_2.push('BF');
country_codes_alpha_2.push('BI');
country_codes_alpha_2.push('KH');
country_codes_alpha_2.push('CM');
country_codes_alpha_2.push('CA');
country_codes_alpha_2.push('CV');
country_codes_alpha_2.push('KY');
country_codes_alpha_2.push('CF');
country_codes_alpha_2.push('TD');
country_codes_alpha_2.push('CL');
country_codes_alpha_2.push('CN');
country_codes_alpha_2.push('CX');
country_codes_alpha_2.push('CC');
country_codes_alpha_2.push('CO');
country_codes_alpha_2.push('KM');
country_codes_alpha_2.push('CG');
country_codes_alpha_2.push('CD');
country_codes_alpha_2.push('CK');
country_codes_alpha_2.push('CR');
country_codes_alpha_2.push('CI');
country_codes_alpha_2.push('HR');
country_codes_alpha_2.push('CU');
country_codes_alpha_2.push('CY');
country_codes_alpha_2.push('CZ');
country_codes_alpha_2.push('DK');
country_codes_alpha_2.push('DJ');
country_codes_alpha_2.push('DM');
country_codes_alpha_2.push('DO');
country_codes_alpha_2.push('EC');
country_codes_alpha_2.push('EG');
country_codes_alpha_2.push('SV');
country_codes_alpha_2.push('GQ');
country_codes_alpha_2.push('ER');
country_codes_alpha_2.push('EE');
country_codes_alpha_2.push('ET');
country_codes_alpha_2.push('FK');
country_codes_alpha_2.push('FO');
country_codes_alpha_2.push('FJ');
country_codes_alpha_2.push('FI');
country_codes_alpha_2.push('FR');
country_codes_alpha_2.push('GF');
country_codes_alpha_2.push('PF');
country_codes_alpha_2.push('TF');
country_codes_alpha_2.push('GA');
country_codes_alpha_2.push('GM');
country_codes_alpha_2.push('GE');
country_codes_alpha_2.push('DE');
country_codes_alpha_2.push('GH');
country_codes_alpha_2.push('GI');
country_codes_alpha_2.push('GR');
country_codes_alpha_2.push('GL');
country_codes_alpha_2.push('GD');
country_codes_alpha_2.push('GP');
country_codes_alpha_2.push('GU');
country_codes_alpha_2.push('GT');
country_codes_alpha_2.push('GG');
country_codes_alpha_2.push('GN');
country_codes_alpha_2.push('GW');
country_codes_alpha_2.push('GY');
country_codes_alpha_2.push('HT');
country_codes_alpha_2.push('HM');
country_codes_alpha_2.push('VA');
country_codes_alpha_2.push('HN');
country_codes_alpha_2.push('HK');
country_codes_alpha_2.push('HU');
country_codes_alpha_2.push('IS');
country_codes_alpha_2.push('IN');
country_codes_alpha_2.push('ID');
country_codes_alpha_2.push('IR');
country_codes_alpha_2.push('IQ');
country_codes_alpha_2.push('IE');
country_codes_alpha_2.push('IM');
country_codes_alpha_2.push('IL');
country_codes_alpha_2.push('IT');
country_codes_alpha_2.push('JM');
country_codes_alpha_2.push('JP');
country_codes_alpha_2.push('JE');
country_codes_alpha_2.push('JO');
country_codes_alpha_2.push('KZ');
country_codes_alpha_2.push('KE');
country_codes_alpha_2.push('KI');
country_codes_alpha_2.push('KP');
country_codes_alpha_2.push('KR');
country_codes_alpha_2.push('KW');
country_codes_alpha_2.push('KG');
country_codes_alpha_2.push('LA');
country_codes_alpha_2.push('LV');
country_codes_alpha_2.push('LB');
country_codes_alpha_2.push('LS');
country_codes_alpha_2.push('LR');
country_codes_alpha_2.push('LY');
country_codes_alpha_2.push('LI');
country_codes_alpha_2.push('LT');
country_codes_alpha_2.push('LU');
country_codes_alpha_2.push('MO');
country_codes_alpha_2.push('MK');
country_codes_alpha_2.push('MG');
country_codes_alpha_2.push('MW');
country_codes_alpha_2.push('MY');
country_codes_alpha_2.push('MV');
country_codes_alpha_2.push('ML');
country_codes_alpha_2.push('MT');
country_codes_alpha_2.push('MH');
country_codes_alpha_2.push('MQ');
country_codes_alpha_2.push('MR');
country_codes_alpha_2.push('MU');
country_codes_alpha_2.push('YT');
country_codes_alpha_2.push('MX');
country_codes_alpha_2.push('FM');
country_codes_alpha_2.push('MD');
country_codes_alpha_2.push('MC');
country_codes_alpha_2.push('MN');
country_codes_alpha_2.push('ME');
country_codes_alpha_2.push('MS');
country_codes_alpha_2.push('MA');
country_codes_alpha_2.push('MZ');
country_codes_alpha_2.push('MM');
country_codes_alpha_2.push('NA');
country_codes_alpha_2.push('NR');
country_codes_alpha_2.push('NP');
country_codes_alpha_2.push('NL');
country_codes_alpha_2.push('AN');
country_codes_alpha_2.push('NC');
country_codes_alpha_2.push('NZ');
country_codes_alpha_2.push('NI');
country_codes_alpha_2.push('NE');
country_codes_alpha_2.push('NG');
country_codes_alpha_2.push('NU');
country_codes_alpha_2.push('NF');
country_codes_alpha_2.push('MP');
country_codes_alpha_2.push('NO');
country_codes_alpha_2.push('OM');
country_codes_alpha_2.push('PK');
country_codes_alpha_2.push('PW');
country_codes_alpha_2.push('PS');
country_codes_alpha_2.push('PA');
country_codes_alpha_2.push('PG');
country_codes_alpha_2.push('PY');
country_codes_alpha_2.push('PE');
country_codes_alpha_2.push('PH');
country_codes_alpha_2.push('PN');
country_codes_alpha_2.push('PL');
country_codes_alpha_2.push('PT');
country_codes_alpha_2.push('PR');
country_codes_alpha_2.push('QA');
country_codes_alpha_2.push('RE');
country_codes_alpha_2.push('RO');
country_codes_alpha_2.push('RU');
country_codes_alpha_2.push('RW');
country_codes_alpha_2.push('BL');
country_codes_alpha_2.push('SH');
country_codes_alpha_2.push('KN');
country_codes_alpha_2.push('LC');
country_codes_alpha_2.push('MF');
country_codes_alpha_2.push('PM');
country_codes_alpha_2.push('VC');
country_codes_alpha_2.push('WS');
country_codes_alpha_2.push('SM');
country_codes_alpha_2.push('ST');
country_codes_alpha_2.push('SA');
country_codes_alpha_2.push('SN');
country_codes_alpha_2.push('RS');
country_codes_alpha_2.push('SC');
country_codes_alpha_2.push('SL');
country_codes_alpha_2.push('SG');
country_codes_alpha_2.push('SK');
country_codes_alpha_2.push('SI');
country_codes_alpha_2.push('SB');
country_codes_alpha_2.push('SO');
country_codes_alpha_2.push('ZA');
country_codes_alpha_2.push('GS');
country_codes_alpha_2.push('ES');
country_codes_alpha_2.push('LK');
country_codes_alpha_2.push('SD');
country_codes_alpha_2.push('SR');
country_codes_alpha_2.push('SJ');
country_codes_alpha_2.push('SZ');
country_codes_alpha_2.push('SE');
country_codes_alpha_2.push('CH');
country_codes_alpha_2.push('SY');
country_codes_alpha_2.push('TW');
country_codes_alpha_2.push('TJ');
country_codes_alpha_2.push('TZ');
country_codes_alpha_2.push('TH');
country_codes_alpha_2.push('TL');
country_codes_alpha_2.push('TG');
country_codes_alpha_2.push('TK');
country_codes_alpha_2.push('TO');
country_codes_alpha_2.push('TT');
country_codes_alpha_2.push('TN');
country_codes_alpha_2.push('TR');
country_codes_alpha_2.push('TM');
country_codes_alpha_2.push('TC');
country_codes_alpha_2.push('TV');
country_codes_alpha_2.push('UG');
country_codes_alpha_2.push('UA');
country_codes_alpha_2.push('AE');
country_codes_alpha_2.push('GB');
country_codes_alpha_2.push('US');
country_codes_alpha_2.push('UM');
country_codes_alpha_2.push('UY');
country_codes_alpha_2.push('UZ');
country_codes_alpha_2.push('VU');
country_codes_alpha_2.push('VE');
country_codes_alpha_2.push('VN');
country_codes_alpha_2.push('VG');
country_codes_alpha_2.push('VI');
country_codes_alpha_2.push('WF');
country_codes_alpha_2.push('EH');
country_codes_alpha_2.push('YE');
country_codes_alpha_2.push('ZM');
country_codes_alpha_2.push('ZW');
var country_codes_alpha_2_countries = {};
country_codes_alpha_2_countries['AF'] = 'Afghanistan';
country_codes_alpha_2_countries['AX'] = 'Aland Islands / Åland Islands';
country_codes_alpha_2_countries['AL'] = 'Albania';
country_codes_alpha_2_countries['DZ'] = 'Algeria';
country_codes_alpha_2_countries['AS'] = 'American Samoa';
country_codes_alpha_2_countries['AD'] = 'Andorra';
country_codes_alpha_2_countries['AO'] = 'Angola';
country_codes_alpha_2_countries['AI'] = 'Anguilla';
country_codes_alpha_2_countries['AQ'] = 'Antarctica';
country_codes_alpha_2_countries['AG'] = 'Antigua and Barbuda';
country_codes_alpha_2_countries['AR'] = 'Argentina';
country_codes_alpha_2_countries['AM'] = 'Armenia';
country_codes_alpha_2_countries['AW'] = 'Aruba';
country_codes_alpha_2_countries['AU'] = 'Australia';
country_codes_alpha_2_countries['AT'] = 'Austria';
country_codes_alpha_2_countries['AZ'] = 'Azerbaijan';
country_codes_alpha_2_countries['BS'] = 'Bahamas';
country_codes_alpha_2_countries['BH'] = 'Bahrain';
country_codes_alpha_2_countries['BD'] = 'Bangladesh';
country_codes_alpha_2_countries['BB'] = 'Barbados';
country_codes_alpha_2_countries['BY'] = 'Belarus';
country_codes_alpha_2_countries['BE'] = 'Belgium';
country_codes_alpha_2_countries['BZ'] = 'Belize';
country_codes_alpha_2_countries['BJ'] = 'Benin';
country_codes_alpha_2_countries['BM'] = 'Bermuda';
country_codes_alpha_2_countries['BT'] = 'Bhutan';
country_codes_alpha_2_countries['BO'] = 'Bolivia, Plurinational State of';
country_codes_alpha_2_countries['BA'] = 'Bosnia and Herzegovina';
country_codes_alpha_2_countries['BW'] = 'Botswana';
country_codes_alpha_2_countries['BV'] = 'Bouvet Island';
country_codes_alpha_2_countries['BR'] = 'Brazil';
country_codes_alpha_2_countries['IO'] = 'British Indian Ocean Territory';
country_codes_alpha_2_countries['BN'] = 'Brunei Darussalam';
country_codes_alpha_2_countries['BG'] = 'Bulgaria';
country_codes_alpha_2_countries['BF'] = 'Burkina Faso';
country_codes_alpha_2_countries['BI'] = 'Burundi';
country_codes_alpha_2_countries['KH'] = 'Cambodia';
country_codes_alpha_2_countries['CM'] = 'Cameroon';
country_codes_alpha_2_countries['CA'] = 'Canada';
country_codes_alpha_2_countries['CV'] = 'Cape Verde';
country_codes_alpha_2_countries['KY'] = 'Cayman Islands';
country_codes_alpha_2_countries['CF'] = 'Central African Republic';
country_codes_alpha_2_countries['TD'] = 'Chad';
country_codes_alpha_2_countries['CL'] = 'Chile';
country_codes_alpha_2_countries['CN'] = 'China';
country_codes_alpha_2_countries['CX'] = 'Christmas Island';
country_codes_alpha_2_countries['CC'] = 'Cocos (Keeling) Islands';
country_codes_alpha_2_countries['CO'] = 'Colombia';
country_codes_alpha_2_countries['KM'] = 'Comoros';
country_codes_alpha_2_countries['CG'] = 'Congo';
country_codes_alpha_2_countries['CD'] = 'Congo, the Democratic Republic of the';
country_codes_alpha_2_countries['CK'] = 'Cook Islands';
country_codes_alpha_2_countries['CR'] = 'Costa Rica';
country_codes_alpha_2_countries['CI'] = 'Cote d\'Ivoire / Côte d\'Ivoire';
country_codes_alpha_2_countries['HR'] = 'Croatia';
country_codes_alpha_2_countries['CU'] = 'Cuba';
country_codes_alpha_2_countries['CY'] = 'Cyprus';
country_codes_alpha_2_countries['CZ'] = 'Czech Republic';
country_codes_alpha_2_countries['DK'] = 'Denmark';
country_codes_alpha_2_countries['DJ'] = 'Djibouti';
country_codes_alpha_2_countries['DM'] = 'Dominica';
country_codes_alpha_2_countries['DO'] = 'Dominican Republic';
country_codes_alpha_2_countries['EC'] = 'Ecuador';
country_codes_alpha_2_countries['EG'] = 'Egypt';
country_codes_alpha_2_countries['SV'] = 'El Salvador';
country_codes_alpha_2_countries['GQ'] = 'Equatorial Guinea';
country_codes_alpha_2_countries['ER'] = 'Eritrea';
country_codes_alpha_2_countries['EE'] = 'Estonia';
country_codes_alpha_2_countries['ET'] = 'Ethiopia';
country_codes_alpha_2_countries['FK'] = 'Falkland Islands (Malvinas)';
country_codes_alpha_2_countries['FO'] = 'Faroe Islands';
country_codes_alpha_2_countries['FJ'] = 'Fiji';
country_codes_alpha_2_countries['FI'] = 'Finland';
country_codes_alpha_2_countries['FR'] = 'France';
country_codes_alpha_2_countries['GF'] = 'French Guiana';
country_codes_alpha_2_countries['PF'] = 'French Polynesia';
country_codes_alpha_2_countries['TF'] = 'French Southern Territories';
country_codes_alpha_2_countries['GA'] = 'Gabon';
country_codes_alpha_2_countries['GM'] = 'Gambia';
country_codes_alpha_2_countries['GE'] = 'Georgia';
country_codes_alpha_2_countries['DE'] = 'Germany';
country_codes_alpha_2_countries['GH'] = 'Ghana';
country_codes_alpha_2_countries['GI'] = 'Gibraltar';
country_codes_alpha_2_countries['GR'] = 'Greece';
country_codes_alpha_2_countries['GL'] = 'Greenland';
country_codes_alpha_2_countries['GD'] = 'Grenada';
country_codes_alpha_2_countries['GP'] = 'Guadeloupe';
country_codes_alpha_2_countries['GU'] = 'Guam';
country_codes_alpha_2_countries['GT'] = 'Guatemala';
country_codes_alpha_2_countries['GG'] = 'Guernsey';
country_codes_alpha_2_countries['GN'] = 'Guinea';
country_codes_alpha_2_countries['GW'] = 'Guinea-Bissau';
country_codes_alpha_2_countries['GY'] = 'Guyana';
country_codes_alpha_2_countries['HT'] = 'Haiti';
country_codes_alpha_2_countries['HM'] = 'Heard Island and McDonald Islands';
country_codes_alpha_2_countries['VA'] = 'Holy See (Vatican City State)';
country_codes_alpha_2_countries['HN'] = 'Honduras';
country_codes_alpha_2_countries['HK'] = 'Hong Kong';
country_codes_alpha_2_countries['HU'] = 'Hungary';
country_codes_alpha_2_countries['IS'] = 'Iceland';
country_codes_alpha_2_countries['IN'] = 'India';
country_codes_alpha_2_countries['ID'] = 'Indonesia';
country_codes_alpha_2_countries['IR'] = 'Iran, Islamic Republic of';
country_codes_alpha_2_countries['IQ'] = 'Iraq';
country_codes_alpha_2_countries['IE'] = 'Ireland';
country_codes_alpha_2_countries['IM'] = 'Isle of Man';
country_codes_alpha_2_countries['IL'] = 'Israel';
country_codes_alpha_2_countries['IT'] = 'Italy';
country_codes_alpha_2_countries['JM'] = 'Jamaica';
country_codes_alpha_2_countries['JP'] = 'Japan';
country_codes_alpha_2_countries['JE'] = 'Jersey';
country_codes_alpha_2_countries['JO'] = 'Jordan';
country_codes_alpha_2_countries['KZ'] = 'Kazakhstan';
country_codes_alpha_2_countries['KE'] = 'Kenya';
country_codes_alpha_2_countries['KI'] = 'Kiribati';
country_codes_alpha_2_countries['KP'] = 'Korea, Democratic People\'s Republic of';
country_codes_alpha_2_countries['KR'] = 'Korea, Republic of';
country_codes_alpha_2_countries['KW'] = 'Kuwait';
country_codes_alpha_2_countries['KG'] = 'Kyrgyzstan';
country_codes_alpha_2_countries['LA'] = 'Lao People\'s Democratic Republic';
country_codes_alpha_2_countries['LV'] = 'Latvia';
country_codes_alpha_2_countries['LB'] = 'Lebanon';
country_codes_alpha_2_countries['LS'] = 'Lesotho';
country_codes_alpha_2_countries['LR'] = 'Liberia';
country_codes_alpha_2_countries['LY'] = 'Libyan Arab Jamahiriya';
country_codes_alpha_2_countries['LI'] = 'Liechtenstein';
country_codes_alpha_2_countries['LT'] = 'Lithuania';
country_codes_alpha_2_countries['LU'] = 'Luxembourg';
country_codes_alpha_2_countries['MO'] = 'Macao';
country_codes_alpha_2_countries['MK'] = 'Macedonia, the former Yugoslav Republic of';
country_codes_alpha_2_countries['MG'] = 'Madagascar';
country_codes_alpha_2_countries['MW'] = 'Malawi';
country_codes_alpha_2_countries['MY'] = 'Malaysia';
country_codes_alpha_2_countries['MV'] = 'Maldives';
country_codes_alpha_2_countries['ML'] = 'Mali';
country_codes_alpha_2_countries['MT'] = 'Malta';
country_codes_alpha_2_countries['MH'] = 'Marshall Islands';
country_codes_alpha_2_countries['MQ'] = 'Martinique';
country_codes_alpha_2_countries['MR'] = 'Mauritania';
country_codes_alpha_2_countries['MU'] = 'Mauritius';
country_codes_alpha_2_countries['YT'] = 'Mayotte';
country_codes_alpha_2_countries['MX'] = 'Mexico';
country_codes_alpha_2_countries['FM'] = 'Micronesia, Federated States of';
country_codes_alpha_2_countries['MD'] = 'Moldova, Republic of';
country_codes_alpha_2_countries['MC'] = 'Monaco';
country_codes_alpha_2_countries['MN'] = 'Mongolia';
country_codes_alpha_2_countries['ME'] = 'Montenegro';
country_codes_alpha_2_countries['MS'] = 'Montserrat';
country_codes_alpha_2_countries['MA'] = 'Morocco';
country_codes_alpha_2_countries['MZ'] = 'Mozambique';
country_codes_alpha_2_countries['MM'] = 'Myanmar';
country_codes_alpha_2_countries['NA'] = 'Namibia';
country_codes_alpha_2_countries['NR'] = 'Nauru';
country_codes_alpha_2_countries['NP'] = 'Nepal';
country_codes_alpha_2_countries['NL'] = 'Netherlands';
country_codes_alpha_2_countries['AN'] = 'Netherlands Antilles';
country_codes_alpha_2_countries['NC'] = 'New Caledonia';
country_codes_alpha_2_countries['NZ'] = 'New Zealand';
country_codes_alpha_2_countries['NI'] = 'Nicaragua';
country_codes_alpha_2_countries['NE'] = 'Niger';
country_codes_alpha_2_countries['NG'] = 'Nigeria';
country_codes_alpha_2_countries['NU'] = 'Niue';
country_codes_alpha_2_countries['NF'] = 'Norfolk Island';
country_codes_alpha_2_countries['MP'] = 'Northern Mariana Islands';
country_codes_alpha_2_countries['NO'] = 'Norway';
country_codes_alpha_2_countries['OM'] = 'Oman';
country_codes_alpha_2_countries['PK'] = 'Pakistan';
country_codes_alpha_2_countries['PW'] = 'Palau';
country_codes_alpha_2_countries['PS'] = 'Palestinian Territory, Occupied';
country_codes_alpha_2_countries['PA'] = 'Panama';
country_codes_alpha_2_countries['PG'] = 'Papua New Guinea';
country_codes_alpha_2_countries['PY'] = 'Paraguay';
country_codes_alpha_2_countries['PE'] = 'Peru';
country_codes_alpha_2_countries['PH'] = 'Philippines';
country_codes_alpha_2_countries['PN'] = 'Pitcairn';
country_codes_alpha_2_countries['PL'] = 'Poland';
country_codes_alpha_2_countries['PT'] = 'Portugal';
country_codes_alpha_2_countries['PR'] = 'Puerto Rico';
country_codes_alpha_2_countries['QA'] = 'Qatar';
country_codes_alpha_2_countries['RE'] = 'Reunion / Réunion';
country_codes_alpha_2_countries['RO'] = 'Romania';
country_codes_alpha_2_countries['RU'] = 'Russian Federation';
country_codes_alpha_2_countries['RW'] = 'Rwanda';
country_codes_alpha_2_countries['BL'] = 'Saint Barthélemy';
country_codes_alpha_2_countries['SH'] = 'Saint Helena, Ascension and Tristan da Cunha';
country_codes_alpha_2_countries['KN'] = 'Saint Kitts and Nevis';
country_codes_alpha_2_countries['LC'] = 'Saint Lucia';
country_codes_alpha_2_countries['MF'] = 'Saint Martin (French part)';
country_codes_alpha_2_countries['PM'] = 'Saint Pierre and Miquelon';
country_codes_alpha_2_countries['VC'] = 'Saint Vincent and the Grenadines';
country_codes_alpha_2_countries['WS'] = 'Samoa';
country_codes_alpha_2_countries['SM'] = 'San Marino';
country_codes_alpha_2_countries['ST'] = 'Sao Tome and Principe';
country_codes_alpha_2_countries['SA'] = 'Saudi Arabia';
country_codes_alpha_2_countries['SN'] = 'Senegal';
country_codes_alpha_2_countries['RS'] = 'Serbia';
country_codes_alpha_2_countries['SC'] = 'Seychelles';
country_codes_alpha_2_countries['SL'] = 'Sierra Leone';
country_codes_alpha_2_countries['SG'] = 'Singapore';
country_codes_alpha_2_countries['SK'] = 'Slovakia';
country_codes_alpha_2_countries['SI'] = 'Slovenia';
country_codes_alpha_2_countries['SB'] = 'Solomon Islands';
country_codes_alpha_2_countries['SO'] = 'Somalia';
country_codes_alpha_2_countries['ZA'] = 'South Africa';
country_codes_alpha_2_countries['GS'] = 'South Georgia and the South Sandwich Islands';
country_codes_alpha_2_countries['ES'] = 'Spain';
country_codes_alpha_2_countries['LK'] = 'Sri Lanka';
country_codes_alpha_2_countries['SD'] = 'Sudan';
country_codes_alpha_2_countries['SR'] = 'Suriname';
country_codes_alpha_2_countries['SJ'] = 'Svalbard and Jan Mayen';
country_codes_alpha_2_countries['SZ'] = 'Swaziland';
country_codes_alpha_2_countries['SE'] = 'Sweden';
country_codes_alpha_2_countries['CH'] = 'Switzerland';
country_codes_alpha_2_countries['SY'] = 'Syrian Arab Republic';
country_codes_alpha_2_countries['TW'] = 'Taiwan, Province of China';
country_codes_alpha_2_countries['TJ'] = 'Tajikistan';
country_codes_alpha_2_countries['TZ'] = 'Tanzania, United Republic of';
country_codes_alpha_2_countries['TH'] = 'Thailand';
country_codes_alpha_2_countries['TL'] = 'Timor-Leste';
country_codes_alpha_2_countries['TG'] = 'Togo';
country_codes_alpha_2_countries['TK'] = 'Tokelau';
country_codes_alpha_2_countries['TO'] = 'Tonga';
country_codes_alpha_2_countries['TT'] = 'Trinidad and Tobago';
country_codes_alpha_2_countries['TN'] = 'Tunisia';
country_codes_alpha_2_countries['TR'] = 'Turkey';
country_codes_alpha_2_countries['TM'] = 'Turkmenistan';
country_codes_alpha_2_countries['TC'] = 'Turks and Caicos Islands';
country_codes_alpha_2_countries['TV'] = 'Tuvalu';
country_codes_alpha_2_countries['UG'] = 'Uganda';
country_codes_alpha_2_countries['UA'] = 'Ukraine';
country_codes_alpha_2_countries['AE'] = 'United Arab Emirates';
country_codes_alpha_2_countries['GB'] = 'United Kingdom';
country_codes_alpha_2_countries['US'] = 'United States';
country_codes_alpha_2_countries['UM'] = 'United States Minor Outlying Islands';
country_codes_alpha_2_countries['UY'] = 'Uruguay';
country_codes_alpha_2_countries['UZ'] = 'Uzbekistan';
country_codes_alpha_2_countries['VU'] = 'Vanuatu';
country_codes_alpha_2_countries['VE'] = 'Venezuela, Bolivarian Republic of';
country_codes_alpha_2_countries['VN'] = 'Viet Nam';
country_codes_alpha_2_countries['VG'] = 'Virgin Islands, British';
country_codes_alpha_2_countries['VI'] = 'Virgin Islands, U.S.';
country_codes_alpha_2_countries['WF'] = 'Wallis and Futuna';
country_codes_alpha_2_countries['EH'] = 'Western Sahara';
country_codes_alpha_2_countries['YE'] = 'Yemen';
country_codes_alpha_2_countries['ZM'] = 'Zambia';
country_codes_alpha_2_countries['ZW'] = 'Zimbabwe';
