include ../../make.env

PACKAGE_DIR=$(BIN_PACKAGE_DIR)/implementation

all:
	$(MAKE) -C tpl_cgi

install: dummy
	$(MAKE) -C tpl_cgi install

clean: dummy
	$(MAKE) -C tpl_cgi clean

uninstall: dummy
	$(MAKE) -C tpl_cgi uninstall

dummy:
