<?php
$translator = \Zend_Registry::get('container')->getService('translator');
$this->headLink()->appendStylesheet( $this->baseUrl('admin-style/admin_stylesheet_context.css') );
$this->headStyle()->appendStyle( "
	.context-block{ width: auto; float: none; height: 440px }
	.context-list-results{ height: 405px; margin-top: 10px; }
	.context-list{ margin: 15px; }
	.context-content{ height: 500px }
	.context-content{ height: 490px }
	.context-item{ width: 525px !important; }
	.toolbar{ padding: 0 !important; }
	.save-button-bar,
	.select-playlist-bar {width: 50%; overflow: hidden; margin:0; float: left;}
	.select-playlist-bar select:{ width: 100% }
	#context-box{ width: auto; height: 520px }
	.iframe .content { margin: 0; }
	body > .content { margin: 0; }
" );
$t = array
(
	'view-article' => $translator->trans('View article', array(), 'articles'),
	'drag-here' => $translator->trans('Drag here to add to list', array(), 'articles'),
	'playlist-updated' => $translator->trans('List updated.', array(), 'articles'),
    'list-saved' => $translator->trans('List saved', array(), 'articles'),
	'list-save-failed' => $translator->trans('Could not save the list', array(), 'articles'),
    'delete' => $translator->trans('Delete'),
    'cancel' => $translator->trans('Cancel'),
	'please-select-playlist' => $translator->trans('Please select a list', array(), 'articles'),
    'item-exists' => $translator->trans('Item already exists in the list', array(), 'articles')
);
$dataUrl = $this->url( array
(
	'action' => 'list-data',
	'controller' => 'playlist',
	'module' => 'admin',
    'id' => '%d',
	'format' => 'json'
), null, true, false);
$saveUrl = $this->url( array
(
	'action' => 'save-data',
	'controller' => 'playlist',
	'module' => 'admin',
	'format' => 'json'
), null, true, false);

$articleName = $this->article->getName();
$articleName = addslashes($articleName);

$js = <<<JS

function toggleDragZonePlaceHolder()
{
	if($('#context_list').find('.context-item').html() != null) {
	    $('#drag-here-to-add-to-list').css('display', 'none');
	} else {
		$('#drag-here-to-add-to-list').css('display', 'block');
	}
}
function fnLoadContextList(data)
{
	$("#context_list").html('');
	if(data.code == 200) {
	    var items = data.items;
	    for(i = 0; i < items.length; i++) {
	        var item = items[i];
	        appendItemToContextList(item.articleId, item.date.date, item.title);
	    }
	}
	toggleDragZonePlaceHolder();
}
function loadContextList(playlistId)
{
	var relatedArticles = $('#context_list').sortable( "serialize");
    var aoData = new Array();
    var items = new Array('1_1','0_0');
    aoData.push("context_box_load_list");
    aoData.push(items);
    aoData.push({ 'playlistId': playlistId });
    callServer('{$dataUrl}'.replace(/%d/, playlistId), aoData, fnLoadContextList, true);
}
function appendItemToContextList(article_id, article_date, article_title, prepend)
{
	var newItem = $('<li class="item" id="'+article_id+'">'+
		'<input type="hidden" name="article-id[]" value="'+article_id+'" />'+
    	'<div class="context-item">'+
        '<div class="context-drag-topics"><a href="#" title="drag to sort"></a></div>'+
        '<div class="context-item-header">'+
        '<div class="context-item-date">'+article_date+'</div>'+
        '<a href="#" class="view-article" style="display: none" ' +
        	'onClick="viewArticle($(this).parent(\'div\').parent(\'div\').parent(\'li.item\').attr(\'id\'));">{$t['view-article']}</a>'+
        '</div>'+
        '<a href="#" class="corner-button" style="display: block" '+
        	'onClick="$(this).parent(\'div\').parent(\'li.item\').remove();toggleDragZonePlaceHolder();"><span class="ui-icon ui-icon-closethick"></span></a>'+
        '<div class="context-item-summary"></div>'+
        '</div>'+
        '</li>');
    newItem.find('.context-item-summary').text(article_title);

	if( typeof prepend != 'undefined' )
    	$("#context_list").prepend( newItem );
    else
    	$("#context_list").append( newItem );

    closeArticle();
}
function deleteContextList()
{
	$("#context_list").html('<div id="drag-here-to-add-to-list" style="">{$t['drag-here']}</div>');
}
function removeFromContext(param)
{
    $("#"+param).remove();
}

function fnPreviewArticle(data)
{
	if(data.code == 200) {
		$("#preview-article-date").val(data.date);
		$("#preview-article-title").html(data.title);
		$("#preview-article-body").html(data.body);
		$(".context-block.context-list").css("display","none");
	    $(".context-block.context-article").css("display","block");
	}
}

function clearActiveArticles() {
	$('.item-active').each( function () {
		$(this).removeClass('item-active');
	});
}

function viewArticle(param)
{
	 clearActiveArticles();
	 $("#"+param).addClass('item-active');
	 var relatedArticles = $('#context_list').sortable( "serialize");
	 var aoData = new Array();
	 var items = new Array('1_1','0_0');

     aoData.push("context_box_preview_article");
     aoData.push(items);
     aoData.push({
         'articleId': param,
     });
    $("#preview-article-id").val(param);
    callServer(['ArticleList', 'doAction'], aoData, fnPreviewArticle);
}

function closeArticle()
{
    $(".context-block.context-list").css("display","block");
    $(".context-block.context-article").css("display","none");
}

function popup_close()
{
	try
	{
        if (parent.$.fancybox.reload) {
            parent.$.fancybox.message = '{$t['list-saved']}';
        }
        parent.$.fancybox.close();
    }
    catch (e) {window.close();}
}

function popup_save()
{
	var playlistId = $('#playlists').val();
	if( !playlistId ) {
		flashMessage('{$t['please-select-playlist']}', 'error', false);
		return false;
	}
	var articles = [];
	var hasArticle = false;
	$('#context-list-form').find('input[type=hidden]').each(function()
	{
		articles.push($(this).val());
		if ('{$this->article->getId()}' == $(this).val()) {
			hasArticle = true;
		}
	});
    var aoData =
    {
        'articles': articles,
        'id': $('#playlists').val()
    };

    var saveCallback = function(data)
    {
    	var playlistId = $('#playlists').val();

		if (hasArticle && parent.$('#added-to-playlists [playlist-id='+playlistId+']').length == 0)
		{
			var newItem = $('<li />').attr('playlist-id', playlistId)
							.text($("#playlists option[value='"+playlistId+"']").text())
			parent.$("#added-to-playlists").append(newItem);
    	}

    	if (!hasArticle)
			parent.$('#added-to-playlists [playlist-id='+playlistId+']').remove();

    	if (parent.$('#added-to-playlists > *').length == 0)
			parent.$('#playlist-default-message').show();
		else
			parent.$('#playlist-default-message').hide();

    	fnSaveCallback.call(this, data);
    }

    callServer('{$saveUrl}', aoData, saveCallback, true );
}

function popup_add()
{
	var playlistId = $('#playlists').val();
	if( !playlistId ) {
		flashMessage('{$t['please-select-playlist']}', 'error', false);
		return false;
	}
	if( !$('#context_list').find('input:hidden[value={$this->article->getId()}]').length )
		appendItemToContextList( '{$this->article->getId()}', '{$this->article->getDate()->format('d.m.Y H:i:s')}', '{$articleName}', true );
	else
		flashMessage('{$t['item-exists']}', 'error', false);
}

function fnSaveCallback(data)
{
	if (typeof data['error'] != 'undefined' && data['error'])
	{
		var flash = flashMessage('{$t['list-save-failed']}', null, false);
		return false;
	}
	var flash = flashMessage('{$t['list-saved']}', null, false);
}
$(function()
{
	$('#playlists').change( function()
	{
		loadContextList($(this).val());
	});
	$('#context_list').sortable({ items : '> li' }).disableSelection();
});

JS;

$this->headScript()->appendScript( $js, "text/javascript" );

?>



<div class="content">
	<div id="context-box">
		<div class="toolbar">

			<div class="select-playlist-bar">
				<form autocomplete="off">
    				<select id="playlists" style="font-size:14px;padding:2px;border:none;width:250px">
    					<option style="color: #aaa" value="" selected="selected"><?php echo $translator->trans('Select a list', array(), 'articles') ?></option>
        	            <?php foreach ($this->playlists as $pl) : ?>
    						<option value="<?php echo $pl->getId() ?>"><?php echo $pl->getName() ?></option>
            	        <?php endforeach; ?>
    				</select>
        		</form>
			</div>

			<div class="save-button-bar">

				<input type="submit" name="add"
					value="<?php echo $translator->trans('Add to list', array(), 'articles'); ?>" class="default-button" onclick="popup_add();"
					id="context_button_save">

				<input type="submit" name="cancel"
					value="<?php echo $translator->trans('Close'); ?>" class="default-button" onclick="popup_close();"
					id="context_button_close">

				<input type="submit" name="save"
					value="<?php echo $translator->trans('Save'); ?>" class="save-button-small" onclick="popup_save();"
					id="context_button_save">
			</div>
		</div>
		<div class="context-content">
    		<div class="context-block context-list">
    			<h3><?php echo $translator->trans('Featured Articles', array(), 'articles'); ?></h3>
    			<div class="context-list-results">
    					<form id="context-list-form">
        					<ul id="context_list" style="margin:0; padding: 0; display:block; overflow-y:auto; overflow-x:hidden; padding: 0; width: 100%; height: 100%">

        					</ul>
    					</form>
    			</div>
    		</div>

    		<div class="context-block context-article" style="display: none">
    			<div class="save-button-bar"><input type="submit"
    				name="add-this-article" value="Add this article"
    				class="save-button-small" onclick="appendItemToContextList($('#preview-article-id').val(), $('#preview-article-date').val(), $('#preview-article-title').html()); toggleDragZonePlaceHolder(); clearActiveArticles();" id="context_button_add"> <input
    				type="submit" name="close" value="Close" class="default-button"
    				onclick="closeArticle(); clearActiveArticles();" id="context_button_close_article">
    			</div>

    			<div class="context-article-preview" style="overflow-y:auto; height:500px;">
    				<input id="preview-article-date" type="hidden" />
    				<input id="preview-article-id" type="hidden" />
    				<h3 id="preview-article-title"></h3>
    				<div id="preview-article-body" style="color: #444444"></div>
    			</div>
    		</div>
    	</div>
    </div>
</div>



