<?php 
$translator = \Zend_Registry::get('container')->getService('translator');
$this->placeholder( 'title' )->set( $translator->trans( 'Featured Article Lists' , array(), 'articles') ); 
?>
<div class="actions">
	<form autocomplete="off">
    <ul class="navigation">
        <li><a class="add" href="#" id="add-ctrl"><?php echo $translator->trans('Add list', array(), 'articles') ?></a></li>
        <!-- li><a class="copy" href="#" id="duplicate-ctrl"><?php echo $translator->trans('Duplicate list', array(), 'articles') ?></a></li-->
        <li>
			<select id="playlists" style="font-size:14px;padding:2px;border:none;">
            	<option style="color: #aaa" value="" selected="selected"><?php echo $translator->trans('Select a list', array(), 'articles') ?></option>
                <?php foreach ($this->playlists as $pl) : ?>
            		<option value="<?php echo $pl->getId() ?>"><?php echo $pl->getName() ?></option>
                <?php endforeach; ?>
            </select>
        </li>
    </ul>
    </form>
</div>


<iframe id="playlist-display" frameborder="0" style="width:1220px; height:750px"></iframe>

<?php

$t = array("cancel" => $translator->trans('Cancel'), "delete" => $translator->trans('Delete'));

$js = <<<JS

$(function()
{
	function loadArticleList(articleId)
	{
    	var aoData = new Array();
    	var items = new Array('1_1','0_0');
    	aoData.push("context_box_load_list");
    	aoData.push(items);
    	aoData.push({ 'articleId': articleId });
    	callServer(['ArticleList', 'doAction'], aoData, fnLoadArticleList);
	}
	function fnLoadArticleList(data)
	{
		var items = data.items;
		if (items.length > 0)
		{
			var injectHtml = '<ul class="block-list">';
	    	for (var i=0; i<items.length; i++)
	    	{
	        	var item = items[i];
	        	injectHtml += '<li>'+item.title+'</li>';
	    	}
	    	injectHtml += '</ul>';
	    	$("#contextBoxArticlesList").html(injectHtml);
		}
		else
		{
			$("#contextBoxArticlesList").html('');
		}
	}

	function openPlaylistDialog(id)
	{
		var url = '{$this->url(array('action' => 'popup', 'controller' => 'playlist', 'module' => 'admin', 'id' => '{{id}}'), null, null, false)}'.replace('{{id}}', id);
		/*$.fancybox
    	({
    		showCloseButton : false,
        	width: 1220,
    	    height : 680,
        	scrolling : 'auto',
        	href : url,
        	type : 'iframe'
    	})*/
    	$('#playlist-display').attr( 'src', url );
	}

	$('#playlists').change( function()
	{
		if ($(this).val() == '') return;
		openPlaylistDialog($(this).val());
		$(this).val('');
	});

	$('#add-ctrl').click( function()
	{
		openPlaylistDialog('');
	});
});
function triggerSelectClick()
{
	$('#playlists').change();
}
JS;
$this->headScript()->appendScript($js, 'text/javascript');
?>
