<?php $this->placeholder( 'title' )->set( getGS( 'Article playlists' ) ); ?>
<div class="actions">
    <ul class="navigation">
        <li><a class="add" href="#" id="add-ctrl"><?php echo getGS('Add playlist') ?></a></li>
        <!-- li><a class="copy" href="#" id="duplicate-ctrl"><?php echo getGS('Duplicate playlist') ?></a></li-->
        <li><a class="remove" href="#" id="remove-ctrl"><?php echo getGS('Remove playlist') ?></a></li>
    </ul>
</div>

<select id="playlists" style="font-size:16px;padding:5px;">
	<option style="color: #aaa" value=""><?php echo getGS('Select a playlist') ?></option>
    <?php foreach ($this->playlists as $pl) : ?>
		<option value="<?php echo $pl->getId() ?>"><?php echo $pl->getName() ?></option>
    <?php endforeach; ?>
</select>

<div id="dialog-confirm" style="display:none" title="<?php echo getGS('Remove playlist') ?>">
	<p><?php echo getGS('Are you sure you want to delete this playlist?') ?></p>
</div>

<?php

$t = array("cancel" => getGS('Cancel'), "delete" => getGS('Delete'));
$deleteUrl = $this->url( array
(
	'action' => 'delete',
	'controller' => 'playlist',
	'module' => 'admin',
	'format' => 'json'
), null, null, false);
$js = <<<JS

$(function()
{
	function loadArticleList(articleId)
	{
    	var aoData = new Array();
    	var items = new Array('1_1','0_0');
    	aoData.push("context_box_load_list");
    	aoData.push(items);
    	aoData.push({ 'articleId': articleId });
    	callServer(['ArticleList', 'doAction'], aoData, fnLoadArticleList);
	}
	function fnLoadArticleList(data)
	{
		var items = data.items;
		if (items.length > 0)
		{
			var injectHtml = '<ul class="block-list">';
	    	for (var i=0; i<items.length; i++)
	    	{
	        	var item = items[i];
	        	injectHtml += '<li>'+item.title+'</li>';
	    	}
	    	injectHtml += '</ul>';
	    	$("#contextBoxArticlesList").html(injectHtml);
		}
		else
		{
			$("#contextBoxArticlesList").html('');
		}
	}

	function openPlaylistDialog(id)
	{
		var url = '{$this->url(array('action' => 'popup', 'controller' => 'playlist', 'module' => 'admin', 'id' => '{{id}}'), null, null, false)}'.replace('{{id}}', id);
		$.fancybox
    	({
    		showCloseButton : false,
        	width: 1220,
    	    height : 680,
        	scrolling : 'auto',
        	href : url,
        	type : 'iframe'
    	})
	}

	$('#playlists').change( function()
	{
		if ($(this).val() == '') return;
		openPlaylistDialog($(this).val());
	});

	$('#add-ctrl').click( function()
	{
		openPlaylistDialog('');
	});

	$( "#dialog-confirm" ).dialog
	({
		resizable: false,
		height:140,
		modal: true,
		autoOpen : false,
		buttons:
		{
			"{$t['delete']}" : function() {
				callServer('{$deleteUrl}', {id:$('#playlists').val()}, function(){ document.location.reload(); }, true );
				$( this ).dialog( "close" );
			},
			"{$t['cancel']}" : function() {
				$( this ).dialog( "close" );
			}
		}
	});

	$('#remove-ctrl').click(function(){ $( "#dialog-confirm" ).dialog('open') });
});

JS;
$this->headScript()->appendScript($js, 'text/javascript');
?>