<?php
regGS("Name<BR><SMALL>(click to see issues)</SMALL>", "Name");
regGS("Delete publication $1", "Publikation $1 löschen");
regGS("No publications.", "Keine Publikationen");
regGS("Default Site Alias", "");
regGS("URL Type", "");
regGS("Country<BR><SMALL>(click to edit)</SMALL>", "Land (bearbeiten, bitte anklicken)");
regGS("Delete entry $1", "Eintrag $1 löschen");
regGS("No entries defined.", "Keine Einträge definiert");
regGS("Back to publication", "");
regGS("Configure publication", "");
regGS("You do not have the right to edit publication information.", "Keine Berechtigung Info der Publikation zu ändern");
regGS("General attributes", "");
regGS("Subscriptions defaults", "");
regGS("Countries defaults", "");
regGS("Changing publication information", "Info der Publikation wird geändert");
regGS("You do not have the right to change publication information.", "Keine Rechte Info der Publikation zu ändern");
regGS("The publication $1 has been successfuly updated.", "Publikation $1 wurde geändert");
regGS("Publication $1 changed", "Publikation $1 wurde geändert");
regGS("The publication information could not be updated.", "Die Info der Publikations konnte nicht verändert werden");
regGS("Please check if another publication with the same or the same site name does not already exist.", "Bitte überprüfen, ob eine Publikation mit dem selben Namen schon existiert");
regGS("Delete publication", "Publikation löschen");
regGS("You do not have the right to delete publications.", "Keine Berechtigung Publikationen zu löschen");
regGS("Are you sure you want to delete the publication $1?", "Sicher, dass Publikation $1 gelöscht werden soll?");
regGS("Deleting publication", "Publikation wird gelöscht");
regGS("There are $1 subscription(s) left.", "$1 Abonement(s) noch vorhanden");
regGS("The publication $1 has been deleted.", "Publikation $1 wurde gelöscht");
regGS("The publication $1 could not be deleted.", "Publikation $1 konnte nicht gelöscht werden");
regGS("Publication $1 deleted", "Publikation $1 wurde gelöscht");
regGS("Adding new publication", "Neue Publikatin hinzufügen");
regGS("The publication could not be added.", "Publikation konnte nicht hinzugefügt werden");
regGS("Select the publication", "Publikation auswählen");
regGS("Add new country default subscription time", "Neue Länderstandardzeit für Abonoments hinzufügen");
regGS("You do not have the right to manage publications.", "Keine Berechtigung, die Publikation zu verändern");
regGS("Please check if another entry with the same country code exists already.", "");
regGS("Adding new country default subscription time", "Hinzufügen von für Abonomentstandardzeit ");
regGS("You must select a country.", "Es muss ein Land gewählt werden");
regGS("The default subscription time for $1 has been added.", "Abonomentstandardzeit für $1 wurde erfolgreich hinzugefügt");
regGS("The default subscription time for country $1 could not be added.", "Abonomentstandardzeit für das Land $1 konnte nicht hinzugefügt werden");
regGS("Change subscription default time", "Abonomentstandardzeit  ändern");
regGS("No default time entry for that country.", "Keine Standardzeiteintragung für dieses Land");
regGS("Changing default subscription time", "Ändern der Abonomentstandardzeit  ");
regGS("The default subscription time for $1 has been successfuly updated.", "Abonomentstandardzeit  für $1 wurde erfolgreich aktualisiert");
regGS("Default subscription time for $1 changed", "Abonomentstandardzeit  für $1 hat sich geändert");
regGS("The default subscription time could not be updated.", "Abonomentstandardzeit  konnte nicht aktualisiert werden");
regGS("Delete subscription default time", "Abonomentstandardzeit  löschen");
regGS("Are you sure you want to delete the subscription default time for $1?", "Sicher, die Abonomentstandardzeit  für $1 zu löschen?");
regGS("Deleting subscription default time", "Löschen von Abonomentstandardzeit  ");
regGS("The subscription default time for $1 has been deleted.", "Abonomentstandardzeit  für $1 wurde gelöscht");
regGS("The default subscription time for $1 could not be deleted.", "Abonomentstandardzeit  für $1 konnte nicht gelöscht werden");
regGS("Subscription default time for $1 deleted", "Abonomentstandardzeit  für $1 gelöscht");
regGS("Name<BR><SMALL>(click to select the publication)</SMALL>", "Name (Publikation auswählen, bitte anklicken)");
regGS("The publication $1 has been successfuly added.", "Publikation $1 wurde hinzugefügt");
regGS("Publication $1 added", "Publikation $1 wurde hinzugefügt");
regGS("Add new alias", "");
regGS("Alias (click to edit)", "");
regGS("Edit aliases", "");
regGS("Publication Aliases", "");
regGS("Back to aliases", "");
regGS("Adding new alias", "");
regGS("The site alias $1 has been added to publication $2.", "");
regGS("The site alias $1 could not be added.", "");
regGS("Another alias with the same name exists already.", "");
regGS("Edit alias", "");
regGS("Editing alias", "");
regGS("The site alias for publication $1 has been modified to $2.", "");
regGS("The site alias $1 could not be modified.", "");
regGS("Delete alias", "");
regGS("No such alias.", "");
regGS("Are you sure you want to delete the alias $1?", "");
regGS("Deleting alias", "");
regGS("The alias $1 could not be deleted.", "");
regGS("The alias $1 has been deleted from publication $2.", "");
regGS("$1 is the default publication alias, it can not be deleted.", "");
regGS("You do not have the right to add publications.", "");
regGS("There are $1 issue(s) left.", "");
regGS("No such country.", "");
regGS("Change publication information", "Information der Publikation ändern");
?>