<?php
regGS("Name<BR><SMALL>(click to see issues)</SMALL>", "Název publikace (klikněte pro náhled vydání)");
regGS("Delete publication $1", "Smazat publikaci $1");
regGS("No publications.", "Žádné publikace");
regGS("Country<BR><SMALL>(click to edit)</SMALL>", "Země (klikněte pro editaci)");
regGS("Delete entry $1", "Smazat položku $1");
regGS("No entries defined.", "Žádné vymezené položky");
regGS("Change publication information", "Změnit informace o publikaci");
regGS("You do not have the right to edit publication information.", "Nemáte právo měnit informace o publikaci");
regGS("Changing publication information", "Změna informací o publikaci");
regGS("You do not have the right to change publication information.", "Nemáte práva změnit informace o publikaci");
regGS("The publication $1 has been successfuly updated.", "Publikace $1 byla úspěšné obnovena");
regGS("Publication $1 changed", "Publikace $1 změněna");
regGS("The publication information could not be updated.", "Publikace nemohla být obnovena");
regGS("Please check if another publication with the same or the same site name does not already exist.", "Zkontrolujte, zda publikace se stejným názvem již neexistuje.");
regGS("Delete publication", "Smazat publikaci");
regGS("You do not have the right to delete publications.", "Nemáte právo mazat publikace");
regGS("Are you sure you want to delete the publication $1?", "Určitě chcete smazat publikaci $1?");
regGS("Deleting publication", "Mazání publikace");
regGS("There are $1 subscription(s) left.", "Zbývá předplatné $1");
regGS("The publication $1 has been deleted.", "Publikace $1 byla smazána");
regGS("The publication $1 could not be deleted.", "Publikace $1 nemohla být smazána");
regGS("Publication $1 deleted", "Publikace $1 byla smazána");
regGS("Adding new publication", "Přidat novou publikaci");
regGS("The publication could not be added.", "Publikace nemohla být přidána");
regGS("Select the publication", "Vyberte publikaci");
regGS("Add new country default subscription time", "Přidat předplatné období pro novou zemi");
regGS("You do not have the right to manage publications.", "Nemáte právo spravovat publikace");
regGS("Adding new country default subscription time", "Přidání předplatného období pro novou zemi");
regGS("You must select a country.", "Vyberte zemi");
regGS("The default subscription time for $1 has been added.", "Předplatné období $1 bylo úspěšně přidáno");
regGS("The default subscription time for country $1 could not be added.", "Předplatné období pro $1 nemohlo být přidáno");
regGS("Change subscription default time", "Změnit předplatné období");
regGS("No default time entry for that country.", "Časová jednotka pro tuto zemi nebyla zadána");
regGS("Changing default subscription time", "Změna předplatného období");
regGS("The default subscription time for $1 has been successfuly updated.", "Předplatné období pro $1 bylo úspěšně obnoveno");
regGS("Default subscription time for $1 changed", "Předplatné období pro $1 bylo změněno");
regGS("The default subscription time could not be updated.", "Předplatné období nemohlo být obnoveno");
regGS("Delete subscription default time", "Smazat předplatné období");
regGS("Are you sure you want to delete the subscription default time for $1?", "Určitě chcete smazat předplatné období pro $1?");
regGS("Deleting subscription default time", "Mazání předplatného období");
regGS("The subscription default time for $1 has been deleted.", "Předplatné období pro $1 bylo smazáno");
regGS("The default subscription time for $1 could not be deleted.", "Předplatné období pro $1 nemohlo být smazáno");
regGS("Subscription default time for $1 deleted", "Předplatné období pro $1 bylo smazáno");
regGS("Name<BR><SMALL>(click to select the publication)</SMALL>", "Název (klikněte pro výběr publikace)");
regGS("The publication $1 has been successfuly added.", "Publikace $1 byla úspěšně přidána");
regGS("Publication $1 added", "Publikace $1 byla přidána");
?>