<?
regGS("Name<BR><SMALL>(click to see issues)</SMALL>","Название<BR><SMALL>(щелкните для просмотра выпуска)</SMALL>:ru");
regGS("Delete publication $1","Удалить публикацию $1:ru");
regGS("No publications.","Нет публикаций.:ru");
regGS("Country<BR><SMALL>(click to edit)</SMALL>","Страна<BR><SMALL>(щелкните для редактирования)</SMALL>:ru");
regGS("Delete entry $1","Удалить запись$1:ru");
regGS("No entries defined.","Нет определенных записей.:ru");
regGS("Change publication information","Изменить информацию публикации:ru");
regGS("You do not have the right to edit publication information.","Вы не имеете права редактирования информации публикации.:ru");
regGS("Changing publication information","Изменение информации публикации:ru");
regGS("You do not have the right to change publication information.","Вы не имеете права изменять информацию публикации.:ru");
regGS("The publication $1 has been successfuly updated.","Публикация $1 была успешно обновлена.:ru");
regGS("Publication $1 changed","Публикация $1 изменена:ru");
regGS("The publication information could not be updated.","Не удалось обновить информацию публикации.:ru");
regGS("Please check if another publication with the same or the same site name does not already exist.","Пожалуйста проверьте, не существует ли уже другая публикация с этим именем или другой сайт с этим именем.:ru");
regGS("Delete publication","Удалить публикацию:ru");
regGS("You do not have the right to delete publications.","Вы не имеете права удалять публикации.:ru");
regGS("Are you sure you want to delete the publication $1?","Вы уверены, что хотите удалить публикацию $1?:ru");
regGS("Deleting publication","Удаление публикации:ru");
regGS("There are $1 image(s) left.","Осталось картинок $1.:ru");
regGS("There are $1 subscription(s) left.","Осталось подписок: $1.:ru");
regGS("The publication $1 has been deleted.","Публикация $1 была удалена.:ru");
regGS("The publication $1 could not be deleted.","Не удалось удалить публикацию $1.:ru");
regGS("Publication $1 deleted","Публикация $1 удалена:ru");
regGS("Adding new publication","Добавление новой публикации:ru");
regGS("The publication could not be added.","Не удалось добавить публикацию.:ru");
regGS("Add new country default subscription time","Добавить время подписки по умолчанию для новой страны:ru");
regGS("You do not have the right to manage publications.","Вы не имеете права управления публикацией.:ru");
regGS("Adding new country default subscription time","Добавление времени подписки по умолчанию для новой страны:ru");
regGS("You must select a country.","Вы должны выбрать страну.:ru");
regGS("The default subscription time for $1 has been added.","Время подписки по умолчанию для $1 успешно добавлено.:ru");
regGS("The default subscription time for country $1 could not be added.","Не удалось добавить время подписки по умолчанию для страны $1.:ru");
regGS("Change subscription default time","Изменение времени подписки по умолчанию:ru");
regGS("No default time entry for that country.","Нет записи о времени по умолчанию для этой страны.:ru");
regGS("Changing default subscription time","Изменение времени подписки по умолчанию:ru");
regGS("The default subscription time for $1 has been successfuly updated.","Время подписки по умолчанию для $1 было успешно обновлено.:ru");
regGS("Default subscription time for $1 changed","Время подписки по умолчанию для $1 изменено:ru");
regGS("The default subscription time could not be updated.","Не удалось обновить время подписки по умолчанию.:ru");
regGS("Delete subscription default time","Удалить время подписки по умолчанию:ru");
regGS("Are you sure you want to delete the subscription default time for $1?","Вы уверены, что хотите удалить время подпискипо умолчанию для $1?:ru");
regGS("Deleting subscription default time","Удалить время подписки по умолчанию:ru");
regGS("The subscription default time for $1 has been deleted.","Время подписки по умолчанию для $1 было удалено.:ru");
regGS("The default subscription time for $1 could not be deleted.","Не удалось удалить время подписки по умолчанию для $1.:ru");
regGS("Subscription default time for $1 deleted","Время подписки по умолчанию для $1 удалено:ru");
regGS("Name<BR><SMALL>(click to select the publication)</SMALL>","Название<BR><SMALL>(щелкните для выбора выпуска)</SMALL>:ru");
regGS("The publication $1 has been successfuly added.","Публикация $1 успешно добавлена:ru");
regGS("Publication $1 added","Добавлен публикация $1:ru");

?>
