<?php
regGS("Name<BR><SMALL>(click to see issues)</SMALL>", "Ime<br><small>(kliknite da vidite izdanje)</small>");
regGS("Delete publication $1", "Izbiši publikaciju $1");
regGS("No publications.", "Nema publikacija.");
regGS("Country<BR><SMALL>(click to edit)</SMALL>", "Država<br><small>(kliknite za uređivanje)</small>");
regGS("Delete entry $1", "Izbriši podatak $1");
regGS("No entries defined.", "Nijedan podatak nije definiran.");
regGS("Change publication information", "Izmjeni podatke o publikaciji");
regGS("You do not have the right to edit publication information.", "Nemate pravo mijenjati podatke o publikacijama.");
regGS("Changing publication information", "Izmjena podataka o publikaciji");
regGS("You do not have the right to change publication information.", "Nemate pravo mijenjati podatke o publikacijama.");
regGS("The publication $1 has been successfuly updated.", "Publikacija $1 je uspješno izmijenjena.");
regGS("Publication $1 changed", "Publikacija $1 je izmijenjena");
regGS("The publication information could not be updated.", "Podaci o publikaciji ne mogu biti osvježeni.");
regGS("Please check if another publication with the same or the same site name does not already exist.", "Provjerite da li slučajno postoji neka druga istoimena publikacija ili istoimeni sajt.");
regGS("Delete publication", "Izbriši publikaciju");
regGS("You do not have the right to delete publications.", "Nemate prava brisati publikacije.");
regGS("Are you sure you want to delete the publication $1?", "Da li ste sigurni da želite brisati publikaciju $1?");
regGS("Deleting publication", "Brisanje publikacije");
regGS("There are $1 subscription(s) left.", "Ostala(-lo) je još $1 pretplata");
regGS("The publication $1 has been deleted.", "Publikacija $1 je izbrisana");
regGS("The publication $1 could not be deleted.", "Publikacija $1 nije mogla biti izbrisana.");
regGS("Publication $1 deleted", "Publikacija $1 je izbrisana");
regGS("Adding new publication", "Dodavanje nove publikacije");
regGS("The publication could not be added.", "Publikacija ne može biti dodana.");
regGS("Add new country default subscription time", "Dodajte novo standardno trajanje pretplate za datu državu");
regGS("You do not have the right to manage publications.", "Nemate pravo manipulirati publikacijama");
regGS("Adding new country default subscription time", "Dodavanje novog standardnog trajanja pretplate za datu državu");
regGS("You must select a country.", "Morate izabrati državu");
regGS("The default subscription time for $1 has been added.", "Standardno trajanje pretplate za $1 je dodano:");
regGS("The default subscription time for country $1 could not be added.", "Standardno trajanje pretplate nije moglo biti dodano za državu: $1 ");
regGS("Change subscription default time", "Izmijeni standardno trajanje pretplate");
regGS("No default time entry for that country.", "Standardno trajanje pretplate nije definirano za tu državu.");
regGS("Changing default subscription time", "Izmijena standardnog trajanja pretplate");
regGS("The default subscription time for $1 has been successfuly updated.", "Standardno trajanje pretplate za publikaciju $1 uspješno je izmijenjeno.");
regGS("Default subscription time for $1 changed", "Standardno trajanje pretplate za publikaciju $1 je izmijenjeno");
regGS("The default subscription time could not be updated.", "Standardno trajanje pretplate nije moglo biti izmijenjeno.");
regGS("Delete subscription default time", "Izbriši standardno trajanje pretplate");
regGS("Are you sure you want to delete the subscription default time for $1?", "Da li ste sigurni da želite izbrisati standardno trajanje pretplate za publikaciju $1");
regGS("Deleting subscription default time", "Brisanje standardnog trajanje pretplate");
regGS("The subscription default time for $1 has been deleted.", "Standardno trajanje pretplate za publikaciju $1 je izbrisano.");
regGS("The default subscription time for $1 could not be deleted.", "Standardno trajanje pretplate za publikaciju $1 nije moglo biti izbrisano");
regGS("Subscription default time for $1 deleted", "Standardno trajanje pretplate za publikaciju $1 je izbrisano");
regGS("Name<BR><SMALL>(click to select the publication)</SMALL>", "Ime<br><small>(kliknite za odabir publikacije)</small>");
regGS("The publication $1 has been successfuly added.", "Publikacija $1 uspješno je dodana");
regGS("Publication $1 added", "Publikacija $1 je dodana");
?>