include ../../make.env

PACKAGE_DIR=$(BIN_PACKAGE_DIR)/implementation

all:
	$(MAKE) -C parser

install: dummy
	$(MAKE) -C parser install

clean: dummy
	$(MAKE) -C parser clean

uninstall: dummy
	$(MAKE) -C parser uninstall

dummy:
