# Introduce the Snippet Entity
CREATE TABLE Snippets (Id INT AUTO_INCREMENT NOT NULL, Name VARCHAR(255) NOT NULL, Snippet LONGTEXT NOT NULL, TemplateId INT DEFAULT NULL, UNIQUE INDEX UNIQ_1457978AF846113F (TemplateId), PRIMARY KEY(Id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB
CREATE TABLE SnippetTemplates (Id INT AUTO_INCREMENT NOT NULL, Name VARCHAR(255) NOT NULL, Template LONGTEXT NOT NULL, PRIMARY KEY(Id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB
CREATE TABLE ArticleSnippets (ArticleId INT NOT NULL, SnippetId INT NOT NULL, INDEX IDX_5080CDE7C53224D (ArticleId), INDEX IDX_5080CDEB00DA91C (SnippetId), PRIMARY KEY(ArticleId, SnippetId)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB
ALTER TABLE Snippets ADD CONSTRAINT FK_1457978AF846113F FOREIGN KEY (TemplateId) REFERENCES SnippetTemplates (Id)
ALTER TABLE ArticleSnippets ADD CONSTRAINT FK_5080CDE7C53224D FOREIGN KEY (ArticleId) REFERENCES Articles (Number)
ALTER TABLE ArticleSnippets ADD CONSTRAINT FK_5080CDEB00DA91C FOREIGN KEY (SnippetId) REFERENCES Snippets (Id)