<?php $this->placeholder('title')->set('Renditions'); ?>

<ul id="rendition-list">
    <?php foreach ($this->renditions as $rendition) { ?>
    <li id="<?php echo $rendition->getName(); ?>"><?php echo $this->escape($rendition->getName()); ?> <small><?php echo $rendition->getSpecs(); ?> <?php echo $rendition->getWidth(), 'x', $rendition->getHeight(); ?></small></li>
    <?php } ?>
</ul>

<button id="rendition-list-button"><?php putGS('Save order'); ?></button>

<script type="text/javascript">
$(function() {
    $('#rendition-list').sortable({cursor: 'move'});
    $('#rendition-list-button').click(function() {
        var button = $(this);
        var originalText = button.text();
        button.text(<?php echo json_encode(getGS('Saving...')); ?>);
        $.post(<?php echo json_encode($this->url(array(
            'module' => 'admin',
            'controller' => 'rendition',
            'action' => 'index',
        ))); ?>, {'order': $('#rendition-list').sortable('toArray')}, function(data, textStatus) {
            button.text(<?php echo json_encode(getGS('Saved')); ?>);
            window.setTimeout(function() {
                button.text(originalText);
            }, 3000);
        });
    });
});
</script>
