<?php
$translator = \Zend_Registry::get('container')->getService('translator');
$this->headTitle($translator->trans('Logs').' - Newscoop Admin', 'SET');
?>

<?php $this->renderFilter($this->form); ?>

<?php
if (empty($this->events)) { // no logs
    $this->renderMessage($translator->trans('No logs.', array(), 'logs'));
    return;
} ?>

<?php $this->renderPager($this->pager); ?>

<script>
    function show(elementId) {
        var element = document.getElementById(elementId);
        element.style.display = 'inline';
    }
    function hide(elementId) {
        var element = document.getElementById(elementId);
        element.style.display = 'none';
    }
</script>

<table class="logs">
    <caption><?php echo $translator->trans('Logs'); ?></caption>
    <tr>
        <th><?php echo $translator->trans('Date/Time'); ?></th>
        <th><?php echo $translator->trans('Resource Type', array(), 'logs'); ?></th>
        <th><?php echo $translator->trans('Action'); ?></th>
        <th><?php echo $translator->trans('Resource', array(), 'logs'); ?></th>
        <th><?php echo $translator->trans('Title', array(), 'logs'); ?></th>
        <th><?php echo $translator->trans('Diff', array(), 'logs'); ?></th>
        <th><?php echo $translator->trans('User', array(), 'logs'); ?></th>
    </tr>
    <?php $item_count = 0; ?>
    <?php foreach ($this->events as $event) { ?>
    <tr class="priority-info">
        <td><?php echo $event->getCreated()->format('Y-m-d H:i:s'); ?></td>
        <td><?php echo $event->getResourceType(); ?></td>
        <td><?php echo $event->getAction(); ?></td>
        <td><?php
            $resource_id = $event->getResourceId();
            echo('<a id="res_id_show_'. $item_count .'" style="display: inline;" href="javascript:show(\'res_id_hide_'. $item_count .'\');hide(\'res_id_show_'. $item_count .'\');show(\'res_id_'. $item_count .'\');">'. $translator->trans('show', array(), 'logs') .'</a>');
            echo('<a id="res_id_hide_'. $item_count .'" style="display: none;" href="javascript:show(\'res_id_show_'. $item_count .'\');hide(\'res_id_hide_'. $item_count .'\');hide(\'res_id_'. $item_count .'\');">'. $translator->trans('hide', array(), 'logs') .'</a>');
            echo('<table id="res_id_'. $item_count .'" style="display: none;">');
            if (is_array($resource_id)) {
                foreach ($resource_id as $key => $value) {
                    if(is_array($value)){
                        $value = 'array';
                    } else {
                        $value = $value;
                    }

                    echo('<tr><td>'.$key.': </td><td>'.$value.'</td></tr>');
                }
            } else {
                echo('<tr><td colspan="2">'.$translator->trans('Broken data', array(), 'logs').'</td></tr>');
            }
            echo('</table>');
        ?></td>
        <td><?php echo $event->getResourceTitle(); ?></td>
        <td><?php
            $resource_diff = $event->getResourceDiff();
            echo('<a id="res_diff_show_'. $item_count .'" style="display: inline;" href="javascript:show(\'res_diff_hide_'. $item_count .'\');hide(\'res_diff_show_'. $item_count .'\');show(\'res_diff_'. $item_count .'\');">'. $translator->trans('show', array(), 'logs') .'</a>');
            echo('<a id="res_diff_hide_'. $item_count .'" style="display: none;" href="javascript:show(\'res_diff_show_'. $item_count .'\');hide(\'res_diff_hide_'. $item_count .'\');hide(\'res_diff_'. $item_count .'\');">'. $translator->trans('hide', array(), 'logs') .'</a>');
            echo('<table id="res_diff_'. $item_count .'" style="display: none;">');
            if (is_array($resource_diff)) {
                foreach ($resource_diff as $key => $value) {
                    if(is_array($value)){
                        $value =  serialize($array);
                    } else {
                        $value = $value;
                    }

                    echo('<tr><td>'.$key.': </td><td>'. $value.'</td></tr>');
                }
            } else {
                echo('<tr><td colspan="2">'.$translator->trans('Broken data', array(), 'logs').'</td></tr>');
            }
            echo('</table>');
        ?></td>
        <td><?php if ($event->getUser()){ echo $event->getUser()->getUsername(); } ?></td>
    </tr>
    <?php $item_count = $item_count + 1; ?>
    <?php } ?>
</table>

<?php $this->renderPager($this->pager); ?>
