<?php $this->placeholder('title')->set(getGS('Logs')); ?>

<?php $this->renderFilter($this->form); ?>

<?php
if (empty($this->logs)) { // no logs
    $this->renderMessage(getGS('No logs.'));
    return;
} ?>

<?php $this->renderPager($this->pager); ?>

<table class="logs">
    <caption><?php putGS('Logs'); ?> <?php echo $this->priorityName ? '/ ' . $this->priorityName : ''; ?></caption>
    <tr>
        <th><?php putGS('Date/Time'); ?></th>
        <th><?php putGS('Severity'); ?></th>
        <th><?php putGS('Description'); ?></th>
        <th><?php putGS('User'); ?></th>
        <th><?php putGS('User IP Address'); ?></th>
    </tr>
    <?php foreach ($this->logs as $log) { ?>
    <tr class="priority-<?php echo $log->getPriority(); ?>">
        <td><?php echo $log->getTimeCreated()->format('Y-m-d H:i:s'); ?></td>
        <td><?php echo $this->priorityNames[$log->getPriority()]; ?></td>
        <td class="text"><?php echo $this->escape($log->getText()); ?></td>
        <td><?php echo $log->getUserName(); ?></td>
        <td><?php echo $log->getClientIP(); ?></td>
    </tr>
    <?php } ?>
</table>

<?php $this->renderPager($this->pager); ?>
