<?php $this->placeholder('title')->set(getGS('Logs')); ?>

<?php $this->renderFilter($this->form); ?>

<?php
if (empty($this->events)) { // no logs
    $this->renderMessage(getGS('No logs.'));
    return;
} ?>

<?php $this->renderPager($this->pager); ?>

<script>
    function show(elementId) {
        var element = document.getElementById(elementId);
        element.style.display = 'inline';
    }
    function hide(elementId) {
        var element = document.getElementById(elementId);
        element.style.display = 'none';
    }
</script>

<table class="logs">
    <caption><?php putGS('Logs'); ?></caption>
    <tr>
        <th><?php putGS('Date/Time'); ?></th>
        <th><?php putGS('Resource Type'); ?></th>
        <th><?php putGS('Action'); ?></th>
        <th><?php putGS('Resource'); ?></th>
        <th><?php putGS('Title'); ?></th>
        <th><?php putGS('Diff'); ?></th>
        <th><?php putGS('User'); ?></th>
    </tr>
    <?php $item_count = 0; ?>
    <?php foreach ($this->events as $event) { ?>
    <tr class="priority-info">
        <td><?php echo $event->getCreated()->format('Y-m-d H:i:s'); ?></td>
        <td><?php echo $event->getResourceType(); ?></td>
        <td><?php echo $event->getAction(); ?></td>
        <td><?php 
            $resource_id = $event->getResourceId();
            echo('<a id="res_id_show_'. $item_count .'" style="display: inline;" href="javascript:show(\'res_id_hide_'. $item_count .'\');hide(\'res_id_show_'. $item_count .'\');show(\'res_id_'. $item_count .'\');">'. getGS('show') .'</a>');
            echo('<a id="res_id_hide_'. $item_count .'" style="display: none;" href="javascript:show(\'res_id_show_'. $item_count .'\');hide(\'res_id_hide_'. $item_count .'\');hide(\'res_id_'. $item_count .'\');">'. getGS('hide') .'</a>');
            echo('<table id="res_id_'. $item_count .'" style="display: none;">');
            foreach ($resource_id as $key => $value) {
                echo('<tr><td>'.$key.': </td><td>'.$value.'</td></tr>');
            }
            echo('</table>');
        ?></td>
        <td><?php echo $event->getResourceTitle(); ?></td>
        <td><?php 
            $resource_diff = $event->getResourceDiff();
            echo('<a id="res_diff_show_'. $item_count .'" style="display: inline;" href="javascript:show(\'res_diff_hide_'. $item_count .'\');hide(\'res_diff_show_'. $item_count .'\');show(\'res_diff_'. $item_count .'\');">'. getGS('show') .'</a>');
            echo('<a id="res_diff_hide_'. $item_count .'" style="display: none;" href="javascript:show(\'res_diff_show_'. $item_count .'\');hide(\'res_diff_hide_'. $item_count .'\');hide(\'res_diff_'. $item_count .'\');">'. getGS('hide') .'</a>');
            echo('<table id="res_diff_'. $item_count .'" style="display: none;">');
            foreach ($resource_diff as $key => $value) {
                echo('<tr><td>'.$key.': </td><td>'.$value.'</td></tr>');
            }
            echo('</table>');
        ?></td>
        <td><?php echo $event->getUser()->getUserName(); ?></td>
    </tr>
    <?php $item_count = $item_count + 1; ?>
    <?php } ?>
</table>

<?php $this->renderPager($this->pager); ?>
