################################################################################
#
# CAMPSITE is a Unicode-enabled multilingual web content
# management system for news publications.
# CAMPFIRE is a Unicode-enabled java-based near WYSIWYG text editor.
# Copyright (C)2000,2001  Media Development Loan Fund
# contact: contact@campware.org - http://www.campware.org
# Campware encourages further development. Please let us know.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
################################################################################

INSERT INTO UserTypes VALUES ('Chief Editor','N','N','N','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','Y','N','N','N','N','Y','Y','N','N','Y','Y','N','N','Y','N','Y','Y','Y','Y','Y');

INSERT INTO Countries VALUES ('AR',1,'Argentina');
INSERT INTO Countries VALUES ('AG',1,'Antigua And Barbuda');
INSERT INTO Countries VALUES ('AQ',1,'Antarctica');
INSERT INTO Countries VALUES ('AI',1,'Anguilla');
INSERT INTO Countries VALUES ('AO',1,'Angola');
INSERT INTO Countries VALUES ('AD',1,'Andorra');
INSERT INTO Countries VALUES ('DE',5,'Deutschland');
INSERT INTO Countries VALUES ('AS',1,'American Samoa');
INSERT INTO Countries VALUES ('AT',6,'Österreich');
INSERT INTO Countries VALUES ('DZ',1,'Algeria');
INSERT INTO Countries VALUES ('IT',14,'Italia');
INSERT INTO Countries VALUES ('AL',1,'Albania');
INSERT INTO Countries VALUES ('FR',12,'France');
INSERT INTO Countries VALUES ('PT',9,'Portugal');
INSERT INTO Countries VALUES ('AF',1,'Afghanistan');
INSERT INTO Countries VALUES ('ES',13,'España');
INSERT INTO Countries VALUES ('AM',1,'Armenia');
INSERT INTO Countries VALUES ('AW',1,'Aruba');
INSERT INTO Countries VALUES ('AU',1,'Australia');
INSERT INTO Countries VALUES ('AT',1,'Austria');
INSERT INTO Countries VALUES ('AZ',1,'Azerbaijan');
INSERT INTO Countries VALUES ('BS',1,'Bahamas');
INSERT INTO Countries VALUES ('BH',1,'Bahrain');
INSERT INTO Countries VALUES ('BD',1,'Bangladesh');
INSERT INTO Countries VALUES ('BB',1,'Barbados');
INSERT INTO Countries VALUES ('BY',1,'Belarus');
INSERT INTO Countries VALUES ('BE',1,'Belgium');
INSERT INTO Countries VALUES ('BZ',1,'Belize');
INSERT INTO Countries VALUES ('BJ',1,'Benin');
INSERT INTO Countries VALUES ('BM',1,'Bermuda');
INSERT INTO Countries VALUES ('BT',1,'Bhutan');
INSERT INTO Countries VALUES ('BO',1,'Bolivia');
INSERT INTO Countries VALUES ('BA',1,'Bosnia And Herzegovina');
INSERT INTO Countries VALUES ('BW',1,'Botswana');
INSERT INTO Countries VALUES ('BV',1,'Bouvet Island');
INSERT INTO Countries VALUES ('BR',1,'Brazil');
INSERT INTO Countries VALUES ('IO',1,'British Indian Ocean Territory');
INSERT INTO Countries VALUES ('BN',1,'Brunei Darussalam');
INSERT INTO Countries VALUES ('BG',1,'Bulgaria');
INSERT INTO Countries VALUES ('BF',1,'Burkina Faso');
INSERT INTO Countries VALUES ('BI',1,'Burundi');
INSERT INTO Countries VALUES ('KH',1,'Cambodia');
INSERT INTO Countries VALUES ('CM',1,'Cameroon');
INSERT INTO Countries VALUES ('CA',1,'Canada');
INSERT INTO Countries VALUES ('CV',1,'Cape Verde');
INSERT INTO Countries VALUES ('KY',1,'Cayman Islands');
INSERT INTO Countries VALUES ('CF',1,'Central African Republic');
INSERT INTO Countries VALUES ('TD',1,'Chad');
INSERT INTO Countries VALUES ('CL',1,'Chile');
INSERT INTO Countries VALUES ('CN',1,'China');
INSERT INTO Countries VALUES ('CX',1,'Christmas Island');
INSERT INTO Countries VALUES ('CC',1,'Cocos (Keeling) Islands');
INSERT INTO Countries VALUES ('CO',1,'Colombia');
INSERT INTO Countries VALUES ('KM',1,'Comoros');
INSERT INTO Countries VALUES ('CG',1,'Congo');
INSERT INTO Countries VALUES ('CD',1,'Congo, The Democratic Republic Of The');
INSERT INTO Countries VALUES ('CK',1,'Cook Islands');
INSERT INTO Countries VALUES ('CR',1,'Costa Rica');
INSERT INTO Countries VALUES ('CI',1,'Cote Divoire');
INSERT INTO Countries VALUES ('HR',1,'Croatia');
INSERT INTO Countries VALUES ('CU',1,'Cuba');
INSERT INTO Countries VALUES ('CY',1,'Cyprus');
INSERT INTO Countries VALUES ('CZ',1,'Czech Republic');
INSERT INTO Countries VALUES ('DK',1,'Denmark');
INSERT INTO Countries VALUES ('DJ',1,'Djibouti');
INSERT INTO Countries VALUES ('DM',1,'Dominica');
INSERT INTO Countries VALUES ('DO',1,'Dominican Republic');
INSERT INTO Countries VALUES ('TP',1,'East Timor');
INSERT INTO Countries VALUES ('EC',1,'Ecuador');
INSERT INTO Countries VALUES ('EG',1,'Egypt');
INSERT INTO Countries VALUES ('SV',1,'El Salvador');
INSERT INTO Countries VALUES ('GQ',1,'Equatorial Guinea');
INSERT INTO Countries VALUES ('ER',1,'Eritrea');
INSERT INTO Countries VALUES ('EE',1,'Estonia');
INSERT INTO Countries VALUES ('ET',1,'Ethiopia');
INSERT INTO Countries VALUES ('FK',1,'Falkland Islands (Malvinas)');
INSERT INTO Countries VALUES ('FO',1,'Faroe Islands');
INSERT INTO Countries VALUES ('FJ',1,'Fiji');
INSERT INTO Countries VALUES ('FI',1,'Finland');
INSERT INTO Countries VALUES ('FR',1,'France');
INSERT INTO Countries VALUES ('FX',1,'France, Metropolitan');
INSERT INTO Countries VALUES ('GF',1,'French Guiana');
INSERT INTO Countries VALUES ('PF',1,'French Polynesia');
INSERT INTO Countries VALUES ('TF',1,'French Southern Territories');
INSERT INTO Countries VALUES ('GA',1,'Gabon');
INSERT INTO Countries VALUES ('GM',1,'Gambia');
INSERT INTO Countries VALUES ('GE',1,'Georgia');
INSERT INTO Countries VALUES ('DE',1,'Germany');
INSERT INTO Countries VALUES ('GH',1,'Ghana');
INSERT INTO Countries VALUES ('GI',1,'Gibraltar');
INSERT INTO Countries VALUES ('GR',1,'Greece');
INSERT INTO Countries VALUES ('GL',1,'Greenland');
INSERT INTO Countries VALUES ('GD',1,'Grenada');
INSERT INTO Countries VALUES ('GP',1,'Guadeloupe');
INSERT INTO Countries VALUES ('GU',1,'Guam');
INSERT INTO Countries VALUES ('GT',1,'Guatemala');
INSERT INTO Countries VALUES ('GN',1,'Guinea');
INSERT INTO Countries VALUES ('GW',1,'Guinea-bissau');
INSERT INTO Countries VALUES ('GY',1,'Guyana');
INSERT INTO Countries VALUES ('HT',1,'Haiti');
INSERT INTO Countries VALUES ('HM',1,'Heard Island And Mcdonald Islands');
INSERT INTO Countries VALUES ('VA',1,'Holy See (Vatican City State)');
INSERT INTO Countries VALUES ('HN',1,'Honduras');
INSERT INTO Countries VALUES ('HK',1,'Hong Kong');
INSERT INTO Countries VALUES ('HU',1,'Hungary');
INSERT INTO Countries VALUES ('IS',1,'Iceland');
INSERT INTO Countries VALUES ('IN',1,'India');
INSERT INTO Countries VALUES ('ID',1,'Indonesia');
INSERT INTO Countries VALUES ('IR',1,'Iran, Islamic Republic Of');
INSERT INTO Countries VALUES ('IQ',1,'Iraq');
INSERT INTO Countries VALUES ('IE',1,'Ireland');
INSERT INTO Countries VALUES ('IL',1,'Israel');
INSERT INTO Countries VALUES ('IT',1,'Italy');
INSERT INTO Countries VALUES ('JM',1,'Jamaica');
INSERT INTO Countries VALUES ('JP',1,'Japan');
INSERT INTO Countries VALUES ('JO',1,'Jordan');
INSERT INTO Countries VALUES ('KZ',1,'Kazakstan');
INSERT INTO Countries VALUES ('KE',1,'Kenya');
INSERT INTO Countries VALUES ('KI',1,'Kiribati');
INSERT INTO Countries VALUES ('KP',1,'Korea, Democratic Peoples Republic Of');
INSERT INTO Countries VALUES ('KR',1,'Korea, Republic Of');
INSERT INTO Countries VALUES ('KW',1,'Kuwait');
INSERT INTO Countries VALUES ('KG',1,'Kyrgyzstan');
INSERT INTO Countries VALUES ('LA',1,'Lao Peoples Democratic Republic');
INSERT INTO Countries VALUES ('LV',1,'Latvia');
INSERT INTO Countries VALUES ('LB',1,'Lebanon');
INSERT INTO Countries VALUES ('LS',1,'Lesotho');
INSERT INTO Countries VALUES ('LR',1,'Liberia');
INSERT INTO Countries VALUES ('LY',1,'Libyan Arab Jamahiriya');
INSERT INTO Countries VALUES ('LI',1,'Liechtenstein');
INSERT INTO Countries VALUES ('LT',1,'Lithuania');
INSERT INTO Countries VALUES ('LU',1,'Luxembourg');
INSERT INTO Countries VALUES ('MO',1,'Macau');
INSERT INTO Countries VALUES ('MK',1,'Macedonia, The Former Yugoslav Republic Of');
INSERT INTO Countries VALUES ('MG',1,'Madagascar');
INSERT INTO Countries VALUES ('MW',1,'Malawi');
INSERT INTO Countries VALUES ('MY',1,'Malaysia');
INSERT INTO Countries VALUES ('MV',1,'Maldives');
INSERT INTO Countries VALUES ('ML',1,'Mali');
INSERT INTO Countries VALUES ('MT',1,'Malta');
INSERT INTO Countries VALUES ('MH',1,'Marshall Islands');
INSERT INTO Countries VALUES ('MQ',1,'Martinique');
INSERT INTO Countries VALUES ('MR',1,'Mauritania');
INSERT INTO Countries VALUES ('MU',1,'Mauritius');
INSERT INTO Countries VALUES ('YT',1,'Mayotte');
INSERT INTO Countries VALUES ('MX',1,'Mexico');
INSERT INTO Countries VALUES ('FM',1,'Micronesia, Federated States Of');
INSERT INTO Countries VALUES ('MD',1,'Moldova, Republic Of');
INSERT INTO Countries VALUES ('MC',1,'Monaco');
INSERT INTO Countries VALUES ('MN',1,'Mongolia');
INSERT INTO Countries VALUES ('MS',1,'Montserrat');
INSERT INTO Countries VALUES ('MA',1,'Morocco');
INSERT INTO Countries VALUES ('MZ',1,'Mozambique');
INSERT INTO Countries VALUES ('MM',1,'Myanmar');
INSERT INTO Countries VALUES ('NA',1,'Namibia');
INSERT INTO Countries VALUES ('NR',1,'Nauru');
INSERT INTO Countries VALUES ('NP',1,'Nepal');
INSERT INTO Countries VALUES ('NL',1,'Netherlands');
INSERT INTO Countries VALUES ('AN',1,'Netherlands Antilles');
INSERT INTO Countries VALUES ('NC',1,'New Caledonia');
INSERT INTO Countries VALUES ('NZ',1,'New Zealand');
INSERT INTO Countries VALUES ('NI',1,'Nicaragua');
INSERT INTO Countries VALUES ('NE',1,'Niger');
INSERT INTO Countries VALUES ('NG',1,'Nigeria');
INSERT INTO Countries VALUES ('NU',1,'Niue');
INSERT INTO Countries VALUES ('NF',1,'Norfolk Island');
INSERT INTO Countries VALUES ('MP',1,'Northern Mariana Islands');
INSERT INTO Countries VALUES ('NO',1,'Norway');
INSERT INTO Countries VALUES ('OM',1,'Oman');
INSERT INTO Countries VALUES ('PK',1,'Pakistan');
INSERT INTO Countries VALUES ('PW',1,'Palau');
INSERT INTO Countries VALUES ('PS',1,'Palestinian Territory, Occupied');
INSERT INTO Countries VALUES ('PA',1,'Panama');
INSERT INTO Countries VALUES ('PG',1,'Papua New Guinea');
INSERT INTO Countries VALUES ('PY',1,'Paraguay');
INSERT INTO Countries VALUES ('PE',1,'Peru');
INSERT INTO Countries VALUES ('PH',1,'Philippines');
INSERT INTO Countries VALUES ('PN',1,'Pitcairn');
INSERT INTO Countries VALUES ('PL',1,'Poland');
INSERT INTO Countries VALUES ('PT',1,'Portugal');
INSERT INTO Countries VALUES ('PR',1,'Puerto Rico');
INSERT INTO Countries VALUES ('QA',1,'Qatar');
INSERT INTO Countries VALUES ('RE',1,'Reunion');
INSERT INTO Countries VALUES ('RO',1,'Romania');
INSERT INTO Countries VALUES ('RU',1,'Russian Federation');
INSERT INTO Countries VALUES ('RW',1,'Rwanda');
INSERT INTO Countries VALUES ('SH',1,'Saint Helena');
INSERT INTO Countries VALUES ('KN',1,'Saint Kitts And Nevis');
INSERT INTO Countries VALUES ('LC',1,'Saint Lucia');
INSERT INTO Countries VALUES ('PM',1,'Saint Pierre And Miquelon');
INSERT INTO Countries VALUES ('VC',1,'Saint Vincent And The Grenadines');
INSERT INTO Countries VALUES ('WS',1,'Samoa');
INSERT INTO Countries VALUES ('SM',1,'San Marino');
INSERT INTO Countries VALUES ('ST',1,'Sao Tome And Principe');
INSERT INTO Countries VALUES ('SA',1,'Saudi Arabia');
INSERT INTO Countries VALUES ('SN',1,'Senegal');
INSERT INTO Countries VALUES ('SC',1,'Seychelles');
INSERT INTO Countries VALUES ('SL',1,'Sierra Leone');
INSERT INTO Countries VALUES ('SG',1,'Singapore');
INSERT INTO Countries VALUES ('SK',1,'Slovakia');
INSERT INTO Countries VALUES ('SI',1,'Slovenia');
INSERT INTO Countries VALUES ('SB',1,'Solomon Islands');
INSERT INTO Countries VALUES ('SO',1,'Somalia');
INSERT INTO Countries VALUES ('ZA',1,'South Africa');
INSERT INTO Countries VALUES ('GS',1,'South Georgia And The South Sandwich Islands');
INSERT INTO Countries VALUES ('ES',1,'Spain');
INSERT INTO Countries VALUES ('LK',1,'Sri Lanka');
INSERT INTO Countries VALUES ('SD',1,'Sudan');
INSERT INTO Countries VALUES ('SR',1,'Suriname');
INSERT INTO Countries VALUES ('SJ',1,'Svalbard And Jan Mayen');
INSERT INTO Countries VALUES ('SZ',1,'Swaziland');
INSERT INTO Countries VALUES ('SE',1,'Sweden');
INSERT INTO Countries VALUES ('CH',1,'Switzerland');
INSERT INTO Countries VALUES ('SY',1,'Syrian Arab Republic');
INSERT INTO Countries VALUES ('TW',1,'Taiwan, Province Of China');
INSERT INTO Countries VALUES ('TJ',1,'Tajikistan');
INSERT INTO Countries VALUES ('TZ',1,'Tanzania, United Republic Of');
INSERT INTO Countries VALUES ('TH',1,'Thailand');
INSERT INTO Countries VALUES ('TG',1,'Togo');
INSERT INTO Countries VALUES ('TK',1,'Tokelau');
INSERT INTO Countries VALUES ('TO',1,'Tonga');
INSERT INTO Countries VALUES ('TT',1,'Trinidad And Tobago');
INSERT INTO Countries VALUES ('TN',1,'Tunisia');
INSERT INTO Countries VALUES ('TR',1,'Turkey');
INSERT INTO Countries VALUES ('TM',1,'Turkmenistan');
INSERT INTO Countries VALUES ('TC',1,'Turks And Caicos Islands');
INSERT INTO Countries VALUES ('TV',1,'Tuvalu');
INSERT INTO Countries VALUES ('UG',1,'Uganda');
INSERT INTO Countries VALUES ('UA',1,'Ukraine');
INSERT INTO Countries VALUES ('AE',1,'United Arab Emirates');
INSERT INTO Countries VALUES ('GB',1,'United Kingdom');
INSERT INTO Countries VALUES ('US',1,'United States');
INSERT INTO Countries VALUES ('UM',1,'United States Minor Outlying Islands');
INSERT INTO Countries VALUES ('UY',1,'Uruguay');
INSERT INTO Countries VALUES ('UZ',1,'Uzbekistan');
INSERT INTO Countries VALUES ('VU',1,'Vanuatu');
INSERT INTO Countries VALUES ('VE',1,'Venezuela');
INSERT INTO Countries VALUES ('VN',1,'Vietnam');
INSERT INTO Countries VALUES ('VG',1,'Virgin Islands, British');
INSERT INTO Countries VALUES ('VI',1,'Virgin Islands, U.S.');
INSERT INTO Countries VALUES ('WF',1,'Wallis And Futuna');
INSERT INTO Countries VALUES ('EH',1,'Western Sahara');
INSERT INTO Countries VALUES ('YE',1,'Yemen');
INSERT INTO Countries VALUES ('YU',1,'Yugoslavia');
INSERT INTO Countries VALUES ('ZM',1,'Zambia');
INSERT INTO Countries VALUES ('ZW',1,'Zimbabwe');
INSERT INTO Countries VALUES ('GB',2,'Marea Britanie');
INSERT INTO Countries VALUES ('RO',2,'România');
INSERT INTO Countries VALUES ('CZ',2,'Republica Cehă');
INSERT INTO Countries VALUES ('YU',4,'Jugoslavija');
