#!/bin/bash

bin_path=`dirname $0`
if [ "$bin_path" = "." ]; then
        script_call="./campsite-remove-instance.php"
        ETC_DIR=`./campsite_config --etc_dir`
        PHP=`./campsite_config --php_cli`
elif [ "$bin_path" = "" ]; then
        BIN_DIR=`campsite_config --bin_dir`
        script_call="$BIN_DIR/campsite-remove-instance.php"
        ETC_DIR=`campsite_config --etc_dir`
        PHP=`campsite_config --php_cli`
else
        script_call="$bin_path/campsite-remove-instance.php"
        ETC_DIR=`$bin_path/campsite_config --etc_dir`
        PHP=`$bin_path/campsite_config --php_cli`
fi

if [ "$1" = "" ]; then
    echo "Usage:"
    echo "$0 <instance_name>"
    echo "    <instance_name>: the name of the instance you want to remove; this"
    echo "        parameter is mandatory"
    exit 1
fi

CMD="$PHP -q $script_call $ETC_DIR $*"
$CMD
exit $?
