ALTER TABLE `UserPerm` ADD `EditorImageAdd` ENUM( 'N', 'Y' ) DEFAULT 'N' NOT NULL ,
ADD `EditorTextAlignment` ENUM( 'N', 'Y' ) DEFAULT 'N' NOT NULL ,
ADD `EditorFontColor` ENUM( 'N', 'Y' ) DEFAULT 'N' NOT NULL ,
ADD `EditorFontSize` ENUM( 'N', 'Y' ) DEFAULT 'N' NOT NULL ,
ADD `EditorFontFace` ENUM( 'N', 'Y' ) DEFAULT 'N' NOT NULL ,
ADD `EditorTable` ENUM( 'N', 'Y' ) DEFAULT 'N' NOT NULL ,
ADD `EditorSuperscript` ENUM( 'N', 'Y' ) DEFAULT 'N' NOT NULL ,
ADD `EditorSubscript` ENUM( 'N', 'Y' ) DEFAULT 'N' NOT NULL ,
ADD `EditorStrikethrough` ENUM( 'N', 'Y' ) DEFAULT 'N' NOT NULL ,
ADD `EditorIndent` ENUM( 'N', 'Y' ) DEFAULT 'N' NOT NULL ,
ADD `EditorListBullet` ENUM( 'N', 'Y' ) DEFAULT 'N' NOT NULL ,
ADD `EditorListNumber` ENUM( 'N', 'Y' ) DEFAULT 'N' NOT NULL ,
ADD `EditorHorizontalRule` ENUM( 'N', 'Y' ) DEFAULT 'N' NOT NULL ,
ADD `EditorSourceView` ENUM( 'N', 'Y' ) DEFAULT 'N' NOT NULL ,
ADD `EditorEnlarge` ENUM( 'N', 'Y' ) DEFAULT 'N' NOT NULL ,
ADD `EditorTextDirection` ENUM( 'N', 'Y' ) DEFAULT 'N' NOT NULL ,
ADD `EditorLink` ENUM( 'N', 'Y' ) DEFAULT 'N' NOT NULL ,
ADD `EditorSubhead` ENUM( 'N', 'Y' ) DEFAULT 'N' NOT NULL ;