<?php
$translator = \Zend_Registry::get('container')->getService('translator');
$this->headTitle($translator->trans('Help', array(), 'help').' - Newscoop Admin', 'SET'); ?>

<img src="<?php echo $this->baseUrl('/admin-style/images/newscoop_logo_big.png') ?>" style="float:left;">

<dl class="metadata">
  <dt><?php echo $translator->trans('Version', array(), 'help'); ?>:</dt> <dd><?php echo $this->version; ?></dd>
  <dt><?php echo $translator->trans('REST API Version', array(), 'help'); ?>:</dt> <dd><?php echo $this->api_version; ?> (<a href="/documentation/rest-api/"><?php echo $translator->trans('Documentation', array(), 'help'); ?></a>)</dd>
  <dt><?php echo $translator->trans('Release date', array(), 'help'); ?>:</dt> <dd><?php echo $this->date; ?></dd>
</dl>

<div class="clear"></div>

<ul class="help">
  <li><p><?php echo $translator->trans("Welcome to the Newscoop help page. Whether you're just getting started or you have a specific question, the best place to look is in one of the Newscoop manuals", array(), 'help'); ?><br /><a href="http://www.sourcefabric.org/en/newscoop/manuals" target="_blank">http://www.sourcefabric.org/en/newscoop/manuals</a></p></li>

  <li><p><?php echo $translator->trans('Alternatively, you can ask a question in our forums at', array(), 'help'); ?> <a href="http://forum.sourcefabric.org/" target="_blank">http://forum.sourcefabric.org</a> <?php echo $translator->trans('or suggest improvements in our bug tracker at', array(), 'help'); ?> <a href="http://dev.sourcefabric.org/" target="_blank">http://dev.sourcefabric.org/</a>.</p></li>

  <li><p><?php echo $translator->trans('To upgrade Newscoop please visit our website', array(), 'help'); ?> <a href="http://www.sourcefabric.org/en/newscoop/download/" target="_blank">http://www.sourcefabric.org/en/newscoop/download/</a>. <?php echo $translator->trans('Sourcefabric also offers a range of support options, which can include installation, hosting and technical support.', array(), 'help'); ?> <?php echo $translator->trans('Talk to us today', array(), 'help'); ?> <a href="https://www.sourcefabric.org/en/home/contact/" target="_blank">https://www.sourcefabric.org/en/home/contact/</a> <?php echo $translator->trans('and help us support quality, independent journalism.', array(), 'help'); ?></p></li>

  <li><p><?php echo $translator->trans('To translate the Newscoop interface and themes, please create an account at', array(), 'help'); ?> <a href="https://www.transifex.com/sourcefabric/newscoop/" target="_blank">https://www.transifex.com/sourcefabric/newscoop/</a>.</p></li>

  <li><p><?php echo $translator->trans('To support us in other ways, visit our Community page', array(), 'help'); ?> <a href="https://www.sourcefabric.org/en/home/help/" target="_blank">https://www.sourcefabric.org/en/home/help/</a>.</p></li>
</ol>
