<?php $this->placeholder('title')->set(getGS('Help')); ?>

<img src="/admin-style/images/newscoop_logo_bigblue.png" />

<ul>
  <li>Version: 3.6.0 beta1</li>
  <li>Released: 2011-06-15</li>
</ul>

<ul class="help">
  <ol><?php putGS('Check the manual. Seriously, our manuals are great and chances are you’ll find the answers to your questions in them. Not there? Read on...'); ?></ol>
  <ol><?php putGS('Post to the forum. Join the Sourcefabric community (it takes two seconds and you can sign-up with an existing Twitter, Google or Facebook account) and post your support query in the Newscoop forum. Minutes later (timezone/caffeine level dependent), a Sourcefabric angel will answer your prayers. If they couldn\'t, continue reading...'); ?></ol>
  <ol><?php putGS('Report a bug. Congratulations! You found a bug! These creatures are not as illusory as we\'d like them to be. Reporting them takes seconds. Visit our bug tracker and create a bug report by selecting Create Issue, then Newscoop and Bug. You can also suggest improvements and new features here.'); ?></ol>
  <ol><?php putGS('When you\'ve exhausted all possibilities, feel free to write to us. The technical knowledge is all in the manuals and forums, but we\'ll at least be able to point you in the right direction.'); ?></ol>
</ul>

