<?php
$translator = \Zend_Registry::get('container')->getService('translator');
?>
<video controls="controls" width="320" height="240">
    <source src="<?php echo $this->src; ?>" type="<?php echo $this->type; ?>" />
    <object type="application/x-shockwave-flash" data="<?php echo $Campsite['WEBSITE_URL']; ?>/js/flowplayer/flowplayer-3.2.5.swf" width="320" height="240">
        <param name="movie" value="<?php echo $Campsite['WEBSITE_URL']; ?>/js/flowplayer/flowplayer-3.2.5.swf" />
		<param name="allowFullScreen" value="true" />
		<param name="wmode" value="transparent" />
        <param name="flashVars" value="config={'playlist':[{'url':'<?php echo $this->src; ?>','autoPlay':false}]}" />
        <span title="<?php echo $translator->trans('No video playback capabilities, please download the video below', array(), 'library'); ?>"><?php echo $this->alt; ?></span>
	</object>
</video>
