B_HTML
B_DATABASE

CHECK_BASIC_ACCESS

B_HEAD
	X_EXPIRES
	X_TITLE({Quick Menu})
E_HEAD

<!sql if $access>dnl
B_STYLE
E_STYLE

<FRAMESET ROWS="70, *" BORDER="0">
    <FRAME SRC="lang.xql" NAME="flang" FRAMEBORDER="0" MARGINHEIGHT="0" NORESIZE SCROLLING="NO">
    <FRAME SRC="empty.xql?bg=0" NAME="f1" FRAMEBORDER="0" MARGINHEIGHT="0" NORESIZE SCROLLING="NO">
</FRAMESET>

<!sql endif>dnl

E_DATABASE
E_HTML
