<?php
    /* @var Zend_View_Helper_HeadLink */
    $headStyle = $this->headLink();
    $headStyle->appendStylesheet($this->baseUrl('/admin-style/comments.css'));
    $headStyle->offsetSetStylesheet('table', '');
    camp_load_translation_strings("feedback");
?>
<?php $this->headScript()->appendFile($this->baseUrl('/js/jquery/doT.js')); ?>
<?php $this->headScript()->appendFile($this->baseUrl('/js/jquery/jquery.ba-iff.js')); ?>
<?php $this->headScript()->appendFile($this->baseUrl('/js/jquery/jquery.version.js')); ?>
<?php $this->headScript()->appendFile($this->baseUrl('/js/jquery/feedback.js')); ?>

<?php $this->placeholder('title')->set(getGS('Feedback Messages')); ?>
<script>
    function putGS(str) {
        var msg = serverObj.translateObj[serverObj.languageObj.indexOf(str)]
        for(i=1, counti=arguments.length; i<counti; i++) {
            msg = msg.replace(new RegExp("\\$"+i,"g"),arguments[i]);
        }
        return msg;
    }
    var serverObj = {};
    serverObj.security = {};
    serverObj.security = {<?php echo SecurityToken::JsParameter(); ?>};

    serverObj.languageObj = [
        'Search',
        'Messages updated.',
        'Messages deleted.',
        'Messages status change to $1.',
        'Message updated.',
        'Message deleted.',
        'Message status change to $1.',
        'Change selected messages status',
        'Actions',
        'New',
        'Processed',
        'Starred',
        'Deleted',
        'Unable to reach Newscoop. Please check your internet connection.',
        'You are about to permanently delete a message.',
        'You are about to permanently delete multiple messages.',
        'Are you sure you want to do it?'
    ];
    
    serverObj.translateObj = [
        '<?php putGS('Search'); ?>',
        '<?php putGS('Messages updated.'); ?>',
        '<?php putGS('Messages deleted.'); ?>',
        '<?php putGS('Messages status change to $1.'); ?>',
        '<?php putGS('Message updated.'); ?>',
        '<?php putGS('Message deleted.'); ?>',
        '<?php putGS('Message status change to $1.'); ?>',
        '<?php putGS('Change selected messages status'); ?>',
        '<?php putGS('Actions');?>',
        '<?php putGS('New'); ?>',
        '<?php putGS('Processed'); ?>',
        '<?php putGS('Starred'); ?>',
        '<?php putGS('Deleted'); ?>',
        '<?php putGS('Unable to reach Newscoop. Please check your internet connection.'); ?>',
        <?php echo json_encode(getGS("You are about to permanently delete a message.")); ?>,
        <?php echo json_encode(getGS("You are about to permanently delete multiple messages.")); ?>,
        <?php echo json_encode(getGS("Are you sure you want to do it?")); ?>
    ];
</script>
<table>
  <tr>
  </tr>
</table>

<script id="comment-tmpl" type="text/html">
<td colspan="4">
  <table cellspacing="0" cellpadding="0" style="width:100%">
    <tbody>
      <tr>
        <td class="commentId sorting_1">
          <input type="checkbox" name="index[]" value="{{message.id}}" class="table-checkbox">
          <span class="index">{{index}}.</span>
        </td>
        <td class="commentUser">
          <div class="commentUserHolder">
            <div {% if (user.is_banned) %}class="user-blocked-avatar"{% endif %}>
              <img src="{{user.avatar}}">
            </div>
            <p>
            <p {% if (user.is_banned) %}class="user-blocked-avatar"{% endif %}><b>{{user.username}}</b></p>
            <p>{{user.name}}</p>
                    
            <p><a href="mailto:{{user.email}}">{{user.email}}</a></p>
            <p><a href="{{user.url}}">{{user.url}}</a></p>
            <p><a href="{{user.banurl}}" class="banUser"><span><?php putGS('Ban/Unban user'); ?></span></a></p>
            </p>
          </div>
        </td>
        <td class="commentMessage">
          <div class="dateCommentHolder">
            <h4>
              <span>{{message.created.date}} <?php putGS('at'); ?> {{message.created.time}}</span>
              <span class="commentSubject">{{message.subject}}</span>
            </h4>
            <p class="commentBody">{{message.message}}</p>
            {% if (attachment.type == 'image') %}
				<div style="border: 1px solid #000000; width: 100%; background-color: #ffffff; padding: 2px;">
				<span style="background-color: #f0f0f0; display: block; padding: 2px; font-weight: bold;"><?php putGS('Attachment'); ?></span>
				<img src="{{attachment.thumbnail}}" style="margin: 4px; float: left; border: 1px solid #000000;">
				<p>{{attachment.name}}</p>
				{% if (attachment.status == 'unapproved') %}
					<div class="approval">
					<form action="{{attachment.approve_url}}">
						<input type="hidden" name="attachment_type" value="{{attachment.type}}" />
						<input type="hidden" name="attachment_id" value="{{attachment.id}}" />
						<?php echo SecurityToken::FormParameter(); ?>
						<div class="buttonBar">
						<input type="submit" value="<?php putGS('Approve'); ?>" class="button">
						</div>
					</form>
					</div>
				{% endif %}
				{% if (attachment.status == 'approved') %}
					<?php putGS('Approved.'); ?>
				{% endif %}
				<div style="clear: both;"></div>
				</div>
            {% endif %}
            {% if (attachment.type == 'document') %}
				<div style="border: 1px solid #000000; width: 100%; background-color: #ffffff; padding: 2px;">
				<span style="background-color: #f0f0f0; display: block; padding: 2px; font-weight: bold;"><?php putGS('Attachment'); ?></span>
				<img src="<?php echo $this->baseUrl('/admin-style/images/pdf.png'); ?>" style="width: 60px; margin: 4px; float: left; border: 1px solid #000000;">
				<p>{{attachment.name}}</p>
				{% if (attachment.status == 'unapproved') %}
					<div class="approval">
					<form action="{{attachment.approve_url}}">
						<input type="hidden" name="attachment_type" value="{{attachment.type}}" />
						<input type="hidden" name="attachment_id" value="{{attachment.id}}" />
						<?php echo SecurityToken::FormParameter(); ?>
						<div class="buttonBar">
						<input type="submit" value="<?php putGS('Approve'); ?>" class="button">
						</div>
					</form>
					</div>
				{% endif %}
				{% if (attachment.status == 'approved') %}
					<?php putGS('Approved.'); ?>
				{% endif %}
				<div style="clear: both;"></div>
				</div>
            {% endif %}
            {% if (attachment.type == 'none') %}
				<div style="border: 1px solid #000000; width: 100%; background-color: #ffffff; padding: 2px;">
				<span style="background-color: #f0f0f0; display: block; padding: 2px; font-weight: bold;"><?php putGS('No attachment'); ?></span>
				<div style="clear: both;"></div>
				</div>
            {% endif %}
          </div>

          <div class="dateCommentHolderReply">
            <fieldset class="content-reply" style="display:none;">
              <h3><?php putGS('Reply to message'); ?></h3>
              <form action="{{message.action.reply}}">
              <input type="hidden" name="parent" value="{{message.id}}" />
              <?php echo SecurityToken::FormParameter(); ?>
              <label><?php putGS('Subject'); ?></label>
              <input name="subject" type="text" class="input_text">
              <label><?php putGS('Message'); ?></label>
              <textarea name="message" class="input_text_area"></textarea>
              <div class="buttonBar">
                <input type="button" value="<?php putGS('Cancel'); ?>" class="button reply-cancel">
                <input type="submit" value="<?php putGS('Submit'); ?>" class="button">
              </div>
              </form>
            </fieldset>
          </div>
        </td>
        <td>
          <div class="commentArticleHolder">
            <p>
				<a href="{{ message.article.url }}" class="articleLink">{{ message.article.name }}</a>
				<br>
				<span>{{ message.publication }}; <b><?php putGS('Section'); ?></b> {{ message.section }}</span>
            </p>
            <p><span>URL: <a href="{{ message.url }}">{{message.url}}</a></span></p>
          </div>
        </td>
      </tr>
    </tbody>
  </table>
  <div class="commentBtns">
    <ul>
      <li>
        <input type="radio" name="action_comment_{{message.id}}" class="action new" id="pending_{{message.id}}" value="pending"/>
        <label for="pending_{{message.id}}"><?php putGS('New'); ?></label>
        &nbsp;&nbsp;
      </li>

      <li>
        <input type="radio" name="action_comment_{{message.id}}" class="action processed" id="processed_{{message.id}}" value="processed"/>
        <label for="processed_{{message.id}}"><?php putGS('Processed'); ?></label>
        &nbsp;&nbsp;
      </li>
      <li>
        <input type="radio" name="action_comment_{{message.id}}" class="action starred" id="starred_{{message.id}}" value="starred" style="height: auto"/>
        <label for="starred_{{message.id}}"><?php putGS('Star'); ?></label>
        &nbsp;&nbsp;
      </li>


      <li><a href="javascript:;" class="actionButton action-reply"><?php putGS('Reply'); ?></a></li>
      <li><a href="javascript:;" id="deleted_{{message.id}}" class="actionButton action"><?php putGS('Delete'); ?></a></li>

    </ul>
  </div>
</td>
<td style="display: none;"></td>
<td style="display: none;"></td>
<td style="display: none;"></td>
</script>

<div class="wrapper">
  <div class="ui-widget-content small-block block-shadow commentsHolder">
    <div class="padded clearfix inner-tabs">
      <div class="tabs">
        <div id="tabs-1">
          <div id="showComments">
            <fieldset><legend><?php putGS('Show'); ?></legend>
            <ul class="status_filter">
              <li class="published" style="display: none;">
                <input type="checkbox" id="show_published" value="approved"> <label for="show_published"><?php putGS('Published'); ?></label>
              </li>
              <li class="new">
                <input type="checkbox" id="show_new" value="pending"> <label for="show_new"><?php putGS('New'); ?></label>
              </li>
              <li class="approved">
                <input type="checkbox" id="show_processed" value="processed"> <label for="show_processed"><?php putGS('Processed'); ?></label>
              </li>
              <li class="hidden">
                <input type="checkbox" id="show_starred" value="starred"> <label for="show_starred"><?php putGS('Starred'); ?></label>
              </li>
            </ul>
            <br>
            <ul class="attachment_filter">
              <li class="none">
                <input type="checkbox" id="show_none" value="none"> <label for="show_none"><?php putGS('With no attachment'); ?></label>
              </li>
              <li class="image">
                <input type="checkbox" id="show_image" value="image"> <label for="show_image"><?php putGS('With image attachment'); ?></label>
              </li>
              <li class="document">
                <input type="checkbox" id="show_document" value="document"> <label for="show_document"><?php putGS('With document attachment'); ?></label>
              </li>
            </ul>
            </fieldset>
          </div>
          <?php $this->renderDatatable(); ?>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="fancybox-tmp"></div>
<div id="fancybox-loading">
  <div></div>
</div>
<div id="fancybox-overlay"></div>
<div id="fancybox-wrap">
  <div id="fancybox-outer">
    <div class="fancybox-bg" id="fancybox-bg-n"></div>
    <div class="fancybox-bg" id="fancybox-bg-ne"></div>
    <div class="fancybox-bg" id="fancybox-bg-e"></div>
    <div class="fancybox-bg" id="fancybox-bg-se"></div>
    <div class="fancybox-bg" id="fancybox-bg-s"></div>
    <div class="fancybox-bg" id="fancybox-bg-sw"></div>
    <div class="fancybox-bg" id="fancybox-bg-w"></div>
    <div class="fancybox-bg" id="fancybox-bg-nw"></div>
    <div id="fancybox-content"></div>
    <a id="fancybox-close"></a>
    <div id="fancybox-title"></div>
    <a href="javascript:;" id="fancybox-left"><span class="fancy-ico"
      id="fancybox-left-ico"></span></a><a href="javascript:;"
      id="fancybox-right"><span class="fancy-ico" id="fancybox-right-ico"></span></a>
  </div>
</div>
<div class="dialogPopup dialog-1" title="<?php putGS('Full article');?>"></div>
