<?php
    /* @var Zend_View_Helper_HeadLink */
    $headStyle = $this->headLink();
    $headStyle->appendStylesheet($this->baseUrl('/admin-style/comments.css'));
    $headStyle->offsetSetStylesheet('table','');
?>
<?php $this->headScript()->appendFile($this->baseUrl('/js/jquery/doT.js')); ?>
<?php $this->headScript()->appendFile($this->baseUrl('/js/jquery/jquery.ba-iff.js')); ?>
<?php $this->headScript()->appendFile($this->baseUrl('/js/jquery/jquery.version.js')); ?>
<?php $this->headScript()->appendFile($this->baseUrl('/js/jquery/feedback.js')); ?>

<?php $this->placeholder('title')->set(getGS('Feedback')); ?>
<script>
    function putGS(str) {
        var msg = serverObj.translateObj[serverObj.languageObj.indexOf(str)]
        for(i=1, counti=arguments.length; i<counti; i++) {
            msg = msg.replace(new RegExp("\\$"+i,"g"),arguments[i]);
        }
        return msg;
    }
    var serverObj = {};
    serverObj.security = {};
    serverObj.security = {<?php echo SecurityToken::JsParameter(); ?>};

    serverObj.languageObj = [
        'Search',
        'Comments updated.',
        'Comments deleted.',
        'Comments status change to $1.',
        'Comment updated.',
        'Comment deleted.',
        'Comment status change to $1.',
        'Change selected comments status',
        'New',
        'Approved',
        'Hidden',
        'Deleted',
        'Unable to reach Newscoop. Please check your internet connection.',
        'You are about to permanently delete a comment.',
        'You are about to permanently delete multiple comments.',
        'Are you sure you want to do it?'
    ];
    
    serverObj.translateObj = [
        '<?php putGS('Search'); ?>',
        '<?php putGS('Comments updated.'); ?>',
        '<?php putGS('Comments deleted.'); ?>',
        '<?php putGS('Comments status change to $1.'); ?>',
        '<?php putGS('Comment updated.'); ?>',
        '<?php putGS('Comment deleted.'); ?>',
        '<?php putGS('Comment status change to $1.'); ?>',
        '<?php putGS('Change selected comments status'); ?>',
        '<?php putGS('New'); ?>',
        '<?php putGS('Approved'); ?>',
        '<?php putGS('Hidden'); ?>',
        '<?php putGS('Deleted'); ?>',
        '<?php putGS('Unable to reach Newscoop. Please check your internet connection.'); ?>',
        <?php echo json_encode(getGS("You are about to permanently delete a comment.")); ?>,
        <?php echo json_encode(getGS("You are about to permanently delete multiple comments.")); ?>,
        <?php echo json_encode(getGS("Are you sure you want to do it?")); ?>
    ];
</script>
<table>
  <tr>
  </tr>
</table>

<script id="comment-tmpl" type="text/html">
<td colspan="4">
  <table cellspacing="0" cellpadding="0" style="width:100%">
    <tbody>
      <tr>
        <td class="commentId sorting_1">
          <input type="checkbox" name="index[]" value="{{message.id}}" class="table-checkbox">
          <span class="index">{{index}}.</span>
        </td>
        <td class="commentUser">
          <div class="commentUserHolder">
            <div>
              <img src="{{user.avatar}}">
            </div>
            <p>
            <p><b>{{user.username}}</b></p>
            <p>{{user.name}}</p>
                    
            <p><a href="mailto:{{user.email}}">{{user.email}}</a></p>
            <p><a href="{{user.url}}">{{user.url}}</a></p>
            <p><a href="{{user.banurl}}" class="banUser"><span><?php putGS('Ban user'); ?></span></a></p>
            </p>
          </div>
        </td>
        <td class="commentMessage">
          <div class="dateCommentHolder">
            <h4>
              <span>{{message.created.date}} <?php putGS('at'); ?> {{message.created.time}}</span>
              <span class="commentSubject">{{message.subject}}</span>
            </h4>
            <p class="commentBody">{{message.message}}</p>
          </div>

          <div class="dateCommentHolderEdit">
            <fieldset class="content-edit" style="display:none;">
              <?php /*echo $this->editForm->setTemplate(array('comment'));*/ ?>
            </fieldset>
          </div>
        </td>
        <td>
          <div class="commentArticleHolder">
            <p class="commentBody">{{url}}</p>
          </div>
        </td>
      </tr>
    </tbody>
  </table>
  <div class="commentBtns">
    <ul>
      <li>
        <input type="radio" name="action_comment_{{message.id}}" class="action new" id="pending_{{message.id}}" value="pending"/>
        <label for="pending_{{message.id}}"><?php putGS('New'); ?></label>
        &nbsp;&nbsp;
      </li>

      <li>
        <input type="radio" name="action_comment_{{message.id}}" class="action approved" id="approved_{{message.id}}" value="approved"/>
        <label for="approved_{{message.id}}"><?php putGS('Processed'); ?></label>
        &nbsp;&nbsp;
      </li>
      <li>
        <input type="radio" name="action_comment_{{message.id}}" class="action hidden" id="hidden_{{message.id}}" value="hidden" style="height: auto"/>
        <label for="hidden_{{message.id}}"><?php putGS('Star'); ?></label>
        &nbsp;&nbsp;
      </li>


      <li><a href="javascript:;" class="actionButton action-reply"><?php putGS('Reply'); ?></a></li>
      <li><a href="javascript:;" id="deleted_{{message.id}}" class="actionButton action"><?php putGS('Delete'); ?></a></li>

    </ul>
  </div>
</td>
<td style="display: none;"></td>
<td style="display: none;"></td>
<td style="display: none;"></td>
</script>

<div class="wrapper">
  <div class="ui-widget-content small-block block-shadow commentsHolder">
    <div class="padded clearfix inner-tabs">
      <div class="tabs">
        <div id="tabs-1">
          <div id="showComments">
            <fieldset><legend><?php putGS('Show'); ?></legend>
            <ul class="status_filter">
              <li class="published" style="display: none;">
                <input type="checkbox" id="show_published" value="approved"> <label for="show_published"><?php putGS('Published'); ?></label>
              </li>
              <li class="new">
                <input type="checkbox" id="show_new" value="pending"> <label for="show_new"><?php putGS('New'); ?></label>
              </li>
              <li class="approved">
                <input type="checkbox" id="show_approved" value="approved"> <label for="show_approved"><?php putGS('Processed'); ?></label>
              </li>
              <li class="hidden">
                <input type="checkbox" id="show_hidden" value="hidden"> <label for="show_hidden"><?php putGS('Starred'); ?></label>
              </li>
              <li class="multipart">
                <input type="checkbox" id="show_multipart" value="multipart"> <label for="show_multipart"><?php putGS('With Files Attached'); ?></label>
              </li>
            </ul>
            </fieldset>
          </div>
          <?php $this->renderDatatable(); ?>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="fancybox-tmp"></div>
<div id="fancybox-loading">
  <div></div>
</div>
<div id="fancybox-overlay"></div>
<div id="fancybox-wrap">
  <div id="fancybox-outer">
    <div class="fancybox-bg" id="fancybox-bg-n"></div>
    <div class="fancybox-bg" id="fancybox-bg-ne"></div>
    <div class="fancybox-bg" id="fancybox-bg-e"></div>
    <div class="fancybox-bg" id="fancybox-bg-se"></div>
    <div class="fancybox-bg" id="fancybox-bg-s"></div>
    <div class="fancybox-bg" id="fancybox-bg-sw"></div>
    <div class="fancybox-bg" id="fancybox-bg-w"></div>
    <div class="fancybox-bg" id="fancybox-bg-nw"></div>
    <div id="fancybox-content"></div>
    <a id="fancybox-close"></a>
    <div id="fancybox-title"></div>
    <a href="javascript:;" id="fancybox-left"><span class="fancy-ico"
      id="fancybox-left-ico"></span></a><a href="javascript:;"
      id="fancybox-right"><span class="fancy-ico" id="fancybox-right-ico"></span></a>
  </div>
</div>
<div class="dialogPopup dialog-1" title="<?php putGS('Full article');?>"></div>
