<?php
// Call CampURITest::main() if this source file is executed directly.
if (!defined("PHPUnit_MAIN_METHOD")) {
    define("PHPUnit_MAIN_METHOD", "CampURITest::main");
}

require_once('PHPUnit/Framework/TestCase.php');
require_once('PHPUnit/Framework/TestSuite.php');

require_once('template_engine/classes/CampURI.php');

require_once('set_path.php');

/**
 * Test class for CampURI.
 * Generated by PHPUnit_Util_Skeleton on 2007-08-01 at 12:24:00.
 */
class CampURITest extends PHPUnit_Framework_TestCase
{
    /**
     *
     */
    var $m_uri = null;

    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main()
    {
        require_once('PHPUnit/TextUI/TestRunner.php');

        $suite  = new PHPUnit_Framework_TestSuite('CampURITest');
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture, for example, open a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
   	{
        $this->m_uri = 'http://johndoe:bubagump@www.johndoeswebsite.org:8080/somepage.php?mv1=val1&mv2=val2&mv3=val3';
        $this->m_uriObj = CampURI::singleton($this->m_uri);

        $this->m_uriParted['scheme'] = 'http';
        $this->m_uriParted['user'] = 'johndoe';
        $this->m_uriParted['password'] = 'bubagump';
        $this->m_uriParted['host'] = 'www.johndoeswebsite.org';
        $this->m_uriParted['port'] = '8080';
        $this->m_uriParted['path'] = '/somepage.php';
        $this->m_uriParted['query'] = 'mv1=val1&mv2=val2&mv3=val3';
    }

    /**
     * Tears down the fixture, for example, close a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    public function testGetScheme()
    {
    	$this->assertEquals($this->m_uriParted['scheme'], $this->m_uriObj->getScheme());
    }

    public function testGetHost()
    {
        $this->assertEquals($this->m_uriParted['host'], $this->m_uriObj->getHost());
    }

    public function testGetPort()
    {
        $this->assertEquals($this->m_uriParted['port'], $this->m_uriObj->getPort());
    }

    public function testGetUser()
    {
        $this->assertEquals($this->m_uriParted['user'], $this->m_uriObj->getUser());
    }

    public function testGetPassword()
    {
        $this->assertEquals($this->m_uriParted['password'], $this->m_uriObj->getPassword());
    }

    public function testGetPath()
    {
        $this->assertEquals($this->m_uriParted['path'], $this->m_uriObj->getPath());
    }

    public function testGetQuery()
    {
        $this->assertEquals($this->m_uriParted['query'], $this->m_uriObj->getQuery());
    }

    public function testQueryArrayToString()
    {
        $queryArray = array('mv1' => 'val1',
                            'mv2' => 'val2',
                            'mv3' => 'val3');
        $toString = CampURI::QueryArrayToString($queryArray);
        $this->assertEquals($this->m_uriParted['query'], $toString);
    }

}

// Call CampURITest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == "CampURITest::main") {
    CampURITest::main();
}
?>