<?php
// Call CampURITemplatePathTest::main() if this source file is executed directly.
if (!defined("PHPUnit_MAIN_METHOD")) {
    define("PHPUnit_MAIN_METHOD", "CampURITemplatePathTest::main");
}

require_once('PHPUnit/Framework/TestCase.php');
require_once('PHPUnit/Framework/TestSuite.php');

require_once('template_engine/classes/CampURITemplatePath.php');

require_once('set_path.php');

/**
 * Test class for CampURITemplatePath.
 * Generated by PHPUnit_Util_Skeleton on 2007-07-02 at 13:27:00.
 */
class CampURITemplatePathTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var object
     */
    protected $m_uri = null;

    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main()
    {
        require_once('PHPUnit/TextUI/TestRunner.php');

        $suite  = new PHPUnit_Framework_TestSuite('CampURITemplatePathTest');
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture, for example, open a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
   	{
        $uri1 = 'http://www.campware.org/look/article.tpl?IdPublication=1&IdLanguage=1&NrIssue=100&NrSection=1000&NrArticle=704';
        $this->m_uri1 = CampURITemplatePath::singleton($uri1);
        
        $uri2 = 'http://www.campware.org/look/section.tpl?IdPublication=1&IdLanguage=1&NrIssue=100';
        $this->m_uri2 = CampURITemplatePath::singleton($uri2);
        
        $uri3 = 'http://www.campware.org/';
        $this->m_uri3 = CampURITemplatePath::singleton($uri3);
    }

    /**
     * Tears down the fixture, for example, close a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    public function testBuildURI()
    {
    	$this->assertEquals('/look/article.tpl?IdPublication=1&IdLanguage=1&NrIssue=100&NrSection=1000&NrArticle=704', $this->m_uri1->buildURI());
        $this->assertEquals('/look/section.tpl?IdPublication=1&IdLanguage=1&NrIssue=100', $this->m_uri2->buildURI());
        $this->assertEquals('/', $this->m_uri3->buildURI());
    }
    
    public function testGetHost()
    {
        $this->assertEquals('www.campware.org', $this->m_uri->getHost());
    }
    
    public function testGetRequestURI()
    {
        $this->assertEquals('/look/article.tpl?IdPublication=1&IdLanguage=1&NrIssue=100&NrSection=1000&NrArticle=704', $this->m_uri->getRequestURI());
    }
    
    public function testGetTemplate()
    {
        $this->assertEquals('article.tpl', $this->m_uri1->getTemplate());
    }

    public function testIsValidTemplate()
    {
        $this->assertEquals(true, $this->m_uri1->isValidTemplate('article.tpl'));
    }

    public function testGetLanguageId()
    {
        $this->assertEquals(1, $this->m_uri1->getQueryVar('IdLanguage'));
    }

    public function testGetPublicationId()
    {
        $this->assertEquals(1, $this->m_uri1->getQueryVar('IdPublication'));
    }

    public function testGetIssueNumber()
    {
        $this->assertEquals(100, $this->m_uri1->getQueryVar('NrIssue'));
    }
    
    public function testGetSectionNumber()
    {
        $this->assertEquals(1000, $this->getQueryVar('NrSection'));
    }
    
    public function testGetArticleNumber()
    {
        $this->assertEquals(704, $this->getQueryVar('NrArticle'));
    }
}

// Call CampURITemplatePathTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == "CampURITemplatePathTest::main") {
    CampURITemplatePathTest::main();
}
?>