<?php $this->placeholder('title')->set(getGS("Edit template: $1 (Template ID: $2)", $this->template->getBasename(), $this->template->getId())); ?>

<div class="template">
    <?php echo $this->replaceForm; ?>

    <div class="image">
        <img src="<?php echo $this->baseUrl('templates/' . $this->template->getKey() . '?time=' . time()); ?>" alt="<?php echo $this->template->getKey(); ?>" />
    </div>
</div>
