<?php $this->placeholder('title')->set(getGS('File manager')); ?>

<ul class="actions" style="font-size:1.3em;margin:0;">
    <li><a href="<?php echo $this->url(array(
        'action' => 'upload',
    )); ?>"><?php putGS('Upload'); ?></a></li>

    <li><a href="#create-folder"><?php putGS('Create folder'); ?></a></li>
    <li><a href="#create-file"><?php putGS('Create file'); ?></a></li>
</ul>
<div style="clear:both"></div>

<table class="themeTemplatesTable templates">
    <?php if (empty($this->path)) { ?>
    <caption><?php putGS('Templates'); ?></caption>
    <?php } else { ?>
    <caption><a href="<?php echo $this->url(array(
        'path' => NULL,
    )); ?>"><?php putGS('Templates'); ?></a> / <?php echo $this->navigation()->breadcrumbs()
        ->setContainer($this->nav)
        ->setMinDepth(0)
        ->setSeparator(' / ');
    ?></caption>
    <?php } ?>

<thead>
<tr>
    <th class="id"><input type="checkbox" name="toggle" class="all" /></th>
    <th><?php putGS('File name'); ?></th>
    <th><?php putGS('Template Id'); ?></th>
    <th><?php putGS('Type'); ?></th>
    <th class="size"><?php putGS('File size'); ?></th>
    <th><?php putGS('Last modified'); ?></th>
    <th></th><!-- size in bytes for sorting -->
    <th></th>
</tr>

<?php if (!empty($this->path)) { ?>
<tr class="parent">
    <td class="id"></td>
    <td><a href="<?php echo $this->url(array(
        'path' => $this->parent,
    )); ?>" class="upOneLevel" title="<?php putGS('Go to parent'); ?>"><?php putGS('Go to parent'); ?></a></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
</tr>
<?php } ?>

</thead>
<tbody>

<?php foreach ($this->folders as $folder) { ?>
<tr class="collection">
    <td class="id"><input type="checkbox" name="file[]" value="<?php echo $folder; ?>" /></td>
    <td><a href="<?php echo $this->url(array(
        'path' => ltrim($this->path . $this->separator . $folder, $this->separator),
    )); ?>" class="folder" title="<?php putGS("Go to '$1'", $folder); ?>"><?php echo $folder; ?></a></td>
    <td></td>
    <td>dir</td>
    <td></td>
    <td></td>
    <td>-1</td>

    <td class="menu"><ul class="actionDropDown">
        <li><a href="#"><?php putGS('Actions'); ?></a><ul>
            <li><a href="#rename" class="rename">Rename</a></li>
            <li><a href="#move" class="duplicate">Move</a></li>
            <li><a href="<?php echo $this->url(array(
                'action' => 'delete',
                'path' => $this->path,
                'file' => $folder,
            )); ?>" class="delete">Delete</a></li>
        </ul></li>
    </ul></td>
</tr>
<?php } ?>

<?php foreach ($this->templates as $file) { ?>
<tr class="template">
    <td class="id"><input type="checkbox" name="file[]" value="<?php echo $file->getBasename(); ?>" /></td>
    <td><a href="<?php echo $this->url(array(
        'action' => 'edit',
        'path' => $this->path,
        'file' => $file->getBasename(),
    )); ?>" class="file" title="<?php putGS("Edit '$1'", $file); ?>"><?php echo $file; ?></a></td>
    <td><?php echo $file->getId(); ?></td>
    <td><?php echo $file->getType(); ?></td>
    <td class="size"><?php echo $this->formatBytes($file->getSize()); ?></td>
    <td><?php echo $file->getChangeTime()->format($this->dateFormat); ?></td>
    <td><?php echo $file->getSize(); ?></td>

    <td class="menu"><ul class="actionDropDown">
        <li><a href="#"><?php putGS('Actions'); ?></a><ul>
            <li><a href="#rename" class="rename">Rename</a></li>
            <li><a href="#move" class="duplicate">Move</a></li>
            <li><a href="#copy" class="duplicate">Copy</a></li>
            <li><a href="<?php echo $this->url(array(
                'action' => 'delete',
                'path' => $this->path,
                'file' => $file->getBasename(),
            )); ?>" class="delete">Delete</a></li>
        </ul></li>
    </ul></td>
</tr>
<?php } ?>
</tbody>
</table>

<div class="dialogPopup" title="<?php putGS('New name'); ?>">
<?php echo $this->dialogForm; ?>
</div>

<script type="text/javascript">
$(function() {
    // actions
	$(".actionDropDown li").hover(function(){
		$(this).children("ul").css("display","block");
		$(this).children("a").addClass("active");
		}, function() {
		$(this).children("ul").css("display","none");
		$(this).children("a").removeClass("active");
		});

	$(".actionDropDown li ul li").hover(function(){
		$(this).children("ul").css("display","block");
		}, function() {
		$(this).childer("ul").css("display","none");
	});

    // dialog
	$('.dialogPopup').dialog({
		autoOpen: false,
		width: 400,
		resizable: false,
		modal: true,
		position:'center',
		buttons: {
            <?php echo json_encode(getGS('Save')); ?>: function() { 
                var form = $('form', $(this));
                var name = $('input[name="name"]', form).val();
                if (!name.length) {
                    alert(<?php echo json_encode(getGS("Name can't be empty")); ?>);
                    return;
                }

                form.submit();
			}, 
            <?php echo json_encode(getGS('Cancel')); ?>: function() { 
				$(this).dialog("close"); 
			} 
        }
	});
				
	// edit dialog
	$('table.templates a[href^="#"]').click(function() {
        var action = $(this).attr('href').substr(1);
        $('form input[name="action"]', $('.dialogPopup')).val(action);

        var file = $('td.id input[name^="file"]', $(this).closest('tr')).val();
        $('form input[name="file"]', $('.dialogPopup')).val(file);

		$('.dialogPopup').dialog('open');
		return false;
	});

    // create dialog
    $('.actions a[href^="#"]').click(function() {
        var action = $(this).attr('href').substr(1);
        $('form input[name="action"]', $('.dialogPopup')).val(action);

		$('.dialogPopup').dialog('open');
		return false;
    });

    $('table.templates').dataTable({
        'aoColumnDefs': [
            { 'bSortable': false, 'aTargets': [0, -1] },
            { 'bVisible': false, 'aTargets': [-2] },
            { 'iDataSort': [6], 'aTargets': [4] }
        ],
        'sDom': 't',
        'bPaginate': false,
        'bJQueryUI': true
    });
});
</script>
