<?php $this->placeholder('title')->set(getGS('Upload')); ?>

<?php if (!$this->isWritable) {
    echo $this->renderError(getGS("'$1' is not writable", $this->destination->getRealpath()));
    return;
} ?>

<?php echo $this->form; ?>

<?php $this->plupload(); ?>

<script type="text/javascript">
$(function() {
    // get existing files for given path
    var items = [];
    $.getJSON('<?php echo $this->url(array(
        'action' => 'get-items',
        'format' => 'json',
    )); ?>', function(data) {
        items = data.items;
    });

    // ask for confirmation if file would override existing
    uploader = $('#uploader').pluploadQueue();
    uploader.bind('FilesAdded', function(up, files) {
        for (i in files) {
            var file = files[i];
            for (j in items) {
                var item = items[j];
                if (item.name == file.name) { // conflict
                    if (!item.id) { // dir
                        alert("<?php putGS("Can't override directory '$1'.", '" + item.name + "'); ?>");
                        up.removeFile(file);
                    } else if (!confirm("<?php putGS("Do you want to override '$1'?", '" + file.name + "'); ?>")) {
                        up.removeFile(file);
                    }

                    break;
                }
            }
        }
    });
});
</script>
