<?php $rand_int = md5(uniqid("", true)); ?>

<div><?php echo $this->headScript(); ?></div>
<div><?php echo $this->headLink(); ?></div>

<div id="wobs_calendar_<?php echo($rand_int); ?>" class="wobs-calendar wobs-calendar-full"></div>

<script>

function formatDate(date)
{
    var s = '';
    var yyyy, mm, dd;

    yyyy = date.getFullYear();
    mm = date.getMonth()+1;
    mm = mm.toString();
    dd = date.getDate();
    dd = dd.toString();

    if (mm.length === 1) {
        mm = "0"+mm;
    }
    if (dd.length === 1) {
        dd = "0"+dd;
    }

    s = yyyy + "-" + mm + "-" + dd;
    return s;
}

function getArticlesOfTheDay( start, end, callback )
{
	var search_start, search_end;

    search_start = formatDate(start);
    search_end = formatDate(end);

    $.post("<?php echo $this->baseUrl('/articleoftheday/article-of-the-day'); ?>",
    	{"format": "json", "start": search_start, "end": search_end,
    	    "publication_id": "<?php echo($this->gimme->publication->identifier); ?>",
    	    "language_id": "<?php echo($this->gimme->language->number); ?>"
        },
    	function(data){
        	callback(data.articles);
    	},
    	"json"
    );
}

$("#wobs_calendar_<?php echo($rand_int); ?>").wobscalendar({
	'today': new Date('<?php echo($this->today[0]); ?>', '<?php echo($this->today[1]-1); ?>', '<?php echo($this->today[2]); ?>'),
	'date': new Date('<?php echo($this->year); ?>', '<?php echo($this->month); ?>', '<?php echo($this->day); ?>'),
	'articles': getArticlesOfTheDay,
	'defaultView': '<?php echo($this->view); ?>',
	'firstDay': <?php echo($this->firstDay); ?>,
	'navigation': <?php if($this->nav){echo 'true';}else{ echo 'false';}?>,
	'showDayNames': <?php if($this->dayNames){echo 'true';}else{ echo 'false';}?>
});
</script>
