<div id="wobs_calendar"></div>

<script type="text/javascript" src="<?php echo $this->baseUrl('/js/jquery/jquery.wobscalendar.js'); ?>"></script>

<script>

function formatDate(date)
{
    var s = '';
    var yyyy, mm, dd;

    yyyy = date.getFullYear();
    mm = date.getMonth()+1;
    mm = mm.toString();
    dd = date.getDate();
    dd = dd.toString();

    if (mm.length === 1) {
        mm = "0"+mm;
    }
    if (dd.length === 1) {
        dd = "0"+dd;
    }

    s = yyyy + "-" + mm + "-" + dd;
    return s;
}

function getArticlesOfTheDay( start, end, callback )
{
	var search_start, search_end;

    search_start = formatDate(start);
    search_end = formatDate(end);

    $.post("<?php echo $this->baseUrl('/articleoftheday/article-of-the-day'); ?>",
    	{"format": "json", "start": search_start, "end": search_end,
    	    "publication_id": "<?php echo($this->gimme->publication->identifier); ?>",
    	    "language_id": "<?php echo($this->gimme->language->number); ?>"
        },
    	function(data){
        	callback(data.articles);
    	},
    	"json"
    );
}

$("#wobs_calendar").wobscalendar({
	name: "Cool Calendar",
	articles: getArticlesOfTheDay
});
</script>
