#!/bin/bash

mkdir -p "$BIN_DIR"
cp -f notifyendsubs "$BIN_DIR"
cp -f notifyevents "$BIN_DIR"
chown $ROOT_USER:$APACHE_GROUP "$BIN_DIR/notifyendsubs" "$BIN_DIR/notifyevents"
chmod 750 "$BIN_DIR/notifyendsubs"
chmod 750 "$BIN_DIR/notifyevents"

if $USER_INSTALL; then exit 0; fi

. ${INSTALL_CONF}/cron_functions
if [ -f /etc/crontab ]; then
    uninstall_cron_task "$BIN_DIR/notifyendsubs" /etc/crontab
    uninstall_cron_task "$BIN_DIR/notifyevents" /etc/crontab
fi
install_cron_task "0" "*/8" "*" "*" "*" "$ROOT_USER" "$BIN_DIR/notifyendsubs" "/etc/cron.d/notifyendsubs" || exit 1
install_cron_task "*/2" "*" "*" "*" "*" "$ROOT_USER" "$BIN_DIR/notifyevents" "/etc/cron.d/notifyevents" || exit 1
restart_cron || exit 1
exit 0
