<?php $this->renderError(); ?>

<?php foreach ($this->resources as $resource) {
    if (!$resource->getRules() && !$resource->getRules(TRUE)) { // ignore empty
        continue;
    }
?>
<dl class="resource">
    <dt><?php echo $resource->getName(); ?></dt>
    <?php foreach ($resource->getRules(TRUE) as $rule) { ?>
    <dd class="inherited <?php echo $rule->getType(); ?>">
        <strong><?php echo $this->ruleTypes[$rule->getType()]; ?></strong>
        <?php echo $rule->getActionName() ?: getGS('Any action'); ?>
    </dd>
    <?php } ?>
    <?php foreach ($resource->getRules() as $rule) { ?>
    <dd class="<?php echo $rule->getType(); ?>">
        <a class="delete" href="<?php echo $this->url(array(
            'action' => 'delete',
            'controller' => 'acl',
            'rule' => $rule->getId(),
        )); ?>"><?php putGS('Remove'); ?></a>
        <strong><?php echo $this->ruleTypes[$rule->getType()]; ?></strong>
        <?php echo $rule->getActionName() ?: getGS('Any action'); ?>
    </dd>
    <?php } ?>
</dl>
<?php } ?>

<?php echo $this->form->render(); ?>
<script type="text/javascript">
$(function() {
    // list actions per resource
    var actions_default = $('select[name=action]').html();
    $('select[name=resource]').change(function() {
        var resource = $(this).val();
        var actions = $('select[name=action]', $(this).closest('dl')).first();

        // reset
        actions.html(actions_default);

        if (resource == 0) { // show all
            return;
        }

        // hide actions not used for resource
        $.getJSON('<?php echo $this->url(array('action' => 'actions', 'controller' => 'acl', 'format' => 'json')); ?>', {
            'resource': resource
        }, function(data) {
            $('option', actions).each(function() {
                var option = $(this);
                if (option.val() > 0 && $.inArray(parseInt(option.val()), data.actions) < 0) {
                    option.detach();
                }
            });
        });
    });
});
</script>
