<?php
$hasRules = false; // any rules?
foreach ($this->resources as $resource) {
    if (!$resource->getRules() && !$resource->getRules(TRUE)) { // ignore empty
        continue;
    }

    $hasRules = true; // yes
?>
<dl class="resource">
    <dt><?php echo $resource->getName(); ?></dt>
    <?php foreach ($resource->getRules(TRUE) as $rule) { ?>
    <dd class="inherited <?php echo $rule->getType(); ?>">
        <strong><?php echo $this->ruleTypes[$rule->getType()]; ?></strong>
        <?php echo $rule->getActionName() ?: getGS('Any action'); ?>
    </dd>
    <?php } ?>
    <?php foreach ($resource->getRules() as $rule) { ?>
    <dd class="<?php echo $rule->getType(); ?>">
        <a class="delete icon" href="<?php echo $this->url(array(
            'action' => 'delete',
            'controller' => 'acl',
            'rule' => $rule->getId(),
        )); ?>" title="<?php putGS('Remove rule'); ?>"><?php putGS('Remove'); ?></a>
        <strong><?php echo $this->ruleTypes[$rule->getType()]; ?></strong>
        <?php echo $rule->getActionName() ?: getGS('Any action'); ?>
    </dd>
    <?php } ?>
</dl>
<?php } ?>

<?php if (!$hasRules) {
    echo $this->renderMessage(getGS('No rules.'));
} ?>
