<?php
    /* @var Zend_View_Helper_HeadLink */
    $headStyle = $this->headLink();
    $headStyle->appendStylesheet($this->baseUrl('/admin-style/comments.css'));
    $headStyle->offsetSetStylesheet('table','');
    $translator = \Zend_Registry::get('container')->getService('translator');
?>
<?php $this->headScript()->appendFile($this->baseUrl('/js/jquery/doT.js')); ?>
<?php $this->headScript()->appendFile($this->baseUrl('/js/jquery/jquery.ba-iff.js')); ?>
<?php $this->headScript()->appendFile($this->baseUrl('/js/jquery/jquery.version.js')); ?>
<?php $this->headScript()->appendFile($this->baseUrl('/js/jquery/comment.js')); ?>

<?php $this->placeholder('title')->set($translator->trans('Comments')); ?>
<script>
    function putGS(str) {
        var msg = serverObj.translateObj[serverObj.languageObj.indexOf(str)]
        for(i=1, counti=arguments.length; i<counti; i++) {
            msg = msg.replace(new RegExp("\\$"+i,"g"),arguments[i]);
        }
        return msg;
    }
    var serverObj = {};
    serverObj.security = {};
    serverObj.security = {<?php echo SecurityToken::JsParameter(); ?>};

    serverObj.languageObj = [
        'Search',
        'Comments updated.',
        'Comments deleted.',
        'Comments status change to $1.',
        'Comment updated.',
        'Comment deleted.',
        'Comment status change to $1.',
        'Actions',
        'Select status',
        'New',
        'Approved',
        'Hidden',
        'Deleted',
        'Unable to reach Newscoop. Please check your internet connection.',
        'You are about to permanently delete a comment.',
        'You are about to permanently delete multiple comments.',
        'Are you sure you want to do it?',
        'Close'
    ];

    serverObj.translateObj = [
        '<?php echo $translator->trans('Search'); ?>',
        '<?php echo $translator->trans('Comments updated.', array(), 'comments'); ?>',
        '<?php echo $translator->trans('Comments deleted.', array(), 'comments'); ?>',
        '<?php echo $translator->trans('Comments status change to $1.', array(), 'comments'); ?>',
        '<?php echo $translator->trans('Comment updated.', array(), 'comments'); ?>',
        '<?php echo $translator->trans('Comment deleted.', array(), 'comments'); ?>',
        '<?php echo $translator->trans('Comment status change to $1.', array(), 'comments'); ?>',
        '<?php echo $translator->trans('Actions'); ?>',
        '<?php echo $translator->trans('Select status', array(), 'comments'); ?>',
        '<?php echo $translator->trans('New'); ?>',
        '<?php echo $translator->trans('Approved', array(), 'comments'); ?>',
        '<?php echo $translator->trans('Hidden'); ?>',
        '<?php echo $translator->trans('Deleted', array(), 'comments'); ?>',
        '<?php echo $translator->trans('Unable to reach Newscoop. Please check your internet connection.', array(), 'comments'); ?>',
        <?php echo json_encode($translator->trans("You are about to permanently delete a comment.", array(), 'comments')); ?>,
        <?php echo json_encode($translator->trans("You are about to permanently delete multiple comments.", array(), 'comments')); ?>,
        <?php echo json_encode($translator->trans("Are you sure you want to do it?", array(), 'comments')); ?>,
        '<?php echo $translator->trans('Close'); ?>',
    ];
</script>
<table>
    <tr>
  </tr>
</table>

<script id="comment-tmpl" type="text/html">
<td colspan="4">
    <table cellspacing="0" cellpadding="0" style="width:100%">
            <tbody><tr>
                    <td class="commentId sorting_1">
                        <input type="checkbox" name="index[]" value="{{comment.id}}" class="table-checkbox">
                        <span class="index">{{index}}.</span>
                    </td>
                    <td class="commentUser">
                        <div class="commentUserHolder">
                            <div{% if (commenter.is.banned.name || commenter.is.banned.email || commenter.is.banned.ip) %} class="user-blocked-avatar"{% endif %}>
                                <img src="{{commenter.avatar}}">
                            </div>
                            <p>
                                <p class="{% if (commenter.is.banned.name) %}user-blocked-avatar{% endif %}">
                                    {% if (commenter.username) %}<a href="<?php echo($this->baseUrl('/profile/')); ?>{{commenter.usernameEncoded}}">{{commenter.username}}</a>{% endif %}
                                    {% if (!commenter.username) %}{{commenter.name}} (<?php echo $translator->trans('Anonymous', array(), 'comments') ?>){% endif %}
                                </p>
                                <p class="{% if (commenter.is.banned.ip) %}user-blocked-avatar{% endif %}"><a target="_blank" href="{{commenter.trace.ip}}">{{commenter.ip}}</a></p>
                                <p class="{% if (commenter.is.banned.email) %}user-blocked-avatar{% endif %}"><a href="mailto:{{commenter.email}}">{{commenter.email}}</a></p>
                                <p><a href="{{commenter.url}}">{{commenter.url}}</a></p>
                                <p><a href="{{commenter.banurl}}" class="banUser"><span><?php echo $translator->trans('Ban/Unban user', array(), 'comments'); ?></span></a></p>
                            </p>
                        </div>
                    </td>
                    <td class="commentMessage">
                        <div class="dateCommentHolder">
                            <h4>
                                <span>{{comment.created.date}} <?php echo $translator->trans('at', array(), 'comments'); ?> {{comment.created.time}}</span>
                                <span class="commentSubject">{{comment.subject}}</span>
                            </h4><!--
                            <div class="ratingHolder">
                                <span class="thumbs up">{{comment.likes}}</span>
                                <span class="thumbs down">{{comment.dislikes}}</span> </div>
                                -->
                            <p class="commentBody">{{comment.message}}</p>
                        </div>

                        <div class="dateCommentHolderEdit">
                            <fieldset class="content-edit" style="display:none;">
                                <?php echo $this->editForm->setTemplate(array('comment')); ?>
                            </fieldset>
                        </div>

                        <div class="dateCommentHolderReply">
                            <fieldset class="content-reply" style="display:none;">
                                <h3><?php echo $translator->trans('Reply to comment', array(), 'comments'); ?></h3>
                                <form action="{{comment.action.reply}}">
                                    <input type="hidden" name="parent" value="{{comment.id}}" />
                                    <?php echo SecurityToken::FormParameter(); ?>
                                    <label><?php echo $translator->trans('Subject'); ?></label>
                                    <input name="subject" type="text" class="input_text">
                                    <label><?php echo $translator->trans('Comment'); ?></label>
                                    <textarea name="message" class="input_text_area"></textarea>
                                    <div class="buttonBar">
                                        <input type="button" value="<?php echo $translator->trans('Cancel'); ?>" class="button reply-cancel">
                                        <input type="submit" value="<?php echo $translator->trans('Submit'); ?>" class="button">
                                    </div>
                                </form>
                            </fieldset>
                        </div>
                    </td>
                    <td>
                        <div class="commentArticleHolder">
                            <p>
                                <a href="{{thread.link.get}}" class="articleLink">{{thread.name}}</a>
                                <br>
                                <span>{{thread.forum.name}}; <b><?php echo $translator->trans('Section'); ?></b> {{thread.section.name}}</span>
                            </p>
                            <a class="goToArticle" href="{{thread.link.edit}}"><?php echo $translator->trans('Go to edit article', array(), 'comments'); ?></a> </div>
                    </td>
                </tr></tbody>
        </table>
        <div class="commentBtns">
            <ul>
                <li>
                    <input type="radio" name="action_comment_{{comment.id}}" class="action new" id="pending_{{comment.id}}" value="pending"/>
                    <label for="pending_{{comment.id}}"><?php echo $translator->trans('New'); ?></label>
                    &nbsp;&nbsp;
                </li>
                {% if(can.enable) %}
                <li>
                    <input type="radio" name="action_comment_{{comment.id}}" class="action approved" id="approved_{{comment.id}}" value="approved"/>
                    <label for="approved_{{comment.id}}"><?php echo $translator->trans('Approved', array(), 'comments'); ?></label>

                    &nbsp;&nbsp;
                </li>
                <li>
                    <input type="radio" name="action_comment_{{comment.id}}" class="action hidden" id="hidden_{{comment.id}}" value="hidden" style="height: auto"/>
                    <label for="hidden_{{comment.id}}"><?php echo $translator->trans('Hidden'); ?></label>
                    &nbsp;&nbsp;
                </li>
                {% endif %}



                {% if(can.edit) %}
                <li><a href="javascript:;" class="actionButton action-edit"><?php echo $translator->trans('Quick edit', array(), 'comments'); ?></a></li>
                {% endif %}
                {% if(can.enable) %}
                <li><a href="javascript:;" class="actionButton action-reply"><?php echo $translator->trans('Reply', array(), 'comments'); ?></a></li>
                <li><a href="javascript:;" id="deleted_{{comment.id}}" class="actionButton action"><?php echo $translator->trans('Delete'); ?></a></li>
                
                {% if(comment.recommended == 0) %}
                <li><a href="javascript:;" id="recommend_{{comment.id}}" class="actionButton action-recommend"><?php echo $translator->trans('Recommend', array(), 'comments'); ?></a></li>
                {% endif %}
                
                {% if(comment.recommended == 1) %}
                <li><a href="javascript:;" id="unrecommend_{{comment.id}}" class="actionButton action-unrecommend"><?php echo $translator->trans('Unrecommend', array(), 'comments'); ?></a></li>
                {% endif %}
                
                {% endif %}
                <!--
                <li><a href="javascript:;" class="action-rating link icon-link"><span class="icon ui-icon-star"></span><?php echo $translator->trans('Add rating', array(), 'comments'); ?></a></li>
                -->
            </ul>
        </div>
</td>
<td style="display: none;"></td>
<td style="display: none;"></td>
<td style="display: none;"></td>
</script>

<div class="wrapper">
    <div class="ui-widget-content small-block block-shadow commentsHolder">
        <div class="padded clearfix inner-tabs">
            <div class="tabs">
                <!--
                <ul>
                    <li><a href="#tabs-1">Comments</a></li>
                    <li><a href="#tabs-2">Users</a></li>
                </ul>
                -->
                <div id="tabs-1">
                    <div id="showComments">
                        <fieldset><legend><?php echo $translator->trans('Show'); ?></legend>
                            <ul class="status_filter">
                                <li class="published" style="display: none;"><input type="checkbox"
                                                                                    id="show_published" value="approved"> <label for="show_published"><?php echo $translator->trans('Published'); ?></label>
                                </li>
                                <li class="new"><input type="checkbox" id="show_new" value="pending"> <label
                                        for="show_new"><?php echo $translator->trans('New'); ?></label></li>
                                <li class="approved"><input type="checkbox" id="show_approved"
                                                            value="approved"> <label for="show_approved"><?php echo $translator->trans('Approved', array(), 'comments'); ?></label>
                                </li>
                                <li class="hidden"><input type="checkbox" id="show_hidden"
                                                          value="hidden"> <label for="show_hidden"><?php echo $translator->trans('Hidden'); ?></label>
                                </li>
                                <!--
                                /** @todo change this when the "cron job" like engine is done */
                                <li class="deleted"><input type="checkbox" id="show_deleted"
                                                           value="deleted"> <label for="show_deleted"><?php echo $translator->trans('Deleted'); ?></label>
                                </li>
                                -->
                            </ul><br>
                            <ul class="recommended_filter">
                                <li class="hidden">
                                    <input type="checkbox" id="show_recommended" value="recommended"> 
                                    <label for="show_recommended"><?php echo $translator->trans('Recommended', array(), 'comments'); ?></label>
                                </li>
                                <li class="hidden">
                                    <input type="checkbox" id="show_unrecommended" value="unrecommended"> 
                                    <label for="show_unrecommended"><?php echo $translator->trans('Unrecommended', array(), 'comments'); ?></label>
                                </li>
                            </ul>
                        </fieldset>
                    </div>
                        <div id="actionExpand" class="dataTables_actions">
                            <!-- <a href="javascript:;" class="sort_tread"> <span
                                    class="css_right ui-icon ui-icon-carat-2-n-s"></span> <?php echo $translator->trans('Sort by Thread order', array(), 'comments'); ?>
                            </a>//--></div>
                        <?php $this->renderDatatable(); ?></div>
                </div>
            </div>
        </div>
    </div>
    <div id="fancybox-tmp"></div>
    <div id="fancybox-loading">
        <div></div>
    </div>
    <div id="fancybox-overlay"></div>
    <div id="fancybox-wrap">
        <div id="fancybox-outer">
            <div class="fancybox-bg" id="fancybox-bg-n"></div>
            <div class="fancybox-bg" id="fancybox-bg-ne"></div>
            <div class="fancybox-bg" id="fancybox-bg-e"></div>
            <div class="fancybox-bg" id="fancybox-bg-se"></div>
            <div class="fancybox-bg" id="fancybox-bg-s"></div>
            <div class="fancybox-bg" id="fancybox-bg-sw"></div>
            <div class="fancybox-bg" id="fancybox-bg-w"></div>
            <div class="fancybox-bg" id="fancybox-bg-nw"></div>
            <div id="fancybox-content"></div>
            <a id="fancybox-close"></a>
            <div id="fancybox-title"></div>
            <a href="javascript:;" id="fancybox-left"><span class="fancy-ico"
                                                            id="fancybox-left-ico"></span></a><a href="javascript:;"
                                                 id="fancybox-right"><span class="fancy-ico" id="fancybox-right-ico"></span></a></div>
    </div>
    <div class="dialogPopup dialog-1" title="<?php echo $translator->trans('Full article', array(), 'comments');?>"></div>