<?php $this->headLink()->appendStylesheet($this->baseUrl('/admin-style/comments.css')); ?>
<h2><?php echo $this->name; ?></h2>
<h1><?php putGS('Comments'); ?></h1>
<div class="wrapper">
  <div class="ui-widget-content small-block block-shadow commentsHolder">
    <div class="padded clearfix inner-tabs">
      <div class="tabs">
        <ul>
          <li><a href="#tabs-1">Comments</a></li>
          <li><a href="#tabs-2">Users</a></li>
        </ul>
        <div id="tabs-1">
<div id="showComments">
<fieldset>
<legend><?php putGS('Show');?></legend>
<ul>
    <li class="published">
        <input type="checkbox" id="show_published">
        <label for="show_published">Published</label>
    </li>
    <li class="new">
        <input type="checkbox" id="show_new">
        <label for="show_new">New</label>
    </li>
    <li class="approved">
        <input type="checkbox" id="show_approved">
        <label for="show_approved">Approved</label>
    </li>
    <li class="hidden">
        <input type="checkbox" id="show_hidden">
        <label for="show_hidden">Hidden</label>
    </li>
    <li class="deleted">
        <input type="checkbox" id="show_deleted">
        <label for="show_deleted">Deleted</label>
    </li>
</ul>
</fieldset>
</div>
<?php $this->renderDatatable(); ?>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
var datatableCallback = {
	rowIndex:1,
	row: function(nRow, aData, iDisplayIndex, iDisplayIndexFull) {
	    that = datatableCallback;
	    elIndex = $('.index', nRow);
	    elIndex.text(that.rowIndex+elIndex.text());
        var tr = $('<tr></tr>');
        tr.addClass(that.rowIndex%2?'list_row_odd odd':'list_row_even even');
        tr.hover(function() {
        	   $(this).find(".commentBtns").css("visibility","visible");
            },function() {
            	$(this).find(".commentBtns").css("visibility","hidden");
            });
        var td = $('<td></td>');
        td.attr('colspan',5);
        nRow = $(nRow);
        actions = nRow.find('.commentThreadOrder').first();
        nRow.find('.commentTimeCreated').removeClass('commentTimeCreated').addClass('commentMessage');//.attr('colspan',2);
        nActions = actions.clone();
        actions.hide();
        td.append($('<table cellspacing="0" cellpadding="0">').append(nRow));
        td.append(nActions.html());
        jRow = tr.append(td);
        that.rowIndex++;
        return jRow.get(0);
    },
    draw: function()
    {
    	that = datatableCallback;
    	that.rowIndex =1;
    }
}
</script>