#!/bin/bash

# remove utilities from older versions
rm -f "$BIN_DIR/notifyendsubs"
rm -f "$BIN_DIR/notifyevents"

mkdir -p "$SBIN_DIR"
install -o $ROOT_USER -g $APACHE_GROUP -m 750 campsite_notifyendsubs "$SBIN_DIR"
install -o $ROOT_USER -g $APACHE_GROUP -m 750 campsite_notifyevents "$SBIN_DIR"

if $USER_INSTALL; then exit 0; fi

. ${INSTALL_CONF}/cron_functions

# remove cron tasks from older versions
uninstall_cron_task "$BIN_DIR/notifyendsubs" "/etc/cron.d/notifyendsubs" &> /dev/null
uninstall_cron_task "$BIN_DIR/notifyevents" "/etc/cron.d/notifyevents" &> /dev/null
if [ -f /etc/crontab ]; then
    uninstall_cron_task "$BIN_DIR/notifyendsubs" /etc/crontab &> /dev/null
    uninstall_cron_task "$BIN_DIR/notifyevents" /etc/crontab &> /dev/null
fi

# install our cron tasks
install_cron_task "0" "*/8" "*" "*" "*" "$ROOT_USER" "$SBIN_DIR/campsite_notifyendsubs" "/etc/cron.d/campsite_notifyendsubs" || exit 1
install_cron_task "*/2" "*" "*" "*" "*" "$ROOT_USER" "$SBIN_DIR/campsite_notifyevents" "/etc/cron.d/campsite_notifyevents" || exit 1
restart_cron || exit 1
exit 0
