#!/bin/bash

rm -f "$SBIN_DIR/campsite_notifyendsubs"
rm -f "$SBIN_DIR/campsite_notifyevents"

if $USER_INSTALL; then exit 0; fi

. ${INSTALL_CONF}/cron_functions
if [ -f /etc/crontab ]; then
    uninstall_cron_task "$SBIN_DIR/campsite_notifyendsubs" /etc/crontab
    uninstall_cron_task "$SBIN_DIR/campsite_notifyevents" /etc/crontab
fi
uninstall_cron_task "$SBIN_DIR/campsite_notifyendsubs" "/etc/cron.d/campsite_notifyendsubs" || exit 1
uninstall_cron_task "$SBIN_DIR/campsite_notifyevents" "/etc/cron.d/campsite_notifyevents" || exit 1
restart_cron
exit 0
