<?php
require_once 'PHPUnit/Framework.php';
require_once dirname(__FILE__) . '/../bootstrap.php';

require_once dirname(__FILE__) . '/../../classes/GeoNames.php';

/**
 * Test class for Geo_Names.
 * Generated by PHPUnit on 2010-12-16 at 15:07:30.
 */
class Geo_NamesTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Geo_Names
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Geo_Names;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testFindCitiesByName().
     */
    public function testFindCitiesByName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testFindCitiesByPosition().
     */
    public function testFindCitiesByPosition()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
