<?php
require_once 'PHPUnit/Framework.php';
require_once dirname(__FILE__) . '/../bootstrap.php';

require_once dirname(__FILE__) . '/../../classes/GeoPreferences.php';

/**
 * Test class for Geo_Preferences.
 * Generated by PHPUnit on 2010-12-16 at 15:04:06.
 */
class Geo_PreferencesTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Geo_Preferences
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Geo_Preferences;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testGetMapProviderDefault().
     */
    public function testGetMapProviderDefault()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetMapInfo().
     */
    public function testGetMapInfo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testPrepareMapIncludes().
     */
    public function testPrepareMapIncludes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetIconsInfo().
     */
    public function testGetIconsInfo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetSearchInfo().
     */
    public function testGetSearchInfo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetPopupsInfo().
     */
    public function testGetPopupsInfo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetIconsFiles().
     */
    public function testGetIconsFiles()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
