tinyMCE.addI18n('pl.campsiteimage_dlg',{
title:"Wstaw obraz",
language:"Język",
section:"Sekcja",
article:"Artykuł",
publication:"Publikacja",
general_tab:"Ogólne",
general_props:"Ostawienia ogólne",
issue:"Wydanie",
target:"Cel",
target_same:"Otwórz w tym samym oknie / ramce",
target_parent:"Otwórz w nadrzędnym oknie / ramce",
target_top:"Otwórz w najwyższym oknie",
target_blank:"Otwórz w nowym oknie",
id:"Id",
style:"Style",
classes:"Klasy",
target_name:"Nazwa celu",
langdir:"Kierunek tekstu",
target_langcode:"Język docelowy",
langcode:"Kod języka",
encoding:"Kodowanie",
mime:"DOcelowy typ MIME",
rel:"Relacja strony do celu",
rev:"Relacja targetu do strony",
tabindex:"Indeks tabulacji",
accesskey:"Klawisz dostępu",
ltr:"Od lewej do prawej",
rtl:"Od prawej do lewej",
link_list:"Lista linków",
is_email:"Podany url wygląda na adres email, chcesz dodać do niego wymagant prefix 'mailto:'?",
is_external:"Podany url wygląda na link zewnętrzny, chcesz dodać do niego wymagant prefix protokołu http:// ?",
caption:"Opis",
alt:"Alt",
alignment:"Wyrównanie",
positiontitle:"Pozycja obrazka",
notset:"Nie ustawione",
left:"Lewa",
right:"Prawa",
middle:"Środek",
resizeratio:"Stopień powiększenia",
resizewidth:"Szerokość",
resizeheight:"Wysokość",
edit:"Edycja",
ok:"OK",
cancel:"Anuluj"
});
