#!/bin/sh

################################################################################
#
# CAMPSITE is a Unicode-enabled multilingual web content
# management system for news publications.
# CAMPFIRE is a Unicode-enabled java-based near WYSIWYG text editor.
# Copyright (C)2000,2001  Media Development Loan Fund
# contact: contact@campware.org - http://www.campware.org
# Campware encourages further development. Please let us know.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
################################################################################                                                              

if [ ! -f campsite-db.sql ]; then
    echo "Database dump file does not exist."
    exit 1
fi

[ "$CAMPSITE_PACKAGE_DIR" = "" ] && cd ../.. && export CAMPSITE_PACKAGE_DIR=`pwd` && cd implementation/database
[ "$INSTALL_CONF" = "" ] && export INSTALL_CONF=${CAMPSITE_PACKAGE_DIR}/.install_conf
. ${INSTALL_CONF}/conf_functions

modules_conf --set DATABASE
[ $? -ne 0 ] && exit 1
password=""
[ "$DATABASE_PASSWORD" != "" ] && password="-p $DATABASE_PASSWORD"

mysqladmin create $DATABASE_NAME -h $DATABASE_SERVER -P $DATABASE_PORT -u $DATABASE_USER $password
result=$?
if [ "$result" != "0" ]; then
    touch ../../campsite_upgrade
    echo "Database alread exists. Type make drop-db to drop old database."
    exit 0
else
    echo -n "Creating campsite database..."
    mysql $DATABASE_NAME -h $DATABASE_SERVER -P $DATABASE_PORT -u $DATABASE_USER $password < campsite-db.sql 1> /dev/null
    [ $? -ne 0 ] && exit 1
    echo "done."
fi
exit 0
