<div class="ui-widget-content big-block block-shadow padded-strong"	id="comments-form">
<form method="GET"	action="/newscoop/admin/articles/comments/do_add_comment.php" id="article-comments">
    <input type="hidden" value="1" name="language_id">
    <input type="hidden" value="64" name="article_number">
<h3>Post a Comment</h3>

<fieldset class="plain">
<ul>
	<li>
	   <label>Author</label>
	   <input type="text" size="41" class="input_text" value="" name="author">
	</li>
	<li>
	   <label>Subject</label>
	   <input type="text" spellcheck="false" size="41" class="input_text" value="" name="subject">
	</li>
	<li>
	   <label>Message</label>
	   <textarea style="width: 99.5%;" spellcheck="true" cols="" rows="8" class="input_text_area" name="message">
	   </textarea>
	</li>
	<li><input type="button" class="default-button" value="Submit"></li>
</ul>
</fieldset>
</form>
</div>
<script>
$().ready(function(){
    $('#article-comments').click(function(){
    	var dataString = 'author='+ $('input[name="author"]').val()
    	               + '&subject=' + $('input[name="subject"]').val()
    	               + '&message=' + $('input[name="message"]').val()
    	               + '&language_id' + $('input[name="language_id"]').val()
    	               + '&article_number' + $('input[name="article_number"]').val();
    	$.ajax({
    	  type: "POST",
    	  url: "<?php echo $this->url(array( 'controller' => 'comments', 'action' => 'add', 'format' => 'json'));?>",
    	  data: dataString,
    	  success: function() {

    	  }
    	});
    	return false;
    });
});
</script>
