<table width="100%" cellspacing="0" cellpadding="6" border="0"
	style="padding-top: 5px;">
	<tbody>
		<tr>
			<td>&nbsp;</td>

			<td width="1%" class="tab_inactive">
			     <a href="?f_comment_screen=inbox"><?php putGS('New'); ?> (<?php echo $this->count->pending; ?>)</a>
            </td>

			<td width="1%" nowrap="" class="tab_active">
                <a href="?f_comment_screen=archive"><?php putGS('Published'); ?> (<?php echo $this->count->approved; ?>)</a>
            </td>

			<td width="98%" style="border-bottom: 1px solid #777;">&nbsp;</td>
		</tr>
	</tbody>
</table>
<table width="100%" style="padding-top: 2px;">
	<tbody>
		<tr>
			<td style="padding-left: 13px;">
			<form method="POST">
			<table cellspacing="0" cellpadding="0">
				<tbody>
					<tr>
						<td></td>

						<td>Items per page:</td>

						<td><input type="text" class="input_text" maxlength="4" size="2"
							value="20" name="f_comment_per_page"></td>

						<td style="padding-left: 15px;">Search: <input type="text"
							class="input_text" size="15" value="" name="f_comment_search"></td>

						<td style="padding-left: 15px;"><select class="input_select"
							name="f_comment_order_by">
							<option selected="selected" value="datestamp">Date posted</option>
							<option value="Name">Article name</option>
							<option value="author">Author</option>
							<option value="thread">Thread</option>
						</select></td>

						<td><a
							href="/newscoop/admin/comments/index.php?f_comment_order_direction=DESC"><img
							border="0"
							src="http://newscoop.com/newscoop/admin-style/images/ascending.png"></a>
						</td>
						<td style="padding-left: 15px;"><input type="submit"
							class="button" value="Search"></td>

					</tr>
				</tbody>
			</table>
			</form>
			</td>
		</tr>
	</tbody>
</table>

<table width="100%" cellspacing="0" cellpadding="0"
	style="border-top: 1px solid #777;">
	<tbody>
		<tr>
			<td width="500px" valign="top" align="left"><!-- The column with date&subject -->
			<table width="100%" cellspacing="1" cellpadding="3" border="0">
				<tbody>
					<tr class="table_list_header">
						<td>&nbsp;</td>
						<td>Date posted</td>
						<td>Subject</td>
						<td>Article</td>
						<td>&nbsp;</td>
					</tr>
					<script>
            comment_ids.push("comment_5");
            arrow_ids.push("arrow_5");
            </script>

					<tr id="subject_5" class="list_row_odd">
						<td width="1%" valign="top" align="left" nowrap="">1</td>
						<td width="1%" valign="top" align="left" nowrap=""
							onclick="onSummaryClick(5);"><a onclick="onSummaryClick(5);"
							href="javascript: void(0);">2010-12-30 11:28:14</a></td>
						<td valign="top" align="left" onclick="onSummaryClick(5);"><a
							onclick="onSummaryClick(5);" href="javascript: void(0);">Somethnig</a></td>
						<td valign="top" align="left" onclick="onSummaryClick(5);"><a
							onclick="onSummaryClick(5);" href="javascript: void(0);">Advertisers
						target online demographic</a></td>
						<td width="1%"><img id="arrow_5"
							src="http://newscoop.com/newscoop/admin-style/images/arrow_left.gif"></td>
					</tr>
					<script>
            comment_ids.push("comment_6");
            arrow_ids.push("arrow_6");
            </script>

					<tr id="subject_6" class="list_row_even">
						<td width="1%" valign="top" align="left" nowrap="">2</td>
						<td width="1%" valign="top" align="left" nowrap=""
							onclick="onSummaryClick(6);"><a onclick="onSummaryClick(6);"
							href="javascript: void(0);">2010-12-30 11:29:51</a></td>
						<td valign="top" align="left" onclick="onSummaryClick(6);"><a
							onclick="onSummaryClick(6);" href="javascript: void(0);">Not ok</a></td>
						<td valign="top" align="left" onclick="onSummaryClick(6);"><a
							onclick="onSummaryClick(6);" href="javascript: void(0);">Advertisers
						target online demographic</a></td>
						<td width="1%"><img style="display: none;" id="arrow_6"
							src="http://newscoop.com/newscoop/admin-style/images/arrow_left.gif"></td>
					</tr>
					<script>
            comment_ids.push("comment_7");
            arrow_ids.push("arrow_7");
            </script>

					<tr id="subject_7" class="list_row_odd">
						<td width="1%" valign="top" align="left" nowrap="">3</td>
						<td width="1%" valign="top" align="left" nowrap=""
							onclick="onSummaryClick(7);"><a onclick="onSummaryClick(7);"
							href="javascript: void(0);">2010-12-30 11:38:36</a></td>
						<td valign="top" align="left" onclick="onSummaryClick(7);"><a
							onclick="onSummaryClick(7);" href="javascript: void(0);">Site
						comment</a></td>
						<td valign="top" align="left" onclick="onSummaryClick(7);"><a
							onclick="onSummaryClick(7);" href="javascript: void(0);">Advertisers
						target online demographic</a></td>
						<td width="1%"><img style="display: none;" id="arrow_7"
							src="http://newscoop.com/newscoop/admin-style/images/arrow_left.gif"></td>
					</tr>
					<script>
            comment_ids.push("comment_10");
            arrow_ids.push("arrow_10");
            </script>

					<tr id="subject_10" class="list_row_even">
						<td width="1%" valign="top" align="left" nowrap="">4</td>
						<td width="1%" valign="top" align="left" nowrap=""
							onclick="onSummaryClick(10);"><a onclick="onSummaryClick(10);"
							href="javascript: void(0);">2010-12-30 14:23:27</a></td>
						<td valign="top" align="left" onclick="onSummaryClick(10);"><a
							onclick="onSummaryClick(10);" href="javascript: void(0);">Site
						comment</a></td>
						<td valign="top" align="left" onclick="onSummaryClick(10);"><a
							onclick="onSummaryClick(10);" href="javascript: void(0);">European
						Council candidates set to be named</a></td>
						<td width="1%"><img style="display: none;" id="arrow_10"
							src="http://newscoop.com/newscoop/admin-style/images/arrow_left.gif"></td>
					</tr>
				</tbody>
			</table>
			</td>

			<td valign="top" style="border-left: 1px solid #777;"><!-- The column where you can edit the comments -->
			<form method="POST" action="do_edit.php"><input type="hidden"
				value="C1JlpKUuKUPaVX8wdGZPon7xQwErrZU4" name="security_token">
			<table cellspacing="0" cellpadding="0" border="0" class="box_table">
				<!-- BEGIN table containing comment controls+content -->
				<tbody>
					<tr id="comment_5">
						<td><!-- table for the action controls -->
						<table>
							<tbody>
								<tr>
									<td style="padding-left: 10px;"><input type="radio"
										onchange="onCommentAction('inbox', 5);" id="inbox_5"
										class="input_radio" value="inbox" name="comment_action_5"></td>

									<td><a onclick="onCommentAction('inbox', 5);"
										href="javascript: void(0);"><b>New</b></a></td>

									<td style="padding-left: 10px;"><input type="radio"
										onchange="onCommentAction('approved', 5);" checked=""
										id="approved_5" class="input_radio" value="approve"
										name="comment_action_5"></td>

									<td><a onclick="onCommentAction('approved', 5);"
										href="javascript: void(0);"><b>Approved</b></a></td>

									<td style="padding-left: 10px;"><input type="radio"
										onchange="onCommentAction('delete', 5);" id="delete_5"
										class="input_radio" value="delete" name="comment_action_5"></td>

									<td><a onclick="onCommentAction('delete', 5);"
										href="javascript: void(0);"><b>Delete</b></a></td>

									<td style="padding-left: 10px;"><input type="radio"
										onchange="onCommentAction('hidden', 5);" id="hidden_5"
										class="input_radio" value="hide" name="comment_action_5"></td>

									<td><a onclick="onCommentAction('hidden', 5);"
										href="javascript: void(0);"><b>Hidden</b></a></td>

									<td style="padding-left: 10px;"><a
										onclick="window.open('/newscoop/admin/comments/ban.php?f_comment_id=5', null, 'resizable=yes, menubar=no, toolbar=no, width=400, height=200, top=200, left=200'); return false;"
										href="javascript: void(0);"><img border="0"
										src="http://newscoop.com/newscoop/admin-style/images/unlink.png"></a>
									</td>

									<td><a
										onclick="window.open('/newscoop/admin/comments/ban.php?f_comment_id=5', null, 'resizable=yes, menubar=no, toolbar=no, width=400, height=200, top=200, left=200'); return false;"
										href="javascript: void(0);"><b>Ban user</b></a></td>

									<td style="padding-left: 10px;"><input type="submit"
										class="button" value="Save" name="save"></td>

								</tr>
							</tbody>
						</table>
						<!-- END table for the action controls --> <!-- BEGIN table with article content -->
						<table width="100%" cellspacing="1" cellpadding="3" border="0"
							style="border-top: 1px solid #8EAED7;">
							<tbody>
								<tr>
									<td style="padding-top: 5px;"><b>Article:</b>&nbsp; <a
										href="/newscoop/admin/articles/edit.php?f_publication_id=2&amp;f_issue_number=12&amp;f_section_number=20&amp;f_article_number=68&amp;f_language_id=1&amp;f_language_selected=1">Advertisers
									target online demographic</a></td>
								</tr>
								<tr id="article_closed_5">
									<td valign="middle"><a
										onclick="HideElement('article_closed_5'); ShowElement('article_5');"
										href="javascript:void(0);"><img border="0" align="absmiddle"
										src="http://newscoop.com/newscoop/admin-style/images/viewmagplus.png"><b>Show
									article</b></a></td>
								</tr>
								<tr id="article_5" style="display: none;">
									<td><a
										onclick="HideElement('article_5'); ShowElement('article_closed_5');"
										href="javascript:void(0);"><img border="0" align="absmiddle"
										src="http://newscoop.com/newscoop/admin-style/images/viewmagminus.png"><b>Hide
									article</b></a><br>
									<table width="100%" cellspacing="0" cellpadding="0"
										bgcolor="#EFEFEF"
										style="margin: 10px; border: 1px solid #777;">
										<tbody>
											<tr>
												<td valign="top" align="left" style="padding: 5px;"><b>highlight:</b>
												</td>
											</tr>

											<tr>
												<td style="border-bottom: 1px solid #777; padding: 10px;">0
												</td>
											</tr>
											<tr>
												<td valign="top" align="left" style="padding: 5px;"><b>deck:</b>
												</td>
											</tr>

											<tr>
												<td style="border-bottom: 1px solid #777; padding: 10px;">Putant
												conceptam id pri, at vis fuisset invidunt. Alia viderer te
												mel. An per sale malorum sadipscing, saepe graeco accusata
												in cum.</td>
											</tr>
											<tr>
												<td valign="top" align="left" style="padding: 5px;"><b>full_text:</b>
												</td>
											</tr>

											<tr>
												<td style="border-bottom: 1px solid #777; padding: 10px;">
												<div id="_mcePaste">Putant conceptam id pri, at vis fuisset
												invidunt. Alia viderer te mel. An per sale malorum
												sadipscing, saepe graeco accusata in cum.</div>
												<div id="_mcePaste">Saperet voluptua efficiendi sed te, sit
												altera placerat mandamus ei. Vitae nonumy percipitur at est.
												Ex pericula gubergren sententiae eos. Eos dicit accusam
												voluptaria eu, ius ad etiam numquam rationibus. Nobis
												aperiri in eam, illud facete in mel. Fabellas principes
												voluptatum eum ex.</div>
												<div id="_mcePaste">Pro ut essent consequuntur, mazim mollis
												ea mea. Ut his augue errem elitr, audire prodesset
												scribentur ius no. Eam ne invidunt insolens electram. Cu
												illum exerci intellegat vel. Harum noluisse usu ut. Decore
												eruditi duo in. Liber urbanitas nec et.</div>
												<div id="_mcePaste">Graeco aliquyam qui id, ne clita
												conceptam referrentur mel. Primis qualisque cu eos. Tale
												nihil mollis mei id. Ne mei phaedrum consequat, duo quis
												noluisse lucilius te. Cum in adhuc simul conclusionemque,
												aliquid abhorreant vel at, id eam malorum diceret
												conclusionemque. Mutat timeam reprehendunt et eam, pro elit
												deterruisset et, sonet singulis ne vim.</div>
												<div id="_mcePaste">An eam aliquam vulputate intellegebat,
												cu sea iudico suavitate, populo intellegat his ei. An vel
												laoreet molestiae. Est nobis eripuit probatus an, te his
												illum dicant. Eu dicit verterem assueverit duo. Vix ei
												audire latine virtute, quod nonummy nam et, ad per graece
												vituperata.</div>
												<div id="_mcePaste">Vix omnis prompta at, vidit mundi ei
												eos, vitae dolorem officiis ex vis. Nibh velit audiam vim
												in. Ea tritani qualisque interpretaris mel, errem principes
												cum te. Mei porro essent verear ea, cum id everti gubergren.
												Ut quis nihil has, sed dicant accusata molestiae ne.</div>
												Putant conceptam id pri, at vis fuisset invidunt. Alia
												viderer te mel. An per sale malorum sadipscing, saepe graeco
												accusata in cum.<br>
												Saperet voluptua efficiendi sed te, sit altera placerat
												mandamus ei. Vitae nonumy percipitur at est. Ex pericula
												gubergren sententiae eos. Eos dicit accusam voluptaria eu,
												ius ad etiam numquam rationibus. Nobis aperiri in eam, illud
												facete in mel. Fabellas principes voluptatum eum ex.<br>
												Pro ut essent consequuntur, mazim mollis ea mea. Ut his
												augue errem elitr, audire prodesset scribentur ius no. Eam
												ne invidunt insolens electram. Cu illum exerci intellegat
												vel. Harum noluisse usu ut. Decore eruditi duo in. Liber
												urbanitas nec et.<br>
												Graeco aliquyam qui id, ne clita conceptam referrentur mel.
												Primis qualisque cu eos. Tale nihil mollis mei id. Ne mei
												phaedrum consequat, duo quis noluisse lucilius te. Cum in
												adhuc simul conclusionemque, aliquid abhorreant vel at, id
												eam malorum diceret conclusionemque. Mutat timeam
												reprehendunt et eam, pro elit deterruisset et, sonet
												singulis ne vim.<br>
												An eam aliquam vulputate intellegebat, cu sea iudico
												suavitate, populo intellegat his ei. An vel laoreet
												molestiae. Est nobis eripuit probatus an, te his illum
												dicant. Eu dicit verterem assueverit duo. Vix ei audire
												latine virtute, quod nonummy nam et, ad per graece
												vituperata.<br>
												Vix omnis prompta at, vidit mundi ei eos, vitae dolorem
												officiis ex vis. Nibh velit audiam vim in. Ea tritani
												qualisque interpretaris mel, errem principes cum te. Mei
												porro essent verear ea, cum id everti gubergren. Ut quis
												nihil has, sed dicant accusata molestiae ne.</td>
											</tr>
										</tbody>
									</table>
									</td>
								</tr>
							</tbody>
						</table>
						<!-- END table with article content --> <!-- BEGIN table with comment content -->
						<table cellspacing="1" cellpadding="3" border="0">
							<tbody>
								<tr>
									<td><b>Date:</b></td>
									<td>2010-12-30 11:28:14</td>
								</tr>

								<tr>
									<td><b>Author:</b></td>
									<td>Test Persona &lt;test@persona.com&gt;
									(79-101-185-177.dynamic.isp.telekom.rs)</td>
								</tr>

								<tr>
									<td><b>Subject:</b></td>
									<td><input type="text" class="input_text" size="30"
										value="Somethnig" name="f_subject_5"></td>
								</tr>

								<tr>
									<td><b>Comment:</b></td>
								</tr>

								<tr>
									<td colspan="2"><textarea cols="70" rows="15"
										class="input_textarea" name="f_comment_5">Something's got me started</textarea></td>
								</tr>
							</tbody>
						</table>
						</td>
					</tr>
					<!-- END table with comment content -->
					<!-- BEGIN table containing comment controls+content -->
					<tr id="comment_6" style="display: none;">
						<td><!-- table for the action controls -->
						<table>
							<tbody>
								<tr>
									<td style="padding-left: 10px;"><input type="radio"
										onchange="onCommentAction('inbox', 6);" id="inbox_6"
										class="input_radio" value="inbox" name="comment_action_6"></td>

									<td><a onclick="onCommentAction('inbox', 6);"
										href="javascript: void(0);"><b>New</b></a></td>

									<td style="padding-left: 10px;"><input type="radio"
										onchange="onCommentAction('approved', 6);" checked=""
										id="approved_6" class="input_radio" value="approve"
										name="comment_action_6"></td>

									<td><a onclick="onCommentAction('approved', 6);"
										href="javascript: void(0);"><b>Approved</b></a></td>

									<td style="padding-left: 10px;"><input type="radio"
										onchange="onCommentAction('delete', 6);" id="delete_6"
										class="input_radio" value="delete" name="comment_action_6"></td>

									<td><a onclick="onCommentAction('delete', 6);"
										href="javascript: void(0);"><b>Delete</b></a></td>

									<td style="padding-left: 10px;"><input type="radio"
										onchange="onCommentAction('hidden', 6);" id="hidden_6"
										class="input_radio" value="hide" name="comment_action_6"></td>

									<td><a onclick="onCommentAction('hidden', 6);"
										href="javascript: void(0);"><b>Hidden</b></a></td>

									<td style="padding-left: 10px;"><a
										onclick="window.open('/newscoop/admin/comments/ban.php?f_comment_id=6', null, 'resizable=yes, menubar=no, toolbar=no, width=400, height=200, top=200, left=200'); return false;"
										href="javascript: void(0);"><img border="0"
										src="http://newscoop.com/newscoop/admin-style/images/unlink.png"></a>
									</td>

									<td><a
										onclick="window.open('/newscoop/admin/comments/ban.php?f_comment_id=6', null, 'resizable=yes, menubar=no, toolbar=no, width=400, height=200, top=200, left=200'); return false;"
										href="javascript: void(0);"><b>Ban user</b></a></td>

									<td style="padding-left: 10px;"><input type="submit"
										class="button" value="Save" name="save"></td>

								</tr>
							</tbody>
						</table>
						<!-- END table for the action controls --> <!-- BEGIN table with article content -->
						<table width="100%" cellspacing="1" cellpadding="3" border="0"
							style="border-top: 1px solid #8EAED7;">
							<tbody>
								<tr>
									<td style="padding-top: 5px;"><b>Article:</b>&nbsp; <a
										href="/newscoop/admin/articles/edit.php?f_publication_id=2&amp;f_issue_number=12&amp;f_section_number=20&amp;f_article_number=68&amp;f_language_id=1&amp;f_language_selected=1">Advertisers
									target online demographic</a></td>
								</tr>
								<tr id="article_closed_6">
									<td valign="middle"><a
										onclick="HideElement('article_closed_6'); ShowElement('article_6');"
										href="javascript:void(0);"><img border="0" align="absmiddle"
										src="http://newscoop.com/newscoop/admin-style/images/viewmagplus.png"><b>Show
									article</b></a></td>
								</tr>
								<tr id="article_6" style="display: none;">
									<td><a
										onclick="HideElement('article_6'); ShowElement('article_closed_6');"
										href="javascript:void(0);"><img border="0" align="absmiddle"
										src="http://newscoop.com/newscoop/admin-style/images/viewmagminus.png"><b>Hide
									article</b></a><br>
									<table width="100%" cellspacing="0" cellpadding="0"
										bgcolor="#EFEFEF"
										style="margin: 10px; border: 1px solid #777;">
										<tbody>
											<tr>
												<td valign="top" align="left" style="padding: 5px;"><b>highlight:</b>
												</td>
											</tr>

											<tr>
												<td style="border-bottom: 1px solid #777; padding: 10px;">0
												</td>
											</tr>
											<tr>
												<td valign="top" align="left" style="padding: 5px;"><b>deck:</b>
												</td>
											</tr>

											<tr>
												<td style="border-bottom: 1px solid #777; padding: 10px;">Putant
												conceptam id pri, at vis fuisset invidunt. Alia viderer te
												mel. An per sale malorum sadipscing, saepe graeco accusata
												in cum.</td>
											</tr>
											<tr>
												<td valign="top" align="left" style="padding: 5px;"><b>full_text:</b>
												</td>
											</tr>

											<tr>
												<td style="border-bottom: 1px solid #777; padding: 10px;">
												<div id="_mcePaste">Putant conceptam id pri, at vis fuisset
												invidunt. Alia viderer te mel. An per sale malorum
												sadipscing, saepe graeco accusata in cum.</div>
												<div id="_mcePaste">Saperet voluptua efficiendi sed te, sit
												altera placerat mandamus ei. Vitae nonumy percipitur at est.
												Ex pericula gubergren sententiae eos. Eos dicit accusam
												voluptaria eu, ius ad etiam numquam rationibus. Nobis
												aperiri in eam, illud facete in mel. Fabellas principes
												voluptatum eum ex.</div>
												<div id="_mcePaste">Pro ut essent consequuntur, mazim mollis
												ea mea. Ut his augue errem elitr, audire prodesset
												scribentur ius no. Eam ne invidunt insolens electram. Cu
												illum exerci intellegat vel. Harum noluisse usu ut. Decore
												eruditi duo in. Liber urbanitas nec et.</div>
												<div id="_mcePaste">Graeco aliquyam qui id, ne clita
												conceptam referrentur mel. Primis qualisque cu eos. Tale
												nihil mollis mei id. Ne mei phaedrum consequat, duo quis
												noluisse lucilius te. Cum in adhuc simul conclusionemque,
												aliquid abhorreant vel at, id eam malorum diceret
												conclusionemque. Mutat timeam reprehendunt et eam, pro elit
												deterruisset et, sonet singulis ne vim.</div>
												<div id="_mcePaste">An eam aliquam vulputate intellegebat,
												cu sea iudico suavitate, populo intellegat his ei. An vel
												laoreet molestiae. Est nobis eripuit probatus an, te his
												illum dicant. Eu dicit verterem assueverit duo. Vix ei
												audire latine virtute, quod nonummy nam et, ad per graece
												vituperata.</div>
												<div id="_mcePaste">Vix omnis prompta at, vidit mundi ei
												eos, vitae dolorem officiis ex vis. Nibh velit audiam vim
												in. Ea tritani qualisque interpretaris mel, errem principes
												cum te. Mei porro essent verear ea, cum id everti gubergren.
												Ut quis nihil has, sed dicant accusata molestiae ne.</div>
												Putant conceptam id pri, at vis fuisset invidunt. Alia
												viderer te mel. An per sale malorum sadipscing, saepe graeco
												accusata in cum.<br>
												Saperet voluptua efficiendi sed te, sit altera placerat
												mandamus ei. Vitae nonumy percipitur at est. Ex pericula
												gubergren sententiae eos. Eos dicit accusam voluptaria eu,
												ius ad etiam numquam rationibus. Nobis aperiri in eam, illud
												facete in mel. Fabellas principes voluptatum eum ex.<br>
												Pro ut essent consequuntur, mazim mollis ea mea. Ut his
												augue errem elitr, audire prodesset scribentur ius no. Eam
												ne invidunt insolens electram. Cu illum exerci intellegat
												vel. Harum noluisse usu ut. Decore eruditi duo in. Liber
												urbanitas nec et.<br>
												Graeco aliquyam qui id, ne clita conceptam referrentur mel.
												Primis qualisque cu eos. Tale nihil mollis mei id. Ne mei
												phaedrum consequat, duo quis noluisse lucilius te. Cum in
												adhuc simul conclusionemque, aliquid abhorreant vel at, id
												eam malorum diceret conclusionemque. Mutat timeam
												reprehendunt et eam, pro elit deterruisset et, sonet
												singulis ne vim.<br>
												An eam aliquam vulputate intellegebat, cu sea iudico
												suavitate, populo intellegat his ei. An vel laoreet
												molestiae. Est nobis eripuit probatus an, te his illum
												dicant. Eu dicit verterem assueverit duo. Vix ei audire
												latine virtute, quod nonummy nam et, ad per graece
												vituperata.<br>
												Vix omnis prompta at, vidit mundi ei eos, vitae dolorem
												officiis ex vis. Nibh velit audiam vim in. Ea tritani
												qualisque interpretaris mel, errem principes cum te. Mei
												porro essent verear ea, cum id everti gubergren. Ut quis
												nihil has, sed dicant accusata molestiae ne.</td>
											</tr>
										</tbody>
									</table>
									</td>
								</tr>
							</tbody>
						</table>
						<!-- END table with article content --> <!-- BEGIN table with comment content -->
						<table cellspacing="1" cellpadding="3" border="0">
							<tbody>
								<tr>
									<td><b>Date:</b></td>
									<td>2010-12-30 11:29:51</td>
								</tr>

								<tr>
									<td><b>Author:</b></td>
									<td>Rio Ferdinand &lt;rio@mutd.co.uk&gt;
									(79-101-185-177.dynamic.isp.telekom.rs)</td>
								</tr>

								<tr>
									<td><b>Subject:</b></td>
									<td><input type="text" class="input_text" size="30"
										value="Not ok" name="f_subject_6"></td>
								</tr>

								<tr>
									<td><b>Comment:</b></td>
								</tr>

								<tr>
									<td colspan="2"><textarea cols="70" rows="15"
										class="input_textarea" name="f_comment_6">Ok, not ok, who knows? Lorem ipsum dolor sit amet, my friend.</textarea></td>
								</tr>
							</tbody>
						</table>
						</td>
					</tr>
					<!-- END table with comment content -->
					<!-- BEGIN table containing comment controls+content -->
					<tr id="comment_7" style="display: none;">
						<td><!-- table for the action controls -->
						<table>
							<tbody>
								<tr>
									<td style="padding-left: 10px;"><input type="radio"
										onchange="onCommentAction('inbox', 7);" id="inbox_7"
										class="input_radio" value="inbox" name="comment_action_7"></td>

									<td><a onclick="onCommentAction('inbox', 7);"
										href="javascript: void(0);"><b>New</b></a></td>

									<td style="padding-left: 10px;"><input type="radio"
										onchange="onCommentAction('approved', 7);" checked=""
										id="approved_7" class="input_radio" value="approve"
										name="comment_action_7"></td>

									<td><a onclick="onCommentAction('approved', 7);"
										href="javascript: void(0);"><b>Approved</b></a></td>

									<td style="padding-left: 10px;"><input type="radio"
										onchange="onCommentAction('delete', 7);" id="delete_7"
										class="input_radio" value="delete" name="comment_action_7"></td>

									<td><a onclick="onCommentAction('delete', 7);"
										href="javascript: void(0);"><b>Delete</b></a></td>

									<td style="padding-left: 10px;"><input type="radio"
										onchange="onCommentAction('hidden', 7);" id="hidden_7"
										class="input_radio" value="hide" name="comment_action_7"></td>

									<td><a onclick="onCommentAction('hidden', 7);"
										href="javascript: void(0);"><b>Hidden</b></a></td>

									<td style="padding-left: 10px;"><a
										onclick="window.open('/newscoop/admin/comments/ban.php?f_comment_id=7', null, 'resizable=yes, menubar=no, toolbar=no, width=400, height=200, top=200, left=200'); return false;"
										href="javascript: void(0);"><img border="0"
										src="http://newscoop.com/newscoop/admin-style/images/unlink.png"></a>
									</td>

									<td><a
										onclick="window.open('/newscoop/admin/comments/ban.php?f_comment_id=7', null, 'resizable=yes, menubar=no, toolbar=no, width=400, height=200, top=200, left=200'); return false;"
										href="javascript: void(0);"><b>Ban user</b></a></td>

									<td style="padding-left: 10px;"><input type="submit"
										class="button" value="Save" name="save"></td>

								</tr>
							</tbody>
						</table>
						<!-- END table for the action controls --> <!-- BEGIN table with article content -->
						<table width="100%" cellspacing="1" cellpadding="3" border="0"
							style="border-top: 1px solid #8EAED7;">
							<tbody>
								<tr>
									<td style="padding-top: 5px;"><b>Article:</b>&nbsp; <a
										href="/newscoop/admin/articles/edit.php?f_publication_id=2&amp;f_issue_number=12&amp;f_section_number=20&amp;f_article_number=68&amp;f_language_id=1&amp;f_language_selected=1">Advertisers
									target online demographic</a></td>
								</tr>
								<tr id="article_closed_7">
									<td valign="middle"><a
										onclick="HideElement('article_closed_7'); ShowElement('article_7');"
										href="javascript:void(0);"><img border="0" align="absmiddle"
										src="http://newscoop.com/newscoop/admin-style/images/viewmagplus.png"><b>Show
									article</b></a></td>
								</tr>
								<tr id="article_7" style="display: none;">
									<td><a
										onclick="HideElement('article_7'); ShowElement('article_closed_7');"
										href="javascript:void(0);"><img border="0" align="absmiddle"
										src="http://newscoop.com/newscoop/admin-style/images/viewmagminus.png"><b>Hide
									article</b></a><br>
									<table width="100%" cellspacing="0" cellpadding="0"
										bgcolor="#EFEFEF"
										style="margin: 10px; border: 1px solid #777;">
										<tbody>
											<tr>
												<td valign="top" align="left" style="padding: 5px;"><b>highlight:</b>
												</td>
											</tr>

											<tr>
												<td style="border-bottom: 1px solid #777; padding: 10px;">0
												</td>
											</tr>
											<tr>
												<td valign="top" align="left" style="padding: 5px;"><b>deck:</b>
												</td>
											</tr>

											<tr>
												<td style="border-bottom: 1px solid #777; padding: 10px;">Putant
												conceptam id pri, at vis fuisset invidunt. Alia viderer te
												mel. An per sale malorum sadipscing, saepe graeco accusata
												in cum.</td>
											</tr>
											<tr>
												<td valign="top" align="left" style="padding: 5px;"><b>full_text:</b>
												</td>
											</tr>

											<tr>
												<td style="border-bottom: 1px solid #777; padding: 10px;">
												<div id="_mcePaste">Putant conceptam id pri, at vis fuisset
												invidunt. Alia viderer te mel. An per sale malorum
												sadipscing, saepe graeco accusata in cum.</div>
												<div id="_mcePaste">Saperet voluptua efficiendi sed te, sit
												altera placerat mandamus ei. Vitae nonumy percipitur at est.
												Ex pericula gubergren sententiae eos. Eos dicit accusam
												voluptaria eu, ius ad etiam numquam rationibus. Nobis
												aperiri in eam, illud facete in mel. Fabellas principes
												voluptatum eum ex.</div>
												<div id="_mcePaste">Pro ut essent consequuntur, mazim mollis
												ea mea. Ut his augue errem elitr, audire prodesset
												scribentur ius no. Eam ne invidunt insolens electram. Cu
												illum exerci intellegat vel. Harum noluisse usu ut. Decore
												eruditi duo in. Liber urbanitas nec et.</div>
												<div id="_mcePaste">Graeco aliquyam qui id, ne clita
												conceptam referrentur mel. Primis qualisque cu eos. Tale
												nihil mollis mei id. Ne mei phaedrum consequat, duo quis
												noluisse lucilius te. Cum in adhuc simul conclusionemque,
												aliquid abhorreant vel at, id eam malorum diceret
												conclusionemque. Mutat timeam reprehendunt et eam, pro elit
												deterruisset et, sonet singulis ne vim.</div>
												<div id="_mcePaste">An eam aliquam vulputate intellegebat,
												cu sea iudico suavitate, populo intellegat his ei. An vel
												laoreet molestiae. Est nobis eripuit probatus an, te his
												illum dicant. Eu dicit verterem assueverit duo. Vix ei
												audire latine virtute, quod nonummy nam et, ad per graece
												vituperata.</div>
												<div id="_mcePaste">Vix omnis prompta at, vidit mundi ei
												eos, vitae dolorem officiis ex vis. Nibh velit audiam vim
												in. Ea tritani qualisque interpretaris mel, errem principes
												cum te. Mei porro essent verear ea, cum id everti gubergren.
												Ut quis nihil has, sed dicant accusata molestiae ne.</div>
												Putant conceptam id pri, at vis fuisset invidunt. Alia
												viderer te mel. An per sale malorum sadipscing, saepe graeco
												accusata in cum.<br>
												Saperet voluptua efficiendi sed te, sit altera placerat
												mandamus ei. Vitae nonumy percipitur at est. Ex pericula
												gubergren sententiae eos. Eos dicit accusam voluptaria eu,
												ius ad etiam numquam rationibus. Nobis aperiri in eam, illud
												facete in mel. Fabellas principes voluptatum eum ex.<br>
												Pro ut essent consequuntur, mazim mollis ea mea. Ut his
												augue errem elitr, audire prodesset scribentur ius no. Eam
												ne invidunt insolens electram. Cu illum exerci intellegat
												vel. Harum noluisse usu ut. Decore eruditi duo in. Liber
												urbanitas nec et.<br>
												Graeco aliquyam qui id, ne clita conceptam referrentur mel.
												Primis qualisque cu eos. Tale nihil mollis mei id. Ne mei
												phaedrum consequat, duo quis noluisse lucilius te. Cum in
												adhuc simul conclusionemque, aliquid abhorreant vel at, id
												eam malorum diceret conclusionemque. Mutat timeam
												reprehendunt et eam, pro elit deterruisset et, sonet
												singulis ne vim.<br>
												An eam aliquam vulputate intellegebat, cu sea iudico
												suavitate, populo intellegat his ei. An vel laoreet
												molestiae. Est nobis eripuit probatus an, te his illum
												dicant. Eu dicit verterem assueverit duo. Vix ei audire
												latine virtute, quod nonummy nam et, ad per graece
												vituperata.<br>
												Vix omnis prompta at, vidit mundi ei eos, vitae dolorem
												officiis ex vis. Nibh velit audiam vim in. Ea tritani
												qualisque interpretaris mel, errem principes cum te. Mei
												porro essent verear ea, cum id everti gubergren. Ut quis
												nihil has, sed dicant accusata molestiae ne.</td>
											</tr>
										</tbody>
									</table>
									</td>
								</tr>
							</tbody>
						</table>
						<!-- END table with article content --> <!-- BEGIN table with comment content -->
						<table cellspacing="1" cellpadding="3" border="0">
							<tbody>
								<tr>
									<td><b>Date:</b></td>
									<td>2010-12-30 11:38:36</td>
								</tr>

								<tr>
									<td><b>Author:</b></td>
									<td>Joshua &lt;jos@hua.com&gt;
									(79-101-185-177.dynamic.isp.telekom.rs)</td>
								</tr>

								<tr>
									<td><b>Subject:</b></td>
									<td><input type="text" class="input_text" size="30"
										value="Site comment" name="f_subject_7"></td>
								</tr>

								<tr>
									<td><b>Comment:</b></td>
								</tr>

								<tr>
									<td colspan="2"><textarea cols="70" rows="15"
										class="input_textarea" name="f_comment_7">Well well, what you see is what you get, simple as that. An eam aliquam vulputate intellegebat, cu sea iudico suavitate, populo intellegat his ei. An vel laoreet molestiae. Est nobis eripuit probatus an, te his illum dicant. Eu dicit verterem assueverit duo, people!</textarea></td>
								</tr>
							</tbody>
						</table>
						</td>
					</tr>
					<!-- END table with comment content -->
					<!-- BEGIN table containing comment controls+content -->
					<tr id="comment_10" style="display: none;">
						<td><!-- table for the action controls -->
						<table>
							<tbody>
								<tr>
									<td style="padding-left: 10px;"><input type="radio"
										onchange="onCommentAction('inbox', 10);" id="inbox_10"
										class="input_radio" value="inbox" name="comment_action_10"></td>

									<td><a onclick="onCommentAction('inbox', 10);"
										href="javascript: void(0);"><b>New</b></a></td>

									<td style="padding-left: 10px;"><input type="radio"
										onchange="onCommentAction('approved', 10);" checked=""
										id="approved_10" class="input_radio" value="approve"
										name="comment_action_10"></td>

									<td><a onclick="onCommentAction('approved', 10);"
										href="javascript: void(0);"><b>Approved</b></a></td>

									<td style="padding-left: 10px;"><input type="radio"
										onchange="onCommentAction('delete', 10);" id="delete_10"
										class="input_radio" value="delete" name="comment_action_10"></td>

									<td><a onclick="onCommentAction('delete', 10);"
										href="javascript: void(0);"><b>Delete</b></a></td>

									<td style="padding-left: 10px;"><input type="radio"
										onchange="onCommentAction('hidden', 10);" id="hidden_10"
										class="input_radio" value="hide" name="comment_action_10"></td>

									<td><a onclick="onCommentAction('hidden', 10);"
										href="javascript: void(0);"><b>Hidden</b></a></td>

									<td style="padding-left: 10px;"><a
										onclick="window.open('/newscoop/admin/comments/ban.php?f_comment_id=10', null, 'resizable=yes, menubar=no, toolbar=no, width=400, height=200, top=200, left=200'); return false;"
										href="javascript: void(0);"><img border="0"
										src="http://newscoop.com/newscoop/admin-style/images/unlink.png"></a>
									</td>

									<td><a
										onclick="window.open('/newscoop/admin/comments/ban.php?f_comment_id=10', null, 'resizable=yes, menubar=no, toolbar=no, width=400, height=200, top=200, left=200'); return false;"
										href="javascript: void(0);"><b>Ban user</b></a></td>

									<td style="padding-left: 10px;"><input type="submit"
										class="button" value="Save" name="save"></td>

								</tr>
							</tbody>
						</table>
						<!-- END table for the action controls --> <!-- BEGIN table with article content -->
						<table width="100%" cellspacing="1" cellpadding="3" border="0"
							style="border-top: 1px solid #8EAED7;">
							<tbody>
								<tr>
									<td style="padding-top: 5px;"><b>Article:</b>&nbsp; <a
										href="/newscoop/admin/articles/edit.php?f_publication_id=2&amp;f_issue_number=13&amp;f_section_number=10&amp;f_article_number=64&amp;f_language_id=1&amp;f_language_selected=1">European
									Council candidates set to be named</a></td>
								</tr>
								<tr id="article_closed_10">
									<td valign="middle"><a
										onclick="HideElement('article_closed_10'); ShowElement('article_10');"
										href="javascript:void(0);"><img border="0" align="absmiddle"
										src="http://newscoop.com/newscoop/admin-style/images/viewmagplus.png"><b>Show
									article</b></a></td>
								</tr>
								<tr id="article_10" style="display: none;">
									<td><a
										onclick="HideElement('article_10'); ShowElement('article_closed_10');"
										href="javascript:void(0);"><img border="0" align="absmiddle"
										src="http://newscoop.com/newscoop/admin-style/images/viewmagminus.png"><b>Hide
									article</b></a><br>
									<table width="100%" cellspacing="0" cellpadding="0"
										bgcolor="#EFEFEF"
										style="margin: 10px; border: 1px solid #777;">
										<tbody>
											<tr>
												<td valign="top" align="left" style="padding: 5px;"><b>highlight:</b>
												</td>
											</tr>

											<tr>
												<td style="border-bottom: 1px solid #777; padding: 10px;">0
												</td>
											</tr>
											<tr>
												<td valign="top" align="left" style="padding: 5px;"><b>deck:</b>
												</td>
											</tr>

											<tr>
												<td style="border-bottom: 1px solid #777; padding: 10px;">BRUSSELS
												- Italian and Greek candidates nominated for President of
												the European Council&nbsp;in secret ballot.</td>
											</tr>
											<tr>
												<td valign="top" align="left" style="padding: 5px;"><b>full_text:</b>
												</td>
											</tr>

											<tr>
												<td style="border-bottom: 1px solid #777; padding: 10px;">
												<div id="_mcePaste">Lorem ipsum sed detraxit signiferumque
												at. Ex nonummy lucilius sit, ex vide ludus per, congue
												incorrupte quo ex! Has modo volumus similique ex! Vitae
												officiis at nam, blandit verterem lucilius vel ex, veri
												rebum nec et?</div>
												<div id="_mcePaste">Mei an laudem vocibus denique, doming
												audiam vis cu. Oblique gloriatur id his! Posse salutandi
												complectitur sea ne, eu per prompta civibus volutpat. Ut pri
												nulla ridens scribentur, mea consetetur reformidans et! Pro
												ad regione reprehendunt, paulo voluptaria sadipscing cu usu.
												Nec dolorem tibique oportere id.</div>
												<div id="_mcePaste">Prima tincidunt liberavisse mea id. Te
												numquam fuisset assentior vis, vis fierent consetetur
												dissentiunt an? Ex possit petentium expetendis sit, tantas
												partiendo eos at. Quo wisi error in, vix ut elit facer
												primis, nec quot laboramus no.</div>
												<div>Ex omnis saepe vix? Scripta sensibus ne nec, pri erat
												detraxit disputationi an, duo sanctus efficiendi
												voluptatibus ne. Regione dolorum phaedrum in sea, eu eam
												sapientem mnesarchum signiferumque? Ea has tractatos
												suavitate, veniam option fuisset cum cu?</div>
												<div>Mei et enim iudico, ei liber disputationi has, ad quo
												enim cetero vocent! Eum an tota phaedrum, his aeque dolore
												an? Usu erat liberavisse consectetuer ex, vero utamur ei
												mei, commodo blandit theophrastus an mel! Ne eum platonem
												constituto, persequeris ullamcorper est in.</div>
												<div>Qui in cetero interesset, fierent efficiantur at nec?
												Sit elit vulputate ut, minim suscipit mandamus te nam, no
												mazim cetero accusata usu. Eu vocent deleniti quo, mucius
												discere eu sit, vel amet commodo alterum et. Ad vis dico
												persequeris! His dolorem deseruisse cu, ad eum dicta
												accusata, his putant melius id.</div>
												<p>Lorem ipsum sed detraxit signiferumque at. Ex nonummy
												lucilius sit, ex vide ludus per, congue incorrupte quo ex!
												Has modo volumus similique ex! Vitae officiis at nam,
												blandit verterem lucilius vel ex, veri rebum nec et?</p>
												<p>Mei an laudem vocibus denique, doming audiam vis cu.
												Oblique gloriatur id his! Posse salutandi complectitur sea
												ne, eu per prompta civibus volutpat. Ut pri nulla ridens
												scribentur, mea consetetur reformidans et! Pro ad regione
												reprehendunt, paulo voluptaria sadipscing cu usu. Nec
												dolorem tibique oportere id.</p>
												<p>Prima tincidunt liberavisse mea id. Te numquam fuisset
												assentior vis, vis fierent consetetur dissentiunt an? Ex
												possit petentium expetendis sit, tantas partiendo eos at.
												Quo wisi error in, vix ut elit facer primis, nec quot
												laboramus no.</p>
												<p>Ex omnis saepe vix? Scripta sensibus ne nec, pri erat
												detraxit disputationi an, duo sanctus efficiendi
												voluptatibus ne. Regione dolorum phaedrum in sea, eu eam
												sapientem mnesarchum signiferumque? Ea has tractatos
												suavitate, veniam option fuisset cum cu?</p>
												<p>Mei et enim iudico, ei liber disputationi has, ad quo
												enim cetero vocent! Eum an tota phaedrum, his aeque dolore
												an? Usu erat liberavisse consectetuer ex, vero utamur ei
												mei, commodo blandit theophrastus an mel! Ne eum platonem
												constituto, persequeris ullamcorper est in.</p>
												<p>Qui in cetero interesset, fierent efficiantur at nec? Sit
												elit vulputate ut, minim suscipit mandamus te nam, no mazim
												cetero accusata usu. Eu vocent deleniti quo, mucius discere
												eu sit, vel amet commodo alterum et. Ad vis dico
												persequeris! His dolorem deseruisse cu, ad eum dicta
												accusata, his putant melius id.</p>
												</td>
											</tr>
										</tbody>
									</table>
									</td>
								</tr>
							</tbody>
						</table>
						<!-- END table with article content --> <!-- BEGIN table with comment content -->
						<table cellspacing="1" cellpadding="3" border="0">
							<tbody>
								<tr>
									<td><b>Date:</b></td>
									<td>2010-12-30 14:23:27</td>
								</tr>

								<tr>
									<td><b>Author:</b></td>
									<td>Pia Zadora &lt;pia@gmail.com&gt;
									(79-101-185-177.dynamic.isp.telekom.rs)</td>
								</tr>

								<tr>
									<td><b>Subject:</b></td>
									<td><input type="text" class="input_text" size="30"
										value="Site comment" name="f_subject_10"></td>
								</tr>

								<tr>
									<td><b>Comment:</b></td>
								</tr>

								<tr>
									<td colspan="2"><textarea cols="70" rows="15"
										class="input_textarea" name="f_comment_10">Congratulations to the Person!</textarea></td>
								</tr>
							</tbody>
						</table>
						</td>
					</tr>
					<!-- END table with comment content -->
				</tbody>
			</table>
			</form>
			<!-- END table containing comment controls+content --> <br>
			</td>
		</tr>
	</tbody>
</table>
