<h2><?php echo $this->name; ?></h2>
<h1><?php putGS('Comments'); ?></h1>

<?php $this->renderDatatable(); ?>

<script type="text/javascript">
$(document).ready(function(){
	$('table.data').dataTable().fnSettings().aoDrawCallback.push({
		"fn": function () {
		   var index = 1;
		   $('.index').each(function(){
                $(this).html(index+$(this).html());
                index++;
            });
		  },
		"sName": "user"
	});

});
</script>