<h1><?php putGS('List comments users'); ?></h1>

<?php $this->renderFilter($this->form); ?>

<?php
if (empty($this->users)) { // no logs
    $this->renderMessage(getGS('No user comments.'));
    return;
} ?>

<?php $this->renderPager($this->pager); ?>

<table class="comments">
    <caption><?php putGS('Comments'); ?></caption>
    <tr>
        <th><?php putGS('Name'); ?></th>
        <th><?php putGS('User'); ?></th>
        <th><?php putGS('Email'); ?></th>
        <th><?php putGS('Url'); ?></th>
        <th><?php putGS('User IP Address'); ?></th>
        <th><?php putGS('Date/Time'); ?></th>
    </tr>
    <?php foreach ($this->users as $user) { ?>
    <tr class="users">
        <td><?php echo $user->getName(); ?></td>
        <td><?php echo $user->getUserName(); ?></td>
        <td><?php echo $user->getEmail(); ?></td>
        <td><?php echo $user->getUrl(); ?></td>
        <td><?php echo $user->getIp(); ?></td>
        <td><?php echo $user->getTimeCreated()->format('Y-m-d H:i:s'); ?></td>
    </tr>
    <?php } ?>
</table>

<?php $this->renderPager($this->pager); ?>