#!/bin/sh

rm -f $UTIL_BIN/notifyendsubs
rm -f $UTIL_BIN/notifyevents
unique_id=$$
crontab_cp1=$unique_id-campsite-crontab1
crontab_cp2=$unique_id-campsite-crontab2
rm -fr /tmp/$crontab_cp1 /tmp/$crontab_cp2
cp -f /etc/crontab /tmp/$crontab_cp1
cat /tmp/$crontab_cp1 | grep -v "$UTIL_BIN/notifyendsubs" > /tmp/$crontab_cp2
cat /tmp/$crontab_cp2 | grep -v "$UTIL_BIN/notifyevents" > /etc/crontab
rm -f /tmp/$crontab_cp1 /tmp/$crontab_cp2
killall -1 crond
exit 0
