<div class="commentBtns">
    <ul>
        <li><a href="javascript:;" id="pending_<?php echo $this->comment->getId();?>" class="action new">New</a></li>
        <li><a href="javascript:;" id="approved_<?php echo $this->comment->getId();?>" class="action approved">Approved</a></li>
        <li><a href="javascript:;" id="hidden_<?php echo $this->comment->getId();?>" class="action hidden">Hidden</a></li>
        <li><a href="javascript:;" id="deleted_<?php echo $this->comment->getId();?>" class="action deleted">Delete</a></li>
        <li><a href="javascript:;" class="action-edit link icon-link"><span class="icon ui-icon-pencil"></span>Quick edit</a></li>
        <li><a href="javascript:;" class="action-rating link icon-link"><span class="icon ui-icon-star"></span>Add rating</a></li>
        <li class="last">
            <a href="<?php echo $this->url(array(
                'controller' => 'comment-commenter',
                'action' => 'toggle-ban',
                'commenter'=> $this->comment->getCommenter()->getId(),
                'forum' => $this->comment->getForum()->getId()
            ));
            ?>" class="banUser"><span>Ban user</span></a>
        </li>
    </ul>
</div>