<div class="dateCommentHolder">
<h4>
<span>
    <?php echo $this->comment->getTimeCreated()->format('Y.i.d.');?>
    <?php putGS('at');?>
    <?php echo $this->comment->getTimeCreated()->format('H:i:s');?>
</span>
<span class="commentSubject"><?php echo $this->comment->getSubject(); ?></span>
</h4>
<div class="ratingHolder">
    <span class="thumbs up"><?php echo $this->comment->getLikes();?></span>
    <span class="thumbs down"><?php echo $this->comment->getDislikes();?></span> </div>
<p class="commentBody">
<?php echo $this->stringLimit($this->comment->getMessage()); ?>
</p>
</div>

<div class="dateCommentHolderEdit">
<fieldset class="content-edit" style="display:none;">
    <form action="<?php echo $this->url(array('action' => 'update', 'format' => 'json'));?>">
    <label><?php putGS('Subject');?></label>
    <input type="hidden" name="comment" value="<?php echo $this->comment->getId();?>" />
    <?php echo SecurityToken::FormParameter();?>
    <input type="text" name="subject" class="input_text" value="<?php echo $this->comment->getSubject(); ?>">
    <label><?php putGS('Comment');?></label>
    <textarea name="message" class="input_text_area"><?php echo $this->comment->getMessage();?></textarea>
<div class="buttonBar">
    <input type="button" value="<?php putGS('Cancel');?>" class="button edit-cancel">
    <input type="button" value="<?php putGS('Reply');?>" class="button edit-reply">
    <input type="submit" value="<?php putGS('Update comment');?>" class="save-button-small update">
    </form>
</div>
</fieldset>

<fieldset class="content-reply" style="display:none;">
    <form action="<?php echo $this->url(array('action' => 'reply', 'format' => 'json'));?>">
    <input type="hidden" name="parent" value="<?php echo $this->comment->getId();?>" />
    <?php echo SecurityToken::FormParameter();?>
    <h3>Reply to comment</h3>
    <label><?php putGS('Subject');?></label>
    <input name="subject" type="text" class="input_text">
    <label><?php putGS('Comment');?></label>
    <textarea name="message" class="input_text_area"></textarea>
<div class="buttonBar">
    <input type="button" value="<?php putGS('Cancel');?>" class="button reply-cancel">
    <input type="submit" value="<?php putGS('Submit');?>'" class="button">
    </form>
</div>
</fieldset>
</div>
