<div class="commentBtns">
    <ul>
        <li><a href="#" class="new">New</a></li>
        <li><a href="#" class="approved">Approved</a></li>
        <li><a href="#" class="hidden">Hidden</a></li>
        <li><a href="#" class="deleted">Delete</a></li>
        <li><a class="link icon-link" href="#"><span class="icon ui-icon-pencil"></span>Quick edit</a></li>
        <li><a class="link icon-link" href="#"><span class="icon ui-icon-star"></span>Add rating</a></li>
        <li class="last">
            <a href="<?php echo $this->url(array(
                'controller' => 'comment-commenter',
                'action' => 'toggle-ban',
                'commenter'=> $this->comment->getCommenter()->getId(),
                'forum' => $this->comment->getForum()->getId()
            ));
            ?>" class="banUser"><span>Ban user</span></a>
        </li>
    </ul>
</div>