<table class="datatable" cellspacing="0" cellpadding="0">
<thead>
<tr>
    <?php foreach ($this->cols as $col) { ?>
    <th><?php echo $col; ?></th>
    <?php } ?>
</tr>
</thead>
<tbody>
<tr>
    <td class="message" colspan="<?php echo sizeof($this->cols); ?>"><?php putGS('Loading..'); ?></td>
</tr>
</tbody>
</table>
<script type="text/javascript">
var datatable;
$(function() {
    datatable = $('table.datatable')
        .wrap($('<div />').addClass('table')).wrap($('<div />').addClass('smartlist'))
        .css('position', 'relative').css('width', '100%')
        .dataTable(
        <?php
            $regex = '/"(fnRowCallback|fnDrawCallback|fnServerData)":"([\w\-\.]+)"/i';
            $replace = '"$1":$2';
            $jsonified = preg_replace($regex, $replace, json_encode($this->iOptions));
        echo $jsonified;
        ?> );
});
</script>
