<?php $translator = \Zend_Registry::get('container')->getService('translator'); ?>
<?php echo $translator->trans('New comment added', array(), 'home');?>

<?php echo $translator->trans('Time created', array(), 'home');?>
<?php echo $this->comment->getTimeCreated()->format('H:i:s');?>
<?php echo $translator->trans('Subject');?>:
<?php echo $this->comment->getSubject(); ?>
<?php echo $translator->trans('Comment');?>
<?php echo $this->comment->getMessage(); ?>
