<!--
See http://developer.yahoo.com/ypatterns/pattern.php?pattern=itempagination
-->
<?php $translator = \Zend_Registry::get('container')->getService('translator'); ?>
<?php if ($this->pageCount): ?>
<div class="paginationControl">
 
<!-- First page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url(array('page' => $this->first)); ?>#media-archive">
    <?php echo $translator->trans('First', array(), 'home'); ?>
  </a> |
<?php else: ?>
  <span class="disabled"><?php echo $translator->trans('First', array(), 'home'); ?></span> |
<?php endif; ?>
 
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url(array('page' => $this->previous)); ?>#media-archive">
    &lt; <?php echo $translator->trans('Previous'); ?>
  </a> |
<?php else: ?>
  <span class="disabled">&lt; <?php echo $translator->trans('Previous'); ?></span> |
<?php endif; ?>
 
<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url(array('page' => $this->next)); ?>#media-archive">
    <?php echo $translator->trans('Next'); ?> &gt;
  </a> |
<?php else: ?>
  <span class="disabled"><?php echo $translator->trans('Next'); ?> &gt;</span> |
<?php endif; ?>
 
<!-- Last page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url(array('page' => $this->last)); ?>#media-archive">
    <?php echo $translator->trans('Last', array(), 'home'); ?>
  </a>
<?php else: ?>
  <span class="disabled"><?php echo $translator->trans('Last', array(), 'home'); ?></span>
<?php endif; ?>
 
</div>
<?php endif; ?>
