<dl class="resource">
    <dt><?php echo $resourceName; ?></dt>
    <?php foreach ($rules as $rule) {
        if (!$rule->inherited) {
            continue;
        } ?>
    <dd class="inherited <?php echo $rule->type; ?>">
        <strong><?php echo $this->ruleTypes[$rule->getType()]; ?></strong>
        <?php echo $rule->getActionName() ?: getGS('Any action'); ?>
    </dd>
    <?php } ?>
    <?php foreach ($resource->getRules() as $rule) { ?>
    <dd class="<?php echo $rule->getType(); ?>">
        <a class="delete icon" href="<?php echo $this->url(array(
            'action' => 'delete',
            'controller' => 'acl',
            'rule' => $rule->getId(),
        )); ?>" title="<?php putGS('Remove rule'); ?>"><?php putGS('Remove'); ?></a>
        <strong><?php echo $this->ruleTypes[$rule->getType()]; ?></strong>
        <?php echo $rule->getActionName() ?: getGS('Any action'); ?>
    </dd>
    <?php } ?>
</dl>

