<?php if (!$this->articlePage) {
    $this->headScript()->appendFile($this->baseUrl('js/underscore.js'));
    $this->headScript()->appendFile($this->baseUrl('js/backbone.js'));
}
?>
<?php $this->headScript()->appendFile($this->baseUrl('js/views/PaginatorView.js')); ?>
<?php $translator = \Zend_Registry::get('container')->getService('translator'); ?>
<div id="slideshow-app">
    <div id="slideshow-paginator"></div><br />
    <a id="add-slideshow" href="<?php echo $this->url(array('controller' => 'slideshow', 'action' => 'create')); ?>" class="modal button"><?php echo $translator->trans('Create slideshow', array(), 'home'); ?></a>
</div>

<ul id="slideshow-list" class="list-view grid slideshow-list"></ul>

<script type="text/template" id="slideshow-template">
<h3 class="title"><a href="<?php echo $this->url(array('controller' => 'slideshow', 'action' => 'edit')); ?>/slideshow/<%= id %>" class="edit" title="<%= headline %>"><%= headline.substr(0, 22) %><% if (headline.length > 22) { %>..<% } %></a></h3>
<div class="preview">
    <% if (!itemsCount) { %>
    <span class="blank"></span>
    <% } else if (item) { %>
    <img src="<?php echo $this->baseUrl('/images/cache/'); ?><%= item.thumbnail.src %>" alt="" />
    <% } else { %>
    <span class="video"></span>
    <% } %>
</div>
<a href="#" class="delete"><?php echo $translator->trans('Delete'); ?></a>
</script>
<?php echo $this->render('paginator-template.phtml'); ?>

<script type="text/javascript">
(function($) {
    // don't cache slideshows list requests
    $.ajaxSetup({ cache: false });

    /**
     * Slideshow model
     */
    var Slideshow = Backbone.Model.extend({
        defaults: {
            item: null
        },

        initialize: function() {
            if (this.get('items')) {
                this.set('item', this.get('items')[0]);
            }
        }
    });

    /**
     * Slideshow collection
     */
    var SlideshowCollection = Backbone.Collection.extend({
        url: <?php echo json_encode($this->url(array('module' => 'admin', 'controller' => 'slideshow-rest'), 'rest')); ?>,
        model: Slideshow
    });

    /**
     * Slideshow view
     */
    var SlideshowView = Backbone.View.extend({
        tagName: "li",

        events: {
            'click .delete': 'delete',
        },

        initialize: function() {
            this.model.bind('change', this.render, this);
            this.template = _.template($('#slideshow-template').html());
        },

        render: function() {
            $(this.el).html(this.template(this.model.toJSON()));
            $(this.el).find('.title .edit').fancybox({
                hideOnContentClick: false,
                width: 1300,
                height: 800,
                type: 'iframe',
                onClosed: function() {
                    slideshowCollection.fetch();
                }
            });
            return this;
        },

        delete: function(e) {
            e.preventDefault();
            if (confirm(<?php echo json_encode($translator->trans('Are you sure you want to delete slideshow?', array(), 'home')); ?>)) {
                this.model.destroy();
                this.remove();
            }
        }
    });

    /**
     * Slideshow list view
     */
    var SlideshowListView = Backbone.View.extend({
        initialize: function() {
            this.collection = this.options.collection;
            this.collection.bind('reset', this.render, this);
            this.collection.bind('remove', this.handleRemove, this);
            this.collection.reset(this.options.slideshows);
        },

        render: function() {
            $('#slideshow-list').empty();
            this.collection.each(function(slideshow) {
                var view = new SlideshowView({model: slideshow});
                $('#slideshow-list').append(view.render().el);
            });
            return this;
        },

        handleRemove: function() {
            this.collection.fetch();
        }
    });

    /**
     * Controls
     */
    var AppView = Backbone.View.extend({
        el: $('#slideshow-app'),
        initialize: function() {
            $(this.el).find('a').fancybox({
                hideOnContentClick: false,
                width: 1300,
                height: 800,
                type: 'iframe',
                onClosed: function() {
                    slideshowCollection.fetch();
                }
            });
        }
    });

    $(function() {
        window.slideshowCollection = new SlideshowCollection();
        var paginator = new PaginatorView({pages: <?php echo $this->pages; ?>, collection: slideshowCollection, el: $('#slideshow-paginator')});
        var view = new SlideshowListView({collection: slideshowCollection, slideshows: <?php echo json_encode($this->slideshows); ?>});
        var app = new AppView();
    });
})(jQuery);
</script>
