<?php $translator = \Zend_Registry::get('container')->getService('translator'); ?>
<script type="text/template" id="slideshow-template">
<h3><%= headline %></h3>
<a href="#" class="delete"><?php echo $translator->trans('Delete'); ?></a>
<ul>
    <% _.each(items, function(item) { %>
    <li><img src="<?php echo $this->baseUrl('/images/cache/'); ?><%= item.thumbnail.src %>" alt="<%= item.caption %>" width="<%= item.thumbnail.width %>" height="<%= item.thumbnail.height %>" /></li>
    <% }); %>
</ul>
</script>
