#!/bin/bash

campsite_version=$1
if [ "$campsite_version" = "" ]; then
    echo "You must supply the Campsite version:"
    echo -e "\t$0 campsite_version [templates_version]"
    exit 1
fi

if [ "$2" != "" ]; then
    templates_version="-v$2"
else
    templates_version=""
fi

dirs=`ls -1 | grep "^sample"`
for dir in $dirs; do
    [ ! -d $dir ] && continue;
    cp -f README $dir
    archive_name="campsite-$campsite_version-$dir$templates_version.tar.gz"
    tar --exclude=.svn -c -z -f $archive_name $dir
    rm -f $dir/README
done
