tinyMCE.addI18n('en.campsiteimage',{
campsiteimage_desc:"Insert image",
title:"Insert image",
language:"Language",
section:"Section",
article:"Article",
publication:"Publication",
general_tab:"General",
general_props:"General properties",
issue:"Issue",
target:"Target",
target_same:"Open in this window / frame",
target_parent:"Open in parent window / frame",
target_top:"Open in top frame (replaces all frames)",
target_blank:"Open in new window",
id:"Id",
style:"Style",
classes:"Classes",
target_name:"Target name",
langdir:"Language direction",
target_langcode:"Target language",
langcode:"Language code",
encoding:"Target character encoding",
mime:"Target MIME type",
rel:"Relationship page to target",
rev:"Relationship target to page",
tabindex:"Tabindex",
accesskey:"Accesskey",
ltr:"Left to right",
rtl:"Right to left",
link_list:"Link list",
is_email:"The URL you entered seems to be an email address, do you want to add the required mailto: prefix?",
is_external:"The URL you entered seems to external link, do you want to add the required http:// prefix?",
caption:"Caption",
alt:"Alt",
alignment:"Alignment",
positiontitle:"Positioning of this image",
notset:"Not set",
left:"Left",
right:"Right",
middle:"Middle",
resizeratio:"Resizing Ratio",
resizewidth:"Resizing Width",
resizeheight:"Resizing Height",
edit:"Edit",
ok:"OK",
cancel:"Cancel"
});
