ALTER TABLE OAuthAccessToken ADD user_id INT DEFAULT NULL;
CREATE INDEX IDX_DDE10DD5A76ED395 ON OAuthAccessToken (user_id);
ALTER TABLE OAuthAuthCode ADD user_id INT DEFAULT NULL;
CREATE INDEX IDX_3DD60F72A76ED395 ON OAuthAuthCode (user_id);
ALTER TABLE OAuthRefreshToken ADD user_id INT DEFAULT NULL;
CREATE INDEX IDX_4A42604CA76ED395 ON OAuthRefreshToken (user_id);