#!/bin/bash

BASE_URL="."

exit_usage()
{
	if [ "$1" = "ERROR" ]; then
		echo "ERROR: Received invalid arguments!"
	fi
	echo "Arguments for creating the:"
	echo -e "- package from a branch/tag/commit:"
	echo -e "\t--what <branch_tag_comming_name> [<package_version>]"
	exit 1
}

revision=
what=$1
shift 1
case $what in
--what)
	branch=$1
	if [ "$branch" = "" ] || [ "$branch" = "-r" ]; then
		exit_usage
	fi
	url="$BASE_URL/campsite"
    plugins_url="$BASE_URL/plugins"
	shift 1
	;;
--help)
	exit_usage
	;;
-h)
	exit_usage
	;;
*)
	exit_usage ERROR
	;;
esac

version=$1
if [ "$version" = "" ]; then
    version=`date +%Y.%m.%d`
fi

base_cmd="git checkout"
cmd="$base_cmd $branch"

pushd ../..

$cmd || exit 1

mv ./plugins/* ./campsite/src/plugins

rm -f ./campsite/documentation/CampsiteTestChecklist*
rm -fr ./campsite/documentation/specifications
rm -fr ./campsite/templates
rm -fr ./campsite/src/tests
find ./campsite/src -name placeholder -exec rm -f {} \;

package_name="campsite-$version.tar.gz"

tar czf $package_name ./campsite
res=$?

mv ./campsite/src/plugins .

if [ $res -eq 0 ]; then
    echo "package $package_name prepared successfully"
else
    echo "error creating package $package_name"
    exit 1
fi

$base_cmd -- .

popd
