#!/bin/bash

BASE_URL="."

exit_usage()
{
	if [ "$1" = "ERROR" ]; then
		echo "ERROR: Received invalid arguments!"
	fi
	echo "Arguments:"
    echo -e "--what <branch_tag_comming_name> [<package_version>]"
	echo -e "\tcreate the package from the given branch/tag/commit"
    echo -e "--zip"
    echo -e "\tpackage format zip (default)"
    echo -e "--tar"
    echo -e "\tpackage format tar"
	exit 1
}

package_format="zip"
revision=
what=$1
shift 1
case $what in
--what)
	branch=$1
	if [ "$branch" = "" ] || [ "$branch" = "-r" ]; then
		exit_usage
	fi
	url="$BASE_URL/newscoop"
    plugins_url="$BASE_URL/plugins"
	shift 1
	;;
--help)
	exit_usage
	;;
-h)
	exit_usage
	;;
--zip)
    package_format="zip"
    ;;
--tar)
    package_format="tar.gz"
    ;;
*)
	exit_usage ERROR
	;;
esac

version=$1
if [ "$version" = "" ]; then
    version=`date +%Y.%m.%d`
fi

base_cmd="git checkout"
cmd="$base_cmd $branch"

pushd ../..

$cmd || exit 1

zend_path="/usr/share/php/libzend-framework-php/Zend"
if [ ! -d "$zend_path" ]; then
    zend_path="/usr/share/php/Zend"
fi

mv ./plugins/* ./newscoop/plugins
cp -fr ./dependencies/include/* ./newscoop/include
cp -fr "$zend_path" ./newscoop/library
rm -fr ./newscoop/tests
find ./newscoop -name placeholder -exec rm -f {} \;

package_name="newscoop-$version"
package_filename="newscoop-$version.$package_format"
cp -a ./newscoop ./$package_name

if [ "package_format" = "tar" ]; then
    tar czf $package_filename ./$package_name
    res=$?
else
    zip -qyr $package_filename ./$package_name
    res=$?
fi

rm -rf ./$package_name
mv ./newscoop/plugins .
rm -fr ./newscoop/include
rm -fr ./newscoop/library/Zend

$base_cmd -- .

if [ $res -eq 0 ]; then
    echo "package $package_filename prepared successfully"
else
    echo "error creating package $package_filename"
    exit 1
fi

popd
