#!/bin/bash

BASE_URL="."

exit_usage()
{
	if [ "$1" = "ERROR" ]; then
		echo "ERROR: Received invalid arguments!"
	fi
	echo "Arguments:"
    echo -e "--what <branch_tag_comming_name> [<package_version>]"
	echo -e "\tcreate the package from the given branch/tag/commit"
    echo -e "--zip"
    echo -e "\tpackage format zip (default)"
    echo -e "--tar"
    echo -e "\tpackage format tar"
	exit 1
}

package_format="zip"
revision=

while [ "$#" != "0" ]; do
    what=$1
    shift
    case $what in
        --what)
	        branch=$1
            shift
	        if [ "$branch" = "" ] || [ "$branch" = "-r" ]; then
		        exit_usage
	        fi

            url="$BASE_URL/newscoop"
            plugins_url="$BASE_URL/plugins"
	    ;;

        --help)
	        exit_usage
	    ;;

        -h)
	        exit_usage
	    ;;

        --zip)
            package_format="zip"
        ;;
        
        --tar)
            package_format="tar.gz"
        ;;

        *)
	        exit_usage ERROR
	    ;;
    esac
done

version=$1
if [ "$version" = "" ]; then
    version=`date +%Y.%m.%d`
fi

base_cmd="git checkout"
cmd="$base_cmd $branch"

pushd ../..

$cmd || exit 1

mv ./plugins/* ./newscoop/plugins
cp -fr ./dependencies/include/* ./newscoop/include
rm -fr ./newscoop/tests
find ./newscoop -name placeholder -exec rm -f {} \;
curl -s https://getcomposer.org/installer | php
php composer.phar install

package_name="newscoop-$version"
package_filename="newscoop-$version.$package_format"
cp -a ./newscoop ./$package_name

if [ "$package_format" = "tar.gz" ]; then
    tar chzf $package_filename ./$package_name \
        --exclude-vcs \
        --exclude '*zendframework1/demos*' \
        --exclude '*zendframework1/documentation*' \
        --exclude '*zendframework1/externals*' \
        --exclude '*zendframework1/tests*'
    res=$?
else
    zip -qr $package_filename ./$package_name \
        -x '*.svn*' '*zendframework1/demos*' '*zendframework1/documentation*' '*zendframework1/externals*' '*zendframework1/tests*'
    res=$?
fi

rm -rf ./$package_name
mv ./newscoop/plugins .
rm -fr ./newscoop/include
rm -fr ./newscoop/library/Zend

$base_cmd -- .

if [ $res -eq 0 ]; then
    echo "package $package_filename prepared successfully"
else
    echo "error creating package $package_filename"
    exit 1
fi

popd
