<?php
$translator = \Zend_Registry::get('container')->getService('translator');
$this->placeholder('title')->captureStart(); ?>
<?php echo $translator->trans('Permissions:', array(), 'user_types'); ?>
<form action="<?php echo $this->url(array(
    'action' => 'edit',
)); ?>" method="POST">
<dl class="zend_form inline">
    <?php echo $this->form->name; ?> <?php echo $this->form->submit; ?>
</dl>
</form>
<?php $this->placeholder('title')->captureEnd(); ?>
