-- add new system preferences for tinymce editor image resizing and zooming
INSERT INTO `SystemPreferences` (`varname`, `value`) VALUES ('EditorImageResizeWidth', '');
INSERT INTO `SystemPreferences` (`varname`, `value`) VALUES ('EditorImageResizeHeight', '');
INSERT INTO `SystemPreferences` (`varname`, `value`) VALUES ('EditorImageZoom', 'N');

-- add disabled time zone by default
INSERT INTO `SystemPreferences` (`varname`, `value`) VALUES ('TimeZone', NULL);

-- add ManageBackup right
INSERT INTO `liveuser_rights` VALUES ('74', '0', 'ManageBackup', '1');
INSERT INTO `liveuser_grouprights` VALUES (1,74,3);

-- Initialize the topics order field
SET @i:=0;
CREATE TEMPORARY TABLE `TopicsTmp` SELECT DISTINCT `Id`, `LanguageId`, `Name`, `TopicOrder` FROM `Topics`;
DELETE FROM `TopicsTmp` WHERE 
    Id IN (SELECT Id FROM `Topics` GROUP BY Id HAVING COUNT(LanguageId) > 1) 
    AND LanguageId NOT IN (SELECT LanguageId FROM `Topics` GROUP BY Id HAVING COUNT(LanguageId) > 1);
UPDATE `TopicsTmp` SET `TopicOrder`= @i:=@i+1 ORDER BY Id ASC, LanguageId ASC, Name ASC;
UPDATE `Topics` SET `TopicOrder`= (SELECT `TopicsTmp`.`TopicOrder` FROM `TopicsTmp` WHERE `TopicsTmp`.Id = `Topics`.Id);


-- Fix the article order issues generated by bad coding

CREATE TEMPORARY TABLE ArticleOrderDup
SELECT NrSection, ArticleOrder, COUNT(ArticleOrder) AS dup FROM Articles 
GROUP BY NrSection, ArticleOrder, IdLanguage
HAVING dup > 1 
ORDER BY ArticleOrder;

UPDATE Articles, ArticleOrderDup 
SET Articles.ArticleOrder = Articles.ArticleOrder + ArticleOrderDup.dup - 1
WHERE Articles.NrSection = ArticleOrderDup.NrSection
    AND Articles.ArticleOrder > ArticleOrderDup.ArticleOrder;

DROP TEMPORARY TABLE ArticleOrderDup;

CREATE TEMPORARY TABLE ArticleOrderDup
SELECT NrSection, ArticleOrder, COUNT(ArticleOrder) AS dup FROM Articles 
GROUP BY NrSection, ArticleOrder, IdLanguage
HAVING dup > 1 
ORDER BY ArticleOrder;

SET @i := 0;
CREATE TEMPORARY TABLE DupOrderArticles
SELECT Articles.Number, Articles.ArticleOrder + (@i := @i + 1) - 1 AS ArticleOrder,
    Articles.NrSection, ArticleOrderDup.dup, 
    (@i < ArticleOrderDup.dup OR (@i := 0)) AS reset_index
FROM Articles, ArticleOrderDup
WHERE Articles.NrSection = ArticleOrderDup.NrSection
    AND Articles.ArticleOrder = ArticleOrderDup.ArticleOrder;

UPDATE Articles, DupOrderArticles
SET Articles.ArticleOrder = DupOrderArticles.ArticleOrder
WHERE Articles.Number = DupOrderArticles.Number
    AND Articles.NrSection = DupOrderArticles.NrSection;

DROP TEMPORARY TABLE ArticleOrderDup;
DROP TEMPORARY TABLE DupOrderArticles;
