#!/bin/bash

bin_path=`dirname $0`
if [ "$bin_path" = "." ] || [ "$bin_path" = "" ]; then
	script_call="./remove_instance.php"
	ETC_DIR=`./campsite_config --etc_dir`
	PHP=`./campsite_config --php_cli`
else
	script_call="$bin_path/remove_instance.php"
	ETC_DIR=`$bin_path/campsite_config --etc_dir`
	PHP=`$bin_path/campsite_config --php_cli`
fi

$"$PHP" -q $"$script_call" $"$ETC_DIR" $*
