#!/bin/sh

bin_path=`dirname $0`
if [ "$bin_path" = "." ] || [ "$bin_path" = "" ]; then
	script_call="./restore_instance.php"
	ETC_DIR=`./campsite_config --etc_dir`
else
	script_call="$bin_path/restore_instance.php"
	ETC_DIR=`$bin_path/campsite_config --etc_dir`
fi

php -q "$script_call" "$ETC_DIR" $*
