#!/bin/bash

bin_path=`dirname $0`
if [ "$bin_path" = "." ]; then
        script_call="./create_instance"
        ETC_DIR=`./campsite_config --etc_dir`
        PHP=`./campsite_config --php_cli`
elif [ "$bin_path" = "" ]; then
        BIN_DIR=`campsite_config --bin_dir`
        script_call="$BIN_DIR/create_instance"
        ETC_DIR=`campsite_config --etc_dir`
        PHP=`campsite_config --php_cli`
else
        script_call="$bin_path/create_instance"
        ETC_DIR=`$bin_path/campsite_config --etc_dir`
        PHP=`$bin_path/campsite_config --php_cli`
fi

pushd $ETC_DIR > /dev/null
for i in *; do
        if [ -d $i ]; then
		$script_call --db_name $i
	fi
done
popd > /dev/null
