<?
regGS("Delete article $1","Artikel $1 löschen");
regGS("You do not have the right to add articles.","Keine Berechtigung Artikel hinzuzufügen");
regGS("Show article on front page","Artikel auf der Startseite anzeigen");
regGS("Show article on section page","Artikel in der Rubrik anzeigen");
regGS("Enter keywords, comma separated","Stichwörter hinzufügen, mit Kommas getrennt");
regGS("Adding new article","Neuen Artikel hinzufügen");
regGS("You must select an article type.","Artikeltyp muss ausgewählt werden");
regGS("The article $1 has been created","Artikel $1 wurde erstellt");
regGS("The article $1 could not be created","Artikel $1 konnte nicht erstellt werden");
regGS("Do you want to edit the article?","Soll der Artikel editiert werden?");
regGS("Article $1 added to $2. $3 from $4. $5 of $6","Artikel $1 wurde zu $2 hinzugefügt. $3 von $4. $5 von $6");
regGS("Delete article","Artikel löschen");
regGS("You do not have the right to delete articles.","Keine Berechtigung Artikel zu löschen");
regGS("Are you sure you want to delete the article $1 ($2)?","Artikel $1 ($2) wirklich löschen?");
regGS("Deleting article","Artikel wird gelöscht");
regGS("The article $1 ($2) has been deleted.","Artikel $1 ($2) wurde gelöscht");
regGS("The article $1 ($2) could not be deleted.","Artikel $1 ($2) konnte nicht gelöscht werden");
regGS("Article $1 ($2) deleted from $3. $4 from $5. $6 ($7) of $8","Artikel $1 ($2) wurde gelöscht. $3 von $4. $5. $6 ($7) von $8");
regGS("Change article status","Artikel Status ändern");
regGS("Change the status of article $1 ($2) from $3 to","Status von Artikel $1 ($2) ändern von $3 auf");
regGS("Changing article status","Ändern des Artikelstatus");
regGS("Status of the article $1 ($2) has been changed from $3 to $4.","Artikelstatus von $1 ($2) wurde geändert von $3 auf $4");
regGS("Status of the article $1 ($2) could not be changed.","Artikelstatus von $1 ($2) konnte nicht geändert werden");
regGS("You do not have the right to change this article status. Once submitted an article can only changed by authorized users.","Keine Berechtigung, diesen Artikelstatus zu ändern. Bereits eingepflegte Artikel  können nur von autorisierten BenutzerInnen geändert werden.");
regGS("Article $1 status from $2. $3 from $4. $5 ($6) of $7 changed","Status von Artikel $1 von $2. $3 von $4. $5 ($6) von $7 geändert.");
regGS("Translate article","Artikel übersetzen.");
regGS("You do not have the right to change this article.  You may only edit your own articles and once submitted an article can only changed by authorized users.","Keine Berechtigung, den Artikel zu ändern.  Bearbeiten nur von eigenen Artikeln möglich. Bereits eingepflegte Artikel können nur von autorisierten BenutzerInnen verändert werden.");
regGS("Edit article details","Artikeldetails bearbeiten");
regGS("Simple editor","Einfacher Editor");
regGS("Advanced editor","erweiterter Editor");
regGS("Allow users without subscriptions to view the article","BenutzerInnen ohne Abonoment Ansicht des Artikels erlauben");
regGS("Unlocking article","Artikel freigeben");
regGS("The article has been unlocked.","Artikel wurde freigegeben");
regGS("The article could not be unlocked.","Artikel konnte nicht freigegeben werden");
regGS("You do not have the right to unlock the article. Once submitted an article can only changed by authorized users.","Keine Berechtigung Artikel freizugeben. Bereits eingepflegte Artikel können nur von autorisierten BenutzerInnen verändert werden.");
regGS("Changing article details","Ändern von Artikeldetails");
regGS("The article has been updated.","Artikel wurde aktualisiert");
regGS("The article cannot be updated or no changes have been made.","Artikel konnte nicht aktualisiert werden oder es wurden keine Änderungen vorgenommen");
regGS("Edit field: $1","Bearbeiten von Feld: $1");
regGS("Preview article","Artikelvorschau");
regGS("This article cannot be previewed. Please make sure it has a <B><I>single article</I></B> template selected.","Artikelvorschau nicht möglich. Bitte sicherstellen, dass nur EIN Artikeltemplate ausgewählt wurde");
regGS("This article has been locked by $1 ($2) at","Der Artikel wurde von $1 ($2) gesperrt");
regGS("Now is $1","Heute ist $1");
regGS("Are you sure you want to unlock it?","Wirklich freigeben?");
regGS("Edit Article","Artikel bearbeiten");

?>
