<?php
regGS("Article Type", "");
regGS("$1 articles found", "");
regGS("Show article on front page", "Zobrazit článek na titulní straně");
regGS("Show article on section page", "Zobrazit článek na stránce rubriky");
regGS("Enter keywords, comma separated", "Vložte klíčová slova, oddělená čárkou");
regGS("Article $1 added to $2. $3 from $4. $5 of $6", "Článek $1 byl přidán do $2. $3 z $4. $5 z $6");
regGS("Are you sure you want to delete the article $1 ($2)?", "Určitě chcete smazat článek $1 ($2)?");
regGS("Article $1 ($2) deleted from $3. $4 from $5. $6 ($7) of $8", "Článek $1 ($2) byl smazán z $3. 4$ z $5. $6 ($7) z $8");
regGS("Change article status", "Změnit stav článku");
regGS("Change the status of article $1 ($2) from $3 to", "Změnit stav článku $1 ($2) z $3");
regGS("Article $1 status from $2. $3 from $4. $5 ($6) of $7 changed", "Stav článku $1z $2. $3 z $4. $5 ($6) z $7 byl změněn");
regGS("Translate article", "Překlat článku");
regGS("You do not have the right to change this article.  You may only edit your own articles and once submitted an article can only changed by authorized users.", "Nemáte právo změnit tento článek. Můžete pouze editova své vlastní články. Podané články mohou být změněny pouze autorizovanými uživateli.");
regGS("Edit article details", "Editovat detaily článku");
regGS("Allow users without subscriptions to view the article", "Povolit náhled článku uživatelům bez předplatného");
regGS("The article has been locked by $1 ($2) $3 hour(s) and $4 minute(s) ago.", "");
regGS("The article has been locked by $1 ($2) $3 minute(s) ago.", "");
regGS("Are you sure you want to unlock it?", "Určitě ho chcete odemknout?");
regGS("Article is locked", "");
regGS("The article has been updated.", "Článek byl obnoven");
regGS("The article cannot be updated or no changes have been made.", "Článek nemohl být obnoven nebo nebyla provedena žádná změna");
regGS("Duplicate article", "");
regGS("The destination section is the same as the source section.", "");
regGS("The article is new; it is not possible to schedule it for automatic publishing.", "");
regGS("No article types were defined. You must create an article type first.", "");
regGS("Edit article types", "");
regGS("Could not save the article. It has been locked by $1 $2 hours and $3 minutes ago.", "");
regGS("You do not have the right to change this article status. Once submitted an article can only changed by authorized users.", "");
regGS("You do not have the right to delete articles.", "");
regGS("You must select an article type.", "");
regGS("Are you sure you want to delete this scheduled action?", "");
?>