<?
regGS("Name<BR><SMALL>(click to see sections)</SMALL>","Название<BR><SMALL>(щелкните для просмотра секций)</SMALL>:ru");
regGS("Front Page Template<BR><SMALL>(click to change)</SMALL>","Шаблон титульной страницы<BR><SMALL>(щелкните для изменения)</SMALL>:ru");
regGS("Single Article Template<BR><SMALL>(click to change)</SMALL>","Шаблон отдельной статьи<BR><SMALL>(щелкните для изменения)</SMALL>:ru");
regGS("Published<BR><SMALL>(yyyy-mm-dd)</SMALL>","Опубликовано<BR><SMALL>(гггг-мм-дд)</SMALL>:ru");
regGS("Delete issue $1","Удаление выпуска $1:ru");
regGS("Change issue status","Изменить статус выпуска:ru");
regGS("You do not have the right to change issues.","Вы не имеете права изменить выпуск.:ru");
regGS("Are you sure you want change the issue $1 status from $2 to $3?","Вы уверены, что хотите поменять статус выпуска $1 с $2 на $3?:ru");
regGS("Changing issue status","Изменение статуса выпуска:ru");
regGS("Status of the issue $1 has been changed from $2 to $3","Статус выпуска $1 был изменен с $2 на $3:ru");
regGS("Issue $1 Published: $2  changed status","Выпуск $1 Опубликован: $2  Измененный статус:ru");
regGS("Status of the issue $1 could not be changed.","Не удалось изменить статус выпуска $1.:ru");
regGS("Add new translation","Добавить новый перевод:ru");
regGS("You do not have the right to add issues.","Вы не имеете права добавления выпуска.:ru");
regGS("The issue $1 has been successfuly added.","Выпуск $1 был успешно добавлен.:ru");
regGS("The issue could not be added.","Не удалось добавить выпуск.:ru");
regGS("Please check if another issue with the same number/language does not already exist.","Пожалуйста проверьте, что еще не существует другого выпуска с таким же номером/языком.:ru");
regGS("Issue $1 added","Выпуск $1 добавлен:ru");
regGS("Change issue details","Сменить параметры выпуска:ru");
regGS("You do not have the right to change issue details.","Вы не имеете права изменить параметры выпуска.:ru");
regGS("Updating issue","Обновление выпуска:ru");
regGS("Changing issue's details","Изменение параметров выпуска:ru");
regGS("The issue $1 has been successfuly changed.","Выпуск $1 был успешно изменен.:ru");
regGS("The issue could not be changed.","Не удалось изменить выпуск.:ru");
regGS("Issue $1 updated in publication $2","Выпуск $1 обновлен в публикации $2:ru");
regGS("Delete issue","Удалить выпуск:ru");
regGS("You do not have the right to delete issues.","Вы не имеете права удаления выпусков.:ru");
regGS("Are you sure you want to delete the issue $1?","Вы уверены, что хотите удалить выпуск $1?:ru");
regGS("Deleting issue","Удаление выпуска:ru");
regGS("The issue $1 has ben deleted.","Выпуск $1 был удален.:ru");
regGS("The issue $1 could not be deleted.","Не удалось удалить выпуск $1.:ru");
regGS("All sections from Issue $1 from publication $2 deleted","Удалены все секции из выпуска $1 публикации $2");
regGS("Issue $1 from publication $2 deleted","Удален выпуск $1 из публикации $2:ru");
regGS("Use the structure of the previous issue","Использовать структуру предыдущего выпуска:ru");
regGS("Copy the entire structure in all languages from the previous issue except for content.","Скопировать всю структуру записи во все языки из предыдущего выпуска за исключением информационого наполнения.:ru");
regGS("You may modify it later if you wish.","Вы можете модифицировать это позже, если пожелаете.:ru");
regGS("Create a new structure","Создать новую структуру:ru");
regGS("Create a complete new structure.","Создать полностью новую структуру.:ru");
regGS("You must define an issue type for each language and then sections for them.","Вы должны определить тип выпуска для каждого языка и, затем, секции для них.:ru");
regGS("Copy previous issue","Скопировать предыдущий выпуск:ru");
regGS("No previous issue.","Нет предыдущего выпуска.:ru");
regGS("Copy structure from issue nr $1","Скопировать структуру из выпуска №$1:ru");
regGS("Copying previous issue","Копирование предыдущего выпуска:ru");
regGS("Copying done.","Копирование завершено.:ru");
regGS("New issue $1 from $2 in publication $3","Новый выпуск $1 из $2 в публикации $3:ru");
regGS("Adding new issue","Добавление нового выпуска:ru");
regGS("Issue $1 added in publication $2","Выпуск $1 добавлен в публикацию $2:ru");
regGS("Preview issue","Предварительный просмотр выпуска:ru");
regGS("This issue cannot be previewed. Please make sure it has a $1 template selected.","Невозможно просмотреть этот выпуск. Пожалуйста убедитесь, что у него выбран шаблон $1.:ru");
regGS("front page","титульная страница:ru");
regGS("Changing issue template","Изменение шаблона выпуска:ru");
regGS("You do not have the right to change issue templates.","Вы не имеете права смены шаблона выпуска.:ru");
regGS("Changing issue template for front page","Изменение шаблона выпуска для титульной страницы:ru");
regGS("Changing issue template for single article","Изменение шаблона выпуска для отдельной страницы:ru");
regGS("The template has been successfully changed.","Шаблон был успешно изменен.:ru");
regGS("Issue template for publication $1 changed to $2","Шаблон выпуска для публикации $1 изменен на $2:ru");
regGS("Issue template for single articles from $1 changed to $2","Шаблон выпуска для отдельной статьи изменен с $1 на $2:ru");
regGS("The template could not be changed.","Не удалось изменить шаблон.:ru");

?>