<?php
regGS("You do not have the right to add IP address groups.", "Nemate pravo da dodajete grupe zasnovane na IP adresama");
regGS("Readers", "");
regGS("Edit reader data", "");
regGS("Add new IP address group", "Dodajte novu korisničku grupu zasnovanu na IP adresi");
regGS("User management", "Administracija korisnicima");
regGS("Set", "Postavi");
regGS("Update", "Izmeni");
regGS("Rights", "Prava");
regGS("IP Access", "IP pristup");
regGS("User Name", "Korisničko ime");
regGS("Full Name", "Puno ime");
regGS("Staff", "Osoblje");
regGS("Delete user $1", "Obriši korisnika $1");
regGS("You do not have the right to create user accounts.", "Nemate pravo da kreirate korisničke naloge");
regGS("Title", "Zvanje");
regGS("Gender", "Pol");
regGS("Mr.", "gospodin");
regGS("Mrs.", "gospođa");
regGS("Ms.", "gospođica");
regGS("Dr.", "doktor");
regGS("Male", "muški");
regGS("Female", "ženski");
regGS("under 18", "ispod 18");
regGS("65 or over", "65 ili više");
regGS("Age", "Starost");
regGS("Confirm password", "Potvrdi lozinku");
regGS("E-Mail", "E-pošta");
regGS("City", "Grad");
regGS("Street Address", "Ulična adresa");
regGS("Postal Code", "Poštanski broj");
regGS("State", "Provincija/region");
regGS("Phone", "Telefon");
regGS("Fax", "Faks");
regGS("Contact Person", "Osoba za kontakt");
regGS("Second Phone", "Alternativni telefon");
regGS("Employer", "Poslodavac");
regGS("Employer Type", "Tip poslodavca");
regGS("Corporate", "Komercijalna delatnost");
regGS("Non-Governmental Organisation", "Nevladina organizacija");
regGS("Government Agency", "Vladina agencija");
regGS("Academic", "Akademska ustanova");
regGS("Media", "Medijska kuća");
regGS("Position", "Pozicija");
regGS("Adding new user account", "Dodavanje novog korisničkog naloga");
regGS("You must select a $1", "Morate izabrati $1");
regGS("The password must be at least 6 characters long and both passwords should match.", "Lozinka mora biti dugačka najmanje 6 karaktera i obe lozinke se moraju poklapati");
regGS("You must select an user type.", "Morate izabrati tip korisnika");
regGS("The user account $1 has been created.", "Kreiran je korisnički nalog za $1 ");
regGS("The user account could not be created.", "Korisnički nalog ne može biti kreiran");
regGS("Please check if an account with the same user name does not already exist.", "Proveri da li nalog pod tim korisničkim imenom već ne postoji");
regGS("User account $1 created", "Kreiran je korisnički nalog za $1");
regGS("Change password", "Promeni lozinku");
regGS("You do not have the right to change user passwords.", "Nemate pravo da menjate korisničke lozinke");
regGS("Changing user password", "Menjanje korisničke lozinke");
regGS("The password could not be changed.", "Lozinka ne može biti promenjena");
regGS("Password changed for $1", "Promenjena je lozinka za $1");
regGS("The password has been changed.", "Lozinka je promenjena");
regGS("User may manage templates", "Korisnik može da upravlja šablonima");
regGS("User may add/change country entries", "Korisnik može da dodaje/menja podatke o državama");
regGS("Edit user account permissions", "Prikaži dodeljena prava za korisnički nalog");
regGS("You do not have the right to change user account permissions.", "Nemate pravo da menjate dodeljena prava za korisničke naloge");
regGS("This user account does not have permissions information.", "Za ovaj korisnički nalog nema informacija o dodeljenim pravima");
regGS("Updating user account permissions", "Izmena dodeljenih prava za korisnički nalog");
regGS("Permissions for $1 changed", "Dodeljena prava za $1 su izmenjena");
regGS("User account permissions have been successfuly updated.", "Dodeljena prava za korisnički nalog uspešno su izmenjena");
regGS("User account permissions could not be updated.", "Dodeljena prava za korisnički nalog ne mogu biti izmenjena");
regGS("Change user account information", "Promenite podatke za korisnički nalog");
regGS("You do not have the right to change user account information.", "Nemate pravo da promenite podatke za korisnički nalog");
regGS("Changing user account information", "Menjanje podataka za korisnički nalog");
regGS("User account information has been changed.", "Podaci za korisnički nalog su promenjeni");
regGS("User account information could not be changed.", "Podaci za korisnički nalog ne mogu biti promenjeni");
regGS("User account information changed for $1", "Podaci za korisnički nalog $1 su promenjeni");
regGS("Old password", "Stara lozinka");
regGS("New password", "Nova lozinka");
regGS("Confirm new password", "Potvrdi novu lozinku");
regGS("Changing your password", "Menjanje vaše lozinke");
regGS("The password you typed is incorrect.", "Lozinka koju ste uneli je neispravna");
regGS("User $1 changed his password", "Korisnik $1 je promenio lozinku");
regGS("Delete user account", "Obriši korisnički nalog");
regGS("You do not have the right to delete user accounts.", "Nemate pravo da brišete korisničke naloge");
regGS("Are you sure you want to delete the user account $1 ?", "Da li ste sigurni da želite da obrišete korisnički nalog $1?");
regGS("Deleting user account", "Brisanje korisničkog naloga");
regGS("The user account $1 has been deleted.", "Korisnički nalog $1 je obrisan");
regGS("The user account $1 could not be deleted.", "Korisnički nalog $1 ne može biti obrisan");
regGS("No such user.", "Nema takvog korisnika");
regGS("User IP access list management", "Upravljanje listom pristupa preko korisničkih IP adresa");
regGS("No records.", "Bez podataka");
regGS("Delete IP Group $1", "Obriši IP grupu $1");
regGS("Start IP", "Početna IP adresa");
regGS("Number of addresses", "Broj adresa");
regGS("IP Access List", "Lista pristupa na osnovu IP adresa");
regGS("Adding new IP Group", "Dodavanje nove grupe zasnovane na IP adresi");
regGS("The IP Group $1 has been created.", "Grupa zasnovana na IP adresi je kreirana");
regGS("IP Group $1 added for user $2", "IP grupa $1 dodata za korisnika $2");
regGS("The IP Group could not be created.", "IP grupa ne može biti kreirana");
regGS("Please check if an account with the same IP Group does not already exist.", "Proverite da li nalog sa istom IP grupom već ne postoji");
regGS("Delete IP Group", "Obriši IP grupu");
regGS("You do not have the right to delete IP Groups.", "Nemate pravo da brišete IP grupe");
regGS("Are you sure you want to delete the IP Group $1?", "Sigurni ste da želite da obrišete IP grupu $1?");
regGS("No such IP Group.", "Nema takve IP grupe");
regGS("Deleting IP Group", "Brisanje IP grupe");
regGS("The IP address group $1 has been deleted.", "Grupa zasnovana na IP adresi $1 je obrisana");
regGS("The IP Group could not be deleted.", "IP grupa ne može biti obrisana");
regGS("No IP Group.", "Nema IP grupe");
?>