<?php
regGS("You do not have the right to add IP address groups.", "لا يحق لك إضافة مجموعات عنوان بروتوكول الإنترنت");
regGS("Readers", "");
regGS("Edit reader data", "");
regGS("Add new IP address group", "أضف مجموعة جديدة من عنوان بروتوكول الإنترنت");
regGS("User management", "إدارة المستخدم");
regGS("Set", "مجموعة");
regGS("Update", "تحديث");
regGS("Rights", "حقوق");
regGS("IP Access", "الدخول إلى بروتوكول الإنترنت");
regGS("User Name", "إسم المستخدم");
regGS("Full Name", "الإسم الكامل");
regGS("Staff", "موظف");
regGS("Delete user $1", " $1 إلغاء المستخدم");
regGS("You do not have the right to create user accounts.", "لا يحق لك وضع اشتراكات للمستخدم");
regGS("Title", "الوظيفة");
regGS("Gender", "الجنس");
regGS("Mr.", "سيد");
regGS("Mrs.", "سيدة");
regGS("Ms.", "آنسة");
regGS("Dr.", "دكتور");
regGS("Male", "ذكر");
regGS("Female", "أنثى");
regGS("under 18", "دون الـ 18 سنة");
regGS("65 or over", "سنة وما فوق65 ");
regGS("Age", "العمر");
regGS("Confirm password", "تأكيد كلمة السر");
regGS("E-Mail", "البريد الالكتروني");
regGS("City", "المدينة");
regGS("Street Address", "عنوان الشارع");
regGS("Postal Code", "الرمز البريدي");
regGS("State", "الولاية");
regGS("Phone", "الهاتف");
regGS("Fax", "الفاكس");
regGS("Contact Person", "الشخص المرجع");
regGS("Second Phone", "رقم هاتف ثان");
regGS("Employer", "رب العمل");
regGS("Employer Type", "نوع رب العمل");
regGS("Corporate", "شركة");
regGS("Non-Governmental Organisation", "منظمة غير حكومية");
regGS("Government Agency", "وكالة حكومية");
regGS("Academic", "أكاديمي");
regGS("Media", "إعلام");
regGS("Position", "مركز الوظيفة");
regGS("Adding new user account", "إضافة اشتراك لمستخدم جديد");
regGS("You must select a $1", "  $1عليك الاختيار ");
regGS("The password must be at least 6 characters long and both passwords should match.", "يجب أن تتألف كلمة السر من 6 أحرف على الأقل. كما يجب أن تكون كلمتا السر متشابهتين");
regGS("You must select an user type.", "يجب إختيار نوع المستخدم");
regGS("The user account $1 has been created.", "  $1 تم وضع اشتراك للمستخدم");
regGS("The user account could not be created.", "لا يمكن وضع اشتراك للمستخدم");
regGS("Please check if an account with the same user name does not already exist.", "الرجاء التأكد من أن اشتراكاّ باسم هذا المستخدم غير موجود مسبقاً");
regGS("User account $1 created", "  $1 تم وضع اشتراك للمستخدم");
regGS("Change password", "تغيير كلمة سرّ المستخدم");
regGS("You do not have the right to change user passwords.", "لا يحق تغيير كلمة سرّ المستخدم");
regGS("Changing user password", "تغيير كلمة سرّ المستخدم");
regGS("The password could not be changed.", "لا يمكن تغيير كلمة السرّ");
regGS("Password changed for $1", " $1 تغيير كلمة السر ل");
regGS("The password has been changed.", "تم تغيير كلمة السر");
regGS("User may manage templates", "يمكن للمستخدم إدارة النماذج");
regGS("User may add/change country entries", "يمكن للمستخدم إضافة بيانات البلدان أم تغييرها");
regGS("Edit user account permissions", "السماح لاشتراك المستخدم");
regGS("You do not have the right to change user account permissions.", "لا يحق لك تغيير الاذن لاشتراك المستخدم");
regGS("This user account does not have permissions information.", "ليس لدى اشتراك المستخدم المعلومات الاذن ");
regGS("Updating user account permissions", "تحديث الاذن لاشتراك المستخدم");
regGS("Permissions for $1 changed", " $1 تغيير السماح ل ");
regGS("User account permissions have been successfuly updated.", "لقد تم تحديث الاذن لاشتراك المستخدم ");
regGS("User account permissions could not be updated.", "لا يمكن تغيير الاذن لاشتراك المستخدم");
regGS("Change user account information", "غيّر معلومات اشتراك المستخدم");
regGS("You do not have the right to change user account information.", "لا يحق لك تغيير معلومات اشتراك المستخدم");
regGS("Changing user account information", "تغيير معلومات اشتراك المستخدم");
regGS("User account information has been changed.", "تم تغيير معلومات اشتراك المستخدم");
regGS("User account information could not be changed.", "لا يمكن تغيير معلومات اشتراك المستخدم");
regGS("User account information changed for $1", "معلومات اشتراك المستخدم ل  $1");
regGS("Old password", "كلمة السر القديمة");
regGS("New password", "كلمة السر الجديدة");
regGS("Confirm new password", "تأكيد كلمة السر الجديدة");
regGS("Changing your password", "تغيير كلمة السر الخاصة بك");
regGS("The password you typed is incorrect.", "كلمة السر التي طبعتها غير صحيحة");
regGS("User $1 changed his password", "بدّل المستخدم 1$ كلمة السر الخاصة به");
regGS("Delete user account", "الغاء اشتراك المستخدم");
regGS("You do not have the right to delete user accounts.", "لا يحق لك إلغاء اشتراكات المستخدم");
regGS("Are you sure you want to delete the user account $1 ?", " هل أنت متأكد من أنك تريد إلغاء اشتراك المستخدم  $1 ؟");
regGS("Deleting user account", "الغاء اشتراك المستخدم");
regGS("The user account $1 has been deleted.", " تم إلغاء اشتراك المستخدم  $1");
regGS("The user account $1 could not be deleted.", "لا يمكن إلغاء اشتراك المستخدم  $1");
regGS("No such user.", "هذا المستخدم غير موجود");
regGS("User IP access list management", "إدارة قائمة دخول المستخدم إلى بروتوكول الإنترنت");
regGS("No records.", "لا بيانات");
regGS("Delete IP Group $1", "الغاء مجموعة بروتوكول الإنترنت  $1");
regGS("Start IP", "ابدأ بروتوكول الإنترنت");
regGS("Number of addresses", "عدد العناوين");
regGS("IP Access List", "قائمة الدخول إلى بروتوكول الإنترنت");
regGS("Adding new IP Group", "إضافة مجموعة جديدة من بروتوكول الإنترنت");
regGS("The IP Group $1 has been created.", "وضع مجموعة بروتوكول الإنترنت  $1");
regGS("IP Group $1 added for user $2", "إضافة مجموعة بروتوكول الإنترنت  $1 إلى المستخدم  $2");
regGS("The IP Group could not be created.", "لا يمكن وضع مجموعة بروتوكول الإنترنت ");
regGS("Please check if an account with the same IP Group does not already exist.", " الرجاء التأكد من عدم وجود اشتراك يتضمن مجموعة بروتوكول الإنترنت نفسها");
regGS("Delete IP Group", " إلغ مجموعة بروتوكول الإنترنت");
regGS("You do not have the right to delete IP Groups.", "لا يحق لك إلغاء مجموعات بروتوكول الإنترنت");
regGS("Are you sure you want to delete the IP Group $1?", " هل أنت متأكد من أنك تريد إلغاء مجموعة بروتوكول الإنترنت  $1؟");
regGS("No such IP Group.", "ليس هناك مجموعة مماثلة من بروتوكول الإنترنت");
regGS("Deleting IP Group", " الغاء مجموعة بروتوكول الإنترنت");
regGS("The IP address group $1 has been deleted.", "تم الغاء مجموعة عنوان بروتوكول الإنترنت  $1");
regGS("The IP Group could not be deleted.", "لا يمكن إلغاء مجموعة بروتوكول الإنترنت");
regGS("No IP Group.", "لا يوجد مجموعة بروتوكول الإنترنت");
?>