<?
regGS("User management","");
regGS("Set","");
regGS("Update","");
regGS("Rights","");
regGS("IP Access","");
regGS("User Name","");
regGS("Full Name","");
regGS("Staff","");
regGS("Delete user $1","");
regGS("You do not have the right to create user accounts.","");
regGS("Title","");
regGS("Gender","");
regGS("Mr.","");
regGS("Mrs.","");
regGS("Ms.","");
regGS("Dr.","");
regGS("Male","");
regGS("Female","");
regGS("under 18","");
regGS("65 or over","");
regGS("Age","");
regGS("Confirm password","");
regGS("E-Mail","");
regGS("City","");
regGS("Street Address","");
regGS("Postal Code","");
regGS("State","");
regGS("Phone","");
regGS("Fax","");
regGS("Contact Person","");
regGS("Second Phone","");
regGS("Employer","");
regGS("Employer Type","");
regGS("Corporate","");
regGS("Non-Governmental Organisation","");
regGS("Government Agency","");
regGS("Academic","");
regGS("Media","");
regGS("Position","");
regGS("Adding new user account","");
regGS("You must select a $1","");
regGS("The password must be at least 6 characters long and both passwords should match.","");
regGS("You must select an user type.","");
regGS("The user account $1 has been created.","");
regGS("The user account could not be created.","");
regGS("Please check if an account with the same user name does not already exist.","");
regGS("User account $1 created","");
regGS("Change user password","");
regGS("You do not have the right to change user passwords.","");
regGS("Changing user password","");
regGS("The password could not be changed.","");
regGS("Password changed for $1","");
regGS("The password has been changed.","");
regGS("User may manage templates","");
regGS("User may add/change country entries","");
regGS("Edit user account permissions","");
regGS("You do not have the right to change user account permissions.","");
regGS("This user account does not have permissions information.","");
regGS("Updating user account permissions","");
regGS("Permissions for $1 changed","");
regGS("User account permissions have been successfuly updated.","");
regGS("User account permissions could not be updated.","");
regGS("Change user account information","");
regGS("You do not have the right to change user account information.","");
regGS("Changing user account information","");
regGS("User account information has been changed.","");
regGS("User account information could not be changed.","");
regGS("User account information changed for $1","");
regGS("Old password","");
regGS("New password","");
regGS("Confirm new password","");
regGS("Changing your password","");
regGS("The password you typed is incorrect.","");
regGS("User $1 changed his password","");
regGS("Delete user account","");
regGS("You do not have the right to delete user accounts.","");
regGS("Are you sure you want to delete the user account $1 ?","");
regGS("Deleting user account","");
regGS("The user account $1 has been deleted.","");
regGS("The user account $1 could not be deleted.","");
regGS("No such user.","");
regGS("User IP access list management","");
regGS("Add new IP address group","");
regGS("No records.","");
regGS("Delete IP Group $1","");
regGS("You do not have the right to add IP address groups.","");
regGS("Start IP","");
regGS("Number of addresses","");
regGS("IP Access List","");
regGS("Adding new IP Group","");
regGS("The IP Group $1 has been created.","");
regGS("IP Group $1 added for user $2","");
regGS("The IP Group could not be created.","");
regGS("Please check if an account with the same IP Group does not already exist.","");
regGS("Delete IP Group","");
regGS("You do not have the right to delete IP Groups.","");
regGS("Are you sure you want to delete the IP Group $1?","");
regGS("No such IP Group.","");
regGS("Deleting IP Group","");
regGS("The IP address group $1 has been deleted.","");
regGS("The IP Group could not be deleted.","");

?>
