<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Newscoop</title>
</head>
<body>
  <h1><?php putGS('An error occurred'); ?></h1>
  <h2><?php echo $this->message ?></h2>

  <?php if (isset($this->exception)): ?>

  <h3><?php putGS('Exception information:'); ?></h3>
  <p>
  		<b>Type:</b> <?php echo get_class( $this->exception ) ?>
  		<br />
  		<b>Code:</b> <?php echo $this->exception->getCode() ?>
  		<br />
      <b>Message:</b> <?php echo $this->exception->getMessage() ?>
      <br />
      <b>File:</b> <?php echo $this->exception->getFile() ?> <b>:</b> <?php echo $this->exception->getLine() ?>
  </p>

  <h3><?php putGS('Stack trace:'); ?></h3>
  <pre><?php echo $this->exception->getTraceAsString() ?>
  </pre>

  <h3><?php putGS('Request Parameters:'); ?></h3>
  <pre><?php echo var_export($this->request->getParams(), true) ?>
  </pre>
  <?php endif ?>

</body>
</html>
