<?php
regGS("Name<BR><SMALL>(click to see sections)</SMALL>","Name<BR><SMALL>(click to see sections)</SMALL>:en");
regGS("Published<BR><SMALL>(yyyy-mm-dd)</SMALL>","Published<BR><SMALL>(yyyy-mm-dd)</SMALL>:en");
regGS("Delete issue $1","Delete issue $1:en");
regGS("Publish articles","Publish articles:en");
regGS("Change issue status","Change issue status:en");
regGS("You do not have the right to change issues.","You do not have the right to change issues.:en");
regGS("Are you sure you want to change the issue $1 status from $2 to $3?","Are you sure you want to change the issue $1 status from $2 to $3?:en");
regGS("Issue $1 Published: $2  changed status","Issue $1 Published: $2  changed status:en");
regGS("Add new translation","Add new translation:en");
regGS("You do not have the right to add issues.","You do not have the right to add issues.:en");
regGS("The issue $1 has been successfuly added.","The issue $1 has been successfuly added.:en");
regGS("The issue could not be added.","The issue could not be added.:en");
regGS("Please check if another issue with the same number/language does not already exist.","Please check if another issue with the same number/language does not already exist.:en");
regGS("Change issue details","Change issue details:en");
regGS("You do not have the right to change issue details.","You do not have the right to change issue details.:en");
regGS("Publication date<BR><SMALL>(yyyy-mm-dd)</SMALL>","Publication date<BR><SMALL>(yyyy-mm-dd)</SMALL>:en");
regGS("Front Page Template","Front Page Template:en");
regGS("Issue $1 added","Issue $1 added:en");
regGS("Issue $1 updated in publication $2","Issue $1 updated in publication $2:en");
regGS("Delete issue","Delete issue:en");
regGS("You do not have the right to delete issues.","You do not have the right to delete issues.:en");
regGS("Are you sure you want to delete the issue $1?","Are you sure you want to delete the issue $1?:en");
regGS("Deleting issue","Deleting issue:en");
regGS("The issue $1 has ben deleted.","The issue $1 has ben deleted.:en");
regGS("The issue $1 could not be deleted.","The issue $1 could not be deleted.:en");
regGS("All sections from Issue $1 from publication $2 deleted", "All sections from Issue $1 from publication $2 deleted:en");
regGS("Issue $1 from publication $2 deleted","Issue $1 from publication $2 deleted:en");
regGS("Use the structure of the previous issue","Use the structure of the previous issue:en");
regGS("Copy the entire structure in all languages from the previous issue except for content.","Copy the entire structure in all languages from the previous issue except for content.:en");
regGS("You may modify it later if you wish.","You may modify it later if you wish.:en");
regGS("Create a new structure","Create a new structure:en");
regGS("Create a complete new structure.","Create a complete new structure.:en");
regGS("You must define an issue type for each language and then sections for them.","You must define an issue type for each language and then sections for them.:en");
regGS("Copy previous issue","Copy previous issue:en");
regGS("No previous issue.","No previous issue.:en");
regGS("Copy structure from issue nr $1","Copy structure from issue nr $1:en");
regGS("Copying previous issue","Copying previous issue:en");
regGS("Copying done.","Copying done.:en");
regGS("Select the issue","Select the issue:en");
regGS("New issue $1 from $2 in publication $3","New issue $1 from $2 in publication $3:en");
regGS("Adding new issue","Adding new issue:en");
regGS("Issue $1 added in publication $2","Issue $1 added in publication $2:en");
regGS("Delete entry", "Delete entry:en");
regGS("Issue Publishing Schedule", "Issue Publishing Schedule");
regGS("Invalid Input: $1", "Invalid Input: $1:en");
?>