UPDATE `SystemPreferences` SET value = "Europe/London" WHERE varname = "TimeZone" AND value = "0";
UPDATE `SystemPreferences` SET value = "Europe/Brussels" WHERE varname = "TimeZone" AND (value = "1" OR value = "+1");
UPDATE `SystemPreferences` SET value = "Europe/Athens" WHERE varname = "TimeZone" AND (value = "2" OR value = "+2");
UPDATE `SystemPreferences` SET value = "Asia/Baghdad" WHERE varname = "TimeZone" AND (value = "3" OR value = "+3");
UPDATE `SystemPreferences` SET value = "Asia/Muscat" WHERE varname = "TimeZone" AND (value = "4" OR value = "+4");
UPDATE `SystemPreferences` SET value = "Asia/Yekaterinburg" WHERE varname = "TimeZone" AND (value = "5" OR value = "+5");
UPDATE `SystemPreferences` SET value = "Asia/Almaty" WHERE varname = "TimeZone" AND (value = "6" OR value = "+6");
UPDATE `SystemPreferences` SET value = "Asia/Bangkok" WHERE varname = "TimeZone" AND (value = "7" OR value = "+7");
UPDATE `SystemPreferences` SET value = "Asia/Singapore" WHERE varname = "TimeZone" AND (value = "8" OR value = "+8");
UPDATE `SystemPreferences` SET value = "Asia/Tokyo" WHERE varname = "TimeZone" AND (value = "9" OR value = "+9");
UPDATE `SystemPreferences` SET value = "Asia/Vladivostok" WHERE varname = "TimeZone" AND (value = "10" OR value = "+10");
UPDATE `SystemPreferences` SET value = "Asia/Magadan" WHERE varname = "TimeZone" AND (value = "11" OR value = "+11");
UPDATE `SystemPreferences` SET value = "Asia/Kamchatka" WHERE varname = "TimeZone" AND (value = "12" OR value = "+12");
UPDATE `SystemPreferences` SET value = "Atlantic/Azores" WHERE varname = "TimeZone" AND value = "-1";
UPDATE `SystemPreferences` SET value = "America/Noronha" WHERE varname = "TimeZone" AND value = "-2";
UPDATE `SystemPreferences` SET value = "America/Argentina/Buenos_Aires" WHERE varname = "TimeZone" AND value = "-3";
UPDATE `SystemPreferences` SET value = "America/La_Paz" WHERE varname = "TimeZone" AND value = "-4";
UPDATE `SystemPreferences` SET value = "America/Bogota" WHERE varname = "TimeZone" AND value = "-5";
UPDATE `SystemPreferences` SET value = "America/Mexico_City" WHERE varname = "TimeZone" AND value = "-6";
UPDATE `SystemPreferences` SET value = "America/Phoenix" WHERE varname = "TimeZone" AND value = "-7";
UPDATE `SystemPreferences` SET value = "America/Metlakatla" WHERE varname = "TimeZone" AND value = "-8";
UPDATE `SystemPreferences` SET value = "Pacific/Gambier" WHERE varname = "TimeZone" AND value = "-9";
UPDATE `SystemPreferences` SET value = "Pacific/Honolulu" WHERE varname = "TimeZone" AND value = "-10";
UPDATE `SystemPreferences` SET value = "Pacific/Midway" WHERE varname = "TimeZone" AND value = "-11";
UPDATE `SystemPreferences` SET value = "Pacific/Kwajalein" WHERE varname = "TimeZone" AND value = "-12";
UPDATE `SystemPreferences` SET value = "" WHERE varname = "TimeZone" AND value NOT IN ("", "Europe/London", "Europe/Brussels", "Europe/Athens", "Asia/Baghdad", "Asia/Muscat", "Asia/Yekaterinburg", "Asia/Almaty", "Asia/Bangkok", "Asia/Singapore", "Asia/Tokyo", "Asia/Vladivostok", "Asia/Magadan", "Asia/Kamchatka", "Atlantic/Azores", "America/Noronha", "America/Argentina", "America/La_Paz", "America/Bogota", "America/Mexico_City", "America/Phoenix", "America/Metlakatla", "Pacific/Gambier", "Pacific/Honolulu", "Pacific/Midway", "Pacific/Kwajalein");
