<?php $this->headLink( array( 'type' => 'text/css', 'href' => $this->baseUrl('/admin-style/common.css'), 'media' => 'screen', 'rel'	=> 'stylesheet' ) ); ?>

<div class="ui-widget-content small-block block-shadow theme-settings">
	<div class="padded clearfix inner-tabs">
		<div class="tabs">
			<ul>
				<li><a href="#tabs-1">Theme settings</a></li>
				<li><a href="#tabs-2">Theme templates</a></li>
			</ul>
			<div id="tabs-1">
				<div class="clear"></div>

				<?php echo $this->action( 'wizard-theme-settings', 'themes', 'admin', array( 'format' => 'adv', 'id' => $this->themeId ) ) ?>

				<div class="themeSettingsTabs">

					<?php echo $this->action( 'wizard-theme-template-settings', 'themes', 'admin', array( 'format' => 'adv', 'id' => $this->themeId ) ) ?>

					<?php echo $this->action( 'wizard-theme-article-types', 'themes', 'admin', array( 'format' => 'adv', 'id' => $this->themeId ) ) ?>

					<input type="button" name="submit" id="submit-settings-ctrl" class="button themeSettingsBtn" value="Save All">

				</div>
			</div>

			<div id="tabs-2">
                <?php echo $this->action( 'files', 'themes', 'admin', array( 'id' => $this->theme->id ) ); ?>

				<div class="clear"></div>
				<ul class="currentDirectory">
					<li>Current directory:</li>
					<li>/</li>
				</ul>
				<fieldset class="themeTemplatesActionHolder">
					<select	class="input_select">
						<option>Actions</option>
						<option>1</option>
						<option>1</option>
					</select>
				</fieldset>

				<div class="dataTables_wrapper">
					<div class="fg-toolbar ui-toolbar ui-widget-header ui-corner-tl ui-corner-tr ui-helper-clearfix">
						<!--<div id="gridx_filter" class="dataTables_filter"></div>-->
					</div>

					<table cellspacing="0" cellpadding="0" class="datatable themeTemplatesTable" id="gridx" style="width: 100%; margin: 0pt;">

						<colgroup>
                    		<col width="20px">
                    		<col width="264px">
                    		<col width="60px">
                    		<col width="80px">
                    		<col width="160px">
                    		<col width="120px">
                    		<col width="100px">
                    	</colgroup>
                    	<thead>
                    		<tr>
                    			<th class="ui-state-default">
                    			<div class="DataTables_sort_wrapper"><input type="checkbox"> <span></span></div>
                    			</th>
                    			<th class="name ui-state-default">
                    			<div class="DataTables_sort_wrapper">Name<span
                    				class="css_right ui-icon ui-icon-carat-2-n-s"></span></div>
                    			</th>
                    			<th class="ui-state-default">
                    			<div class="DataTables_sort_wrapper">ID<span
                    				class="css_right ui-icon ui-icon-carat-2-n-s"></span></div>
                    			</th>
                    			<th class="ui-state-default">
                    			<div class="DataTables_sort_wrapper">Type<span
                    				class="css_right ui-icon ui-icon-carat-2-n-s"></span></div>
                    			</th>
                    			<th class="ui-state-default flag">
                    			<div class="DataTables_sort_wrapper">Cache lifetime, sec.<span
                    				class="css_right ui-icon ui-icon-carat-2-n-s"></span></div>
                    			</th>
                    			<th class="ui-state-default flag">
                    			<div class="DataTables_sort_wrapper">Date modified<span
                    				class="css_right ui-icon ui-icon-carat-2-n-s"></span></div>
                    			</th>
                    			<th class="ui-state-default flag">
                    			<div class="DataTables_sort_wrapper">Action<span></span></div>
                    			</th>
                    		</tr>
                    	</thead>
                    	<tbody>
                    		<tr class="odd controls">
                    			<td colspan="7"><a href="#" class="upOneLevel">up one level </a></td>
                    		</tr>
                    		<tr class="odd">
                    			<td><input type="checkbox"></td>
                    			<td><a href="#" class="folder">_css</a></td>
                    			<td>&nbsp;</td>
                    			<td>dir</td>
                    			<td align="center">&nbsp;</td>
                    			<td>&nbsp;</td>
                    			<td>
                    			<ul class="actionDropDown">
                    				<li><a href="#">Actions</a>
                    				<ul>
                    					<li><a href="#" class="newFolder">New folder</a></li>
                    					<li><a href="#" class="newTemplate">New template</a></li>
                    					<li><a href="#" class="rename">Rename</a></li>
                    					<li><a href="#" class="duplicate">Duplicate</a></li>
                    					<li><a href="#" class="delete">Delete</a></li>
                    				</ul>
                    				</li>
                    			</ul>
                    			</td>
                    		</tr>
                    		<tr class="even">
                    			<td><input type="checkbox"></td>
                    			<td><a href="#" class="folder">_img</a></td>
                    			<td>&nbsp;</td>
                    			<td>dir</td>
                    			<td align="center">&nbsp;</td>
                    			<td>&nbsp;</td>
                    			<td>
                    			<ul class="actionDropDown">
                    				<li><a href="#">Actions</a>
                    				<ul>
                    					<li><a href="#" class="newFolder">New folder</a></li>
                    					<li><a href="#" class="newTemplate">New template</a></li>
                    					<li><a href="#" class="rename">Rename</a></li>
                    					<li><a href="#" class="duplicate">Duplicate</a></li>
                    					<li><a href="#" class="delete">Delete</a></li>
                    				</ul>
                    				</li>
                    			</ul>
                    			</td>
                    		</tr>
                    		<tr class="odd">
                    			<td><input type="checkbox"></td>
                    			<td><a href="#" class="folder">_tpl</a></td>
                    			<td>&nbsp;</td>
                    			<td>dir</td>
                    			<td align="center">&nbsp;</td>
                    			<td>&nbsp;</td>
                    			<td>
                    			<ul class="actionDropDown">
                    				<li><a href="#">Actions</a>
                    				<ul>
                    					<li><a href="#" class="newFolder">New folder</a></li>
                    					<li><a href="#" class="newTemplate">New template</a></li>
                    					<li><a href="#" class="rename">Rename</a></li>
                    					<li><a href="#" class="duplicate">Duplicate</a></li>
                    					<li><a href="#" class="delete">Delete</a></li>
                    				</ul>
                    				</li>
                    			</ul>
                    			</td>
                    		</tr>
                    		<tr class="even">
                    			<td><input type="checkbox"></td>
                    			<td><a href="#" class="file">issue.tpl</a></td>
                    			<td>1128</td>
                    			<td>template</td>
                    			<td align="center">0</td>
                    			<td align="right">28.04.2011</td>
                    			<td>
                    			<ul class="actionDropDown">
                    				<li><a href="#">Actions</a>
                    				<ul>
                    					<li><a href="#" class="newFolder">New folder</a></li>
                    					<li><a href="#" class="newTemplate">New template</a></li>
                    					<li><a href="#" class="rename">Rename</a></li>
                    					<li><a href="#" class="duplicate">Duplicate</a></li>
                    					<li><a href="#" class="delete">Delete</a></li>
                    				</ul>
                    				</li>
                    			</ul>
                    			</td>
                    		</tr>
                    		<tr class="odd">
                    			<td><input type="checkbox"></td>
                    			<td><a href="#" class="file">section.tpl</a></td>
                    			<td>1129</td>
                    			<td>template</td>
                    			<td align="center">0</td>
                    			<td align="right">28.04.2011</td>
                    			<td>
                    			<ul class="actionDropDown">
                    				<li><a href="#">Actions</a>
                    				<ul>
                    					<li><a href="#" class="newFolder">New folder</a></li>
                    					<li><a href="#" class="newTemplate">New template</a></li>
                    					<li><a href="#" class="rename">Rename</a></li>
                    					<li><a href="#" class="duplicate">Duplicate</a></li>
                    					<li><a href="#" class="delete">Delete</a></li>
                    				</ul>
                    				</li>
                    			</ul>
                    			</td>
                    		</tr>
                    		<tr class="even">
                    			<td><input type="checkbox"></td>
                    			<td><a href="#" class="file">article.tpl</a></td>
                    			<td>1130</td>
                    			<td>template</td>
                    			<td align="center">0</td>
                    			<td align="right">28.04.2011</td>
                    			<td>
                    			<ul class="actionDropDown">
                    				<li><a href="#">Actions</a>
                    				<ul>
                    					<li><a href="#" class="newFolder">New folder</a></li>
                    					<li><a href="#" class="newTemplate">New template</a></li>
                    					<li><a href="#" class="rename">Rename</a></li>
                    					<li><a href="#" class="duplicate">Duplicate</a></li>
                    					<li><a href="#" class="delete">Delete</a></li>
                    				</ul>
                    				</li>
                    			</ul>
                    			</td>
                    		</tr>
                    	</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>



