<div class="ui-widget-content small-block block-shadow theme-settings">

	<div class="padded clearfix inner-tabs">
		<div class="tabs">
			<ul>
				<li><a href="#tabs-1">Theme settings</a></li>
				<li><a href="#tabs-2">Theme templates</a></li>
			</ul>
			
			<div id="tabs-1">
				
				<div class="clear"></div>
	
	
					<fieldset class="versionHolder">
					
						<?php echo $this->themeForm ?>
						
                    </fieldset>

				<div class="themeSettingsTabs">
					
					<a href="#" class="addNewOutput">Add new output</a>

                    <ul class="themeSettingsTabsNav">
                        <?php foreach( $this->outputs as $k => $out ) : ?>
                    		<li><a href="#themeSettingsTab<?php echo $k+1 ?>"><?php echo $out->getName() ?></a></li>
                        <?php endforeach; ?>
                    </ul>

					<div id="themeSettingsTab1">

						<fieldset class="templateSettings"><legend>Template settings</legend> <!-- dl class="zend_form">
                                	<dt><label>Front page template:</label></dt>
                                	<dd><select class="input_select">
                                		<option>front.tpl</option>
                                		<option>2</option>
                                	</select></dd>
                                	<dt><label>Section page template:</label></dt>
                                	<dd><select class="input_select">
                                		<option>section.tpl</option>
                                		<option>2</option>
                                	</select></dd>
                                	<dt><label>Article page template:</label></dt>
                                	<dd><select class="input_select">
                                		<option>article.tpl</option>
                                		<option>2</option>
                                	</select></dd>
                                </dl --></fieldset>


						<fieldset><legend>Match article types</legend>

							<div class="themeArticleType">

<h4>Theme article types</h4>

<span>News</span>
<ul>
	<li>Deck (single line, 100 characters)</li>
	<li>Body (Multiline)</li>
</ul>

<span>Quotes</span>
<ul>
	<li>Deck (single line)</li>
	<li>Body (multiline)</li>
</ul>

</div>

<div class="matchWithExisting">

<h4>Match with existing</h4>

<ul>
	<li>
	<div><input type="checkbox"> <label>Do nothing</label></div>
	<div><input type="checkbox"> <label>Create article type</label></div>
	<select class="input_select">
		<option>1</option>
		<option>2</option>
	</select></li>
	<li class="withPadding">
	<div><input type="checkbox"> <label>Do nothing</label></div>
	<div><input type="checkbox"> <label>Create article type</label></div>
	<select class="input_select">
		<option>1</option>
		<option>2</option>
	</select></li>
	<li class="withPadding">
	<div><input type="checkbox"> <label>Do nothing</label></div>
	<div><input type="checkbox"> <label>Create article type</label></div>
	<select class="input_select">
		<option>1</option>
		<option>2</option>
	</select></li>
	<li>
	<div><input type="checkbox"> <label>Do nothing</label></div>
	<div><input type="checkbox"> <label>Create article type</label></div>
	<select class="input_select">
		<option>1</option>
		<option>2</option>
	</select></li>
	<li class="withPadding">
	<div><input type="checkbox"> <label>Do nothing</label></div>
	<div><input type="checkbox"> <label>Create article type</label></div>
	<select class="input_select">
		<option>1</option>
		<option>2</option>
	</select></li>
	<li class="withPadding">
	<div><input type="checkbox"> <label>Do nothing</label></div>
	<div><input type="checkbox"> <label>Create article type</label></div>
	<select class="input_select">
		<option>1</option>
		<option>2</option>
	</select></li>
</ul>
</div>
</fieldset>
<input type="submit" name="submit" class="button themeSettingsBtn"
	value="Save All"></div>
<div id="themeSettingsTab2"></div>
<div id="themeSettingsTab3"></div>
</div>
</div>
<div id="tabs-2">

    <?php
    echo $this->action( 'files', 'themes', 'admin', array( 'id' => $this->theme->id ) );
    ?>
	
	<div class="clear"></div>
<ul class="currentDirectory">
	<li>Current directory:</li>
	<li>/</li>
</ul>
<fieldset class="themeTemplatesActionHolder"><select
	class="input_select">
	<option>Actions</option>
	<option>1</option>
	<option>1</option>
</select></fieldset>
<div class="dataTables_wrapper">
<div
	class="fg-toolbar ui-toolbar ui-widget-header ui-corner-tl ui-corner-tr ui-helper-clearfix">
<!--<div id="gridx_filter" class="dataTables_filter"></div>--></div>
<table cellspacing="0" cellpadding="0"
	class="datatable themeTemplatesTable" id="gridx"
	style="width: 100%; margin: 0pt;">
	<colgroup>
		<col width="20px">
		<col width="264px">
		<col width="60px">
		<col width="80px">
		<col width="160px">
		<col width="120px">
		<col width="100px">
	</colgroup>
	<thead>
		<tr>
			<th class="ui-state-default">
			<div class="DataTables_sort_wrapper"><input type="checkbox"> <span></span></div>
			</th>
			<th class="name ui-state-default">
			<div class="DataTables_sort_wrapper">Name<span
				class="css_right ui-icon ui-icon-carat-2-n-s"></span></div>
			</th>
			<th class="ui-state-default">
			<div class="DataTables_sort_wrapper">ID<span
				class="css_right ui-icon ui-icon-carat-2-n-s"></span></div>
			</th>
			<th class="ui-state-default">
			<div class="DataTables_sort_wrapper">Type<span
				class="css_right ui-icon ui-icon-carat-2-n-s"></span></div>
			</th>
			<th class="ui-state-default flag">
			<div class="DataTables_sort_wrapper">Cache lifetime, sec.<span
				class="css_right ui-icon ui-icon-carat-2-n-s"></span></div>
			</th>
			<th class="ui-state-default flag">
			<div class="DataTables_sort_wrapper">Date modified<span
				class="css_right ui-icon ui-icon-carat-2-n-s"></span></div>
			</th>
			<th class="ui-state-default flag">
			<div class="DataTables_sort_wrapper">Action<span></span></div>
			</th>
		</tr>
	</thead>
	<tbody>
		<tr class="odd controls">
			<td colspan="7"><a href="#" class="upOneLevel">up one level </a></td>
		</tr>
		<tr class="odd">
			<td><input type="checkbox"></td>
			<td><a href="#" class="folder">_css</a></td>
			<td>&nbsp;</td>
			<td>dir</td>
			<td align="center">&nbsp;</td>
			<td>&nbsp;</td>
			<td>
			<ul class="actionDropDown">
				<li><a href="#">Actions</a>
				<ul>
					<li><a href="#" class="newFolder">New folder</a></li>
					<li><a href="#" class="newTemplate">New template</a></li>
					<li><a href="#" class="rename">Rename</a></li>
					<li><a href="#" class="duplicate">Duplicate</a></li>
					<li><a href="#" class="delete">Delete</a></li>
				</ul>
				</li>
			</ul>
			</td>
		</tr>
		<tr class="even">
			<td><input type="checkbox"></td>
			<td><a href="#" class="folder">_img</a></td>
			<td>&nbsp;</td>
			<td>dir</td>
			<td align="center">&nbsp;</td>
			<td>&nbsp;</td>
			<td>
			<ul class="actionDropDown">
				<li><a href="#">Actions</a>
				<ul>
					<li><a href="#" class="newFolder">New folder</a></li>
					<li><a href="#" class="newTemplate">New template</a></li>
					<li><a href="#" class="rename">Rename</a></li>
					<li><a href="#" class="duplicate">Duplicate</a></li>
					<li><a href="#" class="delete">Delete</a></li>
				</ul>
				</li>
			</ul>
			</td>
		</tr>
		<tr class="odd">
			<td><input type="checkbox"></td>
			<td><a href="#" class="folder">_tpl</a></td>
			<td>&nbsp;</td>
			<td>dir</td>
			<td align="center">&nbsp;</td>
			<td>&nbsp;</td>
			<td>
			<ul class="actionDropDown">
				<li><a href="#">Actions</a>
				<ul>
					<li><a href="#" class="newFolder">New folder</a></li>
					<li><a href="#" class="newTemplate">New template</a></li>
					<li><a href="#" class="rename">Rename</a></li>
					<li><a href="#" class="duplicate">Duplicate</a></li>
					<li><a href="#" class="delete">Delete</a></li>
				</ul>
				</li>
			</ul>
			</td>
		</tr>
		<tr class="even">
			<td><input type="checkbox"></td>
			<td><a href="#" class="file">issue.tpl</a></td>
			<td>1128</td>
			<td>template</td>
			<td align="center">0</td>
			<td align="right">28.04.2011</td>
			<td>
			<ul class="actionDropDown">
				<li><a href="#">Actions</a>
				<ul>
					<li><a href="#" class="newFolder">New folder</a></li>
					<li><a href="#" class="newTemplate">New template</a></li>
					<li><a href="#" class="rename">Rename</a></li>
					<li><a href="#" class="duplicate">Duplicate</a></li>
					<li><a href="#" class="delete">Delete</a></li>
				</ul>
				</li>
			</ul>
			</td>
		</tr>
		<tr class="odd">
			<td><input type="checkbox"></td>
			<td><a href="#" class="file">section.tpl</a></td>
			<td>1129</td>
			<td>template</td>
			<td align="center">0</td>
			<td align="right">28.04.2011</td>
			<td>
			<ul class="actionDropDown">
				<li><a href="#">Actions</a>
				<ul>
					<li><a href="#" class="newFolder">New folder</a></li>
					<li><a href="#" class="newTemplate">New template</a></li>
					<li><a href="#" class="rename">Rename</a></li>
					<li><a href="#" class="duplicate">Duplicate</a></li>
					<li><a href="#" class="delete">Delete</a></li>
				</ul>
				</li>
			</ul>
			</td>
		</tr>
		<tr class="even">
			<td><input type="checkbox"></td>
			<td><a href="#" class="file">article.tpl</a></td>
			<td>1130</td>
			<td>template</td>
			<td align="center">0</td>
			<td align="right">28.04.2011</td>
			<td>
			<ul class="actionDropDown">
				<li><a href="#">Actions</a>
				<ul>
					<li><a href="#" class="newFolder">New folder</a></li>
					<li><a href="#" class="newTemplate">New template</a></li>
					<li><a href="#" class="rename">Rename</a></li>
					<li><a href="#" class="duplicate">Duplicate</a></li>
					<li><a href="#" class="delete">Delete</a></li>
				</ul>
				</li>
			</ul>
			</td>
		</tr>
	</tbody>
</table>
</div>
</div>
</div>
</div>


<script type="text/javascript">    
$(function()
{

	// Tabs
	$('.tabs, .themeSettingsTabs').tabs();
	$('.tabs').tabs('select', '#tabs-1');
    // BUTTONS
    $('.fg-button').hover
   	(
    	function(){ $(this).removeClass('ui-state-default').addClass('ui-state-focus'); },
    	function(){ $(this).removeClass('ui-state-focus').addClass('ui-state-default'); }
	);
	$('.icon-button').hover
	(
		function() { $(this).addClass('ui-state-hover'); }, 
		function() { $(this).removeClass('ui-state-hover'); }
	);
	$('.text-button').hover
	(
		function() { $(this).addClass('ui-state-hover'); }, 
		function() { $(this).removeClass('ui-state-hover'); }
	);
	$(".actionDropDown li").hover(function()
	{
		$(this).children("ul").css("display","block");
		$(this).children("a").addClass("active");
	}, function() 
	{
		$(this).children("ul").css("display","none");
		$(this).children("a").removeClass("active");
	});
	$(".actionDropDown li ul li").hover(function()
	{
		$(this).children("ul").css("display","block");
	}, function() 
	{
		$(this).childer("ul").css("display","none");
	});
		
	$('.matchWithExisting ul li div input').click(function()
	{
		if (this.checked) 
		{
			$(this).parent().parent().find("div").removeClass('active');
			$(this).parent().addClass('active');
			$(this).parent().parent().find("select").attr('disabled', 'disabled');
			$(this).parent().parent().find("div input").attr('checked', false);
			$(this).attr('checked', true);
		} 
		else 
		{
			$(this).parent().removeClass('active');
			$(this).parent().parent().find("select").removeAttr('disabled');
		}
	}) 
});
</script>

<script type="text/javascript">
$(document).ready(function()
{
	$('.toggle-button').click(function() 
	{
		$('.closeable').toggle('fast');
		$(this).toggleClass("closed");
		return false;
	}).next().hide();
	$('.toggle-link').click(function() 
	{
		$('.more-options').toggle('fast');
		$(this).toggleClass("opened");
		return false;
	}).next().hide();
});


</script>