
<div class="ui-widget-content small-block themesListHolder">
	<div class="tabs ui-tabs ui-widget ui-widget-content ui-corner-all">
    	<ul class="themesListTabsBtns ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
        	<li class="ui-state-default ui-corner-top ui-tabs-selected ui-state-active">
        		<a href="javascript:void(0)">Available themes</a>
        	</li>
        	<?php foreach( $this->publications as $pub ) : ?>
        		<li class="ui-state-default ui-corner-top">
        		    <a href="javascript:void(0)" pub-id="<?php echo $pub->getId(); ?>"><?php echo $pub->getName(); ?></a>
        		</li> 
        	<?php endforeach; ?>
		</ul>
        <a href="#" id="addNewPublication">Add new Publication</a>
        <div id="tabs-1">
		
            <?php echo $this->mytable; ?>
		
		</div>
	</div>
</div>	

<script id="datatableTmpl_0" type="text/x-jQuery-tmpl">
<div>
	<div class="DataTables_sort_wrapper">
    	<input class="toggle-checkbox" type="checkbox" value="{{id}}">
        <span></span>
	</div>
</div>
</script>

<script id="datatableTmpl_1" type="text/x-jQuery-tmpl">
<ul class="themesListTabs ui-tabs ui-widget ui-corner-all">
	{% for( i in images ) %}
	<li class="imageItem ui-tabs-panel ui-widget-content ui-corner-bottom 
			{% if( i > 0 ) %}ui-tabs-hide{% endif %}" id="themesListTabD">
    	<a id="example1" href="{{images[i]}}">
			<img src="<?php echo $this->url() ?>{{images[i]}}" alt="{{images[i]}}" />
		</a>
	</li>
	{% endfor %}
</ul>
</script>

<script id="datatableTmpl_2" type="text/x-jQuery-tmpl">

	<div class="themesListTabs ui-tabs">
		<h3>{{title}} <span>// <?php echo getGS( 'version' ) ?> {{version}}</span></h3>
        <p><i><b><?php echo getGS( 'Design' ) ?>:</b> {{designer}}</i></p>
		<ul class="imageCtrls ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
            <li class="ui-state-default ui-corner-top ui-tabs-selected ui-state-active">
				<a href="javascript:void(0)">
                    <?php echo getGS( 'Issue page' ) ?>
					<span><?php echo getGS( 'Click to enlarge' ) ?></span>
				</a>
			</li>
            <li class="ui-state-default ui-corner-top">
				<a href="javascript:void(0)">
					<?php echo getGS( 'Section page' ); ?>
					<span><?php echo getGS( 'Click to enlarge' ) ?></span>
				</a>
			</li>
        	<li class="ui-state-default ui-corner-top">
				<a href="javascript:void(0)">
                    <?php echo getGS( 'Article page' ) ?>
					<span><?php echo getGS( 'Click to enlarge' ) ?></span>
				</a>
			</li>
    	</ul>
	</div>

</script>

<script id="datatableTmpl_3" type="text/x-jQuery-tmpl">
<div>
	<span class="compatibilityTitle">{{compat}}</span>
	<i>{{text}}</i>
</div>
</script>

<script id="datatableTmpl_4" type="text/x-jQuery-tmpl">
<div>
	<div class="actionMessage"></div>
	<ul class="actionDropDown">
    	<li>
        	<a href="#">Actions</a>
			<ul class="block-shadow">
				<li>
					<a href="#" class="add"><span>Add to publication</span></a>
					<ul class="block-shadow actions-publications">
						<?php foreach( $this->publications as $pub ) : ?>
						<li>
        		    		<a href="<?php echo $this->url( array
        		    		( 
        		    			'action'     => 'assign-to-publication', 
        		    			'controller' => 'themes',
        		    		    'module'     => 'admin',
        		    		    'pub-id'     => $pub->getId(),
        		    		    'theme-id'	 => '{{id}}' 
        		    		), null, null, false )?>" 
							pub-id="<?php echo $pub->getId(); ?>" class="assign-ctrl"><?php echo $pub->getName(); ?></a>
        				</li> 
        	            <?php endforeach; ?>
						<li class="copy-to-avail-themes" style="display:none">
        		    		<a href="javascript:void(0)"><?php echo getGS( 'Copy to available themes' ); ?></a>
        				</li> 
					</ul>
				</li>
				<li>
					<a href="<?php echo $this->url( array
    				    ( 
    				    	'action' => 'edit', 'controller' => 'themes', 'module' => 'admin', 'id' => '{{id}}' 
    				    ), null, null, false )  ?>" class="edit">
						Edit	
					</a>
				</li>
            	<li><a href="#" class="delete">Delete</a></li>
			</ul>
		</li>
	</ul>
</div>
</script>

<script type="text/javascript">
function log( x ){ console.log( x ); }
newscoopDatatables =
{
	callbackRow : function( node, strings, dispIndex, theIndex )
	{
		for( i in strings )
		{
			if( $.trim( strings[i] ) == "" ) continue;
			
			eval( "var theData = " + strings[i] );
			try
			{
				//console.log( newscoopDatatables.templates[i] )
				//$( "#datatableTmpl_" + i ).tmpl( theData )
				//var x = dooTz.template( $( "#datatableTmpl_" + i ).html() );
				//console.log( x(theData) );
				//$( theTd ).html( $( "#datatableTmpl_" + i ).tmpl( theData ) );
				var theTd = $( node ).children().eq( i ).html( "" );
				$( theTd ).html( newscoopDatatables.templates[i]( theData ) ); 
			}
			catch( e ){ console.log( e ); }
		}
		return node;
	},
	callbackDraw : function()
	{
		//$('.themesListTabs').tabs({event: 'mouseover'});
		$('.themesListTabs li a').mouseover( function()
		{
			var parentLi = $(this).parent( 'li' );
			parentLi.siblings().removeClass( 'ui-tabs-selected ui-state-active' );
			parentLi.addClass( 'ui-tabs-selected ui-state-active' );

			var idx = parentLi.parent('ul').find( 'li' ).index( parentLi );
			var imgs = $(this).parents( 'td' ).eq(0).prev().find( 'li' );
			imgs.addClass( 'ui-tabs-hide' ).eq( idx ).removeClass( 'ui-tabs-hide' );
		});

		$(".themesListTabs div a").fancybox();
		
		$(".actionDropDown li").hover(function()
		{
			$(this).children("ul").css("display","block");
			$(this).children("a").addClass("active");
		}, function() 
		{
			$(this).children("ul").css("display","none");
			$(this).children("a").removeClass("active");
		});
		$(".actionDropDown li ul li").hover(function()
		{
			$(this).children("ul").css("display","block");
		}, function() 
		{
			$(this).childer("ul").css("display","none");
		});

		try
		{
			$( document.body ).data( 'newscoop.themesDatatable.oneFilterCallback' ).apply( this );
			$( document.body ).removeData( 'newscoop.themesDatatable.oneFilterCallback' );
		}
		catch( e ){}	
	}
}
$( function()
{
	// tabs functionallity 
	$('.themesListHolder .themesListTabsBtns li a').click( function()
	{
		var parentLi = $(this).parent();
		parentLi.siblings().removeClass( 'ui-tabs-selected ui-state-active' );
		parentLi.addClass('ui-tabs-selected ui-state-active');

		var datatable = $( document.body ).data( 'newscoop.themesDatatable' );
		var pubId 	  = $(this).attr( 'pub-id' );
		if( pubId )
		{
			datatable.fnFilter( pubId, 4 );
			$( document.body ).data( 'newscoop.themesDatatable.oneFilterCallback', function()
			{ 
				$('.copy-to-avail-themes').show();
				$('.actions-publications li a[pub-id='+pubId+']').parent().hide();
			});
		}
		else
		{
			datatable.fnSettings().aoPreSearchCols[4].sSearch = ""; // hacked
			datatable.fnFilter( "" );
			$( document.body ).data( 'newscoop.themesDatatable.oneFilterCallback', function()
			{ 
				$('.actions-publications li a[pub-id]:parent').show()
				$('.copy-to-avail-themes').hide();
			});
		}
	})
	// store the processed templates
	var templates = [];
	$('script[type=text/x-jQuery-tmpl]').each( function()
	{
		templates.push( $(this).template() );
	})
	newscoopDatatables.templates = templates;

	$('.assign-ctrl').live( 'click', function( evt )
	{
		var thisA = $(this)
		$.ajax
		({ 
			url : $(this).attr('href')+'/format/json',
			success : function( data )
			{
				var msgCon = thisA.parents('ul.actionDropDown').prev('div').show().text( data.exception.message );
				msgCon.delay(3000).fadeTo( 'fast', 0.01, function(){ $(this).html( '' ); })
			}
		})
		evt.preventDefault()
	})
});
</script>
 
