<?php
$translator = \Zend_Registry::get('container')->getService('translator');
?>
<div class="actions">
    <ul class="navigation">
        <!-- li><a class="add" href="#" id="create">Create theme</a></li -->
        <li><a class="upload" href="#" id="upload">Import theme</a></li>
        <!-- li><a class="download" href="#" id="download">Download theme</a></li -->
        <!-- li><a class="duplicate" href="#" id="duplicate">Duplicate theme</a></li -->
    </ul>
</div>

<div class="ui-widget-content small-block themesListHolder">
	<div class="tabs ui-tabs ui-widget ui-widget-content ui-corner-all">
    	<ul class="themesListTabsBtns ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
        	<li class="ui-state-default ui-corner-top ui-tabs-selected ui-state-active">
        		<a href="javascript:void(0)">Available themes</a>
        	</li>
        	<?php foreach( $this->publications as $pub ) : ?>
        		<li class="ui-state-default ui-corner-top">
        		    <a href="javascript:void(0)" pub-id="<?php echo $pub->getId(); ?>"><?php echo $this->escape($pub->getName()); ?></a>
        		</li>
        	<?php endforeach; ?>
		</ul>
        <div id="tabs-1">

            <?php echo $this->mytable; ?>

		</div>
	</div>
</div>
<script type="text/javascript">
$(function() {
    $('.themesListHolder .ui-tabs .ui-widget-header li').hover(function() {
        $(this).addClass('ui-state-hover');
    }, function() {
        $(this).removeClass('ui-state-hover');
    });
});
</script>

<script id="popupTmpl" type="text/x-jQuery-tmpl" title="<?php echo $translator->trans( 'Import theme' , array(), 'themes') ?>">
	<div class="message-holder">
		<div class="upload-error" style="display:none"><?php echo $translator->trans( 'Import failed!' , array(), 'themes') ?></div>
		<div class="upload-success" style="display:none"><?php echo $translator->trans( 'Import succeded!' , array(), 'themes') ?></div>
	</div>
	<?php echo $this->uploadForm->setAttrib( 'target', 'upload-frame' ); ?>
	<iframe frameborder="0" name="upload-frame" id="upload-frame" width="0" height="0"></iframe>
</script>

<script id="confirmDeleteTmpl" type="text/x-jQuery-tmpl" title="<?php echo $translator->trans( 'Delete theme' , array(), 'themes') ?>">
	<div class="message-holder">
		<div class="delete-message"> </div>
	</div>
	<?php echo $translator->trans( 'Are you sure you want to delete this theme?' , array(), 'themes') ?>
</script>

<script id="confirmUnassignTmpl" type="text/x-jQuery-tmpl" title="<?php echo $translator->trans( 'Unassign theme' , array(), 'themes') ?>">
    <div class="message-holder">
        <div class="unassign-message"> </div>
        <?php echo $translator->trans( 'Are you sure you want to unassign this theme?' , array(), 'themes') ?>
    </div>
</script>

<?php /* do not change this _0 here.. again */ ?>
<script id="datatableTmpl_0" type="text/x-jQuery-tmpl">
	<ul class="themesListTabs ui-tabs ui-widget ui-corner-all">
		{% for( i in images ) %}
		<li class="imageItem ui-tabs-panel ui-widget-content ui-corner-bottom
			{% if( i > 0 ) %} ui-tabs-hide {% endif %}" id="themesListTabD">
            <a id="example1" rel="theme_{{id}}" href="<?php echo $this->themesPath ?>/{{images[i]}}">
				<img src="<?php echo $this->themesPath ?>/{{images[i]}}" alt="{{images[i]}}" />
			</a>
		</li>
		{% endfor %}
	</ul>
</script>

<script id="datatableTmpl_1" type="text/x-jQuery-tmpl">
	<div class="themesListTabs ui-tabs">
		<h3>{{title}} <span>// <?php echo $translator->trans( 'version' , array(), 'themes') ?> {{version}}</span></h3>
        <p><i><b><?php echo $translator->trans( 'Design' , array(), 'themes') ?>:</b> {{designer}}</i></p>
		<ul class="imageCtrls ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
            <li class="ui-state-default ui-corner-top ui-tabs-selected ui-state-active">
                <a href="javascript:void(0)" rel="theme_{{id}}_b" title="<?php echo $translator->trans('Issue page', array(), 'themes'); ?>">
                    <?php echo $translator->trans( 'Issue page' , array(), 'themes') ?>
					<span><?php echo $translator->trans( 'Click to enlarge' , array(), 'themes') ?></span>
				</a>
			</li>
            <li class="ui-state-default ui-corner-top">
                <a href="javascript:void(0)" rel="theme_{{id}}_b" title="<?php echo $translator->trans('Section page', array(), 'themes'); ?>">
					<?php echo $translator->trans( 'Section page' , array(), 'themes'); ?>
					<span><?php echo $translator->trans( 'Click to enlarge' , array(), 'themes') ?></span>
				</a>
			</li>
        	<li class="ui-state-default ui-corner-top">
                <a href="javascript:void(0)" rel="theme_{{id}}_b" title="<?php echo $translator->trans('Article page', array(), 'themes'); ?>">
                    <?php echo $translator->trans( 'Article page' , array(), 'themes') ?>
					<span><?php echo $translator->trans( 'Click to enlarge' , array(), 'themes') ?></span>
				</a>
			</li>
    	</ul>
	</div>
</script>

<script id="datatableTmpl_2" type="text/x-jQuery-tmpl">
	<div>
		<span class="compatibilityTitle">{{compat}}</span>
		<i>{{text}}</i>
	</div>
</script>

<script id="datatableTmpl_3" type="text/x-jQuery-tmpl">
	<div class="actionMessage"></div>
	<ul class="actionDropDown">
    	<li>
        	<a href="#"><?php echo $translator->trans( 'Actions' ) ?></a>
			<ul class="block-shadow">
				<li>
					<a href="#" class="add"><span><?php echo $translator->trans( 'Add to publication' , array(), 'themes') ?></span></a>
					<ul class="block-shadow actions-publications">
						<?php foreach( $this->publications as $pub ) : ?>
						<li>
        		    		<a href="<?php echo $this->url( array
        		    		(
        		    			'action'     => 'assign-to-publication',
        		    			'controller' => 'themes',
        		    		    'module'     => 'admin',
        		    		    'pub-id'     => $pub->getId(),
        		    		    'theme-id'	 => '{{id}}'
        		    		), null, null, false )?>"
							pub-id="<?php echo $pub->getId(); ?>" class="assign-ctrl"><?php echo $this->escape($pub->getName()); ?></a>
        				</li>
        	            <?php endforeach; ?>
						<li class="copy-to-avail-themes" style="display:none">
        		    		<a href="<?php echo $this->url( array
        		    		(
        		    			'action'     => 'copy-to-available',
        		    			'controller' => 'themes',
        		    		    'module'     => 'admin',
        		    		    'theme-id'	 => '{{id}}'
        		    		), null, null, false )?>"><?php echo $translator->trans( 'Copy to available themes' , array(), 'themes'); ?></a>
        				</li>
					</ul>
				</li>
				<li>
					<a href="<?php echo $this->url( array
    				    (
    				    	'action'     => 'unassign',
    				    	'controller' => 'themes',
    				    	'module'     => 'admin',
    				    	'id'         => '{{id}}'
    				    ), null, null, false )  ?>" class="unassign" style="display:none">
						<?php echo $translator->trans( 'Unassign' , array(), 'themes') ?>
					</a>
				</li>
				<li>
					<a href="<?php echo $this->url( array
    				    (
    				    	'action'     => 'advanced-theme-settings',
    				    	'controller' => 'themes',
    				    	'module'     => 'admin',
    				    	'id'         => '{{id}}'
    				    ), null, null, false )  ?>" class="edit">
						<?php echo $translator->trans( 'Edit' ) ?>
					</a>
				</li>
				<li>
					<a href="<?php echo $this->url( array
    				    (
    				    	'action'     => 'export',
    				    	'controller' => 'themes',
    				    	'module'     => 'admin',
    				    	'id'         => '{{id}}'
    				    ), null, null, false )  ?>" class="download">
						<?php echo $translator->trans( 'Export' , array(), 'themes') ?> (<?php echo $translator->trans( 'zip' , array(), 'themes') ?>)
					</a>
				</li>
            	<li>
					<a href="<?php echo $this->url( array
    				    (
    				    	'action'     => 'delete',
    				    	'controller' => 'themes',
    				    	'module'     => 'admin',
    				    	'id'         => '{{id}}'
    				    ), null, null, false )  ?>" class="delete">
						<?php echo $translator->trans( 'Delete' ) ?>
					</a>
				</li>
			</ul>
		</li>
	</ul>
</script>

