<fieldset>
	<legend>Match article types</legend>
	<div class="themeArticleType">
        <h4>Theme article types</h4>
        <span>News</span>
        <ul>
        	<li>Deck (single line, 100 characters)</li>
        	<li>Body (Multiline)</li>
        </ul>
        <span>Quotes</span>
        <ul>
        	<li>Deck (single line)</li>
        	<li>Body (multiline)</li>
        </ul>
   </div>
   <div class="matchWithExisting">
		<h4>Match with existing</h4>
        <ul>
        	<li>
            	<div><input type="checkbox"> <label>Do nothing</label></div>
            	<div><input type="checkbox"> <label>Create article type</label></div>
            	<select class="input_select">
            		<option>1</option>
            		<option>2</option>
            	</select>
            </li>
        	<li class="withPadding">
        		<div><input type="checkbox"> <label>Do nothing</label></div>
        		<div><input type="checkbox"> <label>Create article type</label></div>
        		<select class="input_select">
        			<option>1</option>
        			<option>2</option>
        		</select>
        	</li>
        	<li class="withPadding">
        		<div><input type="checkbox"> <label>Do nothing</label></div>
        		<div><input type="checkbox"> <label>Create article type</label></div>
        		<select class="input_select">
        			<option>1</option>
        			<option>2</option>
        		</select>
        	</li>
        	<li>
        		<div><input type="checkbox"> <label>Do nothing</label></div>
        		<div><input type="checkbox"> <label>Create article type</label></div>
        		<select class="input_select">
        			<option>1</option>
        			<option>2</option>
        		</select>
        	</li>
        	<li class="withPadding">
        		<div><input type="checkbox"> <label>Do nothing</label></div>
        		<div><input type="checkbox"> <label>Create article type</label></div>
        		<select class="input_select">
        			<option>1</option>
        			<option>2</option>
        		</select>
        	</li>
        	<li class="withPadding">
        		<div><input type="checkbox"> <label>Do nothing</label></div>
        		<div><input type="checkbox"> <label>Create article type</label></div>
        		<select class="input_select">
        			<option>1</option>
        			<option>2</option>
        		</select>
        	</li>
        </ul>
	</div>
</fieldset>