<fieldset>
	<legend>Match article types</legend>
	<div class="themeArticleType">
        <h4>Theme article types</h4>
        <?php foreach ( $this->articleTypes as $typeName => $typeFields ) : ?>
        	<span><?php echo $typeName ?></span>
        	<ul>
        	<?php foreach ( $typeFields as $fieldName => $fieldProps ) : ?>
    			<li><?php echo $fieldName ?> (<?php echo $fieldProps->type ?> <?php echo $fieldProps->length ?>)</li>
        	<?php endforeach; ?>
        	</ul>
        <?php endforeach; ?>
   </div>
   <div class="matchWithExisting">
		<h4>Match with existing</h4>
        <ul>
        	<li>
            	<div><input type="checkbox"> <label>Do nothing</label></div>
            	<div><input type="checkbox"> <label>Create article type</label></div>
            	<select class="input_select">
            		<option>1</option>
            		<option>2</option>
            	</select>
            </li>
        	<li class="withPadding">
        		<div><input type="checkbox"> <label>Do nothing</label></div>
        		<div><input type="checkbox"> <label>Create article type</label></div>
        		<select class="input_select">
        			<option>1</option>
        			<option>2</option>
        		</select>
        	</li>
        	<li class="withPadding">
        		<div><input type="checkbox"> <label>Do nothing</label></div>
        		<div><input type="checkbox"> <label>Create article type</label></div>
        		<select class="input_select">
        			<option>1</option>
        			<option>2</option>
        		</select>
        	</li>
        	<li>
        		<div><input type="checkbox"> <label>Do nothing</label></div>
        		<div><input type="checkbox"> <label>Create article type</label></div>
        		<select class="input_select">
        			<option>1</option>
        			<option>2</option>
        		</select>
        	</li>
        	<li class="withPadding">
        		<div><input type="checkbox"> <label>Do nothing</label></div>
        		<div><input type="checkbox"> <label>Create article type</label></div>
        		<select class="input_select">
        			<option>1</option>
        			<option>2</option>
        		</select>
        	</li>
        	<li class="withPadding">
        		<div><input type="checkbox"> <label>Do nothing</label></div>
        		<div><input type="checkbox"> <label>Create article type</label></div>
        		<select class="input_select">
        			<option>1</option>
        			<option>2</option>
        		</select>
        	</li>
        </ul>
	</div>
</fieldset>