<h1><?php echo getGS('Edit'), ' ', $this->role->getName(); ?></h1>

<?php $this->renderError(); ?>

<?php foreach ($this->resources as $resource) { ?>
<dl class="resource">
    <dt><?php echo $resource->name ?: getGS('Global'); ?></dt>
    <?php foreach ($resource->rules as $rule) { ?>
    <dd class="<?php echo $rule->getType(); ?>">
        <a class="delete" href="<?php echo $this->url(array('action' => 'delete-rule', 'rule' => $rule->getId(), 'role' => $this->role->getId())); ?>"><?php putGS('Remove'); ?></a>
        <strong><?php echo $this->ruleTypes[$rule->getType()]; ?></strong>
        <?php echo $rule->getAction() ? $rule->getAction()->getName() : getGS('Any action'); ?>
    </dd>
    <?php } ?>
</dl>
<?php } ?>

<?php echo $this->form->setAction($this->url())->setMethod('post')->render(); ?>

<script type="text/javascript">
$(function() {
    // list actions per resource
    var actions_default = $('select[name=action]').html();
    $('select[name=resource]').change(function() {
        var resource = $(this).val();
        var actions = $('select[name=action]', $(this).closest('dl')).first();

        // reset
        actions.html(actions_default);

        if (resource == 0) { // show all
            return;
        }

        // hide actions not used for resource
        $.getJSON(g_admin_url + '/user-types/actions', {
            'resource': resource
        }, function(data) {
            $('option', actions).each(function() {
                var option = $(this);
                if (option.val() > 0 && $.inArray(parseInt(option.val()), data) < 0) {
                    option.detach();
                }
            });
        });
    });
});
</script>
