<h1><?php echo getGS('User types'); ?></h1>

<?php
$this->renderActions(array(
    $this->url(array('action' => 'add')) => getGS('Add new user type'),
));
?>

<?php
if (empty($this->roles)) {
    $this->renderMessage(getGS('No user types.'));
    return;
}
?>

<ul class="edit user-types">
    <?php foreach ($this->roles as $role) { ?>
    <li>
        <a class="delete confirm" href="<?php echo $this->url(array('action' => 'delete', 'role' => $role->getId())); ?>" title="<?php putGS('Delete user type $1', $role->getName()); ?>"><?php putGS('Delete'); ?></a>
        <a class="edit" href="<?php echo $this->url(array('action' => 'edit', 'role' => $role->getId())); ?>" title="<?php putGS('Edit user type $1', $role->getName()); ?>"><?php echo $role->getName(); ?></a>
    </li>
    <?php } ?>
</ul>
