<h1><?php echo getGS('User types'); ?></h1>

<?php
$this->renderActions(array(
    $this->url(array('action' => 'add-group')) => getGS('Add new user type'),
));
?>

<?php
if (empty($this->groups)) {
    $this->renderMessage(getGS('No user types.'));
    return;
}
?>

<ul class="edit user-types">
    <?php foreach ($this->groups as $group) { ?>
    <li>
        <a class="delete confirm" href="<?php echo $this->url(array(
            'action' => 'delete-group',
            'group' => $group->getId(),
        )); ?>" title="<?php putGS('Delete user type $1', $group->getName()); ?>"><?php putGS('Delete'); ?></a>
        <a class="edit" href="<?php echo $this->url(array(
            'action' => 'edit-role',
            'role' => $group->getRoleId(),
        )); ?>" title="<?php putGS('Edit user type $1', $group->getName()); ?>"><?php echo $group->getName(); ?></a>
    </li>
    <?php } ?>
</ul>
