<?php
$translator = \Zend_Registry::get('container')->getService('translator');
$this->headScript()->appendFile($this->baseUrl('js/views/PaginatorView.js'));

?>
<div id="modal-top">
    <div class="toolbar fixed-top" id="app">
    <h1><?php echo $translator->trans('Attach').'/'.$translator->trans('Detach').' '.$translator->trans('Slideshows', array(), 'articles'); ?>
        <span style="float: right;">
          <button id="attach-slideshows-button" class="prime"><?php echo $translator->trans('Save'); ?></button>
        </span>
    </h1>
    </div>
</div>
<h2 class="attached-slideshow"><?php echo $translator->trans('Attached Slideshows', array(), 'article_images'); ?></h2>
<section>
    <ul id="article-slideshows" class="slideshow attached"></ul>
</section>


<section>
    <div class="search-wrapper">
    <form method="post" action="<?php echo($this->url(array(
            'module' => 'admin',
            'controller' => 'slideshow',
            'action' => 'attach',
    ))); ?>">
    <div class="search">
        <input type="text" placeholder="<?php echo($translator->trans('Search')); ?>" name="q" value="<?php if ($this->q) echo $this->escape($this->q); ?>">
        <input type="submit" value="<?php echo($translator->trans('Search')); ?>">
    </div>
    </form>
    <nav></nav>
    </div>
</section>

<section>
    <ul id="slideshow-list" class="list-view grid slideshow-list"></ul>
</section>
<script type="text/template" id="slideshow-template">
<h3 class="title"><%= headline.substring(0, 22) %><% if (headline.length > 22) { %>..<% } %></h3>
<small>(<?php echo $translator->trans('Items: ', array(), 'article_images'); ?><%= itemsCount %>)</small>
<div class="preview">
    <% if (!itemsCount) { %>
    <span class="blank"></span>
    <% } else if (item) { %>
    <img src="<?php echo $this->baseUrl('/images/cache/'); ?><%= item.thumbnail.src %>" alt=""/>
    <% } else { %>
    <span class="video"></span>
    <% } %>
</div>
<span class="info"></span>
</script>
<?php echo $this->render('paginator-template.phtml'); ?>

<script type="text/javascript">
(function($) {
    /**
     * Slideshow model
     */
    var Slideshow = Backbone.Model.extend({
        defaults: {
            item: null,
            attached: false
        },

        initialize: function() {
            if (this.get('items')) {
                this.set('item', this.get('items')[0]);
            }
        },

        addToArticle: function(article) {
            if (!article.get('slideshows').get(this.get('id'))) {
                unlockSaveButton();
                article.get('slideshows').add(this);
            }
        },

        removeFromArticle: function(article) {
            unlockSaveButton();
            article.get('slideshows').remove(this.get('id'));
        }
    });

    /**
     * Slideshow collection
     */
    var SlideshowCollection = Backbone.Collection.extend({
        model: Slideshow,
        url: <?php echo json_encode($this->url(array('format' => 'json'))); ?>,
        comparator: function(slideshow) {
            return -1 * slideshow.get('id');
        }
    });

    /**
     * Article model
     */
    var Article = Backbone.Model.extend({
        url: <?php echo json_encode($this->url(array('action' => 'article'))); ?>,

        initialize: function(params) {
            this.set('slideshows', new SlideshowCollection(this.get('slideshows')));
        }
    });

    /**
     * Slideshow view
     */
    var SlideshowView = Backbone.View.extend({
        tagName: "li",

        events: {
            'click': 'action',
            'mouseout': 'removeHint',
            'mouseover': 'addHint'
        },

        initialize: function() {
            this.model.bind('change', this.render, this);
            this.template = _.template($('#slideshow-template').html());
        },

        render: function() {
            $(this.el).html(this.template(this.model.toJSON()));
            return this;
        },

        addHint: function() { // no-op
            $(this.el).find('.info').text(this.hint ? this.hint : '');
        },

        removeHint: function() {
            $(this.el).find('.info').text('');
        }
    });

    var AddSlideshowView = SlideshowView.extend({
        hint: <?php echo json_encode($translator->trans('Attach')); ?>,

        action: function() {
            this.model.addToArticle(window.article);
        }
    });

    var RemoveSlideshowView = SlideshowView.extend({
        hint: <?php echo json_encode($translator->trans('Detach', array(), 'article_images')); ?>,

        action: function() {
            this.model.removeFromArticle(window.article);
        }
    });

    /**
     * Slideshow list view
     */
    var SlideshowListView = Backbone.View.extend({
        initialize: function() {
            this.collection = this.options.collection;
            this.collection.bind('reset', this.render, this);
            this.collection.reset(this.options.slideshows);
        },

        render: function() {
            $('#slideshow-list').empty();
            this.collection.each(function(slideshow) {
                var view = new AddSlideshowView({model: slideshow});
                $('#slideshow-list').append(view.render().el);
            });
            return this;
        }
    });

    /**
     * Article slideshows view
     */
    var ArticleSlideshowsView = Backbone.View.extend({
        initialize: function() {
            this.collection = this.options.collection;
            this.collection.bind('add', this.render, this);
            this.collection.bind('remove', this.render, this);
            this.render();
        },

        render: function() {
            var list = $(this.el);
            list.empty();
            this.collection.each(function(slideshow) {
                var view = new RemoveSlideshowView({model: slideshow});
                list.append(view.render().el);
            });

            return this;
        }
    });

    /**
     * Article view
     */
    var ArticleView = Backbone.View.extend({
        el: $('#app'),

        events: {
            'click #attach-slideshows-button': 'saveArticle'
        },

        initialize: function() {
            this.article = this.options.article;
            this.article.bind('sync', this.close, this);
        },

        saveArticle: function() {
            this.article.save();
            showFlashMessage("<?php echo $translator->trans('The article slideshows have been successfully updated, please close the window.', array(), 'articles'); ?>");
        },

        close: function() {
            $('#attach-slideshows-button').prop('disabled', true);
            $('#attach-slideshows-button').addClass('btn-disabled');
            if (parent.$.fancybox !== undefined) {
                parent.$.fancybox.close();
            }
        }
    });

    var showFlashMessage = function (msg, type) {
        if (parent.$.fancybox === undefined) {
            flashMessage(msg, type);
        }
    };

    var unlockSaveButton = function () {
        $('#attach-slideshows-button').prop('disabled', false);
        $('#attach-slideshows-button').removeClass('btn-disabled');
    }

    $(function() {
        window.article = new Article(<?php echo json_encode($this->article); ?>);
        var app = new ArticleView({article: article});
        var slideshowCollection = new SlideshowCollection();
        var paginatorView = new PaginatorView({pages: <?php echo $this->pages; ?>, collection: slideshowCollection, el: $('body > nav')});
        var slideshowView = new SlideshowListView({collection: slideshowCollection, slideshows: <?php echo json_encode($this->slideshowsJson($this->slideshows)); ?>});
        var articleSlideshowsView = new ArticleSlideshowsView({collection: article.get('slideshows'), el: $('#article-slideshows')});
    });
})(jQuery);
</script>
