<a class="ui-state-default icon-button right-floated" href="<?php echo $this->url(array(
    'module' => 'admin',
    'controller' => 'slideshow',
    'action' => 'create',
    'article_number' => $this->articleNumber,
)); ?>" id="create-slideshow"><span class="ui-icon ui-icon-plusthick"></span><?php putGS('Create'); ?></a>

<a class="ui-state-default icon-button right-floated" href="<?php echo $this->url(array(
    'module' => 'admin',
    'controller' => 'slideshow',
    'action' => 'attach',
    'article_number' => $this->articleNumber,
)); ?>" id="attach-slideshow"><span class="ui-icon ui-icon-plusthick"></span><?php putGS('Attach'); ?></a>

<?php if (count($this->slideshows) === 0) { ?>
<p><?php putGS('No slideshows'); ?></p>

<?php } else { ?>
<ul class="slideshows">
    <?php foreach ($this->slideshows as $slideshow) { ?>
    <li>
        <a href="<?php echo $this->url(array(
            'module' => 'admin',
            'controller' => 'slideshow',
            'action' => 'detach',
            'slideshow' => $slideshow->getId(),
        )); ?>" class="detach" title="<?php putGS('Detach $1', $slideshow->getHeadline()); ?>"><?php putGS('Detach'); ?></a>

        <a href="<?php echo $this->url(array(
            'module' => 'admin',
            'controller' => 'slideshow',
            'action' => 'edit',
            'slideshow' => $slideshow->getId(),
        )); ?>" title="<?php putGS('Edit $1', $slideshow->getHeadline()); ?>"><?php echo $slideshow->getHeadline(); ?></a>
    </li>
    <?php } ?>
</ul>
<?php } ?>

<script type="text/javascript">
    var loadSlideshows = function() {
        $('#media-slideshows').load("<?php echo $this->url(array(
            'module' => 'admin',
            'controller' => 'slideshow',
            'action' => 'box',
            'article_number' => $this->articleNumber,
        )); ?>");
    }

    $(function() {
        $('#media-slideshows a').not('.detach').fancybox({
            hideOnContentClick: false,
            width: 960,
            height: 600,
            type: 'iframe',
            onClosed: loadSlideshows
        });

        $('#media-slideshows a.detach').click(function(e) {
            e.preventDefault();
            $.post($(this).attr('href'), function(data, textStatus) {
                loadSlideshows();
            });
        });
    });
</script>
