<?php 
$this->headLink()->appendStylesheet($this->baseUrl('/admin-style/image_management.css')); 
$translator = \Zend_Registry::get('container')->getService('translator');
?>
<?php $this->placeholder('bodyId')->set('next'); $this->placeholder('bodyClass')->set('dark'); ?>
<h1><?php echo $translator->trans('Slideshow', array(), 'article_images'); ?> <small id="slideshow-rendition-info"><?php echo $this->package->getRendition()->getInfo(); ?></small></h1>
<form id="edit-form" method="<?php echo $this->form->getMethod(); ?>">

<div class="editarea">
    <div>
        <?php if ($this->item->isVideo()) { ?>
        <h2>Video: <?php echo $this->item->getVideoUrl(); ?></h2>
        <?php } ?>
        <?php echo $this->item->isImage() ? $this->imageEditor($this->rendition, $this->image) : $this->videoPreview($this->item->getVideoUrl(), $this->rendition->getWidth(), $this->rendition->getHeight()); ?>
        <?php if ($this->item->isVideo()) { ?>
        <input type="text" name="url" value="<?php echo $this->escape($this->form->url->getValue()); ?>" />
        <?php } ?>
        <input type="text" name="caption" value="<?php echo $this->escape($this->form->caption->getValue()); ?>" placeholder="<?php echo $translator->trans('Add caption', array(), 'article_images'); ?>" /><br />
        <button class="save-button"><?php echo $translator->trans('Save'); ?></button>
    </div>

    <?php if (($prev = $this->package->getPrev($this->item)) !== null) { ?>
    <a href="<?php echo $this->url(array(
        'item' => $this->package->getPrev($this->item)->getId(),
    )); ?>" class="prev"><span></span><?php echo $translator->trans('Previous'); ?></a>
    <?php } ?>

    <?php if (($next = $this->package->getNext($this->item)) !== null) { ?>
    <a href="<?php echo $this->url(array(
        'item' => $next->getId(),
    )); ?>" class="next"><span></span><?php echo $translator->trans('Next'); ?></a>
    <?php } ?>

    <a href="<?php echo $this->url(array(
        'action' => 'edit',
        'item' => null,
        'format' => null
    )); ?>" class="done button"><?php echo $translator->trans('Done editing', array(), 'article_images'); ?></a>
</div>

</form>

<?php $this->currentItem = $this->item; ?>
<ul class="slideshow editor">
    <?php foreach ($this->item->getPackageItems() as $item) { ?>
    <?php echo $this->slideshowItem($item, $this->currentItem); ?>
    <?php } ?>
</ul>
