<li id="item-<?php echo $this->item->getId(); ?>"<?php echo $this->current !== null && $this->current->getId() === $this->item->getId() ? ' class="active"' : ''; ?>>
    <a href="<?php echo $this->url(array(
        'module' => 'admin',
        'controller' => 'slideshow',
        'action' => 'edit-item',
        'item' => $this->item->getId(),
    )); ?>">
        <figure>
            <div><?php echo $this->item->isImage() ? $this->renditionPreview($this->item->getRendition(), 100, 100, $this->item->getImage()) : $this->videoPreview($this->item->getVideoUrl()); ?></div>
            <figcaption><?php echo $this->item->getCaption() ?: getGS('no caption'); ?></figcaption>
        </figure>
    </a>
    <a href="<?php echo $this->url(array(
        'module' => 'admin',
        'controller' => 'slideshow',
        'action' => 'remove-item',
        'item' => $this->item->getId(),
    )); ?>" class="remove"><?php putGS('Remove'); ?></a>
</li>
