<li id="item-<?php echo $this->item->getId(); ?>">
    <a href="<?php echo $this->url(array(
        'module' => 'admin',
        'controller' => 'slideshow',
        'action' => 'edit-item',
        'item' => $this->item->getId(),
    )); ?>">
        <figure>
            <?php echo $this->item->isImage() ? $this->renditionPreview($this->item->getRendition(), 100, 100, $this->item->getImage()) : $this->videoPreview($this->item->getVideoUrl()); ?>
            <figcaption><?php echo $this->item->getCaption() ?: getGS('Edit caption'); ?></figcaption>
        </figure>
    </a>
    <a href="<?php echo $this->url(array(
        'module' => 'admin',
        'controller' => 'slideshow',
        'action' => 'remove-item',
        'item' => $this->item->getId(),
    )); ?>" class="remove">Remove</a>
</li>
