<?php
$translator = \Zend_Registry::get('container')->getService('translator');
?>
<dl class="slideshow-preview">
    <dt><?php echo $this->escape($this->helperSlideshow->getHeadline()); ?> (<?php echo $this->helperSlideshow->getItemsCount(), ' ',  $this->translate(array(
        $translator->trans('Item', array(), 'article_images'),
        $translator->trans('Items', array(), 'article_images'),
        $this->helperSlideshow->getItemsCount(),
    )); ?>)</dt>
    <?php $counter = 0; ?>
    <?php foreach ($this->helperSlideshow->getItems() as $item) { ?>
    <dd<?php echo $counter++ === 0 ? ' class="first"' : ''; ?>><?php echo $this->slideshowItemPreview($item); ?></dd>
    <?php } ?>
</dl>
