<?php 
$translator = \Zend_Registry::get('container')->getService('translator');
$this->placeholder('title')->set($translator->trans('IP Access', array(), 'user_subscriptions')); 
?>

<?php $this->renderActions(); ?>

<?php if (!$this->subscriber->hasIps()) {
    $this->renderMessage($translator->trans('No IP Addresses', array(), 'user_subscriptions'));
    return;
} ?>

<table>
<tr>
    <th><?php echo $translator->trans('Start IP', array(), 'user_subscriptions'); ?></th>
    <th><?php echo $translator->trans('Number of Addressses', array(), 'user_subscriptions'); ?></th>
    <th><?php echo $translator->trans('Delete'); ?></th>
</tr>
<?php foreach ($this->subscriber->getIps() as $ip) { ?>
<tr>
    <td><?php echo $ip; ?></td>
    <td><?php echo $ip->getNumber(); ?></td>
    <td><a href="<?php echo $this->url(array(
        'controller' => 'subscription-ip',
        'action' => 'delete',
        'user' => $this->subscriber->getId(),
        'ip' => $ip->getIp(),
    )); ?>"><?php echo $translator->trans('Delete'); ?></a></td>
</tr>
<?php } ?>
</table>
