#!/bin/bash
#
#	/etc/rc.d/init.d/campsite
#
# Starts the campsite daemon
#

################################################################################
#
# CAMPSITE is a Unicode-enabled multilingual web content
# management system for news publications.
# CAMPFIRE is a Unicode-enabled java-based near WYSIWYG text editor.
# Copyright (C)2000,2001  Media Development Loan Fund
# contact: contact@campware.org - http://www.campware.org
# Campware encourages further development. Please let us know.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
################################################################################

# Source function library.

CAMPSITECTL=/usr/local/campsite/campsitectl

test -x $CAMPSITECTL || exit 0


#
#	See how we were called.
#
case "$1" in
  start)
	# Check if atd is already running
        THREADS=`ps ax | grep campsite_server| grep -v grep | wc -l`
        if [ $THREADS -gt 0 ]; then
	    echo "campsite daemon is already started"
	else
	    echo -n 'Starting campsite daemon: '
	    $CAMPSITECTL start
	    echo
	fi
	;;
  stop)
	echo -n 'Stopping campsite daemon: '
	$CAMPSITECTL stop
	echo
	;;
  reload|restart)
	$0 stop
	$0 start
	;;
  status)
	$CAMPSITECTL status
	;;
  *)
	echo "Usage: /etc/rc.d/init.d/campsite {start|stop|restart|reload|status}"
	exit 1
esac

exit 0
