#!/bin/bash

################################################################################
#
# CAMPSITE is a Unicode-enabled multilingual web content
# management system for news publications.
# CAMPFIRE is a Unicode-enabled java-based near WYSIWYG text editor.
# Copyright (C)2000,2001  Media Development Loan Fund
# contact: contact@campware.org - http://www.campware.org
# Campware encourages further development. Please let us know.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
################################################################################

mkdir -p $BIN_DIR
echo "Stop old version server (if installed)"
test -f $BIN_DIR/$CAMPSITECTL && $BIN_DIR/$CAMPSITECTL stop
rm -f $BIN_DIR/$CAMPSITE_SERVER
cp -f $CAMPSITE_SERVER $BIN_DIR
chown ${ROOT_USER}:${APACHE_GROUP} ${BIN_DIR}/$CAMPSITE_SERVER
chmod 755 $BIN_DIR/$CAMPSITE_SERVER
chmod +s $BIN_DIR/$CAMPSITE_SERVER
cp -f $CAMPSITECTL $BIN_DIR
chown ${ROOT_USER}:${ROOT_GROUP} ${BIN_DIR}/$CAMPSITECTL
chmod 755 $BIN_DIR/$CAMPSITECTL

if $USER_INSTALL; then exit 0; fi

RC_INIT=/etc/init.d
if [ -d $"$RC_INIT" ]; then
	cp -f $"$CAMPSITEINIT" $"$RC_INIT"
	chown ${ROOT_USER}:${ROOT_GROUP} $"${RC_INIT}/$CAMPSITEINIT"
	[ $? -ne 0 ] && echo "ERROR installing start/stop script" && exit 1
	chmod 755 $"$RC_INIT/$CAMPSITEINIT"
	ln -s $"$RC_INIT/$CAMPSITEINIT" $"/etc/rc2.d/S95$CAMPSITEINIT"
	ln -s $"$RC_INIT/$CAMPSITEINIT" $"/etc/rc3.d/S95$CAMPSITEINIT"
	ln -s $"$RC_INIT/$CAMPSITEINIT" $"/etc/rc5.d/S95$CAMPSITEINIT"
	ln -s $"$RC_INIT/$CAMPSITEINIT" $"/etc/rc0.d/K50$CAMPSITEINIT"
	ln -s $"$RC_INIT/$CAMPSITEINIT" $"/etc/rc6.d/K50$CAMPSITEINIT"
elif [ -d /etc/rc.d ]; then
	if [ ! -f /etc/rc.d/rc.local ]; then
		echo -e "#!/bin/bash\n" > /etc/rc.d/rc.local
	fi
	grep -w $CAMPSITECTL /etc/rc.d/rc.local > /dev/null
	if [ "$?" != "0" ]; then
		echo "$BIN_DIR/$CAMPSITECTL start" >> /etc/rc.d/rc.local
		[ $? -ne 0 ] && echo "ERROR installing start/stop script" && exit 1
	fi
fi

exit 0
