#!/bin/sh

################################################################################
#
# CAMPSITE is a Unicode-enabled multilingual web content
# management system for news publications.
# CAMPFIRE is a Unicode-enabled java-based near WYSIWYG text editor.
# Copyright (C)2000,2001  Media Development Loan Fund
# contact: contact@campware.org - http://www.campware.org
# Campware encourages further development. Please let us know.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
################################################################################

mkdir -p $UTIL_BIN
echo "Stop old version server (if installed)"
test -f $UTIL_BIN/$CAMPSITECTL && $UTIL_BIN/$CAMPSITECTL stop
rm -f $UTIL_BIN/$CAMPSITE_SERVER
cp -f $CAMPSITE_SERVER $UTIL_BIN
cp -f $CAMPSITECTL $UTIL_BIN
if [ -d $RC_INIT ]; then
	cp -f $CAMPSITEINIT $RC_INIT
	chmod +x $RC_INIT$CAMPSITEINIT
	test -f $RC_INIT$CAMPSITEINIT && ln -s $RC_INIT$CAMPSITEINIT /etc/rc.d/rc3.d/S95$CAMPSITEINIT
	test -f $RC_INIT$CAMPSITEINIT && ln -s $RC_INIT$CAMPSITEINIT /etc/rc.d/rc5.d/S95$CAMPSITEINIT
	test -f $RC_INIT$CAMPSITEINIT && ln -s $RC_INIT$CAMPSITEINIT /etc/rc.d/rc0.d/K50$CAMPSITEINIT
	test -f $RC_INIT$CAMPSITEINIT && ln -s $RC_INIT$CAMPSITEINIT /etc/rc.d/rc6.d/K50$CAMPSITEINIT
elif [ -d /etc/rc.d ]; then
	if [ ! -f /etc/rc.d/rc.local ]; then
		echo -e "#!/bin/sh\n" > /etc/rc.d/rc.local
	fi
	grep -w $CAMPSITECTL /etc/rc.d/rc.local > /dev/null
	if [ "$?" != "0" ]; then
		echo "$UTIL_BIN/$CAMPSITECTL start" >> /etc/rc.d/rc.local
	fi
fi
chown root.$(HTTP_GROUP) $UTIL_BIN -R
chmod 750 $UTIL_BIN -R
