#!/bin/bash

DATABASE_USER=root
DATABASE_PASSWORD=
DATABASE_NAME=campsite34

if [ "$1" != "" ]; then
    DATABASE_NAME=$1
fi
if [ "$DATABASE_PASSWORD" != "" ]; then
    password_string="-p$DATABASE_PASSWORD"
fi

TABLES_TO_FILL="
 Aliases\
 ArticleAuthors\
 ArticleImages\
 ArticleIndex\
 ArticleTopics\
 ArticleTypeMetadata\
 Articles\
 Authors\
 AutoId\
 Images\
 Issues\
 KeywordIndex\
 Publications\
 Sections\
 Templates\
 Topics\
 Translations\
 Xnews_article\
 liveuser_groupusers\
 liveuser_perm_users\
 liveuser_perm_users_perm_user_id_seq\
 liveuser_users\
 liveuser_users_auth_user_id_seq\
 liveuser_rights\
 liveuser_rights_right_id_seq\
 liveuser_grouprights\
 phorum_forums\
 phorum_users"

CUSTOM_TABLES="Xnews_article"

mysqldump -u $DATABASE_USER $password_string -t --insert-ignore \
  $DATABASE_NAME $TABLES_TO_FILL > campsite_demo_data.sql
mysqldump -u $DATABASE_USER $password_string -d --insert-ignore \
  "$DATABASE_NAME" $CUSTOM_TABLES > campsite_demo_tables.sql
