#!/bin/bash

DATABASE_USER=root
DATABASE_PASSWORD=
DATABASE_NAME=campsite

if [ "$1" != "" ]; then
    DATABASE_NAME=$1
fi
if [ "$DATABASE_PASSWORD" != "" ]; then
    password_string="-p$DATABASE_PASSWORD"
fi

TABLES="
 Aliases\
 ArticleAttachments\
 ArticleAudioclips\
 ArticleAuthors\
 ArticleComments\
 ArticleImages\
 ArticleIndex\
 ArticlePublish\
 ArticleTopics\
 ArticleTypeMetadata\
 Articles\
 Attachments\
 AudioclipMetadata\
 Authors\
 AutoId\
 Classes\
 Countries\
 Dictionary\
 EnumerationElements\
 Enumerations\
 Errors\
 Events\
 Images\
 IssuePublish\
 Issues\
 KeywordClasses\
 KeywordIndex\
 Languages\
 ObjectTypes\
 Plugins\
 Publications\
 Sections\
 SubsDefTime\
 SubsSections\
 Subscriptions\
 TemplateTypes\
 Templates\
 TimeUnits\
 TopicFields\
 Topics\
 Translations\
 URLTypes\
 XArticle\
 XInterview\
 XService\
 XSpecial\
 Xlink\
 Xnews_article\
 Xsava\
 phorum_banlists\
 phorum_files\
 phorum_forum_group_xref\
 phorum_forums\
 phorum_groups\
 phorum_messages\
 phorum_pm_buddies\
 phorum_pm_folders\
 phorum_pm_messages\
 phorum_pm_xref\
 phorum_search\
 phorum_settings\
 phorum_subscribers\
 phorum_user_custom_fields\
 phorum_user_group_xref\
 phorum_user_newflags\
 phorum_user_permissions\
 plugin_blog_blog\
 plugin_blog_comment\
 plugin_blog_entry\
 plugin_blog_entry_topic\
 plugin_blog_topic\
 plugin_interview_interviews\
 plugin_interview_items\
 plugin_poll\
 plugin_poll_answer\
 plugin_poll_article\
 plugin_poll_issue\
 plugin_poll_publication\
 plugin_poll_section\
 plugin_pollanswer_attachment"

mysqldump -u $DATABASE_USER $password_string -t --insert-ignore \
  $DATABASE_NAME $TABLES > campsite_demo_data.sql
mysqldump -u $DATABASE_USER $password_string -d --insert-ignore \
  $DATABASE_NAME $TABLES > campsite_demo_tables.sql
