<?php $this->placeholder('title')->set(getGS('Languages')); ?>

<?php $this->renderActions(); ?>

<?php if (empty($this->languages)) { // no languages
    $this->renderMessage(getGS('No languages.'));
    return;
} ?>

<table class="languages">
    <tr>
        <th><?php putGS('Language'); ?></th>
        <th><?php putGS('Native name'); ?></th>
        <th><?php putGS('Code'); ?></th>
        <th><?php putGS('Delete'); ?></th>
    </tr>
    <?php foreach ($this->languages as $language) { ?>
    <tr>
        <td><a href="<?php echo $this->url(array('action' => 'edit', 'language' => $language->getId())); ?>"><?php echo $language->getName(); ?></a></td>
        <td><?php echo htmlspecialchars($language->getNativeName()); ?></td>
        <td class="text"><?php echo $language->getCode(); ?></td>
        <td>
          <?php if ($language->getCode() !== 'en') { ?>
          <a class="delete confirm" href="<?php echo $this->url(array('action' => 'delete', 'language' => $language->getId())); ?>"><?php putGS('Delete'); ?></a>
          <?php } ?>
        </td>
    </tr>
    <?php } ?>
</table>
