<?php
// Call ArticlesListTest::main() if this source file is executed directly.
if (!defined('PHPUnit_MAIN_METHOD')) {
    define('PHPUnit_MAIN_METHOD', 'ArticlesListTest::main');
}

require_once('PHPUnit/Framework.php');

require_once('template_engine/classes/ArticlesList.php');

require_once('set_path.php');

/**
 * Test class for ArticlesList.
 * Generated by PHPUnit on 2007-07-19 at 14:49:31.
 */
class ArticlesListTest extends PHPUnit_Framework_TestCase {
    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main() {
        require_once('PHPUnit/TextUI/TestRunner.php');

        $suite  = new PHPUnit_Framework_TestSuite('ArticlesListTest');
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown() {
    }

    /**
     * @todo Implement testCreateList().
     */
    public function testCreateList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testProcessConstraints().
     */
    public function testProcessConstraints() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testProcessOrderString().
     */
    public function testProcessOrderString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testProcessParameters().
     */
    public function testProcessParameters() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}

// Call ArticlesListTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == 'ArticlesListTest::main') {
    ArticlesListTest::main();
}
?>
