<?php
// Call IssueTest::main() if this source file is executed directly.
if (!defined("PHPUnit_MAIN_METHOD")) {
    define("PHPUnit_MAIN_METHOD", "IssueTest::main");
}

require_once('PHPUnit/Framework/TestCase.php');
require_once('PHPUnit/Framework/TestSuite.php');

require_once('template_engine/classes/ComparisonOperation.php');
require_once('template_engine/classes/Operator.php');
require_once('classes/Issue.php');

require_once('set_path.php');
require_once('db_connect.php');

/**
 * Test class for Issue.
 * Generated by PHPUnit_Util_Skeleton on 2007-07-02 at 13:27:00.
 */
class IssueTest extends PHPUnit_Framework_TestCase
{
    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main()
    {
        require_once('PHPUnit/TextUI/TestRunner.php');

        $suite  = new PHPUnit_Framework_TestSuite('IssueTest');
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture, for example, open a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, close a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    public function testGetList()
    {
        global $g_ado_db;

        // builds basic parameters
        $leftOperand = 'IdPublication';
        $rightOperand = 1;
        $operator = new Operator('is', 'sql');
        $comparisonOperationObj1 = new ComparisonOperation($leftOperand,
                                                           $operator,
                                                           $rightOperand);
        $leftOperand = 'IdLanguage';
        $rightOperand = 1;
        $operator = new Operator('is', 'sql');
        $comparisonOperationObj2 = new ComparisonOperation($leftOperand,
                                                           $operator,
                                                           $rightOperand);

        // builds the constraint
        $leftOperand = 'PublicationDate';
        $rightOperand = '2007-08-12';
        $operator = new Operator('smaller', 'sql');
        $comparisonOperationObj3 = new ComparisonOperation($leftOperand,
                                                           $operator,
                                                           $rightOperand);

        // sets the params for Issue::GetList()
        $params = array($comparisonOperationObj1,
                        $comparisonOperationObj2,
                        $comparisonOperationObj3);
        $order = array('Name' => 'DESC');
        $limitStart = 0;
        $limitOffset = 0;

        // gets the list of issues
        $issuesList = Issue::GetList($params, $order, $limitStart, $limitOffset);

        $iList = array();
        $sql = "SELECT * FROM Issues WHERE PublicationDate < '2007-08-12' AND Published = 'Y' ORDER BY Name DESC";
        $issues = $g_ado_db->GetAll($sql);
        foreach ($issues as $issue) {
            $iList[] = new Issue($issue['IdPublication'],
                                 $issue['IdLanguage'],
                                 $issue['Number']);
        }

        $this->assertEquals(sizeof($iList), sizeof($issuesList));

        $i = 0;
        $matches = 0;
        foreach ($issuesList as $issue) {
            $this->assertEquals($iList[$i]->getIssueNumber(), $issue->getIssueNumber());
            $i++;
        }
    } // fn testGetList

    public function testGetListBadParameter()
    {
        global $g_ado_db;

        // builds the constraint
        $leftOperand = 'ShortName';
        $rightOperand = 'first';
        $operator = new Operator('is', 'sql');
        $comparisonOperationObj = new ComparisonOperation($leftOperand,
                                                          $operator,
                                                          $rightOperand);

        // sets the params for Issue::GetList()
        $params = array($comparisonOperationObj);
        $order = array('Name' => 'DESC');
        $limitStart = 0;
        $limitOffset = 0;

        $this->assertEquals(null, Issue::GetList($params, $order, $limitStart, $limitOffset));
    } // fn testGetListBadParameter

} // class IssueTest

// Call IssueTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == "IssueTest::main") {
    IssueTest::main();
}
?>