<?php echo $this->doctype(); ?>
<html lang="<?php echo $this->locale; ?>" dir="ltr">
<head>
    <meta charset="utf-8" />
    <?php echo $this->headTitle(); ?>

    <meta http-equiv="Expires" content="now" />

    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/jquery-ui-1.8.6.custom.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/admin_stylesheet_new.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/admin_stylesheet.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/javascript/jquery/fancybox/jquery.fancybox-1.3.4.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/fg.menu.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/ColVis.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/widgets.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/zend_admin_stylesheet.css'); ?>" />

	<!--[if IE 6]>
	<style type="text/css">
		.fg-menu-ipod .fg-menu li { width: 95%; }
		.fg-menu-ipod .ui-widget-content { border:0; }
	</style>
	<![endif]-->

    <script type="text/javascript" src="/javascript/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="/javascript/jquery-ui/jquery-ui.min.js"></script>
    <script type="text/javasctipt" src="/javascript/jquery-ui/ui/i18n/jquery.ui.datepicker-<?php echo $this->locale; ?>.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('/javascript/jquery/jquery-ui-timepicker-addon.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('/javascript/jquery/fg.menu.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('/javascript/jquery/jquery.cookie.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('/javascript/jquery/jquery.dataTables.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('/javascript/jquery/ColVis.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('/javascript/jquery/jquery.widgets.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('/javascript/jquery/fancybox/jquery.fancybox-1.3.4.pack.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('/javascript/admin.js'); ?>"></script>

    <script type="text/javascript"><!--
        <?php if (strpos($_SERVER['HTTP_REFERER'], 'login.php') !== FALSE) { ?>
        // close window after relogin
        if (opener && !opener.closed && opener.setSecurityToken) {
            opener.setSecurityToken(g_security_token);
            opener.focus();
            window.close();
        }
        <?php } ?>

        // set vars
        var popupFlash = false;
        var website_url = '<?php echo $this->baseUrl(); ?>';
        var g_admin_url = '<?php echo $this->baseUrl('admin'); ?>';
        var g_admin_img = '<?php echo $this->baseUrl('admin-style/images'); ?>';
        var g_security_token = '<?php echo SecurityToken::GetToken(); ?>';

        var localizer = localizer || {
            processing: '<?php putGS('Processing...'); ?>',
            session_expired: '<?php putGS('Session expired.'); ?>',
            please: '<?php putGS('Please'); ?>',
            login: '<?php putGS('login'); ?>',
            confirm: '<?php putGS('Are you sure you want to'); ?>'
        };

        $(function() {
            <?php if ($this->locale != 'en') { ?>
            // init datepicker
            $.datepicker.setDefaults( $.datepicker.regional['<?php echo $this->locale; ?>'] );
            <?php } ?>
        });
    //--></script>
</head>
<body>
<div class="meta-bar">
    <ul>
        <li><a href="<?php echo $this->baseUrl('admin/logout.php'); ?>"><?php putGS('Logout'); ?></a></li>
        <li><a href="<?php echo $this->helpUrl; ?>" target="_blank"><?php putGS('Help'); ?></a></li>
        <li><?php putGS("Signed in: $1", '<strong>' . $this->user->getRealName() . '</strong>'); ?></li>
    </ul>
</div>

<?php echo $this->render('admin_menu.phtml'); ?>

<div class="content">
    <?php echo $this->layout()->content; ?>
</div>

<?php if (!empty($this->messages)) { ?>
<script type="text/javascript"><!--
$(function() {
    <?php foreach ($this->messages as $message) { ?>
    flashMessage('<?php echo $this->escape($message); ?>');
    <?php } ?>
});
//--></script>
<?php } ?>

<?php camp_html_copyright_notice(); ?>
</body>
</html>
