<?php
/**
 * Generate admin menu.
 */

global $Campsite, $g_user;

camp_load_translation_strings('home');

$showPublishingEnvironmentMenu = ($g_user->hasPermission('ManageTempl')
    || $g_user->hasPermission('DeleteTempl')
    || $g_user->hasPermission('ManageArticleTypes')
    || $g_user->hasPermission('DeleteArticleTypes')
    || $g_user->hasPermission('ManageTopics')
    || $g_user->hasPermission('ManageLanguages')
    || $g_user->hasPermission('DeleteLanguages')
    || $g_user->hasPermission('ManageCountries')
    || $g_user->hasPermission('DeleteCountries'));

$showConfigureMenu = ($showPublishingEnvironmentMenu
    || $g_user->hasPermission('ManageLocalizer')
    || $g_user->hasPermission('ViewLogs'));

$showUserMenu = ($g_user->hasPermission('ManageUsers')
    || $g_user->hasPermission('DeleteUsers')
    || $g_user->hasPermission('ManageSubscriptions')
    || $g_user->hasPermission('ManageUserTypes')
    || $g_user->hasPermission('ManageReaders')
    || $g_user->hasPermission('SyncPhorumUsers'));

$showAdminActions = (($g_user->hasPermission('ManageIssue') && $g_user->hasPermission('AddArticle'))
    || (CampCache::IsEnabled() && $g_user->hasPermission('ClearCache')));

// init view
$view = isset($this) ? $this : new Zend_View;

// build menu pages
$pages = array(
    array(
        'label' => getGS('Dashboard'),
        'module' => 'admin',
    ),
    array(
        'label' => getGS('Content'),
        'uri' => '#',
    ),
    array(
        'label' => getGS('Actions'),
        'uri' => '#',
    ),
    array(
        'label' => getGS('Configure'),
        'uri' => '#',
    ),
    array(
        'label' => getGS('Users'),
        'uri' => '#',
    ),
);

// add content menu
$pages[1]['pages'][] = array(
    'label' => 'Publications',
    'module' => 'admin',
    'controller' => 'pub',
    'action' => 'index.php',
);

if ($g_user->hasPermission('CommentModerate')) {
    $pages[1]['pages'][] = array(
        'label' => getGS('Comments'),
        'module' => 'admin',
        'controller' => 'comments',
        'action' => 'index.php',
    );
}

$pages[1]['pages'][] = array(
    'label' => getGS('Media Archive'),
    'module' => 'admin',
    'controller' => 'media-archive',
    'action' => 'index.php',
);

$pages[1]['pages'][] = array(
    'label' => getGS('Search'),
    'module' => 'admin',
    'controller' => 'universal-list',
    'action' => 'index.php',
);

// add content/publications
foreach ($Campsite['publications'] as $publication) {
    $pubId = $publication->getPublicationId();
    $publication_page = array(
        'label' => $publication->getName(),
        'uri' => $view->baseUrl("admin/pub/?Pub=$pubId"),
    );

    // add content/publication/issue
    if (isset($Campsite['issues'][$pubId])) {
        foreach ($Campsite['issues'][$pubId] as $issue) {
            $issueId = $issue->getIssueNumber();
            $languageId = $issue->getLanguageId();
            $issue_page = array(
                'label' => sprintf('%d. %s (%s)',
                    $issue->getIssueNumber(),
                    $issue->getName(),
                    $issue->getLanguageName()),
                'uri' => $view->baseUrl("admin/sections/?Pub=$pubId&Issue=$issueId&Language=$languageId"),
            );

            // add content/publication/issue/section
            if (isset($Campsite['sections'][$pubId][$issueId][$languageId])) {
                foreach ($Campsite['sections'][$pubId][$issueId][$languageId] as $section) {
                    $sectionId = $section->getSectionNumber();
                    $section_page = array(
                        'label' => sprintf('%d. %s',
                            $section->getSectionNumber(),
                            $section->getName()),
                        'uri' => $view->baseUrl("admin/articles/?f_publication_id=$pubId&f_issue_number=$issueId&f_language_id=$languageId&f_section_number=$sectionId"),
                    );
                    $issue_page['pages'][] = $section_page;
                }
                if (count($Campsite['sections'][$pubId][$issueId][$languageId]) > 0) {
                    $issue_page['pages'][] = array(
                        'label' => getGS('More...'),
                        'uri' => $view->baseUrl("admin/sections/?Pub=$pubId&Issue=$issueId&Language=$languageId"),
                    );
                }
            }

            $publication_page['pages'][] = $issue_page;
        }

        if (count($Campsite['issues'][$pubId]) > 0) {
            $publication_page['pages'][] = array(
                'label' => getGS('More...'),
                'uri' => $view->baseUrl("admin/pub/?Pub=$pubId"),
            );
        }
    }

    $pages[1]['pages'][] = $publication_page;
}

// add actions menu
if ($g_user->hasPermission('AddArticle')) {
    $pages[2]['pages'][] = array(
        'label' => getGS('Add new article'),
        'module' => 'admin',
        'controller' => 'articles',
        'action' => 'add_move.php',
    );
}

if ($g_user->hasPermission('ManageTempl')) {
    $pages[2]['pages'][] = array(
        'label' => getGS('Upload new template'),
        'module' => 'admin',
        'controller' => 'templates',
        'action' => 'upload_templ.php',
    );
}

if ($g_user->hasPermission('ManagePub')) {
    $pages[2]['pages'][] = array(
        'label' => getGS('Add new publication'),
        'module' => 'admin',
        'controller' => 'pub',
        'action' => 'add.php',
    );
}

if ($g_user->hasPermission('ManageUsers')) {
    $pages[2]['pages'][] = array(
        'label' => getGS('Add new staff member'),
        'uri' => $view->baseUrl("admin/users/edit.php?uType=Staff"),
    );
}

if ($g_user->hasPermission('ManageUsers')) {
    $pages[2]['pages'][] = array(
        'label' => getGS('Add new subscriber'),
        'uri' => $view->baseUrl("admin/users/edit.php?uType=Subscribers"),
    );
}

if ($g_user->hasPermission('ManageUserTypes')) {
    $pages[2]['pages'][] = array(
        'label' => getGS('Add new user type'),
        'module' => 'admin',
        'controller' => 'user_types',
        'action' => 'add.php',
    );
}

if ($g_user->hasPermission('ManageArticleTypes')) {
    $pages[2]['pages'][] = array(
        'label' => getGS('Add new article type'),
        'module' => 'admin',
        'controller' => 'article_types',
        'action' => 'add.php',
    );
}

if ($g_user->hasPermission('ManageCountries')) {
    $pages[2]['pages'][] = array(
        'label' => getGS('Add new country'),
        'module' => 'admin',
        'controller' => 'country',
        'action' => 'add.php',
    );
}

if ($g_user->hasPermission('ManageLanguages')) {
    $pages[2]['pages'][] = array(
        'label' => getGS('Add new language'),
        'module' => 'admin',
        'controller' => 'languages',
        'action' => 'add_modify.php',
    );
}

$pages[2]['pages'][] = array(
    'label' => getGS('Change your password'),
    'uri' => $view->baseUrl("admin/users/edit.php?uType=Staff&User={$g_user->getUserId()}"),
);

if ($showAdminActions) {
    if ($g_user->hasPermission('ManageIssue') && $g_user->hasPermission('AddArticle')) {
        $pages[2]['pages'][] = array(
            'label' => getGS('Import XML'),
            'module' => 'admin',
            'controller' => 'articles',
            'action' => 'la_import.php',
        );
    }

    if ((CampCache::IsEnabled() || CampTemplateCache::factory()) && $g_user->hasPermission('ClearCache')) {
        $pages[2]['pages'][] = array(
            'label' => getGS('Clear system cache'),
            'uri' => $view->baseUrl('admin/?clear_cache=yes'),
        );
    }

    if ($g_user->hasPermission('ManageBackup')) {
        $pages[2]['pages'][] = array(
            'label' => getGS('Backup/Restore'),
            'module' => 'admin',
            'controller' => 'backup.php',
        );
    }
}

// add configure menu
if ($showConfigureMenu) {
    if ($g_user->hasPermission('ChangeSystemPreferences')) {
        $pages[3]['pages'][] = array(
            'label' => getGS('System Preferences'),
            'module' => 'admin',
            'controller' => 'system_pref',
            'action' => 'index.php',
        );
    }

    if ($g_user->hasPermission('ManageTempl') || $g_user->hasPermission('DeleteTempl')) {
        $pages[3]['pages'][] = array(
            'label' => getGS('Templates'),
            'module' => 'admin',
            'controller' => 'templates',
            'action' => 'index.php',
        );
    }

    if ($g_user->hasPermission('ManageArticleTypes') || $g_user->hasPermission('DeleteArticleTypes')) {
        $pages[3]['pages'][] = array(
            'label' => getGS('Article Types'),
            'module' => 'admin',
            'controller' => 'article_types',
            'action' => 'index.php',
        );
    }

    if ($g_user->hasPermission('ManageTopics')) {
        $pages[3]['pages'][] = array(
            'label' => getGS('Topics'),
            'module' => 'admin',
            'controller' => 'topics',
            'action' => 'index.php',
        );
    }

    if ($g_user->hasPermission('ManageLanguages') || $g_user->hasPermission('DeleteLanguages')) {
        $pages[3]['pages'][] = array(
            'label' => getGS('Languages'),
            'module' => 'admin',
            'controller' => 'languages',
            'action' => 'index.php',
        );
    }

    if ($g_user->hasPermission('ManageCountries') || $g_user->hasPermission('DeleteCountries')) {
        $pages[3]['pages'][] = array(
            'label' => getGS('Countries'),
            'module' => 'admin',
            'controller' => 'country',
            'action' => 'index.php',
        );
    }

    if ($g_user->hasPermission('ManageLocalizer')) {
        $pages[3]['pages'][] = array(
            'label' => getGS('Localizer'),
            'module' => 'admin',
            'controller' => 'localizer',
            'action' => 'index.php',
        );
    }

    if ($g_user->hasPermission('ViewLogs')) {
        $pages[3]['pages'][] = array(
            'label' => getGS('Logs'),
            'module' => 'admin',
            'controller' => 'logs',
        );
    }
}

// add user menu
if ($showUserMenu) {
    if ($g_user->hasPermission('ManageUsers') || $g_user->hasPermission('DeleteUsers')) {
        $pages[4]['pages'][] = array(
            'label' => getGS('Staff'),
            'uri' => $view->baseUrl('admin/users/?uType=Staff&reset_search=true'),
        );
    }

    if (($g_user->hasPermission('ManageReaders') || $g_user->hasPermission('ManageSubscriptions'))
            && SystemPref::Get('ExternalSubscriptionManagement') != 'Y') {
        $pages[4]['pages'][] = array(
            'label' => getGS('Subscribers'),
            'uri' => $view->baseUrl('admin/users/?uType=Subscribers&reset_search=true'),
        );
    }

    if ($g_user->hasPermission('ManageUserTypes')) {
        $pages[4]['pages'][] = array(
            'label' => getGS('Staff User Types'),
            'module' => 'admin',
            'controller' => 'user_types',
            'action' => 'index.php',
        );
    }

    if ($g_user->hasPermission('SyncPhorumUsers')) {
        $pages[4]['pages'][] = array(
            'label' => getGS('Synchronize Newscoop and Phorum users'),
            'uri' => $view->baseUrl('admin/?sync_users=yes'),
        );
    }

    if ($g_user->hasPermission('EditAuthors')) {
        $pages[4]['pages'][] = array(
            'label' => getGS('Manage Authors'),
            'module' => 'admin',
            'controller' => 'users',
            'action' => 'authors.php',
        );
    }
}

// get plugins menu
$plugin_pages = CampPlugin::CreatePluginMenu();
if (!empty($plugin_pages)) {
    $pages[] = array(
        'label' => getGS('Plugins'),
        'uri' => '#',
        'pages' => $plugin_pages,
    );
}

$container = new Zend_Navigation($pages);
$view->navigation($container);
?>

<div class="main-menu-bar">
    <div class="logo"></div>
    <?php echo $view->navigation(); ?>
</div>

<?php if (isset($this)) { // zend framework only ?>
<div class="breadcrumb-bar zend clearfix">
    <?php echo $this->navigation()->breadcrumbs(); ?>
</div>
<?php } ?>
