<?php
/**
 * Generate admin menu.
 */

global $Campsite, $g_user;

camp_load_translation_strings('home');

if (!isset($g_user)) {
    $g_user = Zend_Registry::get('user');
}

$showPublishingEnvironmentMenu = ($g_user->hasPermission('ManageTempl')
    || $g_user->hasPermission('DeleteTempl')
    || $g_user->hasPermission('ManageArticleTypes')
    || $g_user->hasPermission('DeleteArticleTypes')
    || $g_user->hasPermission('ManageTopics')
    || $g_user->hasPermission('ManageLanguages')
    || $g_user->hasPermission('DeleteLanguages')
    || $g_user->hasPermission('ManageCountries')
    || $g_user->hasPermission('DeleteCountries'));

$showConfigureMenu = ($showPublishingEnvironmentMenu
    || $g_user->hasPermission('ManageLocalizer')
    || $g_user->hasPermission('ViewLogs'));

$showUserMenu = ($g_user->hasPermission('ManageUsers')
    || $g_user->hasPermission('DeleteUsers')
    || $g_user->hasPermission('ManageSubscriptions')
    || $g_user->hasPermission('ManageUserTypes')
    || $g_user->hasPermission('ManageReaders')
    || $g_user->hasPermission('SyncPhorumUsers'));

$showAdminActions = (($g_user->hasPermission('ManageIssue') && $g_user->hasPermission('AddArticle'))
    || (CampCache::IsEnabled() && $g_user->hasPermission('ClearCache')));

// init view
$view = isset($this) ? $this : new Zend_View;

// build menu pages
$pages = array(
    array(
        'label' => getGS('Dashboard'),
        'module' => 'admin',
    ),
    array(
        'label' => getGS('Content'),
        'uri' => '#',
    ),
    array(
        'label' => getGS('Actions'),
        'uri' => '#',
    ),
    array(
        'label' => getGS('Configure'),
        'uri' => '#',
    ),
    array(
        'label' => getGS('Users'),
        'uri' => '#',
    ),
);

$pages[1]['pages'][] = array(
    'label' => 'Publications',
    'module' => 'admin',
    'controller' => 'pub',
    'action' => 'index.php',
    'resource' => 'publication',
    'privilege' => 'manage',
);

$pages[1]['pages'][] = array(
    'label' => getGS('Comments'),
    'module' => 'admin',
    'controller' => 'comments',
    'action' => 'index.php',
    'resource' => 'comment',
    'privilege' => 'moderate',
);

$pages[1]['pages'][] = array(
    'label' => getGS('Media Archive'),
    'module' => 'admin',
    'controller' => 'media-archive',
    'action' => 'index.php',
);

$pages[1]['pages'][] = array(
    'label' => getGS('Search'),
    'module' => 'admin',
    'controller' => 'universal-list',
    'action' => 'index.php',
);

// add content/publications
foreach ($Campsite['publications'] as $publication) {
    $pubId = $publication->getPublicationId();
    $publication_page = array(
        'label' => $publication->getName(),
        'uri' => $view->baseUrl("admin/pub/?Pub=$pubId"),
    );

    // add content/publication/issue
    if (isset($Campsite['issues'][$pubId])) {
        foreach ($Campsite['issues'][$pubId] as $issue) {
            $issueId = $issue->getIssueNumber();
            $languageId = $issue->getLanguageId();
            $issue_page = array(
                'label' => sprintf('%d. %s (%s)',
                    $issue->getIssueNumber(),
                    $issue->getName(),
                    $issue->getLanguageName()),
                'uri' => $view->baseUrl("admin/sections/?Pub=$pubId&Issue=$issueId&Language=$languageId"),
            );

            // add content/publication/issue/section
            if (isset($Campsite['sections'][$pubId][$issueId][$languageId])) {
                foreach ($Campsite['sections'][$pubId][$issueId][$languageId] as $section) {
                    $sectionId = $section->getSectionNumber();
                    $section_page = array(
                        'label' => sprintf('%d. %s',
                            $section->getSectionNumber(),
                            $section->getName()),
                        'uri' => $view->baseUrl("admin/articles/?f_publication_id=$pubId&f_issue_number=$issueId&f_language_id=$languageId&f_section_number=$sectionId"),
                    );
                    $issue_page['pages'][] = $section_page;
                }
                if (count($Campsite['sections'][$pubId][$issueId][$languageId]) > 0) {
                    $issue_page['pages'][] = array(
                        'label' => getGS('More...'),
                        'uri' => $view->baseUrl("admin/sections/?Pub=$pubId&Issue=$issueId&Language=$languageId"),
                    );
                }
            }

            $publication_page['pages'][] = $issue_page;
        }

        if (count($Campsite['issues'][$pubId]) > 0) {
            $publication_page['pages'][] = array(
                'label' => getGS('More...'),
                'uri' => $view->baseUrl("admin/pub/?Pub=$pubId"),
            );
        }
    }

    $pages[1]['pages'][] = $publication_page;
}

$pages[2]['pages'][] = array(
    'label' => getGS('Add new article'),
    'module' => 'admin',
    'controller' => 'articles',
    'action' => 'add_move.php',
    'resource' => 'article',
    'privilege' => 'add',
);

$pages[2]['pages'][] = array(
    'label' => getGS('Upload new template'),
    'module' => 'admin',
    'controller' => 'templates',
    'action' => 'upload_templ.php',
    'resource' => 'template',
    'privilege' => 'manage',
);

$pages[2]['pages'][] = array(
    'label' => getGS('Add new publication'),
    'module' => 'admin',
    'controller' => 'pub',
    'action' => 'add.php',
    'resource' => 'publication',
    'privilege' => 'add',
);

$pages[2]['pages'][] = array(
    'label' => getGS('Add new staff member'),
    'module' => 'admin',
    'controller' => 'staff',
    'action' => 'add',
    'resource' => 'user',
    'privilege' => 'manage',
);

$pages[2]['pages'][] = array(
    'label' => getGS('Add new subscriber'),
    'module' => 'admin',
    'controller' => 'subscriber',
    'action' => 'add',
    'resource' => 'user',
    'privilege' => 'manage',
);

$pages[2]['pages'][] = array(
    'label' => getGS('Add new user type'),
    'module' => 'admin',
    'controller' => 'user-group',
    'action' => 'add',
    'resource' => 'user-group',
    'privilege' => 'manage',
);

$pages[2]['pages'][] = array(
    'label' => getGS('Add new article type'),
    'module' => 'admin',
    'controller' => 'article_types',
    'action' => 'add.php',
    'resource' => 'article-type',
    'privilege' => 'manage',
);

$pages[2]['pages'][] = array(
    'label' => getGS('Add new country'),
    'module' => 'admin',
    'controller' => 'country',
    'action' => 'add.php',
    'resource' => 'country',
    'privilege' => 'manage',
);

$pages[2]['pages'][] = array(
    'label' => getGS('Change your password'),
    'module' => 'admin',
    'controller' => 'staff',
    'action' => 'edit',
    'params' => array(
        'user' => $g_user->getId(),
    ),
);

if ($showAdminActions) {
    if ($g_user->hasPermission('ManageIssue') && $g_user->hasPermission('AddArticle')) {
        $pages[2]['pages'][] = array(
            'label' => getGS('Import XML'),
            'module' => 'admin',
            'controller' => 'articles',
            'action' => 'la_import.php',
        );
    }

    if ((CampCache::IsEnabled() || CampTemplateCache::factory()) && $g_user->hasPermission('ClearCache')) {
        $pages[2]['pages'][] = array(
            'label' => getGS('Clear system cache'),
            'uri' => $view->baseUrl('admin/?clear_cache=yes'),
        );
    }

    $pages[2]['pages'][] = array(
        'label' => getGS('Backup/Restore'),
        'module' => 'admin',
        'controller' => 'backup.php',
        'resource' => 'backup',
        'privilege' => 'manage',
    );
}

// add configure menu
if ($showConfigureMenu) {
    $pages[3]['pages'][] = array(
        'label' => getGS('System Preferences'),
        'module' => 'admin',
        'controller' => 'system_pref',
        'action' => 'index.php',
        'resource' => 'system-preferences',
        'privilege' => 'edit',
    );

    if ($g_user->hasPermission('ManageTempl') || $g_user->hasPermission('DeleteTempl')) {
        $pages[3]['pages'][] = array(
            'label' => getGS('Templates'),
            'module' => 'admin',
            'controller' => 'templates',
            'action' => 'index.php',
        );
    }

    $pages[3]['pages'][] = array(
        'label' => getGS('Article Types'),
        'module' => 'admin',
        'controller' => 'article_types',
        'action' => 'index.php',
        'resource' => 'article-type',
        'privilege' => 'manage',
    );

    $pages[3]['pages'][] = array(
        'label' => getGS('Topics'),
        'module' => 'admin',
        'controller' => 'topics',
        'action' => 'index.php',
        'resource' => 'topic',
        'privilege' => 'manage',
    );

    $pages[3]['pages'][] = array(
        'label' => getGS('Languages'),
        'module' => 'admin',
        'controller' => 'languages',
        'resource' => 'language',
        'privilege' => 'manage',
        'pages' => array(
            array(
                'label' => getGS('Edit language'),
                'module' => 'admin',
                'controller' => 'languages',
                'action' => 'edit',
                'visible' => false,
                'resource' => 'language',
                'privilege' => 'manage',
            ),
            array(
                'label' => getGS('Add new language'),
                'module' => 'admin',
                'controller' => 'languages',
                'action' => 'add',
                'visible' => false,
                'resource' => 'language',
                'privilege' => 'manage',
            ),
        ));

    if ($g_user->hasPermission('ManageCountries') || $g_user->hasPermission('DeleteCountries')) {
        $pages[3]['pages'][] = array(
            'label' => getGS('Countries'),
            'module' => 'admin',
            'controller' => 'country',
            'action' => 'index.php',
        );
    }

    if ($g_user->hasPermission('ManageLocalizer')) {
        $pages[3]['pages'][] = array(
            'label' => getGS('Localizer'),
            'module' => 'admin',
            'controller' => 'localizer',
            'action' => 'index.php',
        );
    }

    if ($g_user->hasPermission('ViewLogs')) {
        $pages[3]['pages'][] = array(
            'label' => getGS('Logs'),
            'module' => 'admin',
            'controller' => 'log',
            'resource' => 'log',
            'privilege' => 'view',
        );
    }
} else {
    unset($pages[3]);
}

// add user menu
if ($showUserMenu) {
    if ($g_user->hasPermission('ManageUsers') || $g_user->hasPermission('DeleteUsers')) {
        $pages[4]['pages'][] = array(
            'label' => getGS('Staff'),
            'module' => 'admin',
            'controller' => 'staff',
            'pages' => array(
                array(
                    'label' => getGS('Add new staff member'),
                    'module' => 'admin',
                    'controller' => 'staff',
                    'action' => 'add',
                    'visible' => false,
                ),
                array(
                    'label' => getGS('Edit staff member'),
                    'module' => 'admin',
                    'controller' => 'staff',
                    'action' => 'edit',
                    'visible' => false,
                    'reset_params' => false,
                    'pages' => array(
                        array(
                            'label' => getGS('Edit access'),
                            'module' => 'admin',
                            'controller' => 'staff',
                            'action' => 'edit-access',
                            'visible' => false,
                        ),
                    ),
                ),
            ),
        );
    }

    if (($g_user->hasPermission('ManageReaders') || $g_user->hasPermission('ManageSubscriptions'))
            && SystemPref::Get('ExternalSubscriptionManagement') != 'Y') {
        $pages[4]['pages'][] = array(
            'label' => getGS('Subscribers'),
            'module' => 'admin',
            'controller' => 'subscriber',
            'resource' => 'subscriber',
            'privilege' => 'manage',
            'pages' => array(
                array(
                    'label' => getGS('Add new subscriber'),
                    'module' => 'admin',
                    'controller' => 'subscriber',
                    'action' => 'add',
                    'visible' => false,
                ),
                array(
                    'label' => getGS('Edit subscriber'),
                    'module' => 'admin',
                    'controller' => 'subscriber',
                    'action' => 'edit',
                    'visible' => false,
                    'reset_params' => false,
                    'pages' => array(
                        array(
                            'label' => getGS('Subscriptions'),
                            'module' => 'admin',
                            'controller' => 'subscription',
                            'action' => 'index',
                            'reset_params' => false,
                            'pages' => array(
                                array(
                                    'label' => getGS('Add new subscription'),
                                    'module' => 'admin',
                                    'controller' => 'subscription',
                                    'action' => 'add',
                                ),
                                array(
                                    'label' => getGS('Edit subscription'),
                                    'module' => 'admin',
                                    'controller' => 'subscription',
                                    'action' => 'edit',
                                ),
                                array(
                                    'label' => getGS('Sections'),
                                    'module' => 'admin',
                                    'controller' => 'subscription-section',
                                    'action' => 'index',
                                    'reset_params' => false,
                                    'pages' => array(
                                        array(
                                            'label' => getGS('Add new subscription section'),
                                            'module' => 'admin',
                                            'controller' => 'subscription-section',
                                            'action' => 'add',
                                        ),
                                        array(
                                            'label' => getGS('Edit section'),
                                            'module' => 'admin',
                                            'controller' => 'subscription-section',
                                            'action' => 'edit',
                                        ),
                                        array(
                                            'label' => getGS('Edit all sections'),
                                            'module' => 'admin',
                                            'controller' => 'subscription-section',
                                            'action' => 'edit-all',
                                        ),
                                    ),
                                ),
                            ),
                        ),
                        array(
                            'label' => getGS('Add new subscription'),
                            'module' => 'admin',
                            'controller' => 'subscription',
                            'action' => 'add',
                        ),
                        array(
                            'label' => getGS('Add new IP Address'),
                            'module' => 'admin',
                            'controller' => 'subscription-ip',
                            'action' => 'add',
                        ),
                    ),
                ),
            ),
        );
    }

    $pages[4]['pages'][] = array(
        'label' => getGS('Staff User Types'),
        'module' => 'admin',
        'controller' => 'user-group',
        'resource' => 'user-group',
        'privilege' => 'manage',
        'pages' => array(
        array(
                'label' => getGS('Add new user type'),
                'module' => 'admin', 
                'controller' => 'user-group',
                'action' => 'add',
                'visible' => false,
            ),
            array(
                'label' => getGS('Edit user type'),
                'module' => 'admin',
                'controller' => 'user-group',
                'action' => 'edit-access',
                'visible' => false,
            ),
        ),
    );

    if ($g_user->hasPermission('SyncPhorumUsers')) {
        $pages[4]['pages'][] = array(
            'label' => getGS('Synchronize Newscoop and Phorum users'),
            'uri' => $view->baseUrl('admin/?sync_users=yes'),
        );
    }

    if ($g_user->hasPermission('EditAuthors')) {
        $pages[4]['pages'][] = array(
            'label' => getGS('Manage Authors'),
            'module' => 'admin',
            'controller' => 'users',
            'action' => 'authors.php',
        );
    }
} else {
    unset($pages[4]);
}

// get plugins menu
$plugin_pages = CampPlugin::CreatePluginMenu();
if (!empty($plugin_pages)) {
    $pages[] = array(
        'label' => getGS('Plugins'),
        'uri' => '#',
        'pages' => $plugin_pages,
    );
}

// set navigation
$navigation = new Zend_Navigation($pages);
$view->navigation()->menu()->setContainer($navigation);
$view->navigation()->breadcrumbs()->setContainer($navigation);
$view->navigation()->breadcrumbs()->setRenderInvisible(true);

if (defined('IN_BUG_HANDLE')) { // prevent navigation causing another error
    return;
}
?>

<div class="main-menu-bar">
    <div class="logo"></div>
    <?php echo $view->navigation(); ?>
</div>

<?php if (!$this->legacy) { // zend framework only ?>
<div class="breadcrumb-bar zend clearfix">
    <?php echo $this->navigation()->breadcrumbs(); ?>
</div>
<?php } ?>
