<?php echo $this->doctype(); ?>
<html lang="<?php echo $this->locale; ?>" dir="ltr">
<head>
    <meta charset="utf-8" />
    <?php echo $this->headTitle(); ?>

    <meta http-equiv="Expires" content="now" />

    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/jquery-ui-1.8.6.custom.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/admin_stylesheet_new.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/admin_stylesheet.css'); ?>" />
</head>
<body>
<div class="meta-bar">
    <ul>
        <li><a href="<?php echo $this->helpUrl; ?>" target="_blank"><?php putGS('Help'); ?></a></li>
    </ul>
</div>

<div class="content">
    <?php echo $this->layout()->content; ?>
</div>

<?php camp_html_copyright_notice(); ?>
</body>
</html>
