<?php camp_load_translation_strings('home'); ?>
<!DOCTYPE html>
<html lang="<?php echo $this->locale; ?>" dir="ltr">
<head>
    <meta charset="utf-8" />
    <meta name="robots" content="noindex, nofollow" />
    <?php echo $this->headTitle(); ?>

    <script>
        // set vars
        var popupFlash = false;
        var website_url = '<?php echo $this->baseUrl(); ?>';
        var g_admin_url = '<?php echo $this->baseUrl('admin'); ?>';
        var g_admin_img = '<?php echo $this->baseUrl('admin-style/images'); ?>';
        var g_security_token = '<?php echo SecurityToken::GetToken(); ?>';

        var localizer = localizer || {
            processing: '<?php putGS('Processing...'); ?>',
            session_expired: '<?php putGS('Session expired.'); ?>',
            please: '<?php putGS('Please'); ?>',
            login: '<?php putGS('login'); ?>',
            confirm: '<?php putGS('Are you sure you want to'); ?>',
            connection_interrupted : '<?php putGS('Connection interrupted') ?>',
            try_again_later : '<?php putGS('try again later') ?>'
        };

        <?php if (isset($_SERVER['HTTP_REFERER']) && strpos($_SERVER['HTTP_REFERER'], 'login.php') !== FALSE) { ?>
        // close window after relogin
        if (opener && !opener.closed && opener.setSecurityToken) {
            opener.setSecurityToken(g_security_token);
            opener.focus();
            window.close();
        }
        <?php } ?>
    </script>

    <link rel="shortcut icon" href="<?php echo $this->baseUrl('/admin-style/images/7773658c3ccbf03954b4dacb029b2229.ico'); ?>" />

    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/jquery-ui-1.8.6.custom.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/js/jquery/fancybox/jquery.fancybox-1.3.4.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/ColVis.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/admin_stylesheet_new.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/admin_stylesheet.css'); ?>" />

    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/action_buttons.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/content.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/fg.menu.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/form.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/layout.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/sidebar.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/widgets.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/zend_admin_stylesheet.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/lists.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/slideshow-list.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/pagination.css'); ?>" />
    <?php if (!$this->legacy) { ?>
    <link rel="stylesheet" media="screen" href="<?php echo $this->baseUrl('/admin-style/form.css'); ?>" />
    <link rel="stylesheet" media="screen" href="<?php echo $this->baseUrl('/admin-style/layout.css'); ?>" />
    <link rel="stylesheet" media="screen" href="<?php echo $this->baseUrl('/admin-style/content.css'); ?>" />
    <link rel="stylesheet" media="screen" href="<?php echo $this->baseUrl('/admin-style/sidebar.css'); ?>" />
    <link rel="stylesheet" media="screen" href="<?php echo $this->baseUrl('/admin-style/misc-pages.css'); ?>" />
    <?php
        $headLink = $this->headLink();
        if(!isset($headLink['table']))
            $headLink->offsetSetStylesheet('table', $this->baseUrl('/admin-style/table.css'));
        elseif(empty($headLink['table']))
            unset($headLink['table']);
        echo $headLink;
    ?>
    <?php } ?>
    <link rel="stylesheet" media="screen" href="<?php echo $this->baseUrl('/js/plupload/js/jquery.plupload.queue/css/jquery.plupload.queue.css'); ?>" />
	<!--[if IE 6]>
	<style type="text/css">
		.fg-menu-ipod .fg-menu li { width: 95%; }
		.fg-menu-ipod .ui-widget-content { border:0; }
	</style> <![endif]-->

    <script src="<?php echo $this->baseUrl('/js/jquery/jquery-1.7.1.min.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('/js/jquery/jquery-ui-1.8.6.custom.min.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('/js/jquery/i18n/jquery.ui.datepicker-' . $this->locale . '.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('/js/jquery/jquery-ui-timepicker-addon.min.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('/js/jquery/fg.menu.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('/js/jquery/jquery.cookie.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('/js/jquery/jquery.dataTables.min.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('/js/jquery/ColVis.min.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('/js/jquery/jquery.widgets.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('/js/jquery/fancybox/jquery.fancybox-1.3.4.pack.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('/js/admin.js'); ?>"></script>
    <?php
        echo $this->headStyle();
        echo $this->headScript();
    ?>
    <script><!--
        $(function() {
            <?php if ($this->locale != 'en') { ?>
            // init datepicker
            $.datepicker.setDefaults( $.datepicker.regional['<?php echo $this->locale; ?>'] );
            <?php } ?>
        });
    //--></script>
</head>
<body id="<?php echo $this->placeholder('bodyId'); ?>"<?php echo $this->placeholder('sidebar') != '' ? ' class="with-sidebar"' : ''; ?>>
<div class="meta-bar">
    <ul>
        <li><a href="/admin/logout"><?php putGS('Logout'); ?></a></li>
        <li><a href="<?php echo $this->url(array('controller' => 'application', 'action' => 'help')); ?>"><?php putGS('Help'); ?></a></li>
        <li><?php putGS("Signed in: $1", sprintf('<strong>%s %s</strong>', $this->currentUser->getFirstName(), $this->currentUser->getLastName())); ?></li>
    </ul>
</div>

<?php echo $this->render('admin_menu.phtml'); ?>

<?php echo $this->legacy ? '' : $this->placeholder('title'); ?>

<?php if ($this->placeholder('sidebar') != '') { ?>
<div class="content-sidebar">
<?php } ?>

<?php if (!$this->legacy) { ?>
<div class="content">
    <?php echo $this->layout()->content; ?>
</div>
<?php } else { ?>
    <?php echo $this->layout()->content; ?>
<?php } ?>

<?php if ($this->placeholder('sidebar') != '') { ?>
<div class="sidebar first">
<?php echo $this->placeholder('sidebar'); ?>
</div>
<?php } ?>

<?php if ($this->placeholder('sidebar') != '') { ?>
</div><!-- /.content-sidebar -->
<?php } ?>

<?php if (!empty($this->messages)) { ?>
<script type="text/javascript"><!--
$(function() {
    <?php foreach ($this->messages as $message) {
        if (is_array($message)) {
            list($type, $message) = array_values($message);
        } else {
            $type = 'highlight';
        } ?>
        flashMessage(<?php echo json_encode($message); ?>, <?php echo json_encode($type); ?>);
    <?php } ?>
});
//--></script>
<?php } ?>

<?php if (!$this->legacy) {
    camp_html_copyright_notice();
} ?>

<script type="text/javascript"><!--
    $(function() {
        <?php if ($this->locale != 'en') { ?>
        // init datepicker
        $.datepicker.setDefaults($.datepicker.regional['<?php echo $this->locale; ?>']);
        <?php } ?>
    });
//--></script>

</body>
</html>
