<?php echo $this->doctype(); ?>
<html lang="<?php echo $this->locale; ?>" dir="ltr">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <?php echo $this->headTitle(); ?>

    <meta http-equiv="Expires" content="now" />

    <script type="text/javascript"><!--
        // set vars
        var popupFlash = false;
        var website_url = '<?php echo $this->baseUrl(); ?>';
        var g_admin_url = '<?php echo $this->baseUrl('admin'); ?>';
        var g_admin_img = '<?php echo $this->baseUrl('admin-style/images'); ?>';
        var g_security_token = '<?php echo SecurityToken::GetToken(); ?>';

        var localizer = localizer || {
            processing: '<?php putGS('Processing...'); ?>',
            session_expired: '<?php putGS('Session expired.'); ?>',
            please: '<?php putGS('Please'); ?>',
            login: '<?php putGS('login'); ?>',
            confirm: '<?php putGS('Are you sure you want to'); ?>'
        };

        <?php if (isset($_SERVER['HTTP_REFERER']) && strpos($_SERVER['HTTP_REFERER'], 'login.php') !== FALSE) { ?>
        // close window after relogin
        if (opener && !opener.closed && opener.setSecurityToken) {
            opener.setSecurityToken(g_security_token);
            opener.focus();
            window.close();
        }
        <?php } ?>
    //--></script>

    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/jquery-ui-1.8.6.custom.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/js/jquery/fancybox/jquery.fancybox-1.3.4.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/ColVis.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/admin_stylesheet_new.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/admin_stylesheet.css'); ?>" />

    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/action_buttons.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/content.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/fg.menu.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/form.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/layout.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/sidebar.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/widgets.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/zend_admin_stylesheet.css'); ?>" />
    <?php echo $this->headLink(); ?>
    <?php if (!$this->legacy) { ?>
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/form.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/layout.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/content.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/sidebar.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/admin-style/table.css'); ?>" />
    <?php } ?>
    <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl('/js/plupload/js/jquery.plupload.queue/css/jquery.plupload.queue.css'); ?>" />
	<!--[if IE 6]>
	<style type="text/css">
		.fg-menu-ipod .fg-menu li { width: 95%; }
		.fg-menu-ipod .ui-widget-content { border:0; }
	</style> <![endif]-->

    <script type="text/javascript" src="<?php echo $this->baseUrl('/js/jquery/jquery-1.4.2.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('/js/jquery/jquery-ui-1.8.6.custom.min.js'); ?>"></script>
    <script type="text/javasctipt" src="<?php echo $this->baseUrl('/js/jquery/i18n/jquery.ui.datepicker-' . $this->locale . '.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('/js/jquery/jquery-ui-timepicker-addon.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('/js/jquery/fg.menu.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('/js/jquery/jquery.cookie.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('/js/jquery/jquery.dataTables.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('/js/jquery/ColVis.min.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('/js/jquery/jquery.widgets.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('/js/jquery/fancybox/jquery.fancybox-1.3.4.pack.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('/js/admin.js'); ?>"></script>
    
    <?php 
    	echo $this->headStyle();
   		echo $this->headScript();
	?>

    <script type="text/javascript"><!--
        $(function() {
            <?php if ($this->locale != 'en') { ?>
            // init datepicker
            $.datepicker.setDefaults( $.datepicker.regional['<?php echo $this->locale; ?>'] );
            <?php } ?>
        });
    //--></script>
</head>
<body<?php echo $this->placeholder('sidebar') != '' ? ' class="with-sidebar"' : ''; ?>>
<div class="meta-bar">
    <ul>
        <li><a href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'logout')); ?>"><?php putGS('Logout'); ?></a></li>
        <li><a href="<?php echo $this->helpUrl; ?>" target="_blank"><?php putGS('Help'); ?></a></li>
        <li><?php putGS("Signed in: $1", '<strong>' . $this->user->getRealName() . '</strong>'); ?></li>
    </ul>
</div>

<?php echo $this->render('admin_menu.phtml'); ?>

<?php echo $this->legacy ? '' : $this->placeholder('title'); ?>

<?php if ($this->placeholder('sidebar') != '') { ?>
<div class="content-sidebar">
<?php } ?>

<?php if (!$this->legacy) { ?>
<div class="content">
    <?php echo $this->layout()->content; ?>
</div>
<?php } else { ?>
    <?php echo $this->layout()->content; ?>
<?php } ?>

<?php if ($this->placeholder('sidebar') != '') { ?>
<div class="sidebar first">
<?php echo $this->placeholder('sidebar'); ?>
</div>
<?php } ?>

<?php if ($this->placeholder('sidebar') != '') { ?>
</div><!-- /.content-sidebar -->
<?php } ?>

<?php if (!empty($this->messages)) { ?>
<script type="text/javascript"><!--
$(function() {
    <?php foreach ($this->messages as $message) {
        if (is_array($message)) {
            list($type, $message) = array_values($message);
        } else {
            $type = 'highlight';
        } ?>
        flashMessage(<?php echo json_encode($message); ?>, <?php echo json_encode($type); ?>);
    <?php } ?>
});
//--></script>
<?php } ?>

<?php if (!$this->legacy) {
    camp_html_copyright_notice();
} ?>

<script type="text/javascript"><!--
    $(function() {
        <?php if ($this->locale != 'en') { ?>
        // init datepicker
        $.datepicker.setDefaults($.datepicker.regional['<?php echo $this->locale; ?>']);
        <?php } ?>
    });
//--></script>

</body>
</html>
