<?php
regGS("Publication<BR><SMALL>(click to see sections)</SMALL>", "Publicaţia");
regGS("Left to pay", "Rămas de plată");
regGS("Active", "Activă");
regGS("Delete subscriptions to $1", "Şterge subscrierile la $1");
regGS("No subscriptions.", "Nu există subscrieri");
regGS("Paid subscription", "Subscriere cu plată");
regGS("Trial subscription", "Subscriere de probă");
regGS("Are you sure you want to delete the subscription to the publication $1?", "Doriţi să ştergeţi subscrierile la publicaţia $1?");
regGS("The subscription has been deleted.", "Subscrierea a fost ştearsă");
regGS("The subscription could not be deleted.", "Subscrierea nu poate fi ştearsă");
regGS("Add sections now", "Adaugă secţiunile acum");
regGS("Add sections later", "Adaugă secţiunile mai târziu");
regGS("Subscription Type", "Tipul subscrierii");
regGS("Paid (payment will be confirmed later)", "Cu plată (confirmarea va fi făcută mai târziu)");
regGS("Paid (confirm payment now)", "Cu plată (confirmă plata acum)");
regGS("Trial", "Probă");
regGS("The subscription has been added successfully.", "Subscrierea a fost adăugată cu succes");
regGS("The subscription could not be added.", "Subscrierea nu poate fi adăugată");
regGS("Please check if there isn't another subscription to the same publication.", "Verificaţi dacă există altă subscriere la aceeaşi publicaţie");
regGS("Change subscription status", "Schimbă starea subscrierii");
regGS("You do not have the right to change subscriptions status.", "Nu aveţi dreptul să schimbaţi starea subscrierii");
regGS("Are you sure you want to deactivate the subscription?", "Doriţi să deactivaţi subscrierea?");
regGS("Are you sure you want to activate the subscription?", "Doriţi să activaţi subscrierea?");
regGS("Changing subscription status", "Schimb starea subscrierii");
regGS("The subscription has been activated.", "Subscrierea a fost activată");
regGS("The subscription has been deactivated.", "Subscrierea a fost deactivată");
regGS("Subscription status could not be changed.", "Starea subscrierii nu poate fi schimbată");
regGS("Update payment", "Actualizare plată");
regGS("The subscription payment was updated.", "Plata subscrierii a fost actualizată");
regGS("Subscription payment could not be changed.", "Plata subscrierii nu poate fi actualizată");
?>