<?php
regGS("Publication<BR><SMALL>(click to see sections)</SMALL>", "Публикација<br><small>(кликните да видите рубрике)</small>");
regGS("Left to pay", "Преостало за плаћање");
regGS("Active", "Активно");
regGS("Delete subscriptions to $1", "Обриши претплате на $1");
regGS("No subscriptions.", "Нема претплата");
regGS("Paid subscription", "Плаћене претплате");
regGS("Trial subscription", "Пробне претплате");
regGS("Are you sure you want to delete the subscription to the publication $1?", "Сигурни сте да желите да обришете претплате на публикацију $1?");
regGS("The subscription has been deleted.", "Претплата је обрисана");
regGS("The subscription could not be deleted.", "Претплата не може бити обрисана");
regGS("Add sections now", "Додај рубрику сад");
regGS("Add sections later", "Додај рубрику касније");
regGS("Subscription Type", "Тип претплате");
regGS("Paid (payment will be confirmed later)", "Плаћено (уплата ће бити потврђена касније) ");
regGS("Paid (confirm payment now)", "Плаћено (потврди уплату сад)");
regGS("Trial", "Пробно");
regGS("The subscription has been added successfully.", "Претплата је успешно додата");
regGS("The subscription could not be added.", "Претплата не може бити додата");
regGS("Please check if there isn't another subscription to the same publication.", "Проверите постоји ли друга претплата на исту публикацију");
regGS("Change subscription status", "Промени статус претплате");
regGS("You do not have the right to change subscriptions status.", "Немате право да мењате статус претплате");
regGS("Are you sure you want to deactivate the subscription?", "Сигурни сте да желите да деактивирате претплату?");
regGS("Are you sure you want to activate the subscription?", "Сигурни сте да желите да активирате претплату?");
regGS("Changing subscription status", "Мењање статуса претплате");
regGS("The subscription has been activated.", "Претплата је активирана");
regGS("The subscription has been deactivated.", "Претплата је деактивирана");
regGS("Subscription status could not be changed.", "Статус претплате не може бити промењен");
regGS("Update payment", "Измени уплату");
regGS("The subscription payment was updated.", "Уплата за претплату је измењена");
regGS("Subscription payment could not be changed.", "Уплата за претплату не може бити измењена");
?>