<?php
regGS("Publication<BR><SMALL>(click to see sections)</SMALL>", "发布（单击查看区）");
regGS("Left to pay", "");
regGS("Active", "");
regGS("Delete subscriptions to $1", "删除向$1的订阅");
regGS("No subscriptions.", "无订阅");
regGS("Paid subscription", "已付订阅");
regGS("Trial subscription", "试订阅");
regGS("Are you sure you want to delete the subscription to the publication $1?", "您确认要删除发布$1的订阅");
regGS("The subscription has been deleted.", "订阅已被删除");
regGS("The subscription could not be deleted.", "订阅不能删除");
regGS("Add sections now", "现在增加区");
regGS("Add sections later", "以后增加区");
regGS("Subscription Type", "订阅类型");
regGS("Paid (payment will be confirmed later)", "已付（付款以后将确认）");
regGS("Paid (confirm payment now)", "已付（现在确认付款）");
regGS("Trial", "试用");
regGS("The subscription has been added successfully.", "订阅已被成功添加");
regGS("The subscription could not be added.", "订阅不能被添加");
regGS("Please check if there isn't another subscription to the same publication.", "请确认是否有同样发布的其它订阅");
regGS("Change subscription status", "改变订阅状态");
regGS("You do not have the right to change subscriptions status.", "您无权修改订阅状态");
regGS("Are you sure you want to deactivate the subscription?", "您确认要解除订阅？");
regGS("Are you sure you want to activate the subscription?", "您确认要激活订阅？");
regGS("Changing subscription status", "正在改变订阅状态");
regGS("The subscription has been activated.", "订阅已被激活");
regGS("The subscription has been deactivated.", "订阅已被解除");
regGS("Subscription status could not be changed.", "订阅状态不能改变");
regGS("Update payment", "更新付款");
regGS("The subscription payment was updated.", "订阅付款被更新");
regGS("Subscription payment could not be changed.", "订阅付款不能修改");
?>