<?php 
$translator = \Zend_Registry::get('container')->getService('translator');
$this->headLink()->appendStylesheet($this->baseUrl('/admin-style/image_management.css'));
$this->headLink()->appendStylesheet($this->baseUrl('/admin-style/renditions.css'));
$this->headLink()->appendStylesheet($this->baseUrl('/admin-style/modal-custom.css'));
?>
<?php $this->placeholder('bodyId')->set('next'); ?>

<div id="modal-top">
    <div class="toolbar fixed-top">
    <div class="save-button-bar"></div>
    <h1>
        <?php echo $translator->trans('Place Images', array(), 'article_images'); ?>
        <span style="float: right;">
        <input type="button" style="display: none;" id="modal-close-btn" value="<?php echo $translator->trans('Finish', array(), 'article_images'); ?>" class="save-button" onClick="parent.$.fancybox.close();">
        </span>
    </h1>
    </div>
</div>

<ul class="renditions">
    <?php foreach ($this->renditions as $rendition) { ?>
    <li id="<?php echo $rendition->getName(); ?>"><?php echo $this->rendition($rendition, $this->previewWidth, $this->previewHeight, $this->articleRenditions[$rendition]); ?></li>
    <?php } ?>
</ul>

<h2><?php echo $translator->trans("Attached images", array(), 'article_images'); ?>
    <div class="inline">
        <button id="set-default"><?php echo $translator->trans('Set selected as default image', array(), 'article_images'); ?></button>
    </div>
</h2>

<?php if (!empty($this->images)) { ?>
<form id="renditions-form" action="<?php echo $this->url(array(
    'module' => 'admin',
    'controller' => 'image',
    'action' => 'set-default-image',
)); ?>" method="POST">
<?php } ?>
<ul id="attached-thumbnails" class="thumbnails">
    <?php if (!empty($this->images)) {  ?>
    <?php foreach ($this->images as $image) { ?>
    <li id="image-<?php echo $image->getId(); ?>">
        <figure>
            <div><?php echo $this->thumbnail($image, 120, 90, 'fit')->getImg($this); ?></div>
            <input type="radio" id="default-<?php echo $image->getId(); ?>" name="default-image" value="<?php echo $image->getId(); ?>" <?php if ($image->isDefault()) { echo 'checked="checked"'; } ?> title="<?php echo $translator->trans('Set as default', array(), 'article_images'); ?>" />
            <figcaption><label for="default-<?php echo $image->getId(); ?>"><?php echo $image->getWidth(), 'x', $image->getHeight(); ?></label></figcaption>
        </figure>
    </li>
    <?php } ?>
    <?php } else { ?>
        <p style="color: #fff; margin-top: 5%"><?php echo $translator->trans('No images attached to article.', array(), 'article_images'); ?></p>
    <?php } ?>
</ul>
<?php if (!empty($this->images)) { ?>
</form>
<?php }?>

<script>
$(function() {
    if (parent.$('div.renditionsModal').length == 0) {
        $('#modal-close-btn').show();
    }

    $('#set-default').click(function() {
        $('form#renditions-form').submit();
    })

    $('.renditions li').droppable({
        hoverClass: 'state-active',
        drop: function(event, ui) {
            var li = $(this);
            $.post("<?php echo $this->url(array(
                'module' => 'admin',
                'controller' => 'image',
                'action' => 'set-rendition',
                'format' => 'json',
            )); ?>", {
                'image': ui.draggable.attr('id'),
                'rendition': li.attr('id')
            }, function (data, textStatus) {
                if (data.exception != undefined) {
                    alert(data.exception);
                    return;
                }

                li.html(data.rendition);
            }, 'json');
        }
    });

    $('.thumbnails li').draggable({
        revert: true,
        opacity: 0.8,
        zIndex: 1000,
        cursor: 'move'
    });

    $('.renditions .reset').live('click', function(e) {
        e.preventDefault();
        var li = $(this).closest('li');
        $.post($(this).attr('href'), function(data, textStatus) {
            li.html(data.rendition);
        }, 'json');
    });
});
</script>
