
<?php
$translator = \Zend_Registry::get('container')->getService('translator');
?>

<?php $this->headLink()->appendStylesheet($this->baseUrl('/admin-style/image_management.css')); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl('/js/plupload/js/jquery.plupload.queue/css/jquery.plupload.queue.css')); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl('/admin-style/admin_stylesheet.css')); ?>

<script type="text/javascript" src="<?php echo $this->baseUrl('/js/plupload/js/plupload.full.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl('/js/plupload/js/jquery.plupload.queue/jquery.plupload.queue.js'); ?>"></script>

<style type="text/css">
#error_holder > table {
    border: 0px;
}
</style>

<?php $this->placeholder('bodyId')->set('next'); ?>

<div id="modal-top">
    <div class="toolbar fixed-top">
    <div class="save-button-bar"></div>
    <h1>
        <?php echo $translator->trans("Attached images", array(), 'article_images'); ?>
        <span style="float: right;">
        <input id="tab_1_submit" type="button" value="<?php echo $translator->trans('Next: Upload and Edit Metadata', array(), 'article_images'); ?>" class="save-button" style="display: none;" onClick="$('#upload_form').submit();">
        <input id="tab_2_submit" type="button" value="<?php echo $translator->trans('Next: Place Images', array(), 'article_images'); ?>" class="save-button" style="display: none;" onClick="document.location = '<?php echo($this->url(array(
            'module' => 'admin',
            'controller' => 'image',
            'action' => 'article',
            'article_number' => $this->article,
            'language_id' => $this->languageId,
        ))); ?>';">
        </span>
    </h1>
    </div>
</div>
<div style="margin-top:40px;">&nbsp;</div>
<?php if(camp_html_has_msgs()) { ?>
<div id="error_holder" style="margin-left: 20px; margin-top: 0px;">
<?php camp_html_display_msgs(); ?>
</div>
<?php } ?>
<?php if (!empty($this->articleImages)) { ?>

<ul id="attached-thumbnails" class="thumbnails">
    <?php foreach ($this->articleImages as $articleImage) { ?>
    <li class="image-detach small" id="attached-image-<?php echo $articleImage->getId(); ?>" style="cursor: pointer;">
        <figure>
            <div class="small"><?php echo $this->thumbnail($articleImage, 75, 75, 'fit')->getImg($this); ?></div>
            <figcaption><label for="default-<?php echo $articleImage->getId(); ?>"><?php echo $articleImage->getWidth(), 'x', $articleImage->getHeight(); ?></label></figcaption>
        </figure>
        <span class="info">&nbsp;</span>
    </li>
    <?php } ?>
</ul>

<?php } else { ?>
<p style="margin-left: 8px"><?php echo $translator->trans('No images attached to article.', array(), 'article_images'); ?></p>
<?php } ?>

<div id="tabs">
	<ul>
		<li><a href="#tabs-1"><?php echo $translator->trans("Add New Image", array(), 'article_images'); ?></a></li>
        <li><a href="#tabs-2"><?php echo $translator->trans("Media Archive", array(), 'article_images'); ?></a></li>
	</ul>
	<div id="tabs-1">
        <form id="upload_form" method="POST" action="<?php echo $this->baseUrl('/admin/media-archive/do_upload.php'); ?>" enctype="multipart/form-data">
        <div style="margin: 8px;">
        </div>
        <input type="hidden" name="f_article_edit" value="1">
        <input type="hidden" name="f_language_id" value="<?php echo($this->languageId); ?>">
        <input type="hidden" name="f_article_number" value="<?php echo($this->article); ?>">
        <?php echo SecurityToken::FormParameter(); ?>
        <div id="uploader" style="border: 0px;"></div>
        <div id="uploader_error" style="border: 0px;"></div>

        <div class="plupload-addon-bottom clearfix">
          <div class="info">
            <?php echo $translator->trans('Specify image url if you want to load it.', array(), 'article_images'); ?>
          </div>
          <div class="inputs">
            <label for="form-url"><?php echo $translator->trans('URL'); ?>:</label><input type="text" class="input_text" size="32" name="f_image_url" id="form-url">
          </div>
        </div>

        </form>
        
	</div>
	<div id="tabs-2">
        
        <div style="margin: 8px;">
        </div>
        
        <form id="search-form" method="post" action="<?php echo($this->url(array(
            'module' => 'admin',
            'controller' => 'image',
            'action' => 'article-attach',
            'article_number' => $this->article,
            'language_id' => $this->languageId,
        ))); ?>">
        <input id="search_input" type="text" placeholder="<?php echo($translator->trans('Search')); ?>" name="q" value="<?php if ($this->q) echo(htmlspecialchars($this->q, ENT_QUOTES, 'UTF-8')); ?>">
        <input type="checkbox" <?php if ($this->newsfeed) { ?>value="on" checked="checked"<?php } else { ?> value="off"<?php } ?> name="with_newsfeeds" id="with_newsfeeds"><label for="with_newsfeeds"><?php echo($translator->trans('Display newsfeed images', array(), 'article_images')); ?></label>
        </form>
        <br>
        <?php if (!empty($this->images)) { ?>
        <div id="image-archive">
        <?php echo $this->paginator; ?>
        </div>
        
        <ul id="thumbnails" class="thumbnails">
            <?php foreach ($this->images as $image) { ?>
            <li id="image-<?php echo $image->getId(); ?>" class="image-attach" style="cursor: pointer;">
                <figure>
                    <div><?php echo $this->thumbnail($image, 150, 150, 'fit')->getImg($this); ?></div>
                    <figcaption><label for="default-<?php echo $image->getId(); ?>"><?php echo $image->getWidth(), 'x', $image->getHeight(); ?></label></figcaption>
                </figure>
                <span class="info">&nbsp;</span>
            </li>
            <?php } ?>
        </ul>

        <?php } else { ?>
        <p style="margin-left: 8px"><?php echo $translator->trans('No images found.', array(), 'article_images'); ?></p>
        <?php } ?>
        
	</div>
</div>

<script>
$(function() {
    
    $("#tabs").tabs();
    if (document.location.hash == '#media-archive') {
		$("#tabs").tabs('option', 'selected', 'tabs-2');
        $('#tab_1_submit').hide();
        $('#tab_2_submit').show();
	}
    else {
        $('#tab_1_submit').show();
        $('#tab_2_submit').hide();
    }
    
    $("#tabs").tabs({
        select: function(event, ui) {
            if (ui.index == 0) {
                $('#tab_1_submit').show();
                $('#tab_2_submit').hide();
                window.location.hash = '';
            }
            if (ui.index == 1) {
                $('#tab_1_submit').hide();
                $('#tab_2_submit').show();
                window.location.hash = '#media-archive';
            }
        }
    });
    
    var form = $('#upload_form');
    var uploader = $('#uploader');

    uploader.pluploadQueue({
        runtimes : "html5, html4",
        unique_names : true,
        max_file_size: <?php echo json_encode($this->maxFileSize()); ?>,
        chunk_size: '500kb',

        url : '<?php echo($this->url(array(
            'module' => 'admin',
            'controller' => 'image',
            'action' => 'upload',
            'format' => 'json',
        ))); ?>',

        flash_swf_url: "<?php echo $this->baseUrl('/js/plupload/js/plupload.flash.swf'); ?>",
        silverlight_xap_url: "<?php echo $this->baseUrl('/js/plupload/js/plupload.silverlight.xap'); ?>",
        
        filters: [{title: '<?php echo $translator->trans('Image Files: ', array(), 'article_images'); ?>', extensions: 'jpg,jpeg,gif,png'}]
    });

    // Client side form validation
    $('#upload_form').submit(function(e) {
        var uploader = $('#uploader').pluploadQueue();

        // Files in queue upload them first
        if ((0 < uploader.files.length) && ((uploader.total.uploaded + uploader.total.failed) != uploader.files.length)) {
            // When all files are uploaded submit form
            uploader.bind('StateChanged', function() {
                if ((uploader.total.uploaded + uploader.total.failed) == uploader.files.length) {
                    $('#upload_form').submit();
                }
            });
            uploader.start();
            if (e && e.preventDefault) {
                e.preventDefault();
            }
            return false;
        }

        return true;
    });
});

$('.image-attach').click(function() {
    var imageId = $(this).attr('id').replace('image-', '');
    
    $.post("<?php echo $this->url(array(
        'module' => 'admin',
        'controller' => 'image',
        'action' => 'set-attach',
        'format' => 'json',
    )); ?>", {
        'image_id': imageId,
        'article_number': <?php echo($this->article); ?>
    }, function (data, textStatus) {
        if (data.exception != undefined) {
            alert(data.exception);
            return;
        }

        window.location.hash = '#media-archive';
        window.location.reload();
    }, 'json');
});

$('.image-attach').mouseover(function() {
    $(this).find('.info').html('<?php echo $translator->trans("Attach"); ?>');
});

$('.image-attach').mouseout(function() {
    $(this).find('.info').html('&nbsp;');
});

$('.image-detach').click(function() {
    var imageId = $(this).attr('id').replace('attached-image-', '');
    
    $.post("<?php echo $this->url(array(
        'module' => 'admin',
        'controller' => 'image',
        'action' => 'set-detach',
        'format' => 'json',
    )); ?>", {
        'image_id': imageId,
        'article_number': <?php echo($this->article); ?>,
        'language_id': <?php echo($this->languageId); ?>
    }, function (data, textStatus) {
        if (data.exception != undefined) {
            alert(data.exception);
            return;
        }

        window.location.reload();
    }, 'json');
});

$('.image-detach').mouseover(function() {
    $(this).find('.info').html('<?php echo $translator->trans("Detach", array(), 'article_images'); ?>');
});

$('.image-detach').mouseout(function() {
    $(this).find('.info').html('&nbsp;');
});

$(function() {

    var search_url_ini = $("#search-form").attr('action');
    search_url_ini = search_url_ini.replace(/\/page\/[\d]*/i, "/page/1");
    search_url_ini = search_url_ini.replace(/#media-archive/i, "");
    search_url_ini += "#media-archive";

    $("#search-form").attr('action', search_url_ini);

});

window.search_functor = null;
window.check_functor = null;

$(function() {
    window.last_input_search = '' + $("#search_input").val();
});

$("#search_input").focus(function() {
    if (window.check_functor) {
        return;
    }

    window.check_functor = setInterval("check_input_search();", 500);
});
$("#search_input").blur(function() {
    if (!window.check_functor) {
        return;
    }

    clearInterval(window.check_functor);
    check_input_search();
});

function check_input_search() {

    var current_input_search = '' + $("#search_input").val();
    if (current_input_search != window.last_input_search) {
        window.last_input_search = current_input_search;
        on_input_search();
    }
};

$("#search_input").keydown(function() {
    check_input_search();
});

$("#search_input").keyup(function() {
    check_input_search();
});

$("#search_input").mousedown(function() {
    check_input_search();
});

$("#search_input").mouseup(function() {
    check_input_search();
});

$("#search_input").change(function() {
    check_input_search();
});

on_input_search = function() {

    var search_url = $("#search-form").attr('action');
    search_url = search_url.replace(/\/search\/[^\/]*/i, "");
    search_url = search_url.replace(/\/page\/[\d]*/i, "/page/1");
    search_url = search_url.replace(/#media-archive/i, "");

    var query_raw = '' + $("#search_input").val();

    if ("" != query_raw) {
        var query_enc = encodeURIComponent(query_raw);
        search_url += "/search/" + query_enc;
    }
    
    search_url += "#media-archive";

    $("#search-form").attr('action', search_url);

    clearTimeout(window.window.search_functor);
    window.search_functor = setTimeout("search_on_change();", 1500);

};

$('#with_newsfeeds').click(function() {

    var cur_url = window.location.href;
    var new_url = cur_url.replace(/#.*/i, "");
    new_url = new_url.replace(/\/page\/.*/i, "");
    new_url = new_url.replace(/\/newsfeed\/.*/i, "");
    new_url += "/"
    new_url = new_url.replace(/\/\/$/, "/");
<?php if (!$this->newsfeed) { ?>
    new_url += "newsfeed/1/";
<?php } ?>

    new_url += "#media-archive";
    window.location.href = new_url;
});

function search_on_change() {
    var current_input_search = '' + $("#search_input").val();
    if (current_input_search != window.last_input_search) {
        return;
    }

    $("#search-form").submit();
};

</script>
