<ul class="renditions">
    <?php foreach ($this->renditions as $rendition) { ?>
    <li>
        <div class="preview" style="width: <?php echo $rendition->getWidth(); ?>px; height: <?php echo $rendition->getHeight(); ?>px">
            <?php if (isset($this->articleRenditions[$rendition->getName()])) { ?>
            <?php $thumbnail = $this->thumbnail($this->articleRenditions[$rendition->getName()]->getImage()->getPath(), $rendition->getWidth(), $rendition->getHeight(), $rendition->getSpecs()); ?>
            <img src="<?php echo $this->url(array(
                'src' => $thumbnail->src,
            ), 'image', true, false); ?>" width="<?php echo $thumbnail->width; ?>" height="<?php echo $thumbnail->height; ?>" alt="" />
            <?php } ?>
        </div>
        <h3 class="rendition-name"><?php echo $this->escape($rendition->getName()); ?></h3></li>
    <?php } ?>
</ul>

<pre style="clear: both; font-size: 1.3em">&uarr; Renditions &darr; Images</pre>

<ul class="thumbnails">
    <?php foreach ($this->images as $image) { ?>
    <li id="image-<?php echo $image->getImageId(); ?>"><?php $thumbnail = $this->thumbnail('images/' . $image->getImageFileName(), 150, 150, 'fit'); ?>
        <img src="<?php echo $this->url(array(
            'src' => $thumbnail->src,
        ), 'image', true, false); ?>" width="<?php echo $thumbnail->width; ?>" height="<?php echo $thumbnail->height; ?>" alt="" />
    </li>
    <?php } ?>
</ul>

<script>
$(function() {
    $('.renditions li').droppable({
        hoverClass: 'ui-state-active',
        drop: function(event, ui) {
            var li = $(this);
            $.post("<?php echo $this->url(array(
                'module' => 'admin',
                'controller' => 'image',
                'action' => 'set-rendition',
            )); ?>", {
                'image': ui.draggable.attr('id'),
                'rendition': li.find('.rendition-name').text()
            }, function (data, textStatus) {
                li.find('.preview').html(data);
            });
        }
    });

    $('.thumbnails li').draggable({
        revert: true,
        zIndex: 1000
    });
});
</script>
