<ul class="renditions">
    <?php foreach ($this->renditions as $rendition) { ?>
    <li><?php echo $this->rendition($rendition, $this->previewWidth, $this->previewHeight, $this->articleRenditions[$rendition]); ?></li>
    <?php } ?>
</ul>

<ul class="thumbnails">
    <?php foreach ($this->images as $image) { ?>
    <li id="image-<?php echo $image->getId(); ?>">
        <figure>
            <?php echo $this->thumbnail($image->getPath(), 100, 100, 'fit')->getImg($this); ?>
            <figcaption><?php echo $image->getWidth(), 'x', $image->getHeight(); ?></figcaption>
        </figure>
    </li>
    <?php } ?>
</ul>

<script>
$(function() {
    $('.renditions li').droppable({
        hoverClass: 'ui-state-active',
        drop: function(event, ui) {
            var li = $(this);
            $.post("<?php echo $this->url(array(
                'module' => 'admin',
                'controller' => 'image',
                'action' => 'set-rendition',
                'format' => 'json',
            )); ?>", {
                'image': ui.draggable.attr('id'),
                'rendition': li.find('.rendition-name').text()
            }, function (data, textStatus) {
                if (data.exception != undefined) {
                    alert(data.exception);
                    return;
                }

                li.html(data.rendition);
            }, 'json');
        }
    });

    $('.thumbnails li').draggable({
        revert: true,
        zIndex: 1000
    });

    $('.renditions .reset').live('click', function(e) {
        e.preventDefault();
        var li = $(this).closest('li');
        $.post($(this).attr('href'), function(data, textStatus) {
            li.html(data.rendition);
        }, 'json');
    });
});
</script>
