<?php
$this->headLink()->appendStylesheet($this->baseUrl('/js/tapmodo-Jcrop-5e58bc9/css/jquery.Jcrop.css'));
$this->headScript()->appendFile($this->baseUrl('/js/tapmodo-Jcrop-5e58bc9/js/jquery.Jcrop.min.js'));
?>

<a href="<?php echo $this->url(array(
    'action' => 'article',
    'rendition' => null,
)); ?>"><h3><?php putGS('Back'); ?></h3></a>


<div id="editor">
    <?php echo $this->thumbnail($this->image->getPath(), $this->rendition->getWidth(), $this->rendition->getHeight(), 'fill')->getImg($this); ?>
    <button id="save-jcrop">Save</button>
</div>

<script>
$(function() {
    var jcrop;
    $('#editor img').Jcrop({
        aspectRatio: <?php echo $this->rendition->getAspectRatio(); ?>,
        minSize: <?php echo json_encode($this->rendition->getMinSize($this->image)); ?>,
        trueSize: <?php echo json_encode(array($this->image->getWidth(), $this->image->getHeight())); ?>
    }, function() {
        jcrop = this;
        jcrop.setSelect(<?php echo json_encode($this->rendition->getSelectArea($this->image)); ?>);
    });


    $('#save-jcrop').click(function() {
        var button = $(this);
        button.text(<?php echo json_encode(getGS("Saving...")); ?>);
        $.post("<?php echo $this->url(array(
            'module' => 'admin',
            'controller' => 'image',
            'action' => 'edit',
            'image' => $this->image->getId(),
            'format' => 'json',
        )); ?>", jcrop.tellSelect(), function (data, textStatus) {
            button.text(<?php echo json_encode(getGS("Saved")); ?>);
            window.setTimeout(function() {
                button.text(<?php echo json_encode(getGS("Save")); ?>);
            }, 3000);
        });
    });
});
</script>
