<?php $this->headLink()->appendStylesheet($this->baseUrl('/admin-style/image_management.css')); ?>

<?php $this->placeholder('bodyId')->set('next'); ?>

<?php
    // Load tinymce for richtext editor
    require_once($GLOBALS['g_campsiteDir']."/admin-files/media-archive/editor_load_tinymce.php");

    $loadAsRichtext = array();
    $captionLimit = SystemPref::Get('MediaCaptionLength');
?>

<div id="modal-top">
    <div class="toolbar fixed-top">
    <div class="save-button-bar"></div>
    <h1>
        <?php putGS('Edit Image Data'); ?>
        <span style="float: right;">
        <input type="button" value="<?php echo putGS('Next: Place Images'); ?>" class="save-button" onClick="$('#edit_image_data_next').val(1);$('#edit_image_data_form').submit();">
        </span>
    </h1>
    </div>
</div>
<div style="margin-top:40px;">&nbsp;</div>

<?php if (!empty($this->images)) { ?>

<form id="edit_image_data_form" method="post" action="<?php echo($this->url(array(
    'module' => 'admin',
    'controller' => 'image',
    'action' => 'edit-image-data'
))); ?>" onSubmit="<?php
    if (SystemPref::Get("MediaRichTextCaptions") == 'Y') {
        echo 'return validateTinyMCEEditors();';
    }
?>">


<input type="hidden" name="article_number" value="<?php echo($this->article); ?>">
<input type="hidden" name="language_id" value="<?php echo($this->languageId); ?>">
<input id="edit_image_data_next" type="hidden" name="next" value="0">

<ul class="thumbnails">
    <?php foreach ($this->images as $image) { ?>
    <li id="image-<?php echo $image->getId(); ?>" style="width: 390px;">
        <figure>
            <div><?php echo $this->thumbnail($image, 150, 150, 'fit')->getImg($this); ?></div>
            <figcaption><label for="default-<?php echo $image->getId(); ?>"><?php echo $image->getWidth(), ' x ', $image->getHeight(); ?></label></figcaption>
        </figure>
        <div class="image-data">
            <label for="" style="font-size: 11px;"><?php
                echo(getGS('Description'));
                $captionLimit = SystemPref::Get('MediaCaptionLength');
                if (SystemPref::Get("MediaRichTextCaptions") == 'Y' && $captionLimit > 0) {
                    echo('&nbsp;'.getGS('(max. $1 characters)', $captionLimit));
                }
            ?>: <a style="float: right;" href="javascript:useForAll('description', <?php echo $image->getId(); ?>);"> <?php echo(getGS('Use for all')); ?></a></label><br>

            <?php
                if (SystemPref::Get("MediaRichTextCaptions") == 'Y') {

                    $languageSelectedObj = new Language((int) camp_session_get('LoginLanguageId', 0));
                    $editorLanguage = !empty($_COOKIE['TOL_Language']) ? $_COOKIE['TOL_Language'] : $languageSelectedObj->getCode();

                    $loadAsRichtext[]   = 'data['.$image->getId().'][description]';
                    ?>
                        <textarea name="data[<?php echo $image->getId(); ?>][description]" id="image_description_<?php echo $image->getId(); ?>" rows="4" class="image-description" style="float:none; width:380px;"><?php echo $image->getDescription(); ?></textarea>
                    <?php
                } else {
                    ?>
                        <input name="data[<?php echo $image->getId(); ?>][description]" id="image_description_<?php echo $image->getId(); ?>" VALUE="<?php echo htmlspecialchars($image->getDescription()); ?>" maxlength="<?php echo $captionLimit; ?>" style="float:none; width:380px;">
                    <?php
                }
            ?>

            <label for="" style="font-size: 11px;"><?php echo(getGS('Location')); ?>: <a style="float: right;" href="javascript:useForAll('place', <?php echo $image->getId(); ?>);"> <?php echo(getGS('Use for all')); ?></a></label><br/>
            <input name="data[<?php echo $image->getId(); ?>][place]" id="image_place_<?php echo $image->getId(); ?>" class="image-place" value="<?php echo $image->getPlace(); ?>" style="float:none; width:380px;"><br/>

            <label for="" style="font-size: 11px;"><?php echo(getGS('Photographer')); ?>: <a style="float: right;" href="javascript:useForAll('photographer', <?php echo $image->getId(); ?>);"> <?php echo(getGS('Use for all')); ?></a></label><br>
            <input name="data[<?php echo $image->getId(); ?>][photographer]" id="image_photographer_<?php echo $image->getId(); ?>" class="image-photographer" value="<?php echo $image->getPhotographer(); ?>" style="float:none; width:380px;"><br/>

            <input type="hidden" name="data[<?php echo $image->getId(); ?>][date]" id="image_date_<?php echo $image->getId(); ?>" class="image-date" value="<?php echo $image->getDate(); ?>">
        </div>
    </li>
    <?php } ?>
</ul>

</form>

<?php
    // Load tinymce once for all textareas
    if (count($loadAsRichtext) > 0) {

        $editorOptions  = array(
            'max_chars' => $captionLimit,
            'toolbar_length' => 19,
        );

        editor_load_tinymce(implode(',', $loadAsRichtext), $this->currentUser, $editorLanguage, $editorOptions);
    }
?>

<script>
function useForAll(field, id) {

    if (field == 'description' && $('#image_' + field + '_' + id).length === 0) {
        // Using tinyMCE for richttext captions
        var textareaID      = $('textarea[name="data['+id+'][description]"]').attr('id');
        var contentToCopy   = tinyMCE.editors[textareaID].getContent();

        var inst;
        for (inst in tinyMCE.editors) {
            if (tinyMCE.editors[inst].getContent) {
                tinyMCE.editors[inst].setContent(contentToCopy);
            }
        }

    } else {
        // Default case
        var className = 'image-' + field;
        var value = $('#image_' + field + '_' + id).val();

        $('.' + className).val(value);
    }
}
</script>

<?php } else { ?>
    <script>
        document.location = '<?php echo($this->url(array(
            'module' => 'admin',
            'controller' => 'image',
            'action' => 'article',
            'article_number' => $this->article,
            'language_id' => $this->languageId,
        ))); ?>';
    </script>
<?php } ?>
