<?php 
$translator = \Zend_Registry::get('container')->getService('translator');
$this->headLink()->appendStylesheet($this->baseUrl('/admin-style/image_management.css')); 
?>
<?php $this->placeholder('bodyId')->set('next'); $this->placeholder('bodyClass')->set('dark'); ?>

<div id="modal-top">
    <div class="toolbar fixed-top">
    <div class="save-button-bar"></div>
    <h1>
        <?php echo $translator->trans('Edit images', array(), 'article_images'); ?>
        <span style="float: right;">
        <a href="<?php echo $this->url(array(
            'action' => 'article',
            'rendition' => null,
        )); ?>" class="save-button"><?php echo $translator->trans('Done editing', array(), 'article_images'); ?></a>
        </span>
    </h1>
    </div>
</div>
<div style="margin-top:40px;">&nbsp;</div>

<form method="POST">

<div class="editarea">
    <div>
        <?php echo $this->imageEditor($this->rendition, $this->image); ?>
        <?php if ($this->rendition->isCrop()) { ?>
        <button id="save-jcrop" class="save-button">Save</button>
        <?php } ?>
    </div>

</div>

</form>

<?php $this->currentRendition = $this->rendition; ?>
<ul class="renditions editor">
    <?php foreach ($this->renditions as $rendition) { ?>
    <li<?php echo $rendition->getName() === $this->currentRendition->getName() ? ' class="active"' : ''; ?>><?php echo $this->rendition($rendition, $this->previewWidth, $this->previewHeight, $this->articleRenditions[$rendition]); ?></li>
    <?php } ?>
</ul>
