<a <?php if ($this->thumbnail !== null) { ?>href="<?php echo $this->url(array(
    'module' => 'admin',
    'controller' => 'image',
    'action' => 'edit',
    'rendition' => $this->rendition->getName(),
    'format' => null,
)); ?>" <?php } ?>title="<?php echo $this->escape(getGS("Edit $1", $this->rendition->getName())); ?>">
<div class="preview-wrap"><div class="preview" style="width: <?php echo $this->preview->getWidth(); ?>px; height: <?php echo $this->preview->getHeight(); ?>px;">
<?php if ($this->thumbnail !== null) {
    echo $this->thumbnail->getImg($this);
} ?>
</div></div>
<h3><span class="rendition-name"><?php echo $this->escape($this->rendition->getName()); ?></span><br /><small><?php echo array_shift(explode('_', $this->rendition->getSpecs())); ?> <?php echo $this->rendition->getWidth(), 'x', $this->rendition->getHeight(); ?></small></h3>
</a>
<?php if (!$this->isDefault) { ?>
<a href="<?php echo $this->url(array(
    'module' => 'admin',
    'controller' => 'image',
    'action' => 'remove-rendition',
    'rendition' => $this->rendition->getName(),
    'format' => 'json',
)); ?>" class="reset">Reset</a>
<?php } ?>
